### ISSUE TITLE
certificate signed by unknown authority (only with containerd)

### ISSUE THREAD

**Issue by andrenth** [kubernetes/kubeadm#1009]
## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`):

kubeadm version: &version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:50:16Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Kubernetes version** (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:53:20Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:08:34Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}

- **Cloud provider or hardware configuration**:

Bare metal.

- **OS** (e.g. from /etc/os-release):

Ubuntu 16.04.

- **Kernel** (e.g. `uname -a`):

4.4.0-109-generic

## What happened?

When installing a master node following the [high availability docs](https://kubernetes.io/docs/setup/independent/high-availability/), but with containerd/crictl instead of docker, `kubeadm exec` fails with "certificate signed by unknown authority". This doesn't happen following the exact same steps but using docker instead.

## What you expected to happen?

`kubeadm exec` should work.

## How to reproduce it (as minimally and precisely as possible)?

I have installed kubelet, kubeadm, kubectl and cri-tools via the debian repository, and cri-containerd 1.1.2 by unpacking the tarball.

Here are my configuration steps:

* Containerd:
```
# tar xf cri-containerd-1.1.2.linux-amd64.tar.gz -C /
# systemctl daemon-reload
```
* Edit /etc/containerd/config.toml:
```
[plugins.cri]
  stream_server_address = "10.20.0.1"
  enable_tls_streaming = true
```
Run commands below:
```
# systemctl start containerd
# modprobe br_netfilter
# sysctl net.bridge.bridge-nf-call-iptables=1
# sysctl net.ipv4.ip_forward=1
# /usr/local/bin/ctr image pull k8s.gcr.io/pause:3.1
# /usr/local/bin/crictl --runtime-endpoint unix:///run/containerd/containerd.sock pull k8s.gcr.io/pause:3.1
```

* IPVS: run commands below
```
# apt install ipvsadm
# modprobe ip_vs
# modprobe ip_vs_rr
# modprobe ip_vs_wrr
# modprobe ip_vs_sh
# modprobe nf_conntrack_ipv4
```

* Kubeadm
Run commands:
```
# apt-get install -y kubelet kubeadm kubectl cri-tools
# echo 'KUBELET_EXTRA_ARGS="--container-runtime=remote --runtime-request-timeout=15m --container-runtime-endpoint=unix:///run/containerd/containerd.sock"' > /etc/default/kubelet`
```

Create kubeadm-config.yaml with the content below:
```
apiVersion: kubeadm.k8s.io/v1alpha2
kind: MasterConfiguration
kubernetesVersion: v1.11.0
apiServerCertSANs:
- "k8s.private.my.domain"
nodeName: k8s.private.my.domain
api:
  controlPlaneEndpoint: "k8s.private.my.domain:6443"
etcd:
  local:
    extraArgs:
      listen-client-urls: "https://127.0.0.1:2379,https://10.0.0.1:2379"
      advertise-client-urls: "https://10.0.0.1:2379"
      listen-peer-urls: "https://10.0.0.1:2380"
      initial-advertise-peer-urls: "https://10.0.0.1:2380"
      initial-cluster: "k8s1=https://10.0.0.1:2380"
    serverCertSANs:
      - k8s1
      - k8s1.private.my.domain
      - 10.0.0.1
    peerCertSANs:
      - k8s1
      - k8s1.private.my.domain
      - 10.0.0.1
networking:
  podSubnet: "10.244.0.0/16"
kubeProxy:
  config:
    mode: "ipvs"
controllerManagerExtraArgs:
  allocate-node-cidrs: "true"
nodeRegistration:
  criSocket: /run/containerd/containerd.sock
```

Finally, run `kubeadm init --ignore-preflight-errors=all --config kubeadm-config.yaml`

All this seems to work and the pods are running, with the exception of coredns, of course:

```
# kubectl -n kube-system get pod
NAME                           READY     STATUS    RESTARTS   AGE
coredns-78fcdf6894-dmb92       0/1       Pending   0          16h
coredns-78fcdf6894-ww7fk       0/1       Pending   0          16h
etcd-k8s1                      1/1       Running   1          16h
kube-apiserver-k8s1            1/1       Running   0          16h
kube-controller-manager-k8s1   1/1       Running   0          16h
kube-proxy-h67dm               1/1       Running   0          16h
kube-scheduler-k8s1            1/1       Running   1          16h
```

However, a `kubectl exec` fails with the error in the subject, which doesn't happen when following the same steps but using Docker.

```
# kubectl exec -n kube-system etcd-k8s1 pstree
error: unable to upgrade connection: error dialing backend: x509: certificate signed by unknown authority
```

## Anything else we need to know?

I've rebuilt this master many times. To reset it, I'm using the following commands:

```
# kubectl drain k8s1 --delete-local-data --force --ignore-daemonsets
# kubectl delete node k8s1

# kubeadm reset -f -v 1 --cri-socket unix:///run/containerd/containerd.sock
# apt-get purge -y kubelet kubeadm kubectl containerd cri-tools runc
# rm -rf /etc/kubernetes
# rm -rf /var/lib/etcd/*
# service containerd stop
# rm -rf /var/lib/containerd/*
# service containerd start
```

From googling I've found that this error can happen when there are leftover certificates from previous installations, but given the commands above, I can't think of how this could be the case.
