### ISSUE TITLE
No way to set cloudProvider: external in new config files

### ISSUE THREAD

**Issue by NeilW** [kubernetes/kubeadm#1018]
# BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`):
kubeadm version: &version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:50:16Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:53:20Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:08:34Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
- **Cloud provider or hardware configuration**:
Brightbox
- **OS** (e.g. from /etc/os-release):
Ubuntu 18.04 LTS
- **Kernel** (e.g. `uname -a`):
Linux srv-k1jym 4.15.0-29-generic #31-Ubuntu SMP Tue Jul 17 15:39:52 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- **Others**:

## What happened?

When looking at upgrading the config version from kubeadm.k8s.io/v1alpha1 there doesn't appear to be a way of specifying 'cloudProvider: external' in the config

## What you expected to happen?

That there is a documented way of using an external cloud provider with kubeadm, including a documented way to boot the cloud-provider as an additional add-on.

## How to reproduce it (as minimally and precisely as possible)?

My v1alpaha1 config is

```
apiVersion: kubeadm.k8s.io/v1alpha1
kind: MasterConfiguration
clusterName: ${cluster_name}
api:
  advertiseAddress: "::"
networking:
  dnsDomain: ${cluster_domainname}
  serviceSubnet: ${service_cidr}
kubernetesVersion: ${k8s_release}
cloudProvider: external
```
(The variables are swapped out during terraform rendering).

The alpha2 example in the documentation here: https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-init/ has nothing about cloudProvider in there. 

## Anything else we need to know?

The documented external cloud provider boot processes seems to expect an apiserver without any TLS connections. I've had to work out from scratch how to boot an external cloud-provider so it will work with a kubeadm created cluster - largely by pulling apart kube-proxy.

Given the move to separated cloud-providers, we could do with the process standardising.
