### ISSUE TITLE
bug with setting clustered etcd with kubeadm

### ISSUE THREAD

**Issue by zidosni** [kubernetes/kubeadm#1049]
<!-- Thanks for filing an issue! Before hitting the button, please answer these questions.-->

## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT

<!--
If this is a BUG REPORT, please:
  - Fill in as much of the template below as you can.  If you leave out information, we can't help you as well.



In both cases, be ready for followup questions, and please respond in a timely
manner.  If we can't reproduce a bug or think a feature already exists, we
might close your issue.  If we're wrong, PLEASE feel free to reopen it and
explain why.
-->


## Versions

**kubeadm version** (use `kubeadm version`):
kubeadm version: &version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:50:16Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:53:20Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

- **Cloud provider or hardware configuration**:
Virtual Machine (VMware) : 8 Cores , 32 GB
- **OS** (e.g. from /etc/os-release):
NAME="Red Hat Enterprise Linux Server"
VERSION="7.5 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.5"
PRETTY_NAME="Red Hat Enterprise Linux"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.5:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.5
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.5"

- **Kernel** (e.g. `uname -a`):
Linux pvlxp145 3.10.0-693.17.1.el7.x86_64 #1 SMP Sun Jan 14 10:36:03 EST 2018 x86_64 x86_64 x86_64 GNU/Linux

- **Others**:


## What happened?
I want to setup etcd cluster using kubeadm as described in https://kubernetes.io/docs/setup/independent/setup-ha-etcd-with-kubeadm/  , but the etcd is running with default parameters (127.0.0.1 as a single node) 
```
ps -ef | grep etcd
root     30059 30042  0 août10 ?      00:10:38 etcd --advertise-client-urls=https://127.0.0.1:2379 --cert-file=/etc/kubernetes/pki/etcd/server.crt --client-cert-auth=true --data-dir=/var/lib/etcd --initial-advertise-peer-urls=https://127.0.0.1:2380 --initial-cluster=pvlxp145=https://127.0.0.1:2380 --key-file=/etc/kubernetes/pki/etcd/server.key --listen-client-urls=https://127.0.0.1:2379 --listen-peer-urls=https://127.0.0.1:2380 --name=pvlxp145 --peer-cert-file=/etc/kubernetes/pki/etcd/peer.crt --peer-client-cert-auth=true --peer-key-file=/etc/kubernetes/pki/etcd/peer.key --peer-trusted-ca-file=/etc/kubernetes/pki/etcd/ca.crt --snapshot-count=10000 --trusted-ca-file=/etc/kubernetes/pki/etcd/ca.crt
```
and
```
 docker ps --no-trunc
CONTAINER ID                                                       IMAGE                                                                                           COMMAND                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                CREATED             STATUS              PORTS               NAMES
16ce3ebfd315cb0b3a3ecde80eb5d00809ecd24565bbe445f2be90e16ee0ab22   k8s.gcr.io/etcd-amd64@sha256:b960569ade5f37205a033dcdc3191fe99dc95b15c6795a6282859070ec2c6124   "etcd --advertise-client-urls=https://127.0.0.1:2379 --cert-file=/etc/kubernetes/pki/etcd/server.crt --client-cert-auth=true --data-dir=/var/lib/etcd --initial-advertise-peer-urls=https://127.0.0.1:2380 --initial-cluster=pvlxp145=https://127.0.0.1:2380 --key-file=/etc/kubernetes/pki/etcd/server.key --listen-client-urls=https://127.0.0.1:2379 --listen-peer-urls=https://127.0.0.1:2380 --name=pvlxp145 --peer-cert-file=/etc/kubernetes/pki/etcd/peer.crt --peer-client-cert-auth=true --peer-key-file=/etc/kubernetes/pki/etcd/peer.key --peer-trusted-ca-file=/etc/kubernetes/pki/etcd/ca.crt --snapshot-count=10000 --trusted-ca-file=/etc/kubernetes/pki/etcd/ca.crt"   23 hours ago        Up 23 hours                             k8s_etcd_etcd-pvlxp145_kube-system_2db1a3941e37520fd336d606c3ca9bcf_0
fb995f360610c339531c95f36d1c4949369649a58e424d59844b6ec8b1b4c04a   k8s.gcr.io/pause:3.1                                                                            "/pause"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               24 hours ago        Up 24 hours                             k8s_POD_etcd-pvlxp145_kube-system_2db1a3941e37520fd336d606c3ca9bcf_1
```
the command 
```kubeadm alpha phase etcd local --config=/tmp/${HOST0}/kubeadmcfg.yaml```
generated a manifest with 127.0.0.1 config, and it didn't take the parametes in kubeadmcfg.yaml

kubeadmcfg.yaml : 
```
apiVersion: "kubeadm.k8s.io/v1alpha2"
kind: MasterConfiguration
etcd:
    localEtcd:
        serverCertSANs:
        - "10.21.25.145"
        peerCertSANs:
        - "10.21.25.145"
        extraArgs:
            initial-cluster: infra0=https://10.21.25.145:2380,infra1=https://10.21.25.141:2380,infra2=https://10.21.25.42:2380
            initial-cluster-state: new
            name: infra0
            listen-peer-urls: https://10.21.25.145:2380
            listen-client-urls: https://10.21.25.145:2379
            advertise-client-urls: https://10.21.25.145:2379
            initial-advertise-peer-urls: https://10.21.25.145:2380
```

I changed manually the generated manifest file (/etc/kubernetes/manifests/etcd.yaml) because it contained "default" values following the guide https://github.com/coreos/etcd/blob/master/Documentation/op-guide/clustering.md 

And my new etcd.yaml file is : 
```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    scheduler.alpha.kubernetes.io/critical-pod: ""
  creationTimestamp: null
  labels:
    component: etcd
    tier: control-plane
  name: etcd
  namespace: kube-system
spec:
  containers:
  - command:
    - etcd
    - --advertise-client-urls=https://10.21.25.145:2379
    - --cert-file=/etc/kubernetes/pki/etcd/server.crt
    - --client-cert-auth=true
    - --data-dir=/var/lib/etcd
    - --initial-advertise-peer-urls=https://10.21.25.145:2380
    - --initial-cluster=infra0=http://10.21.25.145:2380,infra1=http://10.21.25.141:2380,infra2=http://10.21.25.42:2380
    - --initial-cluster-token=etcd-cluster-1
    - --initial-cluster-state=new
    - --key-file=/etc/kubernetes/pki/etcd/server.key
    - --listen-client-urls=https://10.21.25.145:2379,https://127.0.0.1:2379
    - --listen-peer-urls=https://10.21.25.145:2380
    - --name=infra0
    - --peer-cert-file=/etc/kubernetes/pki/etcd/peer.crt
    - --peer-client-cert-auth=true
    - --peer-key-file=/etc/kubernetes/pki/etcd/peer.key
    - --peer-trusted-ca-file=/etc/kubernetes/pki/etcd/ca.crt
    - --snapshot-count=10000
    - --trusted-ca-file=/etc/kubernetes/pki/etcd/ca.crt
    image: k8s.gcr.io/etcd-amd64:3.2.18
    imagePullPolicy: IfNotPresent
    livenessProbe:
      exec:
        command:
        - /bin/sh
        - -ec
        - ETCDCTL_API=3 etcdctl --endpoints=https://10.21.25.145:2379 --cacert=/etc/kubernetes/pki/etcd/ca.crt
          --cert=/etc/kubernetes/pki/etcd/healthcheck-client.crt --key=/etc/kubernetes/pki/etcd/healthcheck-client.key
          get foo
      failureThreshold: 8
      initialDelaySeconds: 15
      timeoutSeconds: 15
    name: etcd
    resources: {}
    volumeMounts:
    - mountPath: /var/lib/etcd
      name: etcd-data
    - mountPath: /etc/kubernetes/pki/etcd
      name: etcd-certs
  hostNetwork: true
  priorityClassName: system-cluster-critical
  volumes:
  - hostPath:
      path: /var/lib/etcd
      type: DirectoryOrCreate
    name: etcd-data
  - hostPath:
      path: /etc/kubernetes/pki/etcd
      type: DirectoryOrCreate
    name: etcd-certs
status: {}
```

## What you expected to happen?
to run etcd with the parameters in kubeadmcfg file

## How to reproduce it (as minimally and precisely as possible)?
To reproduce the bug, follow the guide https://kubernetes.io/docs/setup/independent/setup-ha-etcd-with-kubeadm/ 

## Anything else we need to know?
docker version
```
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 02:21:36 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 02:21:36 2017
 OS/Arch:      linux/amd64
 Experimental: false
```
journalctl -xe | grep -i etcd
```
août 11 17:20:38 pvlxp145 kubelet[5297]: E0811 17:20:38.796028    5297 remote_runtime.go:332] ExecSync 16ce3ebfd315cb0b3a3ecde80eb5d00809ecd24565bbe445f2be90e16ee0ab22 '/bin/sh -ec ETCDCTL_API=3 etcdctl --endpoints=https://[127.0.0.1]:2379 --cacert=/etc/kubernetes/pki/etcd/ca.crt --cert=/etc/kubernetes/pki/etcd/healthcheck-client.crt --key=/etc/kubernetes/pki/etcd/healthcheck-client.key get foo' from runtime service failed: rpc error: code = Unknown desc = cannot connect to the Docker daemon. Is 'docker daemon' running on this host?: dial unix /var/run/docker.sock: connect: no such file or directory
août 11 17:20:38 pvlxp145 kubelet[5297]: E0811 17:20:38.799865    5297 remote_runtime.go:332] ExecSync 16ce3ebfd315cb0b3a3ecde80eb5d00809ecd24565bbe445f2be90e16ee0ab22 '/bin/sh -ec ETCDCTL_API=3 etcdctl --endpoints=https://[127.0.0.1]:2379 --cacert=/etc/kubernetes/pki/etcd/ca.crt --cert=/etc/kubernetes/pki/etcd/healthcheck-client.crt --key=/etc/kubernetes/pki/etcd/healthcheck-client.key get foo' from runtime service failed: rpc error: code = Unknown desc = cannot connect to the Docker daemon. Is 'docker daemon' running on this host?: dial unix /var/run/docker.sock: connect: no such file or directory
août 11 17:20:38 pvlxp145 kubelet[5297]: E0811 17:20:38.803670    5297 remote_runtime.go:332] ExecSync 16ce3ebfd315cb0b3a3ecde80eb5d00809ecd24565bbe445f2be90e16ee0ab22 '/bin/sh -ec ETCDCTL_API=3 etcdctl --endpoints=https://[127.0.0.1]:2379 --cacert=/etc/kubernetes/pki/etcd/ca.crt --cert=/etc/kubernetes/pki/etcd/healthcheck-client.crt --key=/etc/kubernetes/pki/etcd/healthcheck-client.key get foo' from runtime service failed: rpc error: code = Unknown desc = cannot connect to the Docker daemon. Is 'docker daemon' running on this host?: dial unix /var/run/docker.sock: connect: no such file or directory
août 11 17:20:38 pvlxp145 kubelet[5297]: W0811 17:20:38.803766    5297 prober.go:103] No ref for container "docker://16ce3ebfd315cb0b3a3ecde80eb5d00809ecd24565bbe445f2be90e16ee0ab22" (etcd-pvlxp145_kube-system(2db1a3941e37520fd336d606c3ca9bcf):etcd)
août 11 17:20:39 pvlxp145 kubelet[5297]: E0811 17:20:39.019729    5297 remote_runtime.go:92] RunPodSandbox from runtime service failed: rpc error: code = Unknown desc = failed to start sandbox container for pod "etcd-pvlxp145": Error response from daemon: failed to update store for object type *libnetwork.endpoint: open : no such file or directory
août 11 17:20:39 pvlxp145 kubelet[5297]: E0811 17:20:39.019942    5297 kuberuntime_sandbox.go:56] CreatePodSandbox for pod "etcd-pvlxp145_kube-system(2db1a3941e37520fd336d606c3ca9bcf)" failed: rpc error: code = Unknown desc = failed to start sandbox container for pod "etcd-pvlxp145": Error response from daemon: failed to update store for object type *libnetwork.endpoint: open : no such file or directory
août 11 17:20:39 pvlxp145 kubelet[5297]: E0811 17:20:39.019979    5297 kuberuntime_manager.go:646] createPodSandbox for pod "etcd-pvlxp145_kube-system(2db1a3941e37520fd336d606c3ca9bcf)" failed: rpc error: code = Unknown desc = failed to start sandbox container for pod "etcd-pvlxp145": Error response from daemon: failed to update store for object type *libnetwork.endpoint: open : no such file or directory
août 11 17:20:39 pvlxp145 kubelet[5297]: E0811 17:20:39.021689    5297 pod_workers.go:186] Error syncing pod 2db1a3941e37520fd336d606c3ca9bcf ("etcd-pvlxp145_kube-system(2db1a3941e37520fd336d606c3ca9bcf)"), skipping: failed to "CreatePodSandbox" for "etcd-pvlxp145_kube-system(2db1a3941e37520fd336d606c3ca9bcf)" with CreatePodSandboxError: "CreatePodSandbox for pod \"etcd-pvlxp145_kube-system(2db1a3941e37520fd336d606c3ca9bcf)\" failed: rpc error: code = Unknown desc = failed to start sandbox container for pod \"etcd-pvlxp145\": Error response from daemon: failed to update store for object type *libnetwork.endpoint: open : no such file or directory"
août 11 17:20:39 pvlxp145 kubelet[5297]: E0811 17:20:39.983374    5297 remote_runtime.go:92] RunPodSandbox from runtime service failed: rpc error: code = Unknown desc = failed to create a sandbox for pod "etcd-pvlxp145": error during connect: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.27/containers/create?name=k8s_POD_etcd-pvlxp145_kube-system_2db1a3941e37520fd336d606c3ca9bcf_3: EOF
```
