### ISSUE TITLE
Improvements to the handling of cluster addons

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubeadm#1091]
this is a tracking issue for addon improvements.
it has a proposal that possibly needs discussion.

a couple of problems:
1) addons rely on the same image repository as the control plane images.

addons don't follow the k8s versioning and the users don't have control of what version of an addon is pulled. 

2) addon manifests are hardcoded in kubeadm and the users need to patch the cluster if they need to apply different specs - (anti-)affinity rules or nodeSelectors etc.

these complexities can be solved if addons are introduced in a separate structure in the kubeadm configuration.

rough pseudo example:
```
ClusterConfiguration:
...
  addons:
  - name: coredns
    image: <some-image-url>
    manifestFile: <some-path-to-manifest>
  - name: kube-proxy
    image: <some-image-url>
    manifestFile: <some-path-to-manifest> # inlining
  - name: <some-other-addon?>
    image: <some-image-url>
    manifestFile: <some-path-to-manifest> # inlining
```

notes:
- core addons can have special handling if needed, possibly reserving some `name`s for such.
- manifest files can contain `---` separated list of objects. Deployment, ConfigMap etc.
- if `minifestFile` is not defined use the defaults (hardcoded) values.
- if `image` is not defined use defaults.

/cc @chuckha @fabriziopandini 

edit1: it was also proposed to have `restore-default-at-upgrade` as a possible knob per addon element.
https://github.com/kubernetes/kubeadm/issues/1091#issuecomment-418759750
