### ISSUE TITLE
Run kubeadm init command on the host that already create etcd with kubeadm

### ISSUE THREAD

**Issue by pytimer** [kubernetes/kubeadm#1107]
## Is this a BUG REPORT or FEATURE REQUEST?

FEATURE REQUEST

## Versions

**kubeadm version** (use `kubeadm version`):

`kubeadm version: &version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:14:39Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
`

**Environment**:
- **Kubernetes version** (use `kubectl version`):

`Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:17:28Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}`

- **OS** (e.g. from /etc/os-release):

```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
- **Kernel** (e.g. `uname -a`):

`Linux master1 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`

- **Others**:

kubeadm configuration file:

```yaml
apiVersion: kubeadm.k8s.io/v1alpha2
kind: MasterConfiguration
kubernetesVersion: v1.11.1
etcd:
    external:
        endpoints:
        - https://192.168.100.10:2379
        caFile: /etc/kubernetes/pki/etcd/ca.crt
        certFile: /etc/kubernetes/pki/apiserver-etcd-client.crt
        keyFile: /etc/kubernetes/pki/apiserver-etcd-client.key
networking:
    podSubnet: 10.204.0.0/16
```

## What happened?

I create [Highly Availabile etcd Cluster with kubeadm](https://kubernetes.io/docs/setup/independent/setup-ha-etcd-with-kubeadm/) successfully.

Now i want to init Kubernetes Cluster on the three etcd host, when i run `kubeadm init --config kubeadm.yaml`, it is failed.

Below error log:

```
[preflight] Some fatal errors occurred:
        [ERROR FileAvailable--etc-kubernetes-manifests-etcd.yaml]: /etc/kubernetes/manifests/etcd.yaml already exists
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
```

## What you expected to happen?

I found kubeadm code [checks.go#L865](https://github.com/kubernetes/kubernetes/blob/36877dafe40495cb43994464e2427355f99042c7/cmd/kubeadm/app/preflight/checks.go#L865)  always check etcd static pod file, this check should be cancelled if use external etcd cluster?

## How to reproduce it (as minimally and precisely as possible)?

- create [Highly Availabile etcd Cluster with kubeadm](https://kubernetes.io/docs/setup/independent/setup-ha-etcd-with-kubeadm/) on three host

- `kubeadm  init --config kubeadm.yaml` on the etcd host
