### ISSUE TITLE
kubeadm 1.11.3 install kubernetes v1.11.3 but image is v1.11.1

### ISSUE THREAD

**Issue by fanux** [kubernetes/kubeadm#1112]
BUG:

```
[root@istiohost kube]# kubectl get node
NAME        STATUS    ROLES     AGE       VERSION
istiohost   Ready     master    2m        v1.11.3
[root@istiohost kube]# cat /etc/kubernetes/manifests/kube-apiserver.yaml |grep image
    image: k8s.gcr.io/kube-apiserver-amd64:v1.11.1
    imagePullPolicy: IfNotPresent
```
kubeadm config:
```
apiVersion: kubeadm.k8s.io/v1alpha2
kind: MasterConfiguration
networking:
  podSubnet: 100.64.0.0/10
kubernetesVersion: v1.11.3
kubeProxy:
    config:
        mode: "ipvs"
```
docker images:
```
k8s.gcr.io/kube-proxy-amd64                        v1.11.1             d5c25579d0ff        8 weeks ago         97.8 MB
k8s.gcr.io/kube-apiserver-amd64                    v1.11.1             816332bd9d11        8 weeks ago         187 MB
k8s.gcr.io/kube-controller-manager-amd64           v1.11.1             52096ee87d0e        8 weeks ago         155 MB
k8s.gcr.io/kube-scheduler-amd64                    v1.11.1
```
images are v1.11.1
