### ISSUE TITLE
Kubeadm upgrade and ETCd certificates location

### ISSUE THREAD

**Issue by oisis** [kubernetes/kubeadm#1113]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> /kind bug
/sig wg-kubeadm-adoption

**What happened**:

 I guess i found bug in kubeadm upgrade command. I want to put SSL certs for ETCd in different location than default one. Kubeadm looks for ETCd certs in /etc/kubernetes/pki/etcd but in my kubeadm config file i setup different location: /etc/kubernetes/etcd/ because i do not want to loose certs when run command kubeadm reset.

**What you expected to happen**:

When i run command: kubeadm upgrade apply --config /etc/kubernetes/kubeadm-config.yaml kubeadm tool cannot find ETCd certs in /etc/kubernetes/etcd/ and trying to generate on and put it to:
/etc/kubernetes/pki/etcd/ directory.

**How to reproduce it (as minimally and precisely as possible)**:

Prepare kubeadm-config.yaml with ETCd config part like this one:

```yaml
etcd:
  external:
    endpoints:
    - https://etcd1.example.com:2379
    - https://etcd2.example.com:2379
    - https://etcd3.example.com:2379
    caFile: /etc/kubernetes/etcd/ca.pem
    certFile: /etc/kubernetes/etcd/client.pem
    keyFile: /etc/kubernetes/etcd/client-key.pem
```
Run
```bash
kubeadm upgrade apply --config /etc/kubernetes/kubeadm-config.yaml
```
**Anything else we need to know?**:
Was doing upgrade from Kubernetes 1.11.2 --> 1.11.3

**Environment**:
- Kubernetes version (use `kubectl version`):
```bash
kubectl version:
Client Version: "v1.11.2"
Server Version: "v1.11.2"
```
- Cloud provider or hardware configuration:
vSphere cluster + virtual machines
- OS (e.g. from /etc/os-release):
```bash
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
- Kernel (e.g. `uname -a`):
```bash
Linux master0 3.10.0-862.3.3.el7.x86_64 #1 SMP Fri Jun 15 04:15:27 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools:
- Others:
