### ISSUE TITLE
kubeadm config add apiServerExtraVolumes parameter,unable to initialize cluster.

### ISSUE THREAD

**Issue by lovebaicai** [kubernetes/kubeadm#1133]
#### The problem describe：
- use kubeadm initialize cluster,if add ```apiServerExtraVolumes``` parameter, process stuck at ```[init] This might take a minute or longer if the control plane images have to be pulled.```,cluster  initialize failed.
- delete ```apiServerExtraVolumes``` parameter, cluster initialize succeed.
- I guess add ```apiServerExtraVolumes```parameter,kube-apiserver pod unable to start.
#### initconfig:
```
apiVersion: kubeadm.k8s.io/v1alpha1
kind: MasterConfiguration
etcd:
  endpoints:
  - https://192.168.7.86:2379
  caFile: /etc/etcd/ssl/ca.pem
  certFile: /etc/etcd/ssl/etcd.pem
  keyFile: /etc/etcd/ssl/etcd-key.pem
  dataDir: /var/lib/etcd
networking:
  dnsDomain: cluster.local
  serviceSubnet: 10.18.0.0/20
kubernetesVersion: 1.10.0
api:
  advertiseAddress: "127.0.0.1"
apiServerCertSANs:
  - 192.168.7.86
  - 127.0.0.1
apiServerExtraVolumes:
  - name: localtime
    hostPath: /etc/localtime
    mountPath: /etc/localtime
featureGates:
  CoreDNS: true
```
#### initialize log：
```
[init] Using Kubernetes version: v1.10.0
[init] Using Authorization modes: [Node RBAC]
[preflight] Running pre-flight checks.
        [WARNING FileExisting-crictl]: crictl not found in system path
Suggestion: go get github.com/kubernetes-incubator/cri-tools/cmd/crictl
[preflight] Starting the kubelet service
[certificates] Generated ca certificate and key.
[certificates] Generated apiserver certificate and key.
[certificates] apiserver serving cert is signed for DNS names [k8s-config-test kubernetes kubernetes.default kubernetes.default.svc kubernetes.default.svc.cluster.local] and IPs [10.18.0.1 192.168.7.86 192.168.7.86 127.0.0.1]
[certificates] Generated apiserver-kubelet-client certificate and key.
[certificates] Generated etcd/ca certificate and key.
[certificates] Generated etcd/server certificate and key.
[certificates] etcd/server serving cert is signed for DNS names [localhost] and IPs [127.0.0.1]
[certificates] Generated etcd/peer certificate and key.
[certificates] etcd/peer serving cert is signed for DNS names [k8s-config-test] and IPs [192.168.7.86]
[certificates] Generated etcd/healthcheck-client certificate and key.
[certificates] Generated apiserver-etcd-client certificate and key.
[certificates] Generated sa key and public key.
[certificates] Generated front-proxy-ca certificate and key.
[certificates] Generated front-proxy-client certificate and key.
[certificates] Valid certificates and keys now exist in "/etc/kubernetes/pki"
[kubeconfig] Wrote KubeConfig file to disk: "/etc/kubernetes/admin.conf"
[kubeconfig] Wrote KubeConfig file to disk: "/etc/kubernetes/kubelet.conf"
[kubeconfig] Wrote KubeConfig file to disk: "/etc/kubernetes/controller-manager.conf"
[kubeconfig] Wrote KubeConfig file to disk: "/etc/kubernetes/scheduler.conf"
[controlplane] Adding extra host path mount "localtime" to "kube-apiserver"
[controlplane] Adding extra host path mount "localtime" to "kube-controller-manager"
[controlplane] Adding extra host path mount "localtime" to "kube-scheduler"
[controlplane] Wrote Static Pod manifest for component kube-apiserver to "/etc/kubernetes/manifests/kube-apiserver.yaml"
[controlplane] Wrote Static Pod manifest for component kube-controller-manager to "/etc/kubernetes/manifests/kube-controller-manager.yaml"
[controlplane] Wrote Static Pod manifest for component kube-scheduler to "/etc/kubernetes/manifests/kube-scheduler.yaml"
[init] Waiting for the kubelet to boot up the control plane as Static Pods from directory "/etc/kubernetes/manifests".
[init] This might take a minute or longer if the control plane images have to be pulled.
```
#### Thanks.
