### ISSUE TITLE
Kubeadm should run kube-proxy under its' own identity

### ISSUE THREAD

**Issue by andrewrynhard** [kubernetes/kubeadm#114]
kubeadm runs kube-proxy under the kubelet's identity. It should run under its' own identity.

**Comment by luxas** [comment]
@liggitt @deads2k Does it sound like a good idea to create a new flag to kube-proxy (`--use-inclusterconfig-creds` or something) where it reads the ca.crt and token from /var/run/secrets?

It would also take the `--master` parameter for knowing where the apiserver is.

Optionally, we could set `--kubernetes-service-node-port=30000` and set the `--master` flag to `localhost:30000` so kubelet will loadbalance the requests to the endpoints for the `kubernetes` service.

Does this sound good to you?

**Comment by deads2k** [comment]
> @liggitt @deads2k Does it sound like a good idea to create a new flag to kube-proxy (--use-inclusterconfig-creds or something) where it reads the ca.crt and token from /var/run/secrets?

I haven't looked at the kube-proxy arg handling in a very long time, but I'd expect it to take a `--kubeconfig` and the resolution of that kubeconfig works like `kubectl`, where if its missing, it attempts to use an in-cluster-config if it is available.

**Comment by mikedanese** [comment]
InClusterConfig uses the kubernetes service vip which isn't setup til the kube-proxy runs. We could however use a service account token.

**Comment by luxas** [comment]
Yes, @mikedanese @deads2k @liggitt are you in favor of a PR that adds a flag so kube-proxy reads the `ca.crt` and `token` from `/var/run/secrets` so we can use a kube-proxy-specific serviceaccount?

kube-proxy can't use the full inclusterconfig because of the chicken-and-egg situation, and we can't either add this functionality by default because it _could_ break existing users.

I could send a such PR next week if that sounds good, it should be pretty straightforward I guess

**Comment by liggitt** [comment]
I'd rather keep kube-proxy simple and make it the responsibility of the thing starting kube-proxy to build a kubeconfig for it.

if you want to run it in a daemonset, that would mean injecting a kubeconfig with the ca/token/master address you want. you can reference the service account token and ca.crt from that kubeconfig if you like:

```
kind: Config
apiVersion: v1
clusters:
- cluster:
    certificate-authority: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    server: https://master:masterport
  name: default
contexts:
- context:
    cluster: default
    namespace: default
    user: default
  name: default
current-context: default
users:
- name: default
  user:
    tokenfile: /var/run/secrets/kubernetes.io/serviceaccount/token
```
