### ISSUE TITLE
kubeadm join with pre-existing client certificate still prompts for bootstrap token

### ISSUE THREAD

**Issue by jstangroome** [kubernetes/kubeadm#1142]
## Versions

**kubeadm version** (use `kubeadm version`):
```
kubeadm version: &version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.0-rc.2", GitCommit:"5a80e28431c7469d677c5b17277266d1da4e5c8d", GitTreeState:"clean", BuildDate:"2018-09-21T21:59:51Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: Generic VM hosting, 8 core, 32GiB ram
- **OS** (e.g. from /etc/os-release): Ubuntu 16.04.5 LTS
- **Kernel** (e.g. `uname -a`): `Linux test-jason-1 4.4.0-135-generic #161-Ubuntu SMP Mon Aug 27 10:45:01 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

## What happened?

Executed `kubeadm join --discovery-file discovery.conf` on a to-be worker node with pre-issued and pre-signed client certificates already specified in the `discovery.conf` as per the feature requested in #945 and implemented in https://github.com/kubernetes/kubernetes/pull/66482.

`kubeadm join` exited immediately with the error message:
```tlsBootstrapToken: Invalid value: "": the bootstrap token is invalid```

The `tlsBootstrapToken` was not provided as a command-line argument, nor was it present in the `discovery.conf` file.

## What you expected to happen?

I expected `kubeadm join` to configure kubelet using the pre-issued client certificates and bypass the bootstrap token process.

## How to reproduce it (as minimally and precisely as possible)?

1. Provision a kubernetes master node.
1. Generate a new private key for the upcoming worker node.
1. Generate a certificate signing request (CSR) for the worker node.
1. Sign the CSR with the kubernetes master's CA key.
1. Obtain base64 encoded versions of the CA public key, the worker node private key, and the signed worker node public certificate.
1. Create a `discovery.conf` file on the new worker node to-be with the following contents, replacing the `{{ }}` place holders as per your environment and the signed certificate generated in the previous steps:
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: {{CA_CERT_PEM_BASE64}}
    server: https://{{CLUSTER_IP}}:6443
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: system:node:{{KUBELET_NAME}}
  name: system:node:{{KUBELET_NAME}}@kubernetes
current-context: system:node:{{KUBELET_NAME}}@kubernetes
kind: Config
preferences: {}
users:
- name: system:node:{{KUBELET_NAME}}
  user:
    client-certificate-data: {{KUBELET_CERT_PEM_BASE64}}
    client-key-data: {{KUBELET_PRIVATE_KEY_PEM_BASE64}}
```
1. Execute `kubeadm join --discovery-file discovery.conf` on the worker node to-be.
