### ISSUE TITLE
Kubeadm does not provide helpful error messages when config validation fails

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes/kubeadm#1159]
From  @seanhig  [comment](https://github.com/kubernetes/kubeadm/issues/1152#issuecomment-427017561) on #1152 

kubeadm returns 

```bash
[root@k8s-m1 admin]# kubeadm init --config /root/kube-adm.yml
host must be a valid IP address or a valid RFC-1123 DNS subdomain
```
 
When an unnecessary "http://" prefix in my template triggered the parse error

**Comment by fabriziopandini** [comment]
@seanhig
I tried to reproduce this use case adding "http://" prefix to the api server advertise address, and the result is:

```bash
vagrant@kubeadm-playground-master:~$ sudo kubeadm init --config=/etc/kubernetes/kubeadm-config.yml
couldn't use "http://10.10.10.11" as "apiserver-advertise-address", must be ipv4 or ipv6 address
```

Could you kindly support me in reproducing your problem?

**Comment by marksugar** [comment]
hello @fabriziopandini 
I have this problem in 1.13.1, I don't know what I missed.

```
localapiEndpoint:
  advertiseAddress: https://172.25.50.13
  bindPort: 6443
---
apiVersion: kubeadm.k8s.io/v1beta1
kind: ClusterConfiguration
kubernetesVersion: "v1.13.1"
controlPlaneEndpoint: https://172.25.50.15:6443
```
as follows
```
[root@DT_Node-172_25_50_13 ~]# kubeadm init --config ./kubeadm-init.yaml
host must be a valid IP address or a valid RFC-1123 DNS subdomain
```
thanks
