### ISSUE TITLE
Calico and podsubnet CIDR docs for kubeadm install need updating

### ISSUE THREAD

**Issue by andrevtg** [kubernetes/kubeadm#1185]
/kind bug

It seems to me that pod subnets in kubernetes 1.12 must be /24 (and not /16). Subnets are defined by "--pod-network-cidr" argument in kubeadm *OR* by a config file such as below:

```
apiVersion: kubeadm.k8s.io/v1alpha3
kind: InitConfiguration
api:
  advertiseAddress: 0.0.0.0
  bindPort: 6443
kubernetesVersion: v1.12.1
---
apiVersion: kubeadm.k8s.io/v1alpha3
kind: ClusterConfiguration
networking:
  podSubnet: 192.168.0.0/24
```

This behaviour also breaks calico setup even if you follow the docs for kubeadm setup.

I had to change CALICO_IPV4POOL_CIDR in "calico.yaml" to "192.168.0.0/24" and things worked fine.

**Environment**:
- Kubernetes version
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.1", GitCommit:"4ed3216f3ec431b140b1d899130a69fc671678f4", GitTreeState:"clean", BuildDate:"2018-10-05T16:36:14Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
Same behaviour on digital ocean CentOS droplets and in local on-prem CentOS VMs.
CentOS 7.5

- OS (e.g. from /etc/os-release):
CentOS 7.5 (on-prem)

- Install tools:
kubeadm

@kubernetes/sig-network-bugs
