### ISSUE TITLE
Support service-node-port-range when initializing kubeadm

### ISSUE THREAD

**Issue by anandanand84** [kubernetes/kubeadm#122]
Currently kubeadm doesn't support service-node-port-range flag in init.

kubeadm init --api-service-node-port-range=30000-32767
Error: unknown flag: --api-service-node-port-range

**Comment by luxas** [comment]
You can do this with the config file, see: https://kubernetes.io/docs/admin/kubeadm/

**Comment by chinglinwen** [comment]
Documents about config file part is unclear ( provide an example to config service-node-port-range? )

**Comment by chinglinwen** [comment]
Thank you for the reply, can I set the range to include 80, so I can
directly map dns name to that node.

I deployed Kong ingress controller, It's service node port is not 80,
service IP is not reachable, so it need outside nginx for ingress is not
good (no just extra layer adds latency, but duplicated nginx config for
every service too )

I'm not sure if it's the Kong's problem, just starting to figure out Kong
ingress.  : )

**Comment by dag24** [comment]
@chinglinwen I am also trying to deploy the Kong ingress controller. I am using kubeadm to create the cluster, not using GKE or AWS (so I cannot simply use `LoadBalancer` to expose it). In case it helps, here is what I did. First I started the cluster using a port range of 80-32767 (as root):

```
$ cat <<EOF > /tmp/kubeadm-init-args.conf
apiVersion: kubeadm.k8s.io/v1alpha1
kind: MasterConfiguration
apiServerExtraArgs:
  service-node-port-range: 80-32767
networking:
  podSubnet: 192.168.0.0/16
EOF

$ kubeadm init --config /tmp/kubeadm-init-args.conf
```

Then, I used `nodePort: 80` on the kong-proxy service:

```
apiVersion: v1
kind: Service
metadata:
  name: kong-proxy
  namespace: kong
spec:
  type: NodePort
  ports:
  - name: kong-proxy
    port: 80
    targetPort: 8000
    nodePort: 80
    protocol: TCP
  selector:
    app: kong
```

Now I can access the kong ingress on port 80. This feels a bit like a "dirty hack", but I have struggled to think of a better way. I am also still learning this. I also considered using iptables to force port 80 traffic to a NodePort in the usual range of 30000-32767. It seems to me like all documentation assumes you have something outside K8S that can map `80 --> 3xxxx`.
