### ISSUE TITLE
kubeadm init does't support feature-gates "HugePages=true"

### ISSUE THREAD

**Issue by pperiyasamy** [kubernetes/kubeadm#1250]
BUG REPORT

When I run kubeadm init with --feature-gates="HugePages=true" option, it fails with unrecognized feature-gate key: HugePages error.

root@ubuntu:~/pods# kubeadm init --pod-network-cidr=193.168.0.0/16 --ignore-preflight-errors Swap --feature-gates="HugePages=true"
unrecognized feature-gate key: HugePages

## Versions

kubeadm version: &version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-24T06:51:33Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}

NAME="Ubuntu"
VERSION="16.04.5 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.5 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

Linux ubuntu 4.4.0-131-generic #157-Ubuntu SMP Thu Jul 12 15:51:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

## What happened?
K8S cluster is not getting initialized with HugePages option, so can't allocate huge page for the pod as per this documentation https://kubernetes.io/docs/tasks/manage-hugepages/scheduling-hugepages/.

## What you expected to happen?
With this option, We should be able to allocate the hugepages inside the container for running high performance DPDK applications.

**Comment by neolit123** [comment]
hi, kubeadm supports different feature gates compared to core k8s.
if you want to enable HugePages you need to pass this gate to the kubelet.

this can be done with the kubeadm v1alpha3 config.
https://godoc.org/k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/v1alpha3

create a file called `config.yaml` and write something like this to the file:
```
apiVersion: kubeadm.k8s.io/v1alpha3
kind: InitConfiguration
nodeRegistration:
  kubeletExtraArgs:
    featureGates: "HugePages=true"
---
apiVersion: kubeadm.k8s.io/v1alpha3
kind: ClusterConfiguration
networking:
  podSubnet: "193.168.0.0/16"
```

then call it with:
```
kubeadm init --v=1 --ignore-preflight-errors=Swap --config=config.yaml
```

hope that helps.

**Comment by pperiyasamy** [comment]
hi, I have tried featureGates "HugePages=true" option with config.yaml, but still kubelet is not started and fails with the same error "server.go:148] unknown flag: --featureGates"

As per this [1] link, HugePages option is available only in Beta version from 1.10 and not in Alpha.
But when I try with the content for config.yaml file like below:

```
apiVersion: kubeadm.k8s.io/v1beta1
kind: InitConfiguration
nodeRegistration:
  kubeletExtraArgs:
    featureGates: "HugePages=true"
---
apiVersion: kubeadm.k8s.io/v1beta1
kind: ClusterConfiguration
networking:
  podSubnet: "193.168.0.0/16"
```

It fails with the error no kind "InitConfiguration" is registered for version "kubeadm.k8s.io/v1beta1" in scheme "k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/scheme/scheme.go:31"

[1] https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/

**Comment by fabriziopandini** [comment]
If I'm not wrong `ExtraArgs` is `map[string]string`so expected syntax is
```
nodeRegistration:
  kubeletExtraArgs:
    featureGates:
       HugePages: true
```
