### ISSUE TITLE
Kubeadm flag —experimental-control-plane in Config file

### ISSUE THREAD

**Issue by Joerg-L** [kubernetes/kubeadm#1251]
How can the flag  `- -experimental-control-plane ` for kubeadm join being set to the Configfile?

**Comment by neolit123** [comment]
i'm assuming you are using 1.13-beta?

this is example config to use on the joining control plane node.
```
apiVersion: kubeadm.k8s.io/v1beta1
kind: JoinConfiguration
controlPlane:
  localAPIEndpoint:
    advertiseAddress: <some-ip>
    bindPort: <some-port>
```
https://godoc.org/k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm#JoinControlPlane

**Comment by Joerg-L** [comment]
I’m just following this guide 
https://kubernetes.io/docs/setup/independent/high-availability/#external-etcd

I’m at the step `Run the copied kubeadm join command from above. Add the flag “–experimental-control-plane”` for adding an additional master.

As I need to set pod-infra-container-image, reference this [post](url
https://github.com/kubernetes/kubeadm/issues/1186#issuecomment-433138705), I’ need to know what to put into the config file for let the node join the cluster as additional master.

**Comment by neolit123** [comment]
this tutorial is for 1.12.
so you need `apiVersion: kubeadm.k8s.io/v1alpha3`.

try:
```
apiVersion: kubeadm.k8s.io/v1alpha3
kind: JoinConfiguration
controlPlane: "true"
localAPIEndpoint:
  advertiseAddress: <some-ip>
  bindPort: <some-port>
nodeRegistration:
  kubeletExtraArgs:
    pod-infra-container-image: "google-containers/pause:3.1"
```
