### ISSUE TITLE
Multi-scheduler example fails in Kubeadm

### ISSUE THREAD

**Issue by jpedro1992** [kubernetes/kubeadm#1274]
## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`):
> ```
> kubeadm version: &version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.0", GitCommit:"0ed33881dc4355495f623c6f22e7dd0b7632b7c0", GitTreeState:"clean", BuildDate:"2018-09-27T17:02:38Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
> ```

**Environment**:
- **Kubernetes version** (use `kubectl version`):
> ```
> Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.0", GitCommit:"0ed33881dc4355495f623c6f22e7dd0b7632b7c0", GitTreeState:"clean", BuildDate:"2018-09-27T17:05:32Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
>Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.0", GitCommit:"0ed33881dc4355495f623c6f22e7dd0b7632b7c0", GitTreeState:"clean", BuildDate:"2018-09-27T16:55:41Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
> ```

* **Cloud provider or hardware configuration**: Bare metal
* **OS** (e.g. from /etc/os-release):
> 
> ```
> NAME="Ubuntu"
> VERSION="16.04.1 LTS (Xenial Xerus)"
> PRETTY_NAME="Ubuntu 16.04.1 LTS"
> VERSION_ID="16.04"
> UBUNTU_CODENAME=xenial
> ```

* **Kernel** (e.g. `uname -a`): 
> ```
> Linux 4.4.0-34-generic #53-Ubuntu SMP Wed Jul 27 16:06:39 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
> ```

## What happened?

I am following the multi-scheduler example to deploy a new scheduler with an extender: 
[https://kubernetes.io/docs/tasks/administer-cluster/configure-multiple-schedulers/](url)

However, when I deploy the scheduler I get the following error:

* **Deploying the scheduler with a specific policy file** : 

> ```
> kubectl logs random-scheduler-67695848d-rg744 --namespace=kube-system random-scheduler
> W1123 10:45:18.454202       1 options.go:272] Neither --kubeconfig nor --master was specified. Using > default API client. This might not work.
> I1123 10:45:18.457089       1 server.go:128] Version: v1.12.3-beta.0
> W1123 10:45:18.457119       1 defaults.go:210] TaintNodesByCondition is enabled, >PodToleratesNodeTaints predicate is mandatory
> couldn't get policy config map kube-system/random-scheduler-config: configmaps "random->scheduler-config" is forbidden: User "system:serviceaccount:kube-system:random-scheduler" cannot >get > resource "configmaps" in API group "" in the namespace "kube-system"
> ```

* **Deploying the scheduler without the policy file** : 
> ```
>kubectl logs random-scheduler-6974d6fb67-6vcmx --namespace=kube-system random-scheduler
>W1123 13:42:15.412341       1 options.go:272] Neither --kubeconfig nor --master was specified. Using >default API client. This might not work.
>I1123 13:42:15.416298       1 server.go:128] Version: v1.12.3-beta.0
>W1123 13:42:15.416331       1 defaults.go:210] TaintNodesByCondition is enabled, >PodToleratesNodeTaints predicate is mandatory
>W1123 13:42:15.417120       1 authorization.go:47] Authorization is disabled
>W1123 13:42:15.417132       1 authentication.go:55] Authentication is disabled
>I1123 13:42:15.417142       1 deprecated_insecure_serving.go:48] Serving healthz insecurely on [::]:10251
>E1123 13:42:15.435403       1 reflector.go:134] k8s.io/client-go/informers/factory.go:131: Failed to list >*v1.StatefulSet: statefulsets.apps is forbidden: User "system:serviceaccount:kube-system:random->scheduler" cannot list resource "statefulsets" in API group "apps" at the cluster scope
>E1123 13:42:15.436020       1 reflector.go:134] k8s.io/client-go/informers/factory.go:131: Failed to list >*v1.ReplicaSet: replicasets.apps is forbidden: User "system:serviceaccount:kube-system:random->scheduler" cannot list resource "replicasets" in API group "apps" at the cluster scope
>E1123 13:42:15.436132       1 reflector.go:134] k8s.io/client-go/informers/factory.go:131: Failed to list >*v1beta1.PodDisruptionBudget: poddisruptionbudgets.policy is forbidden: User >"system:serviceaccount:kube-system:random-scheduler" cannot list resource "poddisruptionbudgets" >in API group "policy" at the cluster scope
>E1123 13:42:15.436323       1 reflector.go:134] k8s.io/client-go/informers/factory.go:131: Failed to list >*v1.StorageClass: storageclasses.storage.k8s.io is forbidden: User "system:serviceaccount:kube->system:random-scheduler" cannot list resource "storageclasses" in API group "storage.k8s.io" at the >cluster scope
>E1123 13:42:15.436579       1 reflector.go:134] k8s.io/client-go/informers/factory.go:131: Failed to list >*v1.PersistentVolumeClaim: persistentvolumeclaims is forbidden: User "system:serviceaccount:kube->system:random-scheduler" cannot list resource "persistentvolumeclaims" in API group "" at the cluster >scope
>E1123 13:42:15.436955       1 reflector.go:134] k8s.io/client-go/informers/factory.go:131: Failed to list >*v1.Node: nodes is forbidden: User "system:serviceaccount:kube-system:random-scheduler" cannot list >resource "nodes" in API group "" at the cluster scope
>E1123 13:42:15.436983       1 reflector.go:134] k8s.io/kubernetes/cmd/kube->scheduler/app/server.go:178: Failed to list *v1.Pod: pods is forbidden: User >"system:serviceaccount:kube-system:random-scheduler" cannot list resource "pods" in API group "" at >the cluster scope 
>E1123 13:42:15.437104       1 reflector.go:134] k8s.io/client-go/informers/factory.go:131: Failed to list >*v1.Service: services is forbidden: User "system:serviceaccount:kube-system:random-scheduler" cannot >list resource "services" in API group "" at the cluster scope
>...
>E1123 13:42:52.524780       1 reflector.go:134] k8s.io/client-go/informers/factory.go:131: Failed to list >*v1beta1.PodDisruptionBudget: poddisruptionbudgets.policy is forbidden: User >"system:serviceaccount:kube-system:random-scheduler" cannot list resource "poddisruptionbudgets" >in API group "policy" at the cluster scope
>E1123 13:42:52.525752       1 reflector.go:134] k8s.io/client-go/informers/factory.go:131: Failed to list >*v1.PersistentVolume: persistentvolumes is forbidden: User "system:serviceaccount:kube->system:random-scheduler" cannot list resource "persistentvolumes" in API group "" at the cluster scope
> ```

## What you expected to happen?

The new scheduler should be able to access the configmap and run properly. I believe there is an issue with the RBAC rules in kubeadm. The new scheduler cannot gain access to the policy file neither the API server.

## How to reproduce it (as minimally and precisely as possible)?
Install kubeadm with calico. Follow the multi-scheduler example :)

## Anything else we need to know?

scheduler-policy-file.yaml:

> ```
>kind: ConfigMap
>apiVersion: v1
>metadata:
>  name: random-scheduler-config
>  namespace: kube-system
>data:
>  policy.cfg: |
>    {
>        "kind" : "Policy",
>        "apiVersion" : "v1",
>        "metadata" : {
>            "name": "random-scheduler-config",
>            "namespace": "kube-system"
>        },
>        "predicates" : [
>            {"name" : "PodFitsResources"},
>            {"name" : "PodFitsHostPorts"},
>            {"name" : "NoDiskConflict"},
>            {"name" : "NoVolumeZoneConflict"},
>            {"name" : "PodToleratesNodeTaints"},
>            {"name" : "MatchInterPodAffinity"}
>        ],
>        "extenders": [
>            {
>                "urlPrefix": "http://127.0.0.1:8100",
>                "apiVersion": "v1",
>                "filterVerb": "filter",
>                "enableHttps": false
>            }
>        ]
>   }
>
> ```

random-scheduler.yaml:

> ```
>apiVersion: v1
>kind: ServiceAccount
>metadata:
>  name: random-scheduler
>  namespace: kube-system
>---
>kind: ClusterRoleBinding
>apiVersion: rbac.authorization.k8s.io/v1
>metadata:
>  name: random-scheduler-as-kube-scheduler
>subjects:
>- kind: ServiceAccount
>  name: random-scheduler
>  namespace: kube-system
>roleRef:
>  kind: ClusterRole
>  name: kube-scheduler
>  apiGroup: rbac.authorization.k8s.io
>---
>apiVersion: apps/v1
>kind: Deployment
>metadata:
>  labels:
>   component: scheduler
>    tier: control-plane
>  name: random-scheduler
>  namespace: kube-system
>spec:
>  selector:
>    matchLabels:
>      component: scheduler
>      tier: control-plane
>  replicas: 1
>  template:
>   metadata:
>      labels:
>        component: scheduler
>        tier: control-plane
>        version: second
>   spec:
>     serviceAccountName: random-scheduler
>     containers:
>     - name: extender
>        image: jpedro1992/random-scheduler:0.0.1
>        ports:
>          - containerPort: 8100
>     - name: random-scheduler
>        image: mirrorgooglecontainers/kube-scheduler:v1.12.3-beta.0
>        command:
>        - /usr/local/bin/kube-scheduler
>        - --address=0.0.0.0
>        - --leader-elect=false
>        - --scheduler-name=random-scheduler
>        - --policy-configmap=random-scheduler-config
>        - --policy-configmap-namespace=kube-system
>        livenessProbe:
>          httpGet:
>            path: /healthz
>            port: 10251
>          initialDelaySeconds: 15
>        readinessProbe:
>          httpGet:
>            path: /healthz
>            port: 10251
>        resources:
>          requests:
>            cpu: '0.1'
>        securityContext:
>          privileged: false
>        volumeMounts: []
>      hostNetwork: false
>      hostPID: false
>      volumes: []
> ```

**Comment by neolit123** [comment]
hello and thanks for the report. this seems more like a question for sig-scheduling /sig-auth in an issue to be added in the kubernetes/kubernetes issue tracker. but we usually recommend stackoverflow too as this doesn't seem like a bug.

> couldn't get policy config map kube-system/random-scheduler-config: configmaps "random->scheduler-config" is forbidden: User "system:serviceaccount:kube-system:random-scheduler" cannot >get > resource "configmaps" in API group "" in the namespace "kube-system"

if you got a running cluster using kubeadm, at that point interactions with the cluster that are not covered in the kubeadm guides are hard to be monitored and supported by the kubeadm team. :[

**Comment by timothysc** [comment]
We should rationalize the docs, this is a documentation problem and folks should use the standard kubeadm HA docs. 

/assign @timothysc 
/kind documentation

**Comment by Jpedro19** [comment]
I just tried to set it up with Katacoda and the scheduler works! Everything runs smoothly. 

Therefore, there must be an error with kubeadm when trying to access the policy configurations and the role of the kube-scheduler :/

**Comment by Adirio** [comment]
I was able to solve the first error by providing the service account of the random-scheduler the role `extension-apiserver-authentication-reader`.

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: random-scheduler-config-role-binding
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
- kind: ServiceAccount
  name: random-scheduler
  namespace: kube-system
```

I'm still having issues with the rest of the API.

**Comment by Adirio** [comment]
Okey I discovered all the roles you need for it to properly work:

```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: random-scheduler
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: random-scheduler-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:kube-scheduler
subjects:
- kind: ServiceAccount
  name: random-scheduler
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: random-scheduler-volume-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:volume-scheduler
subjects:
- kind: ServiceAccount
  name: random-scheduler
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: random-scheduler-config-role-binding
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
- kind: ServiceAccount
  name: random-scheduler
  namespace: kube-system
```
