### ISSUE TITLE
Kubeadm init successfully but kube-proxy and coredns pods not create

### ISSUE THREAD

**Issue by pytimer** [kubernetes/kubeadm#1275]
## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`):

```
[root@master211 ~]# kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-24T06:51:33Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Kubernetes version** (use `kubectl version`):
```
[root@master211 ~]# kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-24T06:54:59Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-24T06:43:59Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
```
- **Cloud provider or hardware configuration**:  virtual machine
- **OS** (e.g. from /etc/os-release):
```
[root@master211 ~]# cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
- **Kernel** (e.g. `uname -a`):
```
[root@master211 ~]# uname -a
Linux master211 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```
- **Others**:

kubeadm.yaml:
```yaml
[root@master211 ~]# cat kubeadm.yaml
apiVersion: kubeadm.k8s.io/v1alpha3
kind: ClusterConfiguration
kubernetesVersion: "v1.12.2"
metadata:
  name: 1.12-sample
apiServerCertSANs:
- "10.33.46.118"
- "cloud.kubernetes.cluster.test.lb"
controlPlaneEndpoint: "cloud.kubernetes.cluster.test.lb:6443"
etcd:
  local:
    serverCertSANs:
    - "10.33.46.211"
    - "10.33.46.118"
    peerCertSANs:
    - "10.33.46.211"
    extraArgs:
      initial-cluster: master211=https://10.33.46.211:2380
      initial-cluster-state: new
      name: master211
      listen-peer-urls: https://10.33.46.211:2380
      listen-client-urls: https://10.33.46.211:2379
      advertise-client-urls: https://10.33.46.211:2379
      initial-advertise-peer-urls: https://10.33.46.211:2380
      cipher-suites: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
networking:
    podSubnet: 10.244.0.0/16
```

/etc/hosts:
```
127.0.0.1 master211
10.33.46.118 cloud.kubernetes.cluster.test.lb
```

## What happened?

Run `kubeadm init --config kubeadm.yaml`  to initialize cluster, the init successfully. But `kubectl get pod -n kube-system`  not found coredns and kube-proxy pods. 

I lookup kube-proxy ds yaml, replicas is not set, and coredns replicas is two, but no pods create. So why? I don't know how to troubelshoot this problems. Anyone can help? Thanks.

## What you expected to happen?

coredns and kube-proxy pod created.

## Anything else we need to know?

This node init successfully that not use `controlPlaneEndpoint` in kubeadm.yaml before. 
Now i want to use `kubeadm join --experimental-control-plane`, so i run `kubeadm reset -f`, it also successfully. But when i init the first node is wrong.

<details>
<summary>kubeadm init logs:</summary>

[root@master211 ~]# kubeadm init --config  kubeadm.yaml
[init] using Kubernetes version: v1.12.2
[preflight] running pre-flight checks
[preflight/images] Pulling images required for setting up a Kubernetes cluster
[preflight/images] This might take a minute or two, depending on the speed of your internet connection
[preflight/images] You can also perform this action in beforehand using 'kubeadm config images pull'
[kubelet] Writing kubelet environment file with flags to file "/var/lib/kubelet/kubeadm-flags.env"
[kubelet] Writing kubelet configuration to file "/var/lib/kubelet/config.yaml"
[preflight] Activating the kubelet service
[certificates] Generated ca certificate and key.
[certificates] Generated apiserver certificate and key.
[certificates] apiserver serving cert is signed for DNS names [master211 kubernetes kubernetes.default kubernetes.default.svc kubernetes.default.svc.cluster.local cloud.kubernetes.cluster.test.lb cloud.kubernetes.cluster.test.lb] and IPs [10.96.0.1 10.33.46.211 10.33.46.118]
[certificates] Generated apiserver-kubelet-client certificate and key.
[certificates] Generated etcd/ca certificate and key.
[certificates] Generated etcd/server certificate and key.
[certificates] etcd/server serving cert is signed for DNS names [master211 localhost] and IPs [127.0.0.1 ::1 10.33.46.211 10.33.46.118]
[certificates] Generated etcd/peer certificate and key.
[certificates] etcd/peer serving cert is signed for DNS names [master211 localhost] and IPs [10.33.46.211 127.0.0.1 ::1 10.33.46.211]
[certificates] Generated etcd/healthcheck-client certificate and key.
[certificates] Generated apiserver-etcd-client certificate and key.
[certificates] Generated front-proxy-ca certificate and key.
[certificates] Generated front-proxy-client certificate and key.
[certificates] valid certificates and keys now exist in "/etc/kubernetes/pki"
[certificates] Generated sa key and public key.
[kubeconfig] Wrote KubeConfig file to disk: "/etc/kubernetes/admin.conf"
[kubeconfig] Wrote KubeConfig file to disk: "/etc/kubernetes/kubelet.conf"
[kubeconfig] Wrote KubeConfig file to disk: "/etc/kubernetes/controller-manager.conf"
[kubeconfig] Wrote KubeConfig file to disk: "/etc/kubernetes/scheduler.conf"
[controlplane] wrote Static Pod manifest for component kube-apiserver to "/etc/kubernetes/manifests/kube-apiserver.yaml"
[controlplane] wrote Static Pod manifest for component kube-controller-manager to "/etc/kubernetes/manifests/kube-controller-manager.yaml"
[controlplane] wrote Static Pod manifest for component kube-scheduler to "/etc/kubernetes/manifests/kube-scheduler.yaml"
[etcd] Wrote Static Pod manifest for a local etcd instance to "/etc/kubernetes/manifests/etcd.yaml"
[init] waiting for the kubelet to boot up the control plane as Static Pods from directory "/etc/kubernetes/manifests"
[init] this might take a minute or longer if the control plane images have to be pulled
[apiclient] All control plane components are healthy after 21.003826 seconds
[uploadconfig] storing the configuration used in ConfigMap "kubeadm-config" in the "kube-system" Namespace
[kubelet] Creating a ConfigMap "kubelet-config-1.12" in namespace kube-system with the configuration for the kubelets in the cluster
[markmaster] Marking the node master211 as master by adding the label "node-role.kubernetes.io/master=''"
[markmaster] Marking the node master211 as master by adding the taints [node-role.kubernetes.io/master:NoSchedule]
[patchnode] Uploading the CRI Socket information "/var/run/dockershim.sock" to the Node API object "master211" as an annotation
[bootstraptoken] using token: djo3is.6zoockaytd56i8ks
[bootstraptoken] configured RBAC rules to allow Node Bootstrap tokens to post CSRs in order for nodes to get long term certificate credentials
[bootstraptoken] configured RBAC rules to allow the csrapprover controller automatically approve CSRs from a Node Bootstrap Token
[bootstraptoken] configured RBAC rules to allow certificate rotation for all node client certificates in the cluster
[bootstraptoken] creating the "cluster-info" ConfigMap in the "kube-public" namespace
[addons] Applied essential addon: CoreDNS
[addons] Applied essential addon: kube-proxy

Your Kubernetes master has initialized successfully!

To start using your cluster, you need to run the following as a regular user:

  mkdir -p $HOME/.kube
  sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
  sudo chown $(id -u):$(id -g) $HOME/.kube/config

You should now deploy a pod network to the cluster.
Run "kubectl apply -f [podnetwork].yaml" with one of the options listed at:
  https://kubernetes.io/docs/concepts/cluster-administration/addons/

You can now join any number of machines by running the following on each node
as root:

  kubeadm join cloud.kubernetes.cluster.test.lb:6443 --token djo3is.6zoockaytd56i8ks --discovery-token-ca-cert-hash sha256:33f0f4271ff07e4be78a0cb33c789a60c1498986c24c3a8241f1c40fa7fdadd5
</details>
