### ISSUE TITLE
Upgrading to 1.13.1 annotates wrong cri socket

### ISSUE THREAD

**Issue by rmb938** [kubernetes/kubeadm#1322]
## Is this a BUG REPORT or FEATURE REQUEST?

Choose one: BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`): `kubeadm version: &version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:36:44Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}`

**Environment**:
- **Kubernetes version** (use `kubectl version`): `Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.3", GitCommit:"435f92c719f279a3a67808c80521ea17d5715c66", GitTreeState:"clean", BuildDate:"2018-11-26T12:57:14Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:31:33Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}`
- **Cloud provider or hardware configuration**: VMware vms
- **OS** (e.g. from /etc/os-release): `Red Hat Enterprise Linux Server release 7.5`
- **Kernel** (e.g. `uname -a`): `4.19.8-1.el7.elrepo.x86_64`

## What happened?

Ran `kubeadm upgrade apply --config /etc/kubernetes/kubeadm.yaml 1.13.1`

Node annotation was changed to `kubeadm.alpha.kubernetes.io/cri-socket: /var/run/dockershim.sock`

## What you expected to happen?

The cri-socket annotation on the node not to change.

Node annotation should stay as `kubeadm.alpha.kubernetes.io/cri-socket: /var/run/containerd/containerd.sock`

I'm not sure if this annotation is actually used for anything, I don't see it causing any issues.

## How to reproduce it (as minimally and precisely as possible)?

Run upgrade apply with a InitConfiguration that sets the cri-socket

## Anything else we need to know?

kubeadm.yaml

```
---
apiVersion: kubeadm.k8s.io/v1beta1
kind: InitConfiguration
bootstrapTokens:
  - token: rku5l9.qsociq1kv9vcckzu
    ttl: "0"
    groups:
      - system:bootstrappers:kubeadm:default-node-token
    usages:
      - signing
      - authentication
nodeRegistration:
  criSocket: /var/run/containerd/containerd.sock
  kubeletExtraArgs:
    runtime-cgroups: /system.slice/containerd.service
    container-runtime: remote
    runtime-request-timeout: 15m
    container-runtime-endpoint: unix:///run/containerd/containerd.sock
---
apiVersion: kubeadm.k8s.io/v1beta1
kind: ClusterConfiguration
etcd:
  external:
    endpoints:
    - https://localhost:2379
    caFile: /etc/kubernetes/pki/etcd/ca.crt
    certFile: /etc/kubernetes/pki/apiserver-etcd-client.crt
    keyFile: /etc/kubernetes/pki/apiserver-etcd-client.key
networking:
  serviceSubnet: 100.96.0.0/16
  podSubnet: 100.97.0.0/16
  dnsDomain: cluster.local

controllerManager:
  extraArgs:
    terminated-pod-gc-threshold: "100"

apiServer:
  extraArgs:
    apiserver-count: "3"

dns:
  type: CoreDNS
```

**Comment by yuexiao-wang** [comment]
I think you should run `kubeadm upgrade apply --config /etc/kubernetes/kubeadm.yaml 1.13.1 --cri-socket /var/run/containerd/containerd.sock`
if you don't set --cri-socket, the default cri-socket is "/var/run/dockershim.sock".

$ /kubeadm upgrade apply --help
Upgrade your Kubernetes cluster to the specified version.

Usage:
  kubeadm upgrade apply [version]

Flags:
      --allow-experimental-upgrades        Show unstable versions of Kubernetes as an upgrade alternative and allow upgrading to an alpha/beta/release candidate versions of Kubernetes.
      --allow-release-candidate-upgrades   Show release candidate versions of Kubernetes as an upgrade alternative and allow upgrading to a release candidate versions of Kubernetes.
      --config string                      Path to a kubeadm configuration file.
      **--cri-socket string                  Specify the CRI socket to connect to. (default "/var/run/dockershim.sock")**

**Comment by rmb938** [comment]
Well I am setting it in the kubeadm configuration, I've also never had to set this for any other upgrade. If this is a change it should have been reflected in the change log and documentation. 

Everything works perfectly fine aside from the annotation being set on the node.

**Comment by neolit123** [comment]
> Well I am setting it in the kubeadm configuration, I've also never had to set this for any other upgrade

can you share you config, please.

**Comment by rmb938** [comment]
It's in the first comment but I'll post it again

```
---
apiVersion: kubeadm.k8s.io/v1beta1
kind: InitConfiguration
bootstrapTokens:
  - token: rku5l9.qsociq1kv9vcckzu
    ttl: "0"
    groups:
      - system:bootstrappers:kubeadm:default-node-token
    usages:
      - signing
      - authentication
nodeRegistration:
  criSocket: /var/run/containerd/containerd.sock
  kubeletExtraArgs:
    runtime-cgroups: /system.slice/containerd.service
    container-runtime: remote
    runtime-request-timeout: 15m
    container-runtime-endpoint: unix:///run/containerd/containerd.sock
---
apiVersion: kubeadm.k8s.io/v1beta1
kind: ClusterConfiguration
etcd:
  external:
    endpoints:
    - https://localhost:2379
    caFile: /etc/kubernetes/pki/etcd/ca.crt
    certFile: /etc/kubernetes/pki/apiserver-etcd-client.crt
    keyFile: /etc/kubernetes/pki/apiserver-etcd-client.key
networking:
  serviceSubnet: 100.96.0.0/16
  podSubnet: 100.97.0.0/16
  dnsDomain: cluster.local

controllerManager:
  extraArgs:
    terminated-pod-gc-threshold: "100"

apiServer:
  extraArgs:
    apiserver-count: "3"

dns:
  type: CoreDNS
```
