### ISSUE TITLE
Unable to deploy cluster using custom hyperkube image from my docker repository

### ISSUE THREAD

**Issue by divyenpatel** [kubernetes/kubeadm#1370]
## Is this a request for help?
Yes

## Versions

**kubeadm version** (use `kubeadm version`):
```
kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-10T23:33:30Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Kubernetes version** (use `kubectl version`):
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-10T23:35:51Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}
```

- **Cloud provider or hardware configuration**:
vSphere Cloud Provider
- **OS** (e.g. from /etc/os-release):
```
# cat /etc/os-release
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
```
- **Kernel** (e.g. `uname -a`):
```
Linux k8s-master 4.4.0-87-generic #110-Ubuntu SMP Tue Jul 18 12:55:35 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```
- **Others**:

## What happened?

I have custom hyperkube image located on my docker hub repository - docker.io/divyen/hyperkube-amd64:v1.13.1

I have my own version of kubelet to download from some web URL.

How do I tell kubeadm to pull hyperkube image from my repository? 
Is there any configuration we can set in the `cluster-init.yaml` file, so kubeadm picks up the binary and hyperkube from specified location?

Here is what I do
```
# cat cluster-init.yaml 
apiVersion: kubeadm.k8s.io/v1beta1
kind: ClusterConfiguration
imageRepository: docker.io/divyen
useHyperKubeImage: true
kubernetesVersion: v1.13.1
networking:
  podSubnet: 10.32.0.0/12
apiServer:
  certSANs:
  - "10.192.128.77"
  extraArgs:
    cloud-provider: vsphere
    cloud-config: /etc/kubernetes/pki/vsphere.conf
controlPlaneEndpoint: "10.192.128.77:6443"
controllerManager:
  extraArgs:
    cloud-config: /etc/kubernetes/pki/vsphere.conf
    cloud-provider: vsphere
```

```
kubeadm init --config cluster-init.yaml
[init] Using Kubernetes version: v1.13.1
[preflight] Pulling images required for setting up a Kubernetes cluster
[preflight] This might take a minute or two, depending on the speed of your internet connection
[preflight] You can also perform this action in beforehand using 'kubeadm config images pull'
error execution phase preflight: [preflight] Some fatal errors occurred:
	[ERROR ImagePull]: failed to pull image docker.io/divyen/hyperkube:v1.13.1: output: Error response from daemon: repository divyen/hyperkube not found: does not exist or no pull access
, error: exit status 1
	[ERROR ImagePull]: failed to pull image docker.io/divyen/pause:3.1: output: Error response from daemon: repository divyen/pause not found: does not exist or no pull access
, error: exit status 1
	[ERROR ImagePull]: failed to pull image docker.io/divyen/etcd:3.2.24: output: Error response from daemon: repository divyen/etcd not found: does not exist or no pull access
, error: exit status 1
	[ERROR ImagePull]: failed to pull image docker.io/divyen/coredns:1.2.6: output: Error response from daemon: repository divyen/coredns not found: does not exist or no pull access
, error: exit status 1
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
```

## What you expected to happen?

* How do I specify image tag and image name here in the `cluster-init.yaml` file?
   My image name and tag is hyperkube-amd64:v1.13.1.

* why pause, etcd and coredns is getting pulled from `docker.io/divyen`? How do I specify images for these components in the `cluster-init.yaml` file.

* Is there a way I can use `kubelet` from hyperkube image? 

## How to reproduce it (as minimally and precisely as possible)?
execute `kubeadm init --config cluster-init.yaml` using cluster-init.yaml specified in this issue.

**Comment by divyenpatel** [comment]
Thanks @fabriziopandini for Config file documentation.
I have already used imageRepository in the config file.

How do I specify image name and image tag.

Another thing  I could not find, How do I specify image repository for rest of the components - `pause `, `etcd `, `coredns`. 

I want them to be pulled from default repository `k8s.gcr.io` and not from the repository where my hyperkube image is located.

**Comment by neolit123** [comment]
`hyperkube-amd64:v1.13.1`
kubeadm adds the arch suffix automatically.
i guess you can also just rename it .

or your custom image has to be a FAT manifest:
https://docs.docker.com/registry/spec/manifest-v2-2/

> Another thing I could not find, How do I specify image repository for rest of the components:
the easiest solution is to push the missing images to your repo.

alternatively you can set individual `ImageMeta` for dns and etcd but not for pause:
https://godoc.org/k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/v1beta1#ClusterConfiguration

so pause:3.1 has to be copied.

**Comment by divyenpatel** [comment]
Thanks @neolit123 

Using following yaml file, I am able to pull etcd and CoreDNS from `k8s.gcr.io` repository.
But regarding `amd64 ` arch suffix, I am not sure where to specify this in the kubeadm config file?
For now I am using rename hack.


```
apiVersion: kubeadm.k8s.io/v1beta1
kind: InitConfiguration
nodeRegistration:
  kubeletExtraArgs:
    cloud-provider: vsphere
    cloud-config: /etc/kubernetes/pki/vsphere.conf
---
apiVersion: kubeadm.k8s.io/v1beta1
kind: ClusterConfiguration
imageRepository: docker.io/divyen
useHyperKubeImage: true
kubernetesVersion: v1.13.1
networking:
  serviceSubnet: "10.244.0.0/16"
  podSubnet: "10.244.0.0/16"
etcd:
  local:
    imageRepository: "k8s.gcr.io"
    imageTag: "3.2.24"
dns:
  type: "CoreDNS"
  imageRepository: "k8s.gcr.io"
  imageTag: "1.2.6"
apiServer:
  extraArgs:
    cloud-provider: vsphere
    cloud-config: /etc/kubernetes/pki/vsphere.conf
controllerManager:
  extraArgs:
    cloud-config: /etc/kubernetes/pki/vsphere.conf
    cloud-provider: vsphere
```
