### ISSUE TITLE
Tracking issue for tracking forced configuration parameters

### ISSUE THREAD

**Issue by bart0sh** [kubernetes/kubeadm#1378]
This is a tracking issue for implementing correct handling of overriding configuration parameters. The goal of it is to list all overrides and decide how to handle them in a user-friendly and generic manner.

Currently at least some of the parameters are simply ignored, which confuses users. Example issues: #1254, #1252, #1028

[Preliminary list of parameters to check:](https://github.com/kubernetes/kubernetes/blob/23111ad414933027d0e2e297461477d0f9d267fd/cmd/kubeadm/app/componentconfigs/defaults.go#L88-L109):

- externalkubeletcfg.Authentication.X509.ClientCAFile
- externalkubeletcfg.Authorization.Mode
- externalkubeletcfg.Authentication.Webhook.Enabled
- externalkubeletcfg.ReadOnlyPort
- externalkubeletcfg.RotateCertificates
- externalkubeletcfg.HealthzBindAddress
- externalkubeletcfg.HealthzPort

Possible solution: Add warnings when parameters are overriden specifying a reason for override.

**Comment by fabriziopandini** [comment]
Another kubeadm override I'm aware of is [here](https://github.com/kubernetes/kubernetes/blob/46fc4dd96aadd2287ebb3ae769240b368552e7bf/cmd/kubeadm/app/phases/controlplane/manifests.go#L204): it enforce authorization modes in the kube-apiserver overriding user ExtraArgs

**Comment by bart0sh** [comment]
@neolit123 How this will help to detect overrides made in user config (similar to failSwapOn)? For example, if user puts "makeIPTablesUtilChains = false" or "syncFrequency: 10s" or one of dozens other parameters into config and run "kubeadm init/join/upgrade/etc --config <config>" with it. User would expect those parameters to be used and kubeadm should warn user if it's not the case.

**Comment by neolit123** [comment]
> How this will help to detect overrides made in user config (similar to failSwapOn)

its manual, no detection.
there is no easy way to do detection and even if we can i don't think we should.

we basically need a wrapper that either updates + prints warning or a utility that prints that some fields were overwritten.

**Comment by neolit123** [comment]
in my opinion we should only address the kubelet overrides, for now.
but i will leave it to others to comment too.

**Comment by fabriziopandini** [comment]
My understanding is that so far we know only two points into he code where kubeadm makes overrides one for kubelet config and one for the API servers extra args; Overall there are less then 10 attributes overwritten by kubeadm.
If that's correct, I don't see value in investing time for building a sophisticated solution for detecting what kubeadm overrides. Let's keep this simple, even if this implies less adaptability to future changes.

However I`m a little bit concerned about how we want the warning to surface to the user, because those overrides a deep in the call stack, because I don't like the Idea of having printf spreading in the code base (we already have two much of them). Any thoughts about this?

**Comment by neolit123** [comment]
> However I`m a little bit concerned about how we want the warning to surface to the user, because those overrides a deep in the call stack, because I don't like the Idea of having printf spreading in the code base (we already have two much of them). Any thoughts about this?

we can use an interface that collects the problem fields in a shared bucket and print them only on the CLI side.

**Comment by chuckha** [comment]
Once we gather a list of everything that is overridden (we will miss some and that's ok, we can improve with time) we will have the ability to let the user know ASAP when we're about to override a value they've set. The printfs won't be nested deep in the code and it could be on initial validation. It does require maintaining a list by hand though.

**Comment by bart0sh** [comment]
Yet another issue that's caused by kubelet ignoring configuration file options. Copied from slack:
```
Hi i try to join a node via config file:
apiVersion: kubeadm.k8s.io/v1beta1
kind: JoinConfiguration
ControlPlane: 
  localAPIEndpoint:
    advertiseAddress: 10.99.120.12
    bindPort: 6443
Discovery:
  BootstrapToken:
    APIServerEndpoint: 10.99.120.10:6443
    Token: zrnbq.o2gjhna4324sgpis
    CACertHashes: 
      - 38966069b81fc8f3234553b3d6be7cf3dd233fe1adbb3803b63db2d2f17aa836```
but still getting
   root@k8s-master-2:~# kubeadm join --config kubeadm-config-k8s-master-2.yaml
discovery: Invalid value: "": bootstrapToken or file must be set
```
