### ISSUE TITLE
Internal dns entries for externalNames stopped working in v1.13.3 ?

### ISSUE THREAD

**Issue by sokoow** [kubernetes/kubeadm#1420]
## Is this a BUG REPORT or FEATURE REQUEST?
BUG REPORT 

## Versions

**kubeadm version** (use `kubeadm version`):

```
kubeadm version: &version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:05:53Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Kubernetes version** (use `kubectl version`):
``` $ kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:08:12Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:00:57Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}```

## What happened?
At some stage in kubeadm, 2-3 versions back resolving externalNames on internal kube dns stopped working. 

## What you expected to happen?

This used to work pretty well. 

## How to reproduce it (as minimally and precisely as possible)?

Create an externalName svc, try to resolve it from any pod.

## Anything else we need to know?

There are workarounds, like creating an endpoint, but it's awkward.

**Comment by bart0sh** [comment]
> Create an externalName svc, try to resolve it from any pod.

can you give exact steps to reproduce the issue please?

**Comment by sokoow** [comment]
Sure:

1. Initialize the cluster using ```kubeadm init```
2. add overlay manifest
3. add this externalName manifest:

```
apiVersion: v1
kind: Service
metadata:
   name: postgres1-rds
   labels:
     k8s-app: postgres1-rds
     kubernetes.io/name: "postgres1-rds"
spec:
   type: ExternalName
   externalName: 10.16.2.8
   ports:
     - port: 5432
       targetPort: 5432
```
4. Try to use this externalName from any other pod by calling postgres1-rds.default:5432

**Comment by bart0sh** [comment]
thanks. Can you elaborate on items 2 and 4 a bit more?

**Comment by bart0sh** [comment]
> This used to work pretty well.

in which k8s release did it work for you last time?

**Comment by sokoow** [comment]
1.10.something - but maybe we'll need more samples of other people to confirm that.

**Comment by neolit123** [comment]
> 2\. add overlay manifest

which CNI plugin are you using?
have you tried with a different one?

**Comment by sokoow** [comment]
I tried flannel and weave already, same problem.

**Comment by sokoow** [comment]
what works is this workaround that I found on internetz:

```
apiVersion: v1
kind: Service
metadata:
  name: postgres1-rds
  namespace: default
spec:
  clusterIP: None
  ports:
  - name: db
    port: 5432
    protocol: TCP
---
kind: Endpoints
apiVersion: v1
metadata:
  name: postgres1-rds
  namespace: default
subsets:
  - addresses:
      - ip: 10.16.10.20
    ports:
      - port: 5432
        name: db
        protocol: TCP
```
