### ISSUE TITLE
Ability to add sidecar containers to static pod manifests

### ISSUE THREAD

**Issue by dsexton** [kubernetes/kubeadm#1490]
## Is this a BUG REPORT or FEATURE REQUEST?

FEATURE REQUEST

It would be helpful if kubeadm had the ability add additional containers to the generated static pod manifests. For example, adding the [aws-encryption-provider](https://github.com/kubernetes-sigs/aws-encryption-provider) to the apiserver pod.

Example:

```yaml
apiVersion: kubeadm.k8s.io/v1beta1
kind: ClusterConfiguration
apiServer:
  extraArgs:
    cloud-provider: "aws"
  extraContainers:
    - name: aws-encryption-provider
      image: k8s.gcr.io/aws-encryption-provider:v0.1.0
      resources:
        limits:
          memory: "200Mi"
        requests:
          memory: "100Mi"
```

You could have a fixed one-off just for encryption provider support, however having this be generic could provide a solution to other use cases down the road.

## Misc References

- [PR for adding aws-encryption-provider to kops](https://github.com/kubernetes/kops/pull/4973)
- [Using a KMS provider for data encryption](https://kubernetes.io/docs/tasks/administer-cluster/kms-provider/)

/cc @chuckha @sethpollack
