### ISSUE TITLE
kubeadm join node display error information not quite incorrect

### ISSUE THREAD

**Issue by pytimer** [kubernetes/kubeadm#1525]
## Is this a BUG REPORT or FEATURE REQUEST?

Choose one: BUG REPORT or FEATURE REQUEST

FEATURE REQUEST

## Versions

**kubeadm version** (use `kubeadm version`):

```sh
[root@k8s-1 ~]# kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:08:49Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Kubernetes version** (use `kubectl version`):
```sh
[root@k8s-1 ~]# kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:02:58Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
```
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
```sh
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
- **Kernel** (e.g. `uname -a`):
```sh
Linux k8s-1 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```
- **Others**:

## What happened?

I create a cluster using `kubeadm`, i run `kubeadm join --config=kubeadm-client.yaml `  join worker to cluster, i forget to set `discovery.bootstrapToken.apiServerEndpoint` and then the kubeadm return log:
```sh
[discovery.bootstrapToken: Required value: APIServerEndpoint is not set, discovery.bootstrapToken.apiServerEndpoints: Invalid value: "": missing port in address]
```

## What you expected to happen?

I think `discovery.bootstrapToken.apiServerEndpoints` -> `discovery.bootstrapToken.apiServerEndpoint` in log. Is it right? Because if it show `discovery.bootstrapToken.apiServerEndpoints` is inconsistent with the configuration.

Correct config file like:
```yaml
apiVersion: kubeadm.k8s.io/v1beta1
kind: JoinConfiguration
discovery:
  bootstrapToken:
    token: "pm0xtx.yvk9eft8fuopdbxj"
    caCertHashes:
    - "sha256:c918c82136d97dd2c84ad58d68831b8e6f04599c86e48b79b6bf6fad63c06160"
    apiServerEndpoint: "kubernetes.cluster.cloud.lb:6443"
```
