### ISSUE TITLE
Do not enable static pods on non-control plane nodes by default

### ISSUE THREAD

**Issue by joshrosso** [kubernetes/kubeadm#1541]
## FEATURE REQUEST

Non-control plane nodes run their kubelets with static pods enabled. I _think_ this is unnecessary and may even provide a security risk. As a process or workload that gains `hostPath` access can arbitrarily place manifests in `/etc/kubernetes/manifests` and run privileged workloads.

My suggestion is to not include the following in `/var/lib/kubelet/config.yaml`.

```
staticPodPath: /etc/kubernetes/manifests
```

This applies to all nodes that are not joined as control plane nodes.

Let me know if this makes sense. If it does, I would be happy to make the change.

## Versions

**kubeadm version**:

```
kubeadm version: &version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:51:21Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:

- **Kubernetes version**:

  ```
  Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:08:12Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
  Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:45:25Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
  ```

**Comment by neolit123** [comment]
static pods are still considered as an alternative way to run a workload on a node.
the user might decide to not manage it via the API server and scheduler so this does have some non-common benefits.

> staticPodPath: /etc/kubernetes/manifests

if we remove this capability now, we might be breaking existing workload scenarios, even if they might be rare.

> As a process or workload that gains hostPath access can arbitrarily place manifests in /etc/kubernetes/manifests and run privileged workloads.

such a workload would need to be privileged to write to the default manifest path. so it feels like this a decision in the hands of the operator - i.e. don't give questionable workloads a privileged run?

said workload writing manifest in the default path can indeed result in pods being spawned, but i think i would consider this a node-level compromise and the only attack that can reach the API server would be a DDoS in terms of mirror pods.

but let's get more opinions on this.

@kubernetes/sig-cluster-lifecycle-pr-reviews 
/assign @mauilion @timothysc 
for evaluation.

**Comment by pytimer** [comment]
We run ovs-agent by static pod, so the kubelet default static pod path is useful to me.If we remove this  capability, i must change other way to deploy ovs-agent.

If we remove this capability, it should support other way instead of static pod.

**Comment by joshrosso** [comment]
@pytimer: for my learning, why run ovs-agent as a static pod rather than a daemonset?

@neolit123:

> such a workload would need to be privileged to write to the default manifest path. so it feels like this a decision in the hands of the operator - i.e. don't give questionable workloads a privileged run? ..... but i think i would consider this a node-level compromise

I believe the exploitation scenario would only require the following.

1. Using `hostPaths` was not restricted on the workload.
1. The workload's process is allowed to run as root inside the container.

Here is my testing to prove this out. If I am misinterpreting the results, let me know.

I have created a `default` pod security policy to replicate this.

```
NAME          PRIV    CAPS               SELINUX    RUNASUSER   FSGROUP     SUPGROUP    READONLYROOTFS   VOLUMES
default       false                      RunAsAny   RunAsAny    MustRunAs   MustRunAs   false            configMap,emptyDir,projected,secret,hostPath,downwardAPI,persistentVolumeClaim
```

Note that `spec.priveleged: false` but I have "accidentally" allowed containers to run their processes as root and leverage `hostPath`.

I have deployed the following workload.

```yaml
apiVersion: 
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: org-1
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1 
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        securityContext:
          runAsUser: 0
        image: joshrosso/test:1.0
        command:
          - sleep
          - "600000"
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: /home/aaaa
            name: test-volume
      volumes:
      - name: test-volume
        hostPath:
          # directory location on host
          path: /etc/kubernetes/manifests
          # this field is optional
          type: DirectoryOrCreate
```


```
kubectl -n org-1 get po nginx-deployment-6b89bddbbf-67cp9 -o yaml | grep -i psp
```

```
kubernetes.io/psp: default
```

Due to the mapping above `/home/aaaa` has been chown'd to `root:root`, but, since I'm running as root in the container:

I can now exec into the container and start writing to `/home/aaaa` (mapped to `/etc/kubernetes/manifests`).

My thought process as to why static pods should not be enabled by default are as follows.

1. Don't run something that's generally not used.
1. Static pods (in my experience) should usually be daemonsets. Turning it on by default can encourage bad behavior.
1. The above exploit
    1. albeit very specific and requires bad configuration.

However, your point about it being a breaking change is very fair. In the field, I'll probably just have to explicitly disable this in future joins. Thanks for the input.
