### ISSUE TITLE
kubeadm stuck updating kube-scheduler static pod

### ISSUE THREAD

**Issue by juliohm1978** [kubernetes/kubeadm#1546]
## What keywords did you search in kubeadm issues before filing this one?
kubeadm stuck Static pod

## Is this a BUG REPORT or FEATURE REQUEST?

Choose one: BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`):
kubeadm version: &version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.3", GitCommit:"435f92c719f279a3a67808c80521ea17d5715c66", GitTreeState:"clean", BuildDate:"2018-11-26T12:54:02Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:

- **Kubernetes version** (use `kubectl version`): 
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.3", GitCommit:"435f92c719f279a3a67808c80521ea17d5715c66", GitTreeState:"clean", BuildDate:"2018-11-26T12:46:57Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.3", GitCommit:"435f92c719f279a3a67808c80521ea17d5715c66", GitTreeState:"clean", BuildDate:"2018-11-26T12:46:57Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}

- **Cloud provider or hardware configuration**: Baremetal/VM

- **OS** (e.g. from /etc/os-release):
```
# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic
```

- **Kernel** (e.g. `uname -a`):
Linux k8s-master01-dev 4.15.0-45-generic #48-Ubuntu SMP Tue Jan 29 16:28:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

## What happened?
Not really a version upgrade, but rather, just using Kubespray to add more nodes in the cluster, but it gets stuck exceuting the following:

```
/usr/local/bin/kubeadm upgrade apply -y v1.12.7 --config=/etc/kubernetes/kubeadm-config.v1alpha3.yaml --ignore-preflight-errors=all --allow-experimental-upgrades --allow-release-candidate-upgrades --etcd-upgrade=false --force
```

Kubeadm shows the following output

```
[preflight] Running pre-flight checks.
[upgrade] Making sure the cluster is healthy:
[upgrade/config] Making sure the configuration is correct:
[upgrade/config] Reading configuration options from a file: /etc/kubernetes/kubeadm-config.v1alpha3.yaml
[upgrade/apply] Respecting the --cri-socket flag that is set with higher priority than the config file.
[upgrade/version] You have chosen to change the cluster version to "v1.12.7"
[upgrade/versions] Cluster version: v1.12.7
[upgrade/versions] kubeadm version: v1.12.7
[upgrade/prepull] Will prepull images for components [kube-apiserver kube-controller-manager kube-scheduler etcd]
[upgrade/prepull] Prepulling image for component etcd.
[upgrade/prepull] Prepulling image for component kube-apiserver.
[upgrade/prepull] Prepulling image for component kube-controller-manager.
[upgrade/prepull] Prepulling image for component kube-scheduler.
[apiclient] Found 1 Pods for label selector k8s-app=upgrade-prepull-kube-controller-manager
[apiclient] Found 0 Pods for label selector k8s-app=upgrade-prepull-etcd
[apiclient] Found 0 Pods for label selector k8s-app=upgrade-prepull-kube-scheduler
[apiclient] Found 1 Pods for label selector k8s-app=upgrade-prepull-kube-apiserver
[apiclient] Found 1 Pods for label selector k8s-app=upgrade-prepull-etcd
[apiclient] Found 1 Pods for label selector k8s-app=upgrade-prepull-kube-scheduler
[upgrade/prepull] Prepulled image for component kube-controller-manager.
[upgrade/prepull] Prepulled image for component etcd.
[upgrade/prepull] Prepulled image for component kube-scheduler.
[upgrade/prepull] Prepulled image for component kube-apiserver.
[upgrade/prepull] Successfully prepulled the images for all the control plane components
[upgrade/apply] Upgrading your Static Pod-hosted control plane to version "v1.12.7"...
Static pod: kube-apiserver-k8s-master01-lab hash: f0fa191a32341e7af401d76b1151ab2c
Static pod: kube-controller-manager-k8s-master01-lab hash: b8c4394fe06f6b77928cb0c052e70d34
Static pod: kube-scheduler-k8s-master01-lab hash: 6b0b582c40f8558c7f9d58be2df41c1e
[upgrade/staticpods] Writing new Static Pod manifests to "/etc/kubernetes/tmp/kubeadm-upgraded-manifests142361161"
[controlplane] wrote Static Pod manifest for component kube-apiserver to "/etc/kubernetes/tmp/kubeadm-upgraded-manifests142361161/kube-apiserver.yaml"
[controlplane] wrote Static Pod manifest for component kube-controller-manager to "/etc/kubernetes/tmp/kubeadm-upgraded-manifests142361161/kube-controller-manager.yaml"
[controlplane] wrote Static Pod manifest for component kube-scheduler to "/etc/kubernetes/tmp/kubeadm-upgraded-manifests142361161/kube-scheduler.yaml"
[upgrade/staticpods] Moved new manifest to "/etc/kubernetes/manifests/kube-apiserver.yaml" and backed up old manifest to "/etc/kubernetes/tmp/kubeadm-backup-manifests-2019-04-29-16-35-18/kube-apiserver.yaml"
[upgrade/staticpods] Waiting for the kubelet to restart the component
[upgrade/staticpods] This might take a minute or longer depending on the component/version gap (timeout 5m0s
Static pod: kube-apiserver-k8s-master01-lab hash: f0fa191a32341e7af401d76b1151ab2c
Static pod: kube-apiserver-k8s-master01-lab hash: f0fa191a32341e7af401d76b1151ab2c
Static pod: kube-apiserver-k8s-master01-lab hash: f79f3764f5c01c03d3f2a137b373aad6
[apiclient] Found 1 Pods for label selector component=kube-apiserver
[upgrade/staticpods] Component "kube-apiserver" upgraded successfully!
[upgrade/staticpods] Moved new manifest to "/etc/kubernetes/manifests/kube-controller-manager.yaml" and backed up old manifest to "/etc/kubernetes/tmp/kubeadm-backup-manifests-2019-04-29-16-35-18/kube-controller-manager.yaml"
[upgrade/staticpods] Waiting for the kubelet to restart the component
[upgrade/staticpods] This might take a minute or longer depending on the component/version gap (timeout 5m0s
Static pod: kube-controller-manager-k8s-master01-lab hash: b8c4394fe06f6b77928cb0c052e70d34
Static pod: kube-controller-manager-k8s-master01-lab hash: dd9d89405893090f4a69d43045f47417
[apiclient] Found 1 Pods for label selector component=kube-controller-manager
[upgrade/staticpods] Component "kube-controller-manager" upgraded successfully!
[upgrade/staticpods] Moved new manifest to "/etc/kubernetes/manifests/kube-scheduler.yaml" and backed up old manifest to "/etc/kubernetes/tmp/kubeadm-backup-manifests-2019-04-29-16-35-18/kube-scheduler.yaml"
[upgrade/staticpods] Waiting for the kubelet to restart the component
[upgrade/staticpods] This might take a minute or longer depending on the component/version gap (timeout 5m0s
Static pod: kube-scheduler-k8s-master01-lab hash: 6b0b582c40f8558c7f9d58be2df41c1e
Static pod: kube-scheduler-k8s-master01-lab hash: 6b0b582c40f8558c7f9d58be2df41c1e
Static pod: kube-scheduler-k8s-master01-lab hash: 6b0b582c40f8558c7f9d58be2df41c1e
Static pod: kube-scheduler-k8s-master01-lab hash: 6b0b582c40f8558c7f9d58be2df41c1e
Static pod: kube-scheduler-k8s-master01-lab hash: 6b0b582c40f8558c7f9d58be2df41c1e
Static pod: kube-scheduler-k8s-master01-lab hash: 6b0b582c40f8558c7f9d58be2df41c1e
Static pod: kube-scheduler-k8s-master01-lab hash: 6b0b582c40f8558c7f9d58be2df41c1e
Static pod: kube-scheduler-k8s-master01-lab hash: 6b0b582c40f8558c7f9d58be2df41c1e

## Repeats indefinitely...

[upgrade/apply] FATAL: couldn't upgrade control plane. kubeadm has tried to recover everything into the earlier state. Errors faced: [timed out waiting for the condition]
```
The message `Static pod: kube-scheduler-k8s-master01-lab hash: 6b0b582c40f8558c7f9d58be2df41c1e` repeats until it reaches a timeout.

As far as I can tell, kubeadm is trying to update the kube-scheduler static pod, but it looks like it's stuck comparing the same pod hash over and over.

Any ideas what could be causing this?

**Comment by neolit123** [comment]
hi, do you get any hints if you increase the verbosity level with e.g `--v=4`.

> Not really a version upgrade, but rather, just using Kubespray to add more nodes in the cluster

i don't understand this part, could you please elaborate?
how is kubeadm upgrade used here to add extra nodes to a Kubespray cluster?

> ## Repeats indefinitely...

anything special about the existing scheduler pod - can you share its manifest?

**Comment by juliohm1978** [comment]
Ok, my apologies for closing this without a proper feedback. We needed to spin up this cluster as fast as possible today, so we decided to scrape it and reinstall it from scratch.

For what it's worth, kubeadm is used by Kubespray to install the cluster and add new nodes. We were just adding a new node. Things went really bad when we realized someone created the new node with an IP already used by another node in a different k8s cluster. This really messed everything to the point of no return.

If this comes up again, this can be reopened.

Thank you!

**Comment by wToad** [comment]
Hello, I have the same issue, I wanted to upgrade my cluster with Kubespray, but some errors occured. I decided to do it on my own with kubeadm (even if kubeadm was disable on the kubespray cluster deployment).

- Kubernetes version:
```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.7", GitCommit:"6f482974b76db3f1e0f5d24605a9d1d38fad9a2b", GitTreeState:"clean", BuildDate:"2019-03-25T02:41:57Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T17:53:03Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider:
```
Openstack
```
- OS:
```
# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.5 LTS
Release:	16.04
Codename:	xenial
```
- Kernel:
```
Linux preprod-k8s-master0 4.4.0-150-generic #176-Ubuntu SMP Wed May 29 18:56:26 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

### What happened?

I use the simplest upgrade commands:
```
# kubeadm upgrade plan v1.12.7
[preflight] Running pre-flight checks.
[upgrade] Making sure the cluster is healthy:
[upgrade/config] Making sure the configuration is correct:
[upgrade/config] Reading configuration from the cluster...
[upgrade/config] FYI: You can look at this config file with 'kubectl -n kube-system get cm kubeadm-config -oyaml'
[upgrade] Fetching available versions to upgrade to
[upgrade/versions] Cluster version: v1.11.3
[upgrade/versions] kubeadm version: v1.12.7

Upgrade to the latest version in the v1.11 series:

COMPONENT            CURRENT   AVAILABLE
API Server           v1.11.3   v1.12.7
Controller Manager   v1.11.3   v1.12.7
Scheduler            v1.11.3   v1.12.7
Kube Proxy           v1.11.3   v1.12.7
CoreDNS                        1.2.2

You can now apply the upgrade by executing the following command:

	kubeadm upgrade apply v1.12.7

_____________________________________________________________________

# kubeadm upgrade apply v1.12.7
[preflight] Running pre-flight checks.
[upgrade] Making sure the cluster is healthy:
[upgrade/config] Making sure the configuration is correct:
[upgrade/config] Reading configuration from the cluster...
[upgrade/config] FYI: You can look at this config file with 'kubectl -n kube-system get cm kubeadm-config -oyaml'
[upgrade/apply] Respecting the --cri-socket flag that is set with higher priority than the config file.
[upgrade/version] You have chosen to change the cluster version to "v1.12.7"
[upgrade/versions] Cluster version: v1.11.3
[upgrade/versions] kubeadm version: v1.12.7
[upgrade/confirm] Are you sure you want to proceed with the upgrade? [y/N]: Y
[upgrade/prepull] Will prepull images for components [kube-apiserver kube-controller-manager kube-scheduler etcd]
[upgrade/prepull] Prepulling image for component etcd.
[upgrade/prepull] Prepulling image for component kube-apiserver.
[upgrade/prepull] Prepulling image for component kube-controller-manager.
[upgrade/prepull] Prepulling image for component kube-scheduler.
[apiclient] Found 0 Pods for label selector k8s-app=upgrade-prepull-kube-apiserver
[apiclient] Found 0 Pods for label selector k8s-app=upgrade-prepull-etcd
[apiclient] Found 0 Pods for label selector k8s-app=upgrade-prepull-kube-controller-manager
[apiclient] Found 0 Pods for label selector k8s-app=upgrade-prepull-kube-scheduler
[upgrade/prepull] Failed prepulled the images for the control plane components error: unable to cleanup the DaemonSet used for prepulling etcd: daemonsets.apps "upgrade-prepull-etcd" not found
root@preprod-k8s-master0:~# kubeadm upgrade apply v1.12.7
[preflight] Running pre-flight checks.
[upgrade] Making sure the cluster is healthy:
[upgrade/config] Making sure the configuration is correct:
[upgrade/config] Reading configuration from the cluster...
[upgrade/config] FYI: You can look at this config file with 'kubectl -n kube-system get cm kubeadm-config -oyaml'
[upgrade/apply] Respecting the --cri-socket flag that is set with higher priority than the config file.
[upgrade/version] You have chosen to change the cluster version to "v1.12.7"
[upgrade/versions] Cluster version: v1.11.3
[upgrade/versions] kubeadm version: v1.12.7
[upgrade/confirm] Are you sure you want to proceed with the upgrade? [y/N]: Y
[upgrade/prepull] Will prepull images for components [kube-apiserver kube-controller-manager kube-scheduler etcd]
[upgrade/prepull] Prepulling image for component etcd.
[upgrade/prepull] Prepulling image for component kube-apiserver.
[upgrade/prepull] Prepulling image for component kube-controller-manager.
[upgrade/prepull] Prepulling image for component kube-scheduler.
[apiclient] Found 0 Pods for label selector k8s-app=upgrade-prepull-kube-controller-manager
[apiclient] Found 0 Pods for label selector k8s-app=upgrade-prepull-kube-scheduler
[apiclient] Found 0 Pods for label selector k8s-app=upgrade-prepull-kube-apiserver
[apiclient] Found 0 Pods for label selector k8s-app=upgrade-prepull-etcd
[upgrade/prepull] Prepulled image for component kube-apiserver.
[upgrade/prepull] Prepulled image for component kube-controller-manager.
[upgrade/prepull] Prepulled image for component kube-scheduler.
[upgrade/prepull] Prepulled image for component etcd.
[upgrade/prepull] Successfully prepulled the images for all the control plane components
[upgrade/apply] Upgrading your Static Pod-hosted control plane to version "v1.12.7"...
Static pod: kube-apiserver-openpaas-preprod-linagora-k8s-master0 hash: cacaf59666c7f9ad5fd5cfb34119fd91
Static pod: kube-controller-manager-openpaas-preprod-linagora-k8s-master0 hash: dd30aded3667c0791198bced69e54dd0
Static pod: kube-scheduler-openpaas-preprod-linagora-k8s-master0 hash: b8848d630ad36ddc239268433b5e1efa
[upgrade/staticpods] Writing new Static Pod manifests to "/etc/kubernetes/tmp/kubeadm-upgraded-manifests255994404"
[controlplane] wrote Static Pod manifest for component kube-apiserver to "/etc/kubernetes/tmp/kubeadm-upgraded-manifests255994404/kube-apiserver.yaml"
[controlplane] wrote Static Pod manifest for component kube-controller-manager to "/etc/kubernetes/tmp/kubeadm-upgraded-manifests255994404/kube-controller-manager.yaml"
[controlplane] wrote Static Pod manifest for component kube-scheduler to "/etc/kubernetes/tmp/kubeadm-upgraded-manifests255994404/kube-scheduler.yaml"
[upgrade/staticpods] Moved new manifest to "/etc/kubernetes/manifests/kube-apiserver.yaml" and backed up old manifest to "/etc/kubernetes/tmp/kubeadm-backup-manifests-2019-06-11-10-23-23/kube-apiserver.yaml"
[upgrade/staticpods] Waiting for the kubelet to restart the component
[upgrade/staticpods] This might take a minute or longer depending on the component/version gap (timeout 5m0s
Static pod: kube-apiserver-openpaas-preprod-linagora-k8s-master0 hash: 72a52cbf43953e22118f505819134075
[apiclient] Found 1 Pods for label selector component=kube-apiserver
[upgrade/staticpods] Component "kube-apiserver" upgraded successfully!
[upgrade/staticpods] Moved new manifest to "/etc/kubernetes/manifests/kube-controller-manager.yaml" and backed up old manifest to "/etc/kubernetes/tmp/kubeadm-backup-manifests-2019-06-11-10-23-23/kube-controller-manager.yaml"
[upgrade/staticpods] Waiting for the kubelet to restart the component
[upgrade/staticpods] This might take a minute or longer depending on the component/version gap (timeout 5m0s
Static pod: kube-controller-manager-openpaas-preprod-linagora-k8s-master0 hash: dd30aded3667c0791198bced69e54dd0
Static pod: kube-controller-manager-openpaas-preprod-linagora-k8s-master0 hash: 6dee512b0920e93ade6a32273e43fa63
[apiclient] Found 1 Pods for label selector component=kube-controller-manager
[upgrade/staticpods] Component "kube-controller-manager" upgraded successfully!
[upgrade/staticpods] Moved new manifest to "/etc/kubernetes/manifests/kube-scheduler.yaml" and backed up old manifest to "/etc/kubernetes/tmp/kubeadm-backup-manifests-2019-06-11-10-23-23/kube-scheduler.yaml"
[upgrade/staticpods] Waiting for the kubelet to restart the component
[upgrade/staticpods] This might take a minute or longer depending on the component/version gap (timeout 5m0s
Static pod: kube-scheduler-openpaas-preprod-linagora-k8s-master0 hash: b8848d630ad36ddc239268433b5e1efa
Static pod: kube-scheduler-openpaas-preprod-linagora-k8s-master0 hash: b8848d630ad36ddc239268433b5e1efa
Static pod: kube-scheduler-openpaas-preprod-linagora-k8s-master0 hash: b8848d630ad36ddc239268433b5e1efa
Static pod: kube-scheduler-openpaas-preprod-linagora-k8s-master0 hash: b8848d630ad36ddc239268433b5e1efa
[...]
[upgrade/apply] FATAL: couldn't upgrade control plane. kubeadm has tried to recover everything into the earlier state. Errors faced: [timed out waiting for the condition]
```

@neolit123 
when I use the verbosity level 4 it doesn't say anything more about the error, and about the manifest:
```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    scheduler.alpha.kubernetes.io/critical-pod: ""
  creationTimestamp: null
  labels:
    component: kube-scheduler
    tier: control-plane
  name: kube-scheduler
  namespace: kube-system
spec:
  containers:
  - command:
    - kube-scheduler
    - --feature-gates=PersistentLocalVolumes=False,VolumeScheduling=False,MountPropagation=False
    - --profiling=False
    - --address=127.0.0.1
    - --kubeconfig=/etc/kubernetes/scheduler.conf
    - --leader-elect=true
    image: gcr.io/google-containers/hyperkube-amd64:v1.11.3
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 8
      httpGet:
        host: 127.0.0.1
        path: /healthz
        port: 10251
        scheme: HTTP
      initialDelaySeconds: 15
      timeoutSeconds: 15
    name: kube-scheduler
    resources:
      requests:
        cpu: 100m
    volumeMounts:
    - mountPath: /etc/kubernetes/scheduler.conf
      name: kubeconfig
      readOnly: true
  hostNetwork: true
  priorityClassName: system-cluster-critical
  volumes:
  - hostPath:
      path: /etc/kubernetes/scheduler.conf
      type: FileOrCreate
    name: kubeconfig
status: {}
```

**Comment by neolit123** [comment]
we have clean e2e test signal for the non-cloud-provider use case (self provisioning nodes): https://k8s-testgrid.appspot.com/sig-cluster-lifecycle-kubeadm#kubeadm-kinder-upgrade-1.11-1.12

so it must be something setup related. what is your kubeadm configuration file?

**Comment by wToad** [comment]
Thank you for answering, I am not familiar with the interface of the link you provided but I will try to check. Here are my files:

```
# cat /etc/kubernetes/kubeadm-config.v1alpha3.yaml 
apiVersion: kubeadm.k8s.io/v1alpha3
kind: InitConfiguration
apiEndpoint:
  advertiseAddress: 51.68.112.134
  bindPort: 6443
nodeRegistration:
  name: openpaas-preprod-linagora-k8s-master0
  taints:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
  criSocket: /var/run/dockershim.sock
---
apiVersion: kubeadm.k8s.io/v1alpha3
kind: ClusterConfiguration
clusterName: cluster.local
etcd:
  external:
      endpoints:
      - https://51.68.112.134:2379
      - https://51.68.113.235:2379
      - https://51.75.13.57:2379
      caFile: /etc/kubernetes/ssl/etcd/ca.pem
      certFile: /etc/kubernetes/ssl/etcd/node-openpaas-preprod-linagora-k8s-master0.pem
      keyFile: /etc/kubernetes/ssl/etcd/node-openpaas-preprod-linagora-k8s-master0-key.pem
networking:
  dnsDomain: cluster.local
  serviceSubnet: 10.233.0.0/18
  podSubnet: 10.233.64.0/18
kubernetesVersion: v1.12.7
controlPlaneEndpoint: 51.68.112.134:6443
apiServerCertSANs:
  - kubernetes
  - kubernetes.default
  - kubernetes.default.svc
  - kubernetes.default.svc.cluster.local
  - 10.233.0.1
  - localhost
  - 127.0.0.1
  - openpaas-preprod-linagora-k8s-master0
  - lb-apiserver.kubernetes.local
  - 51.68.112.134
certificatesDir: /etc/kubernetes/ssl
imageRepository: gcr.io/google-containers
unifiedControlPlaneImage: ""
apiServerExtraArgs:
  authorization-mode: Node,RBAC
  bind-address: 0.0.0.0
  insecure-port: "0"
  apiserver-count: "1"
  endpoint-reconciler-type: lease
  service-node-port-range: 30000-32767
  kubelet-preferred-address-types: "InternalDNS,InternalIP,Hostname,ExternalDNS,ExternalIP"
  storage-backend: etcd3
  runtime-config: admissionregistration.k8s.io/v1alpha1
  allow-privileged: "true"
  cloud-provider: openstack
  cloud-config: /etc/kubernetes/cloud_config
controllerManagerExtraArgs:
  node-monitor-grace-period: 40s
  node-monitor-period: 5s
  pod-eviction-timeout: 5m0s
  node-cidr-mask-size: "24"
  cloud-provider: openstack
  cloud-config: /etc/kubernetes/cloud_config
schedulerExtraArgs:
apiServerExtraVolumes:
- name: cloud-config
  hostPath: /etc/kubernetes/cloud_config
  mountPath: /etc/kubernetes/cloud_config
controllerManagerExtraVolumes:
- name: openstackcacert
  hostPath: "/etc/kubernetes/openstack-cacert.pem"
  mountPath: "/etc/kubernetes/openstack-cacert.pem"
- name: cloud-config
  hostPath: /etc/kubernetes/cloud_config
  mountPath: /etc/kubernetes/cloud_config
---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
bindAddress: 0.0.0.0
clientConnection:
 acceptContentTypes: ""
 burst: 10
 contentType: application/vnd.kubernetes.protobuf
 kubeconfig: /var/lib/kube-proxy/kubeconfig.conf
 qps: 5
clusterCIDR: ""
configSyncPeriod: 15m0s
conntrack:
 max: null
 maxPerCore: 32768
 min: 131072
 tcpCloseWaitTimeout: 1h0m0s
 tcpEstablishedTimeout: 24h0m0s
enableProfiling: false
healthzBindAddress: 0.0.0.0:10256
iptables:
 masqueradeAll: false
 masqueradeBit: 14
 minSyncPeriod: 0s
 syncPeriod: 30s
ipvs:
 excludeCIDRs: null
 minSyncPeriod: 0s
 scheduler: ""
 syncPeriod: 30s
metricsBindAddress: 127.0.0.1:10249
mode: iptables
oomScoreAdj: -999
portRange: ""
resourceContainer: ""
udpIdleTimeout: 250ms
```

```
# cat /etc/kubernetes/kube-scheduler-kubeconfig.yaml 
apiVersion: v1
kind: Config
clusters:
- name: local
  cluster:
    certificate-authority: /etc/kubernetes/ssl/ca.pem
    server: https://127.0.0.1:6443
users:
- name: kube-scheduler
  user:
    client-certificate: /etc/kubernetes/ssl/kube-scheduler.pem
    client-key: /etc/kubernetes/ssl/kube-scheduler-key.pem
contexts:
- context:
    cluster: local
    user: kube-scheduler
  name: kube-scheduler-cluster.local
current-context: kube-scheduler-cluster.local
```
