### ISSUE TITLE
area/kubeadm label does not exist

### ISSUE THREAD

**Issue by fejta** [kubernetes/kubeadm#1547]
/assign @timothysc @fabriziopandini @neolit123

```yaml
 jsonPayload: {
  author:  "fabriziopandini"   
  component:  "hook"   
  event-GUID:  "ec05b660-6aab-11e9-9277-dc8d94bf201a"   
  event-type:  "pull_request"   
  level:  "warning"   
  msg:  "Unable to add nonexistent labels: ["area/kubeadm"]"   
  org:  "kubernetes"   
  plugin:  "owners-label"   
  pr:  1545   
  repo:  "kubeadm"   
  url:  "https://github.com/kubernetes/kubeadm/pull/1545"   
 }
```

Please remove this from the OWNERS file in this repo: https://github.com/kubernetes/kubeadm/blob/fc185e23ba206ac3b84befd6ff33e7c94f52235d/OWNERS#L25

Or create this label: https://github.com/kubernetes/test-infra/tree/master/label_sync
