### ISSUE TITLE
v15 masterHA with LB -> etcd tries the LB's IP instead of directly the node.

### ISSUE THREAD

**Issue by ReSearchITEng** [kubernetes/kubeadm#1566]
kubeadm MasterHA v15 with conf files.

Error joining the secondary-master to the control plane. 
It tries to go to the LB IP (10.0.0.254) instead of going directly to the 10.0.0.[1-2]:2379.

```
etcd.go:96] etcd endpoints read from pods: https://10.0.0.254:2379
error execution phase check-etcd: error syncing endpoints with etc: dial tcp 10.0.0.254:2379: connect: connection refused
```

## Versions

**kubeadm version** (use `kubeadm version`):
 kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.0-alpha.3.325+a1eaacd59bec0b", GitCommit:"a1eaacd59bec0b6cb02544c9122c11efe9569c9b", GitTreeState:"clean", BuildDate:"2019-05-14T09:43:07Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Kubernetes version** (use `kubectl version`):
v1.15.0-alpha.3
- **Cloud provider or hardware configuration**: byo
- **OS** (e.g. from /etc/os-release): Centos/RH

## What happened?
Cannot join secondary master to the control plane, when using a LB

## What you expected to happen?
secondary master should try to connect to 10.0.0.1:2379 (machine01:2379), not LB:2379.

## How to reproduce it (as minimally and precisely as possible)?
kubeadm init on primary master, using the 1st kubeadm.conf below
kubeadm join on secondary, using the 2nd kubeadm.conf below

### ------- primary-master kubeadm.conf
kubeadm init --config kubeadm.conf --experimental-upload-certs
```
#############
###------- primary-master kubeadm.conf
### this time with etcd.local.* defined
### it was tried also without etcd.local.* defined
#############
kind: ClusterConfiguration
apiVersion: kubeadm.k8s.io/v1beta2
etcd:
  local:
    serverCertSANs:
    - 10.0.0.1
    - machine0001
    - machine0001.corp.example.com
    peerCertSANs:
    - 10.0.0.1
    - machine0001
    - machine0001.corp.example.com
    extraArgs:
      initial-cluster-state: new
      name: machine0001
      listen-peer-urls: https://10.0.0.1:2380
      listen-client-urls: https://10.0.0.1:2379
      advertise-client-urls: https://10.0.0.1:2379
      initial-advertise-peer-urls: https://10.0.0.1:2380
      initial-cluster: machine0001=https://10.0.0.1:2380
kubernetesVersion: v1.15.0-alpha.3
networking:
    podSubnet: 10.244.0.0/16
controlPlaneEndpoint: 10.0.0.254
apiServer:
    certSANs:
    - 10.0.0.1
    - machine0001.corp.example.com
    - machine0001
    - lb.corp.example.com
    - 127.0.0.1
    - 10.0.0.254

---
apiVersion: kubeadm.k8s.io/v1beta2
kind: InitConfiguration
localAPIEndpoint:
    advertiseAddress: 10.0.0.254
    bindPort: 6443
nodeRegistration:
    taints:
    -   effect: NoSchedule
        key: node-role.kubernetes.io/master
---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
clusterCIDR: 10.244.0.0/16
kind: KubeProxyConfiguration
mode: ipvs
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
```

### ------- secondary-master kubeadm.conf
kubeadm join --v 9 --config kubeadm.conf
```
### this time with etcd.local.* defined
### it was tried also without etcd.local.* defined
### In both cases etcd tried to connect to 10.0.0.254:2379 (which is the ip of lb-master.corp.example.com, and LB does not forward etcd port)
###############
kind: ClusterConfiguration
apiVersion: kubeadm.k8s.io/v1beta2
etcd:
  local:
    serverCertSANs:
    - 10.0.0.2
    - machine0002
    - machine0002.corp.example.com
    peerCertSANs:
    - 10.0.0.2
    - machine0002
    - machine0002.corp.example.com
    extraArgs:
      initial-cluster-state: new
      name: machine0002
      listen-peer-urls: https://10.0.0.2:2380
      listen-client-urls: https://10.0.0.2:2379
      advertise-client-urls: https://10.0.0.2:2379
      initial-advertise-peer-urls: https://10.0.0.2:2380
      initial-cluster: machine0002=https://10.0.0.2:2380,machine0001=https://10.0.0.1:2380
kubernetesVersion: v1.15.0-alpha.3
networking:
    podSubnet: 10.244.0.0/16
controlPlaneEndpoint: 10.0.0.254
apiServer:
    certSANs:
    - 10.0.0.1
    - machine0001.corp.example.com
    - machine0001
    - lb.corp.example.com
    - 127.0.0.1
    - 10.0.0.254

---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
clusterCIDR: 10.244.0.0/16
kind: KubeProxyConfiguration
mode: ipvs
---
controlPlane:
   localAPIEndpoint:
     advertiseAddress: 0.0.0.0
#      bindPort: 6443
   certificateKey: 0f1d051eb5a270c0154a1129379854168123d90ab5c48ac3589160a4c4beeb2d    # 1.15 (v1beta2) onwards
apiVersion: kubeadm.k8s.io/v1beta2
discovery:
  bootstrapToken:
    apiServerEndpoint: lb-master.corp.example.com:6443
    #apiServerEndpoint: machine0001.corp.example.com:6443
    token: abcdef.fi7gp1cjfv5oufuz
    # unsafeSkipCAVerification: true
    caCertHashes:
    - sha256:cf40e483d7fd61bd6fa241578ab1b401c48e9c2d21b0583d868d8597774e9de0
kind: JoinConfiguration
```
