### ISSUE TITLE
kubeadm init will override the kubelet config under /var/lib/kubelet/config.yaml

### ISSUE THREAD

**Issue by Cherishty** [kubernetes/kubeadm#1576]
## Is this a BUG REPORT or FEATURE REQUEST?
 BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`):
kubeadm version: &version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:20:34Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
**Environment**:
- **Kubernetes version** (use `kubectl version`): 1.14.2
- **Cloud provider or hardware configuration**: no
- **OS** (e.g. from /etc/os-release): CentOS Linux release 7.5.1804 (Core)
- **Kernel** (e.g. `uname -a`): Linux stcvl-060.localdomain 3.10.0-862.14.4.el7.x86_64 #1 SMP 
- **Others**:

## What happened?
In newer version (as k8s 1.14.2), kubelet may read start params  from `/var/lib/kubelet/config.yaml` via **--config params**. 
However if it is the first time to initialize the cluster (via **kubeadm init**), given kubelet-config will be `overridden `by the one kubeadm generate.  How can I pass my kubelet-config to kubeadm for better initialization?

For my knowledge, kubeadm init can pass --config as well , where I find **kubeletExtraArgs** inner `InitConfiguration`, some fields such as **cgroup-driver** can be modified here. However I wonder if this config can cover all the params kubelet can provide, like `eviction `and `auth mode` ? 

If so, how can I do it? I find the doc on [goDoc](https://godoc.org/k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/v1beta1), but it does not show much of the detail in `KubeletExtraArgs `section

## What you expected to happen?
customization the start params for kubelet when initalize k8s via kubeadm

**Comment by yagonobre** [comment]
You can use the `kubelet.config.k8s.io/v1beta1` on init config.
like
```
apiVersion: kubeadm.k8s.io/v1beta1
kind: ClusterConfiguration
etcd:
  external:
    endpoints: xpto1,xpto2,xpto3,,xpto4,xpto5
    caFile: /etc/kubernetes/pki/etcd-ca.crt
    certFile: /etc/kubernetes/pki/client.crt
    keyFile: /etc/kubernetes/pki/client.key
---
address: 0.0.0.0
apiVersion: kubelet.config.k8s.io/v1beta1
authentication:
  anonymous:
    enabled: false
```

/triage support

**Comment by chenzhiwei** [comment]
@Cherishty You can add your kubelet config.yaml parameters to kubeadm init config file, so kubeadm can generate the expected config.yaml for you.

But I have a PR to automatically detect cgroup-driver and systemd-resolved during generating kubelet config.yaml, so these two parameters may be changed by kubeadm. https://github.com/kubernetes/kubernetes/pull/77059

**Comment by Cherishty** [comment]
thanks @yagonobre  and @chenzhiwei .
Yes, I did realize kubelet params can be imgrated to kubeadm config, but the only question is: **how to do so**

For instance, I want to config the `eviction policy` and `auth mode`, but I am NOT sure how to do this in kubeadm config, since the [official doc](https://godoc.org/k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/v1beta1) does **NOT** mention this part
 (I guess it should located in `InitConfiguration.KubeletExtraArgs`, but what's the detail?)

**Comment by yagonobre** [comment]
@cherishty you can use, something like this as  you init config
``` 
apiVersion: kubeadm.k8s.io/v1beta1
kind: ClusterConfiguration
...
---
apiVersion: kubelet.config.k8s.io/v1beta1
authentication:
  anonymous:
    enabled: false
evictionHard:
  imagefs.available: 15%
  memory.available: 5%
  nodefs.available: 10%
  nodefs.inodesFree: 5%
systemReserved:
  memory: 1Gi
  cpu: 2m
  ephemeral-storage: 2Gi
evictionPressureTransitionPeriod: 5m0s
```
