### ISSUE TITLE
handling of extraArgs which are allowed multiple times

### ISSUE THREAD

**Issue by ghouscht** [kubernetes/kubeadm#1601]
The current implementation of `extraArgs` in the `ControlPlaneComponent` is backed by a `map[string]string` type and this leads to some problems we're currently facing. For example the api-server allows some arguments multiple times (`--service-account-key-file` and `--tls-sni-cert-key`). We can't handle this with the `extraArgs` type as it is a map which of course does not allow the same key twice and thus overrides previous declarations.

Example:

```yaml
---
apiVersion: kubeadm.k8s.io/v1beta1
kind: ClusterConfiguration
kubernetesVersion: 1.14.2
apiServer:
  extraArgs:
    "tls-sni-cert-key": "/etc/kubernetes/pki/apiserver.crt,/etc/kubernetes/pki/apiserver.key"
    "tls-sni-cert-key": "/etc/kubernetes/pki/mycert.crt,/etc/kubernetes/pki/mykey.key" # overrides the previous declaration
```

(This is probably also a problem for other control plane components but I haven't checked that.)

Our current approach to solve this, is to "patch" the api-server manifest after the initial setup with kubeadm is complete (ansible playbook). This works quite well as a workaround, but I think kubeadm should allow us to solve this without the need to touch the generated kube-apiserver manifest.

_Originally posted by @ghouscht in https://github.com/kubernetes/kubeadm/issues/1439#issuecomment-495502283_

------------
EDIT by neolit123

- implemented in this PR for v1beta4
https://github.com/kubernetes/kubernetes/pull/119156

- optimize argument.go logic
https://github.com/kubernetes/kubernetes/pull/121020

- TODO
the same problem happens for CLI flags:
https://github.com/kubernetes/kubeadm/issues/1413
see the discussion there.

**Comment by zbindenren** [comment]
How about the following structure:

```yaml
---
apiVersion: kubeadm.k8s.io/v1beta1
kind: ClusterConfiguration
kubernetesVersion: 1.14.2
apiServer:
  extraArgs:
    - name: "tls-sni-cert-key"
      value: "/etc/kubernetes/pki/apiserver.crt,/etc/kubernetes/pki/apiserver.key"
    - name: "tls-sni-cert-key"
      value: "/etc/kubernetes/pki/mycert.crt,/etc/kubernetes/pki/mykey.key"
```

**Comment by creation-shin-chan** [comment]
@zbindenren 
I have the same problem wit "--service-account-key-file". Your suggestion didn't work. kubeadm just gives me unmarshal error.

**Comment by neolit123** [comment]
for now you'd have to patch your manifest files manually after they are created.
(i.e. after kubeadm finishes running).

there is a WIP alpha feature for 1.16 that will allow you to customize static pods using patches:
https://github.com/kubernetes/kubeadm/issues/1379

but i'm keeping this issue open in case we figure a good way to allow multiple keys with the same name.

**Comment by zbindenren** [comment]
@creation-shin-chan that does not actually work. This was just a proposition how it could be implemented.

**Comment by creation-shin-chan** [comment]
@zbindenren 
I create kubeadm-config.yaml as you suggested. However, kubeadm upgrade --config=kubeadm-config.yaml give me unsharl error. 

In kube-apiserver.yaml manifest (in /etc/kubernetes/manifests), I added these lines.
```
    - --service-account-key-file=/etc/kubernetes/pki/pub.pem
    - --service-account-signing-key-file=/etc/kubernetes/pki/priv.key
```

Therefore, I need `--service-account-key-file=/etc/kubernetes/pki/pub.pem` and `--service-account-key-file=/etc/kubernetes/pki/sa.pub` in kube-apiserver manifest. 

So I tried adding `service-account-key-file: /etc/kubernetes/pki/pub.pem` to kubeadm-config.yaml and run kubeadm init or upgrade, `--service-account-key-file=/etc/kubernetes/pki/sa.pub` disappears and kube-controller-manager doesn't start up with unauthorized error. 

At the moment, I need to add the public keys into a single file or manually add `--service-account-key-file=/etc/kubernetes/pki/pub.pem` parameter. 
However, every time I run kubeadm upgrade to upgrade kubernetes version, the parameter manually added disappears so I need to add it again manually.

**Comment by neolit123** [comment]
> However, every time I run kubeadm upgrade to upgrade kubernetes version, the parameter manually added disappears so I need to add it again manually.

yes, upgrade will overwrite the existing manifests on disk. that is because it uses the CluserConfiguration in the kubeadm-config ConfigMap as the source of truth and the ClusterConfiguration does not support multiple keys with the same name in a map.

please note that using `kubeadm upgrade --config=kubeadm-config.yaml` to reconfigure the cluster is not recommended it really performs more than updating your manifests.

ticket for cluster reconf https://github.com/kubernetes/kubeadm/issues/970
but reconf will not work unless we support the multiple keys.

as mentioned kustomize patches will allow you to patch your changes and preserve them during init and uprade:
https://github.com/kubernetes/kubeadm/issues/1379 (WIP)
but if you already started the cluster, then you need to design your patches for upgrade.

**Comment by neolit123** [comment]
merging with https://github.com/kubernetes/kubeadm/issues/1413
that issue outlines the CLI flag problem and this one outlines the kubeadm config problem.

**Comment by hickeng** [comment]
@neolit123 I'm seeing the same issue with `kustomize` dropping all but the last value when run against a `kubeadm.yaml` that has two similarly named extraArgs present (`tls-sni-cert-key` in this specific case).

I'm not clear how patching afterwards using `kustomize` is expected to improve this.
Please note this is using `kustomize` binary and NOT the kustomize integrated into kubeadm.

**Comment by fabriziopandini** [comment]
@hickeng 
The `ExtraArgs` field in the kubeadm config file is a `map[string]string`, so it does not support duplicated key no matter if you pass them manually or if you try to add them with kustomize. 
Instead, If I got it right, what @neolit123 is suggesting is to use kustomize to patch the generated API server Pod manifest changing the `args` list directly

**Comment by dnmgns** [comment]
👀

**Comment by neolit123** [comment]
marking as `api-change`, because of the `map[string]string` binding in the API.

**Comment by prashantpsr24** [comment]
Facing the same issue with kubeadm

**Comment by neolit123** [comment]
for now you have to patch your YAML manually or it should be possible with the --exterimental-kustomize=` feature too, currently.

**Comment by xlgao-zju** [comment]
@neolit123 any plan to change the `ExtraArgs ` to other form? Like 

```go
type arg struct {
  key    string
  value string
}
```

instead of map[string][string]

**Comment by neolit123** [comment]
we haven't made this fix because it also has to change in the latest API v1beta3.
but a multi-map of sorts would work too:
https://stackoverflow.com/a/19519386

**Comment by BenTheElder** [comment]
the kustomize answer doesn't seem very great because you need to know the original flag value and include it in the new flag ?
repeated flags / a list like pod env seems like a workable approach though, is kubeadm planning to create a new API version?

**Comment by neolit123** [comment]
> is kubeadm planning to create a new API version?

yes - v1beta3, although when that will happen is unclear:
https://github.com/kubernetes/kubeadm/issues?q=is%3Aissue+is%3Aopen+label%3Akind%2Fapi-change

**Comment by BenTheElder** [comment]
/remove-lifecycle stale
Is this being considered for a v1beta3? There's still some components that are staying relatively flag based (like API server) that accept repeated flags.

**Comment by neolit123** [comment]
unlikely that i would have the time to work on this, but if someone wants to give this a shot before Thursday next week (code freeze for 1.22), it might be doable.

my concerns here would be around conversion and syntax.
current syntax for extra args is

```
extraArgs:
  foo: bar
```
but i don't think we can preserve it with this change, since both JSON and YAML do not support duplicate keys in maps.

**Comment by BenTheElder** [comment]
I think we'd have to switch to something more like the env list in podspec, code freeze probably does make this too soon for v1beta3, maybe a v1beta4? I'm not sure we can have a portable spec handling this without some API change.

Some yaml libraries do allow duplicate keys, but it is out of spec https://github.com/yaml/pyyaml/issues/165 and doesn't seem reasonable to target.

**Comment by neolit123** [comment]
if not for this API version it can be done for the next one, but it might take a while before v-next.
name/value as in podspec and an API change makes the most sense; similar was proposed above.

alternatively this could also be a `[]map[string]string`, this has a very close syntax for yaml users (who are a majority):
```
extraArgs:
  - foo1: bar1
  - foo2: bar2
```
but not so similar for JSON users.

the same feels a bit hacky and requires validation to limit to one max key per `map[string]string`, so that there are no:
```
extraArgs:
  - foo1: bar1
    foo2: bar2
  - foo3: bar3
```

in any case, we do hope that users will always use `kubeadm config migrate` when moving from v1beta2->3.

**Comment by bjethwan** [comment]
This is issue impacted our design. For our platform based on k8s we wanted to use separate PKI for "aws iam for pods" and  k8s service accounts.

**Comment by neolit123** [comment]
> This issue impacted our design

the workaround is to use --experimental-patches (--patches in 1.22) and have a the extra flags added using a patch (not using extraArgs).

**Comment by bjethwan** [comment]
@neolit123 Thanks! I am trying this at the moment.
However, I had this doubt in my head as how does kube-apiserver know about it's own sa.key/sa.pub vs we use for example amazon-eks-pod-identity-webhook. As for the k8s service account I read that it's kube-controller-manager responsible for generating the sa/secret token. Is it the mutating webhook for other stuff that queries kube-apiserver for configured PKI keypair?
I have asked the same question here: https://github.com/aws/amazon-eks-pod-identity-webhook/issues/118

**Comment by neolit123** [comment]
You can ask these questions in #sig-auth in the k8s slack.

**Comment by challa-pradyumna** [comment]
> if not for this API version it can be done for the next one, but it might take a while before v-next. EDIT: the API change itself is not that complicated, but kubeadm just makes to many assumptions about this being a `map[string]string` in a lot of places...
> 
> name/value as in podspec and an API change makes the most sense; similar was proposed above.
> 
> alternatively this could also be a `[]map[string]string`, this has a very close syntax for yaml users (who are a majority):
> 
> ```
> extraArgs:
>   - foo1: bar1
>   - foo2: bar2
> ```
> 
> but not so similar for JSON users.
> 
> the same feels a bit hacky and requires validation to limit to one max key per `map[string]string`, so that there are no:
> 
> ```
> extraArgs:
>   - foo1: bar1
>     foo2: bar2
>   - foo3: bar3
> ```

How about 
```
extraArgs:
- foo1:
  - bar1
- foo2:
  - bar2
  - bar3
```

**Comment by chendave** [comment]
/help

for anyone who want to take this, pls assign this to yourself.

**Comment by ajfriesen** [comment]
Struggled with this today and found a pretty stupid workaround:

broken but desired:

```yaml
apiServer:
  extraArgs:
    oidc-issuer-url: https://sts.windows.net/1234/
    oidc-client-id: 1234
    oidc-username-claim: email
    oidc-groups-claim: groups
    oidc-required-claim: family_name=1234
    oidc-required-claim: given_name=12341234
```

works but ugly workaround:
```yaml
apiServer:
  extraArgs:
    oidc-issuer-url: https://sts.windows.net/1234/
    oidc-client-id: 1234
    oidc-username-claim: email
    oidc-groups-claim: groups
    oidc-required-claim: family_name=1234    - --oidc-required-claim=given_name=12341234
```

This will be rendered like this in the `kube-apiserver` manifest and runs perfectly fine since it will just be passed as a string option to the `kube-apiserver`

```yaml
spec:
  containers:
  - command:
    - kube-apiserver
    - --oidc-client-id=1234
    - --oidc-groups-claim=groups
    - --oidc-issuer-url=https://sts.windows.net/1234/
    - --oidc-required-claim=family_name=1234    - --oidc-required-claim=given_name=12341234
```

Using `kubeadm.k8s.io/v1beta3` with 1.28
