### ISSUE TITLE
kubeadm join does not apply taints

### ISSUE THREAD

**Issue by joerocklin** [kubernetes/kubeadm#1619]
## Versions

**kubeadm version**: v1.12.9

**Environment**:
- **Kubernetes version**: v1.12.9
- **Cloud provider or hardware configuration**: AWS
- **OS**: Amazon Linux 2
- **Kernel**: 4.14.121-109.96.amzn2.x86_64

## What happened?

When trying to join a new worker node with taints using `kubeadm join` the taints were not applied.

## What you expected to happen?

The taints to be applied

## How to reproduce it (as minimally and precisely as possible)?

Using the following node configuration:

```yaml
apiVersion: kubeadm.k8s.io/v1alpha3
kind: JoinConfiguration
caCertPath: /etc/kubernetes/pki/ca.crt
<snip to remove token data>
nodeRegistration:
  criSocket: /var/run/dockershim.sock
  taints:
  - effect: NoSchedule
    key: dedicated
    value: team
  kubeletExtraArgs:
    cloud-provider: aws
```

Run `kubeadm join --config kubeadm-node.conf`. Observe a successful cluster join but no taints applied.

## Anything else we need to know?

The join command did not generate a `/var/lib/kubelet/kubeadm-flags.env` file which contained the `register-with-taints` flag. I believe this is due to an improper call to `WriteKubeletDynamicEnvFile` introduced in https://github.com/kubernetes/kubernetes/commit/8af751fe90150d6cbeb14b40c41cd31049d510cf#diff-0960dc0bb7c3e7113a0daa027856b8f9R492.

The version before this commit had the static value of `true` for the `registerTaintsUsingFlags` parameter to `WriteKubeletDynamicEnvFile`.

This appears to only apply to 1.12. I have applied a small fix [based on the 1.13 implementation](https://github.com/kubernetes/kubernetes/blob/bda90cd6042eeb5c74b338e967ba7dcfebb6a3e5/cmd/kubeadm/app/cmd/join.go#L514) of this call and it works just fine. I will submit a PR with this fix (though I have no idea if any changes are being accepted for 1.12 right now).

edit: grammar fixes.
