### ISSUE TITLE
advertise-address

### ISSUE THREAD

**Issue by oaudry** [kubernetes/kubeadm#1620]
BUG REPORT

advertise-address is not applied when used with kubeadm init

## Versions

kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:41:54Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

- on premise
- **OS** (e.g. from /etc/os-release): Debian GNU/Linux 9 (stretch)
- **Kernel** (e.g. `uname -a`): 4.9.168-1+deb9u2
- **Others**:

## What happened?

the following configuration for advertise-address is not used :

```
root@sbg2-k8s001:~# cat kubeadm-config.yaml 
apiVersion: kubeadm.k8s.io/v1beta1
kind: ClusterConfiguration
kubernetesVersion: stable
apiServer:
  certSANs:
  - "api.k8s.smobe.fr"
  extraArgs:
    advertise-address: 192.168.208.12
networking:
   podSubnet: "10.244.0.0/16"
```

## What you expected to happen?

configuration for advertise-address is used

## How to reproduce it (as minimally and precisely as possible)?

compare the result of 

`kubeadm init --config=kubeadm-config.yaml`

and  

`kubeadm init --pod-network-cidr=10.244.0.0/16 --apiserver-advertise-address=192.168.208.12 `
the second command work as expected but I cannot specify certSANs from command line.

## Anything else we need to know?

I followed the exemple in documentation. https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/control-plane-flags/

many thx for your help.

oau
