### ISSUE TITLE
Pods can't resolve using CoreDNS

### ISSUE THREAD

**Issue by manulqwerty** [kubernetes/kubeadm#1659]
## Versions

**kubeadm version** (use `kubeadm version`):
```
kubeadm version: &version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:37:41Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```
**Environment**:
- **Kubernetes version** (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:32:14Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```
- **Cloud provider or hardware configuration**:
`Debian 9 VM (4 GB RAM - 4 Cores)`
- **OS** (e.g. from /etc/os-release):
`Debian GNU/Linux 9 (stretch)`
- **Kernel** (e.g. `uname -a`):
`Linux kmaster 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1+deb9u3 (2019-06-16) x86_64 GNU/Linux`

## What happened?
I've tried so much installation guides in order to create a cluster. 
Everything works fine until I try to scale the pods (Cassandra for example), so i thought that the problem could be in the DNS.
I followed this guide: https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/
And as I thought, the buxybox cannot resolve the name kubernetes.default.
I think i'm missing a configuration step or something. These are my installation steps:
```bash
apt update
apt install -y \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg2 \
    software-properties-common
curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -
add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/debian \
   $(lsb_release -cs) \
   stable"
apt update
apt install -y docker-ce docker-ce-cli containerd.io
curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
cat <<EOF >/etc/apt/sources.list.d/kubernetes.list
deb http://apt.kubernetes.io/ kubernetes-xenial main
EOF
apt update
apt install -y kubelet kubeadm kubectl
apt-mark hold kubelet kubeadm kubectl
kubeadm config images pull
```
This is how I initialize my cluster:
```bash
kubeadm init --pod-network-cidr=10.244.0.6/16
mkdir -p $HOME/.kube
cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
chown $(id -u):$(id -g) $HOME/.kube/config
kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
# Using only the master:
kubectl taint nodes --all node-role.kubernetes.io/master-
# With this line the cluster works (only with one node):
iptables -P FORWARD ACCEPT
```
The pods are all running:
```bash
root@kmaster:~/dashboard# kubectl get pods --all-namespaces
NAMESPACE              NAME                                          READY   STATUS    RESTARTS   AGE
default                busybox                                       1/1     Running   0          39m
kube-system            coredns-5c98db65d4-7rtzb                      1/1     Running   0          63m
kube-system            coredns-5c98db65d4-89mm6                      1/1     Running   0          63m
kube-system            etcd-kmaster                                  1/1     Running   0          41m
kube-system            kube-apiserver-kmaster                        1/1     Running   0          41m
kube-system            kube-controller-manager-kmaster               1/1     Running   0          41m
kube-system            kube-flannel-ds-amd64-vmxwn                   1/1     Running   0          63m
kube-system            kube-flannel-ds-amd64-zx7f7                   1/1     Running   0          40m
kube-system            kube-proxy-4crnt                              1/1     Running   0          40m
kube-system            kube-proxy-szjpt                              1/1     Running   0          63m
kube-system            kube-scheduler-kmaster                        1/1     Running   0          41m
kubernetes-dashboard   kubernetes-dashboard-5c8f9556c4-2grf7         1/1     Running   0          57m
kubernetes-dashboard   kubernetes-metrics-scraper-86456cdd8f-m5rh6   1/1     Running   0          57m
```
```bash
root@kmaster:~/# kubectl get svc -n kube-system
NAME       TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)                  AGE
kube-dns   ClusterIP   10.96.0.10   <none>        53/UDP,53/TCP,9153/TCP   81m
```
Busybox can't even ping the dns:
```bash
kubectl exec busybox ip a s
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
3: eth0@if6: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1450 qdisc noqueue
    link/ether 56:1d:5d:e2:e1:9e brd ff:ff:ff:ff:ff:ff
    inet 10.244.1.2/24 scope global eth0
       valid_lft forever preferred_lft forever
```
Busybox Resolver:
```bash
kubectl exec busybox cat /etc/resolv.conf
nameserver 10.96.0.10
search default.svc.cluster.local svc.cluster.local cluster.local localdomain
options ndots:5
```
Logs: 
```bash
for p in $(kubectl get pods --namespace=kube-system -l k8s-app=kube-dns -o name); do kubectl logs --namespace=kube-system $p; done
.:53
2019-07-10T16:58:22.575Z [INFO] CoreDNS-1.3.1
2019-07-10T16:58:22.575Z [INFO] linux/amd64, go1.11.4, 6b56a9c
CoreDNS-1.3.1
linux/amd64, go1.11.4, 6b56a9c
2019-07-10T16:58:22.575Z [INFO] plugin/reload: Running configuration MD5 = 5d5369fbc12f985709b924e721217843
```
Running pods like Cassandra, they die trying to resolve the other pods name. For example:
I have 3 pods: Cassandra-0, Cassandra-1, Cassandra-2
Cassandra-1 and Cassandra-2 die because they cannot resolve Cassandra-1 name.
## What you expected to happen?
I expect that the pods can connect.

## How to reproduce it (as minimally and precisely as possible)?
Installing kubeadm in any linux distribution.

## Anything else we need to know?
I think there's any simple step that I'm missing, so even if it is a stupid step please tell me.
I've already read this issue: https://github.com/kubernetes/kubeadm/issues/1056 but can't resolve my problem.
Thank you.

**Comment by neolit123** [comment]
also, what distros are Casandra and busybox based on?

see
https://github.com/kubernetes/kubeadm/issues/1657#issuecomment-509772693
yesterday i tried playing with a busybox Pod to `nslookup` a domain and i noticed that it simply doesn't work, while a the DNS resolve from Pod with a debian stretch based container worked fine.

please try something like that and report back.

cc @chrisohaver @rajansandeep

**Comment by chrisohaver** [comment]
Busybox's nslookup doesn't use the search domains defined in `/etc/resolv.conf`.
AFAIK, all versions of busybox after 1.28 are affected.

**Comment by chrisohaver** [comment]
Please enable logging in CoreDNS, so we can see what queries are reaching it, and what they look like (e.g. what the cassandra queries look like).
From the naming of the Cassandra pods, the look like they are a stateful set.  Which means to be able to access them via a DNS name, you'll need to expose them via a headless service that targets the pods in the stateful set.  Each member of the stateful set then can be addressed as an endpoint of the headless service, ... e.g. `cassandra-0.myservice.default.svc.cluster.local.`

**Comment by manulqwerty** [comment]
Thank you for replying.
- Enable login in CoreDNS: `kubectl -n kube-system edit configmap coredns`
## Cassandra Cluster
I've found a cassandra cluster with the next yamsl and it seems to work. I don't know why the busybox doesn't resolve the DNS.
### Create a Cassandra Headless Service
`kubectl create -f cassandra-service.yaml`
```yml
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cassandra
  name: cassandra
spec:
  clusterIP: None
  ports:
    - port: 9042
  selector:
    app: cassandra
```
`kubectl create -f local-volumes.yaml`
```yml
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cassandra-data-1
  labels:
    type: local
    app: cassandra
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/data/cassandra-data-1
  persistentVolumeReclaimPolicy: Recycle
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cassandra-data-2
  labels:
    type: local
    app: cassandra
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/data/cassandra-data-2
  persistentVolumeReclaimPolicy: Recycle
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cassandra-data-3
  labels:
    type: local
    app: cassandra
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/data/cassandra-data-3
  persistentVolumeReclaimPolicy: Recycle
```
`kubectl create -f cassandra-statefulset.yaml`
```yml
---                                                                                                        
apiVersion: "apps/v1beta1"                                                                                 
kind: StatefulSet                                                                                          
metadata:                                                                                                  
  name: cassandra                                                                                          
spec:
  serviceName: cassandra
  replicas: 1
  template:
    metadata:
      labels:
        app: cassandra
    spec:
      containers:
        - name: cassandra
          image: cassandra:3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7000
              name: intra-node
            - containerPort: 7001
              name: tls-intra-node
            - containerPort: 7199
              name: jmx
            - containerPort: 9042
              name: cql
          env:
            - name: CASSANDRA_SEEDS
              value: cassandra-0.cassandra.default.svc.cluster.local                                      
            - name: MAX_HEAP_SIZE
              value: 256M
            - name: HEAP_NEWSIZE
              value: 100M
            - name: CASSANDRA_CLUSTER_NAME
              value: "Cassandra"
            - name: CASSANDRA_DC
              value: "DC1"
            - name: CASSANDRA_RACK
              value: "Rack1"
            - name: CASSANDRA_ENDPOINT_SNITCH
              value: GossipingPropertyFileSnitch
          volumeMounts:
            - name: cassandra-data
              mountPath: /var/lib/cassandra/data
  volumeClaimTemplates:
    - metadata:
        name: cassandra-data
        annotations:  # comment line if you want to use a StorageClass                                    
          # or specify which StorageClass
          volume.beta.kubernetes.io/storage-class: ""   # comment line if you                             
          # want to use a StorageClass or specify which StorageClass                                      
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
```
After all these:
```bash
root@kmaster:~/Cassandra# kubectl get all --all-namespaces
NAMESPACE              NAME                                              READY   STATUS    RESTARTS   AGE
default                pod/cassandra-0                                   1/1     Running   0          2m21s
kube-system            pod/coredns-5c98db65d4-djb8j                      1/1     Running   0          29m
kube-system            pod/coredns-5c98db65d4-nlgbq                      1/1     Running   0          29m
kube-system            pod/etcd-kmaster                                  1/1     Running   0          28m
kube-system            pod/kube-apiserver-kmaster                        1/1     Running   0          28m
kube-system            pod/kube-controller-manager-kmaster               1/1     Running   0          28m
kube-system            pod/kube-flannel-ds-amd64-7jw9t                   1/1     Running   0          25m
kube-system            pod/kube-flannel-ds-amd64-kjr6w                   1/1     Running   0          27m
kube-system            pod/kube-proxy-9gwm6                              1/1     Running   0          25m
kube-system            pod/kube-proxy-qgz96                              1/1     Running   0          29m
kube-system            pod/kube-scheduler-kmaster                        1/1     Running   0          28m
kubernetes-dashboard   pod/kubernetes-dashboard-5c8f9556c4-h8sc9         1/1     Running   0          23m
kubernetes-dashboard   pod/kubernetes-metrics-scraper-86456cdd8f-wrcqv   1/1     Running   0          23m


NAMESPACE              NAME                                TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                  AGE
default                service/cassandra                   ClusterIP   None             <none>        9042/TCP                 14m
default                service/kubernetes                  ClusterIP   10.96.0.1        <none>        443/TCP                  29m
kube-system            service/kube-dns                    ClusterIP   10.96.0.10       <none>        53/UDP,53/TCP,9153/TCP   29m
kubernetes-dashboard   service/dashboard-metrics-scraper   ClusterIP   10.110.39.116    <none>        8000/TCP                 23m
kubernetes-dashboard   service/kubernetes-dashboard        ClusterIP   10.106.158.215   <none>        443/TCP                  23m

NAMESPACE     NAME                                     DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR                     AGE
kube-system   daemonset.apps/kube-flannel-ds-amd64     2         2         2       2            2           beta.kubernetes.io/arch=amd64     27m
kube-system   daemonset.apps/kube-flannel-ds-arm       0         0         0       0            0           beta.kubernetes.io/arch=arm       27m
kube-system   daemonset.apps/kube-flannel-ds-arm64     0         0         0       0            0           beta.kubernetes.io/arch=arm64     27m
kube-system   daemonset.apps/kube-flannel-ds-ppc64le   0         0         0       0            0           beta.kubernetes.io/arch=ppc64le   27m
kube-system   daemonset.apps/kube-flannel-ds-s390x     0         0         0       0            0           beta.kubernetes.io/arch=s390x     27m
kube-system   daemonset.apps/kube-proxy                2         2         2       2            2           beta.kubernetes.io/os=linux       29m

NAMESPACE              NAME                                         READY   UP-TO-DATE   AVAILABLE   AGE
kube-system            deployment.apps/coredns                      2/2     2            2           29m
kubernetes-dashboard   deployment.apps/kubernetes-dashboard         1/1     1            1           23m
kubernetes-dashboard   deployment.apps/kubernetes-metrics-scraper   1/1     1            1           23m

NAMESPACE              NAME                                                    DESIRED   CURRENT   READY   AGE
kube-system            replicaset.apps/coredns-5c98db65d4                      2         2         2       29m
kubernetes-dashboard   replicaset.apps/kubernetes-dashboard-5c8f9556c4         1         1         1       23m
kubernetes-dashboard   replicaset.apps/kubernetes-metrics-scraper-86456cdd8f   1         1         1       23m

NAMESPACE   NAME                         READY   AGE
default     statefulset.apps/cassandra   1/1     13m
```
