### ISSUE TITLE
Support customize object metadata in ClusterConfiguration

### ISSUE THREAD

**Issue by jfbai** [kubernetes/kubeadm#1676]
## What keywords did you search in kubeadm issues before filing this one?

ObjectMeta, annotation, label

## Is this a BUG REPORT or FEATURE REQUEST?

FEATURE REQUEST

## In Details

Currently, kubeadm does not support add customized labels or annotations into control-plane components ( I don't know if it is by design not to support such a feature). It would be better to add object metadata in the ClusterConfiguration.

```
apiVersion: kubeadm.k8s.io/v1beta1
kind: ClusterConfiguration
kubernetesVersion: v1.15.0
clusterName: "example-cluster"
apiServer:
    metadata:
        annotations:
            example: "example"
        labels:
            example: "example"
    extraArgs:
        v: "3"
```

If this feature request is accepted, I can help implement.

/kind feature
