### ISSUE TITLE
stop using etcdctl as a liveness probe

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubeadm#1708]
there is a plan to move all kubernetes images to distroless, which means that the etcd image can no longer host the etcdctl binary.

links:
https://github.com/kubernetes/enhancements/blob/master/keps/sig-release/20190316-rebase-images-to-distroless.md
https://github.com/kubernetes/kubernetes/issues/70249
https://github.com/kubernetes/kubernetes/pull/77748#issuecomment-491420068

currently in kubeadm we have a probe for etcd healthchecks that is defined here:
https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/util/staticpod/utils.go#L82-L98

and results in this object:
```
livenessProbe:
      exec:
        command:
        - /bin/sh
        - -ec
        - ETCDCTL_API=3 etcdctl --endpoints=https://[127.0.0.1]:2379 --cacert=/etc/kubernetes/pki/etcd/ca.crt --cert=/etc/kubernetes/pki/etcd/healthcheck-client.crt --key=/etc/kubernetes/pki/etcd/healthcheck-client.key
          get foo
      failureThreshold: 8
      initialDelaySeconds: 15
      timeoutSeconds: 15
```

while the potential removal of etcdctl from the images, might cause a breakage to more projects and not only kubeadm, to be on the safer side, we should think of alternative ways of implementing the health check.

possible solution:
https://github.com/etcd-io/etcd/blob/master/Documentation/op-guide/monitoring.md#health-check
