### ISSUE TITLE
[ASK QUESTION]   kubeadm deploy podname with hostname

### ISSUE THREAD

**Issue by banghuaji** [kubernetes/kubeadm#1789]
I use kubeadm deploy kubernetes.

found the yaml store in  /etc/kubernetes/manifests,
such as 
```
root@192-168-104-240:/etc/kubernetes/manifests# cat etcd.yaml 
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    component: etcd   
    tier: control-plane
  name: etcd                        
  namespace: kube-system
spec:
  containers:
```
**pod name is etcd ,but when i show the kubernetes pod info ,Show the following:**
```
kube-apiserver-192-168-104-240                1/1     Running   1          65d
kube-controller-manager-192-168-104-240       1/1     Running   3          65d
```
the pod name with hostname ,why??
