### ISSUE TITLE
kubeadm losing enforceNodeAllocatable option

### ISSUE THREAD

**Issue by ezh** [kubernetes/kubeadm#1832]
## Versions

```
kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:37:41Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T17:01:15Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:32:14Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```

## What happened?

I need to set `cgroupsPerQOS: false`
Here is a part of my kubeadm.yaml:
```
---
    kind: KubeletConfiguration
    apiVersion: kubelet.config.k8s.io/v1beta1
    cgroupsPerQOS: false
    cgroupDriver: cgroupfs
    enforceNodeAllocatable: []
```
enforceNodeAllocatable must be empty because of 
```
KubeletConfiguration: Invalid value: "": invalid configuration: EnforceNodeAllocatable (--enforce-node-allocatable) is not supported unless Cgroups
PerQOS (--cgroups-per-qos) feature is turned on
```
I provided explicit value with empty array.
/var/lib/kubelet/config.yaml haven't `enforceNodeAllocatable`. `kubeadm` is finished, but `kubelet` is unable to start.

The only solution is to manually update /var/lib/kubelet/config.yaml or add the `--enforce-node-allocatable` option as kubelet parameter.

## What you expected to happen?

`enforceNodeAllocatable: []` should be preserved in /var/lib/kubelet/config.yaml

## How to reproduce it (as minimally and precisely as possible)?

run kubeadm init -config kubeadm.yaml with:
```
---
    kind: KubeletConfiguration
    apiVersion: kubelet.config.k8s.io/v1beta1
    cgroupsPerQOS: false
    enforceNodeAllocatable: []
```

**Comment by neolit123** [comment]
hello, this seems like a kubelet issue.

> enforceNodeAllocatable: [] should be preserved in /var/lib/kubelet/config.yaml

kubeadm itself does not manage this field.
instead of being preserved what value are you seeing for this field after kubeadm finishes?

also what is your kubelet version?

**Comment by neolit123** [comment]
please answer the above questions, but i think you can workaround that by passing the flag from the kubeadm config like so for Init or JoinConfiguration:
```
apiVersion: kubeadm.k8s.io/v1beta2
kind: InitConfiguration
nodeRegistration:
  kubeletExtraArgs:
    enforce-node-allocatable: ""
```
xref https://godoc.org/k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/v1beta2

@rosti
is this because the KubeletConfiguration has
```
EnforceNodeAllocatable []string `json:"enforceNodeAllocatable,omitempty"`
```

if the array is empty it's always defaulted to "pods"?
https://godoc.org/k8s.io/kubelet/config/v1beta1

**Comment by ezh** [comment]
```
 kubelet --version
Kubernetes v1.15.0
```
1. command line `--enforce-node-allocatable` is deprecated. We should use config instead;
2. I tried kubeletExtraArgs approach but this option was lost when I used `kubeadm join ...` on neighbor.

Am I correct? Or did I missed something?

**Comment by neolit123** [comment]
> command line --enforce-node-allocatable is deprecated. We should use config instead;

this is true. but the config field does not work (see bellow).

> I tried kubeletExtraArgs approach but this option was lost when I used kubeadm join ... on neighbor.

JoinConfiguration also has
```
nodeRegistration:
  kubeletExtraArgs:
    enforce-node-allocatable: ""
```
but this means passing `--config` on `kubeadm join` too.

> KubeletConfiguration: Invalid value: "": invalid configuration: EnforceNodeAllocatable (--enforce-node-allocatable) is not supported unless Cgroups
PerQOS (--cgroups-per-qos) feature is turned on.

i'm closing this because this is a problem in the kubelet.
passing the empty list `[]` from the kubelet config does not work and the user has to pass the flag.

verified by testing locally using:
doesn't work:
```
kind: ClusterConfiguration
apiVersion: kubeadm.k8s.io/v1beta2
kubernetesVersion: v1.16.0
---
kind: KubeletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1
enforceNodeAllocatable: []
cgroupsPerQOS: false
cgroupDriver: cgroupfs
```

works:
```
kind: ClusterConfiguration
apiVersion: kubeadm.k8s.io/v1beta2
kubernetesVersion: v1.16.0
---
kind: KubeletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1
enforceNodeAllocatable: []
cgroupsPerQOS: false
cgroupDriver: cgroupfs
---
kind: InitConfiguration
apiVersion: kubeadm.k8s.io/v1beta2
nodeRegistration:
  kubeletExtraArgs:
    enforce-node-allocatable: ""
```

feel free to open a kubernetes/kubernetes ticket for this (i couldn't find one).
