### ISSUE TITLE
Kubeadm v1.16.2 - cannot get https (dial tcp: i/o timeout ErrRegisterACMEAccount)

### ISSUE THREAD

**Issue by patsadow2** [kubernetes/kubeadm#1857]
FROM: https://github.com/jetstack/cert-manager/issues/2279

I spent 2 days trying to make it run with no effects :(

**Describe the bug**:
I cannot get cert for https

Failed to verify ACME account: Get https://acme-staging-v02.api.letsencrypt.org/directory: dial tcp: i/o timeout
ErrRegisterACMEAccount

- i am able to curl "https://acme-staging-v02.api.letsencrypt.org/directory" from cluster and pods cert-manager
- i also tried to add:
```
podDnsPolicy: "None"
podDnsConfig:
  nameservers:
    - "1.1.1.1"
    - "8.8.8.8"
```

**Expected behaviour**:
certs

**Steps to reproduce the bug**:

Installed KubeAdm, MetalLB, Ingress, Helm

```
kubectl apply --validate=false -f https://raw.githubusercontent.com/jetstack/cert-manager/release-0.11/deploy/manifests/00-crds.yaml
kubectl create namespace cert-manager

#kubectl apply -f cert-app.yaml (problem with web.io)

helm repo add jetstack https://charts.jetstack.io
helm repo update
helm install  --name cert-manager --namespace cert-manager --version v0.11.0 jetstack/cert-manager
#helm install  --name cert-manager --namespace cert-manager --version v0.11.0 stable/cert-manager -f values.yaml
#helm install --name cert-manager --namespace kube-system --version v0.11.0 jetstack/cert-manager -f values.yaml
```

cert-app.yaml

```
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
 name: letsencrypt-staging
spec:
 acme:
   server: https://acme-staging-v02.api.letsencrypt.org/directory
   email: xxx@gmail.com
   privateKeySecretRef:
     name: letsencrypt-staging
   solvers:
   - http01:
       ingress:
         class: nginx
---         
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuard
spec:
  selector:
    matchLabels:
      app: kuard
  replicas: 1
  template:
    metadata:
      labels:
        app: kuard
    spec:
      containers:
      - image: gcr.io/kuar-demo/kuard-amd64:1
        imagePullPolicy: Always
        name: kuard
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: kuard
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: kuard
---    
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kuard
  annotations:
    kubernetes.io/ingress.class: nginx   
    cert-manager.io/issuer: letsencrypt-staging
spec:
  tls:
  - hosts:
    - mycert.xxx.com
    secretName: quickstart-example-tls
  rules:
  - host: mycert.xxx.com
    http:
      paths:
      - path: /
        backend:
          serviceName: kuard
          servicePort: 80

```
**Anything else we need to know?**:

Please help

**Environment details:**:
- Kubernetes version: kubeadm 1.16
- Cloud-provider/provisioner linux: 16.04
- cert-manager version: v0.11
- Install method: helm

/kind bug
