### ISSUE TITLE
Kubeadm init phase: kubelet-start failed

### ISSUE THREAD

**Issue by Davidrjx** [kubernetes/kubeadm#1908]
## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`):
kubeadm version: &version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:14:19Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
**Environment**:
- **Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:16:51Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
- **Cloud provider or hardware configuration**:
bare metal
- **OS** (e.g. from /etc/os-release):
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
- **Kernel** (e.g. `uname -a`):
Linux fuxi-dl-66 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1 (2019-04-12) x86_64 GNU/Linux
- **Others**:

## What happened?

kubeadm init phase, kubelet start failed, rough error looks like
```
...
[kubelet-check] It seems like the kubelet isn't running or healthy.
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10248/healthz' failed with error: Get http://localhost:10248/healthz: dial tcp 127.0.0.1:10248: connect: connection refused.
...
```

## What you expected to happen?

kubeadm init phase, all steps ok, especially for kubelet

## How to reproduce it (as minimally and precisely as possible)?

kubeadm create a HA cluster with three nodes by config file

## Anything else we need to know?
kubeadm component version 1.15.5

**Comment by neolit123** [comment]
/triage support
please provide the whole list and exact commands you are executing.

**Comment by Davidrjx** [comment]
@neolit123 ok
kubeadm init config file looks like
```
apiVersion: kubeadm.k8s.io/v1beta2
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: "10.90.8.51"
  bindPort: 6443
nodeRegistration:
  kubeletExtraArgs:
    cgroup-driver: "systemd"
---
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
clusterName: "danlu-hp-k8s-cluster"
kubernetesVersion: "v1.15.5"
controlPlaneEndpoint: "10.90.8.253:16443"
apiServer:
  certSANs:
  - "10.90.8.253"
  extraArgs:
    apiserver-count: "3"
    service-node-port-range: "35000-45000"
etcd:
  external:
    endpoints:
    - "https://10.90.8.51:2379"
    - "https://10.90.8.61:2379"
    - "https://10.90.8.81:2379"
    caFile: "/etc/kubernetes/pki/etcd/certs/ca.pem"
    certFile: "/etc/kubernetes/pki/etcd/certs/client.pem"
    keyFile: "/etc/kubernetes/pki/etcd/certs/client-key.pem"
networking:
  podSubnet: "192.168.0.0/16"
---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
mode: "ipvs"
#resourceContainer: "/"
nodePortAddresses:
- 10.90.1.0/24
- 10.90.8.0/24
- 10.170.22.0/24
- 10.200.0.0/24
portRange: "45001-55001"
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
cpuManagerPolicy: static
cgroupDriver: "systemd"
podPidsLimit: 10240
enforceNodeAllocatable:
- "pods"
- "kube-reserved"
- "system-reserved"
systemReserved:
  cpu: "2"
  memory: "8Gi"
systemReservedCgroup: "/system.slice"
kubeReserved:
  cpu: "2"
  memory: "8Gi"
  ephemeral-storage: "10Gi"
kubeReservedCgroup: "/system.slice/kubelet.service"
```
and exec `sudo kubeadm init --config kubeadm-config-v1.15.5.yaml --upload-certs`
