### ISSUE TITLE
CoreDNS pods scheduled on the control plane node

### ISSUE THREAD

**Issue by ereslibre** [kubernetes/kubeadm#1931]
## Is this a BUG REPORT or FEATURE REQUEST?

/kind feature

## What happened?

When deploying a Kubernetes cluster using `kubeadm` we are creating CoreDNS with a [default replica of 2](https://github.com/kubernetes/kubernetes/blob/d87c921a516a5b0387269910cef8551fae62de7f/cmd/kubeadm/app/phases/addons/dns/manifests.go#L226).

When performing the `kubeadm init` execution, the CoreDNS deployment will be scheduled fully on the only control plane node available at this time. When joining further control plane nodes or worker nodes both CoreDNS instances will remain on the first control plane node where they were scheduled at the time of creation.

## What you expected to happen?

This is to gather information about how would we feel about performing the following changes:

- Introduce a `preferredDuringSchedulingIgnoredDuringExecution` anti-affinity rule, so the scheduler will favour nodes where there's not a CoreDNS pod running already.

This on its own doesn't make any difference (also, note that it's `preferred` and not `required`: otherwise a single control plane node without workers would never succeed to create the CoreDNS deployment, since requirements would never be met).

The next step then would be that `kubeadm` when `kubeadm join` has finished, and the new node is registered, would perform the following checks:

- Read the `CoreDNS` deployment pods from the Kube API. If all pods are running on the same node, perform a kill of one pod, forcing Kubernetes to reschedule (at this point, the `preferredDuringSchedulingIgnoredDuringExecution` mentioned before will get into the game, and the rescheduled pod will be placed on the new node).

Maybe this is something we don't want to do, as we would be making `kubeadm` tied to workload specific logic, and with the addon story coming it might not make sense. However, this is something that happens on every `kubeadm` based deployment, and that will make CoreDNS fail temporarily if the first control plane node goes away in an HA environment until those pods are rescheduled somewhere else. Just because they were initially scheduled on the only control plane node available.

What do you think? cc/ @neolit123 @rosti @fabriziopandini @yastij

**Comment by neolit123** [comment]
@ereslibre this is a duplicate of:
https://github.com/kubernetes/kubeadm/issues/1657

please read the whole discussion there.

>preferredDuringSchedulingIgnoredDuringExecution

this is problematic because it would leave the second replica as pending.
if someone is running the e2e test suite on a single CP node cluster it will fail.

**Comment by ereslibre** [comment]
> this is problematic because it would leave the second replica as pending.

This should not happen with `preferredDuringSchedulingIgnoredDuringExecution`, but with `requiredDuringSchedulingIgnoredDuringExecution`. I can check though, but I'm fairly sure with `preferred` it will just work even with a single node.

**Comment by neolit123** [comment]
>  I can check though, but I'm fairly sure with preferred it will just work even with a single node.

both replicas will land on the same CP node in the begging and then then the "join" process has to amend the Deployment?

**Comment by ereslibre** [comment]
Yes, the `join` process would `kubectl delete` one of the pods through the API, I specify the details on the body of the issue.

**Comment by neolit123** [comment]
please add this as agenda for next week.
the future coredns operator (as kubeadm will no longer include coredns in the future, by default) will run it as a DaemonSet.

i'm really in favor of breaking the users now and deploying it as DS and adding an action required in the release notes.

**Comment by neolit123** [comment]
@rajansandeep i proposed that we should chat about this in the next office hours on Wednesday.
potentially decide if we want to proceed with changes for 1.18.

**Comment by rajansandeep** [comment]
@neolit123 Yes, I agree. Would like to discuss what would be the potential direction for this.

**Comment by neolit123** [comment]
today i played with deploying CoreDNS as a DS with this manifest (based on the existing Deployment manifest). it works fine and targets CP nodes only.

<details>

```
apiVersion: apps/v1
  kind: DaemonSet
  metadata:
    name: {{ .DeploymentName }}
    namespace: kube-system
    labels:
      k8s-app: kube-dns
  spec:
    selector:
      matchLabels:
        k8s-app: kube-dns
    template:
      metadata:
        labels:
          k8s-app: kube-dns
      spec:
        priorityClassName: system-cluster-critical
        serviceAccountName: coredns
        tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
        - key: {{ .ControlPlaneTaintKey }}
          effect: NoSchedule
        nodeSelector:
          beta.kubernetes.io/os: linux
          {{ .ControlPlaneTaintKey }}: ""
        containers:
        - name: coredns
          image: {{ .Image }}
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: 170Mi
            requests:
              cpu: 100m
              memory: 70Mi
          args: [ "-conf", "/etc/coredns/Corefile" ]
          volumeMounts:
          - name: config-volume
            mountPath: /etc/coredns
            readOnly: true
          ports:
          - containerPort: 53
            name: dns
            protocol: UDP
          - containerPort: 53
            name: dns-tcp
            protocol: TCP
          - containerPort: 9153
            name: metrics
            protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /ready
              port: 8181
              scheme: HTTP
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              add:
              - NET_BIND_SERVICE
              drop:
              - all
            readOnlyRootFilesystem: true
        dnsPolicy: Default
        volumes:
          - name: config-volume
            configMap:
              name: coredns
              items:
              - key: Corefile
                path: Corefile
```

</details>

i think it's also time to deprecate kube-dns in 1.18 and apply a 3 cycle deprecation policy to it, unless we switch to an addon installer sooner than that.
