### ISSUE TITLE
Support DNS SRV for external etcd endpoints discovery

### ISSUE THREAD

**Issue by YanzheL** [kubernetes/kubeadm#1933]
## Is this a request for help?

no

## What keywords did you search in kubeadm issues before filing this one?
external etcd, DNS SRV

## Is this a BUG REPORT or FEATURE REQUEST?

FEATURE REQUEST

## Versions

**kubeadm version** (use `kubeadm version`): 1.16.3

**Environment**:
- **Kubernetes version** (use `kubectl version`):  1.16.3

## What happened?
Currently, we can configure external etcd endpoints in `kubeadm-config.yaml` like this
```yaml
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
...
etcd:
    external:
        endpoints:
        - https://ETCD_0_IP:2379
        - https://ETCD_1_IP:2379
        - https://ETCD_2_IP:2379
....
```
It needs me to provide all endpoints of external etcd cluster nodes, which lacks a mechanism of "auto discovery".

## What you expected to happen?

Inspired by [etcd cluster DNS discovery](https://github.com/etcd-io/etcd/blob/master/Documentation/v2/clustering.md#dns-discovery), etcd cluster nodes support DNS SRV lookup via etcd argument `--discovery-srv etcd.example.com`  to discover other nodes, I suggest that kubeadm can use a similar way to discover external etcd endpoints.

For example:

```yaml
...
etcd:
    external:
        endpoints:
        - srv://etcd.example.com
....
```

## Anything else we need to know?

Their implementation for this feature: etcd-io/etcd#8281

**Comment by neolit123** [comment]
hi, this request is related to:
https://github.com/kubernetes/kubeadm/issues/1598
but for external etcd.

> It needs me to provide all endpoints of external etcd cluster nodes, which lacks a mechanism of "auto discovery".

you can also put your external etcd nodes behind a load balancer and only list the LB endpoint instead of all the members.

```
etcd:
    external:
        endpoints:
        - srv://etcd.example.com
```

this will not work, because in the case of external etcd the list of endpoints (or a single LB) are simply passed on the kube-apiserver with (TLS ensured). for external etcd kubeadm does not manage etcd members and the DNS discovery.

this feels to me like a feature request for the kube-apiserver.

i'm going to keep this open for a discussion, but i don't think there is much we can do on the kubeadm side.

@kubernetes/sig-cluster-lifecycle
