### ISSUE TITLE
discovery.bootstrapToken.token missing port in address

### ISSUE THREAD

**Issue by andpeterson** [kubernetes/kubeadm#1956]
#1247  Is this a BUG REPORT or FEATURE REQUEST?
BUG REPORT

## Versions

**kubeadm version:** v1.15.3

**Environment**: Dev
- **Kubernetes version** (use `kubectl version`): v1.15.3
- **Cloud provider or hardware configuration**: VirtualBox
- **OS** (e.g. from /etc/os-release): Ubuntu 16.04.6 LTS (Xenial Xerus)
- **Kernel** (e.g. `uname -a`): 4.4.0-169-generic
- **Others**:

## What happened?
Two vagrant ubuntu boxes. The master box is initialized with this script. 
```
sudo kubeadm config images pull --kubernetes-version=v1.15.3
sudo kubeadm init --kubernetes-version=v1.15.3 --pod-network-cidr=10.244.0.0/16 --apiserver-advertise-address=192.168.33.11
```
along with initializing other tools such as helm, flannel, open-ebs, MetalLB...

The second machine being the slave.
This config.yaml file is located with our setup script.
```yaml
apiVersion: kubeadm.k8s.io/v1beta2
kind: JoinConfiguration
discovery:
  bootstrapToken:
    apiServerEndpoint: 192.168.33.11:6443
    token: TOKEN
    caCertHashes:
    - sha256:HASH
  timeout: 5m0s
nodeRegistration:
  name: testname
  criSocket: /var/run/dockershim.sock
  name: ubuntu-master
  taints: null
```
and is executed with
sudo kubeadm join /installer/config.yaml --discovery-token-ca-cert-hash sha256:HASH

Outputing this error:
```
[discovery.bootstrapToken.token: Invalid value: "": the bootstrap token is invalid, discovery.bootstrapToken.apiServerEndpoint: Invalid value: "/installer/config.yaml": address /installer/config.yaml: missing port in address, discovery.tlsBootstrapToken: Invalid value: "": the bootstrap token is invalid]
```
Probably doesnt change anything but this error occurs when I change the apiServerEndpoint to 
```yaml
    apiServerEndpoint: 192.168.33.11:6443
```
## What you expected to happen?
The slave machine to join to the master machine.

## How to reproduce it (as minimally and precisely as possible)?
sudo kubeadm join /installer/config.yaml --discovery-token-ca-cert-hash sha256:HASH

config.yaml
```
apiVersion: kubeadm.k8s.io/v1beta2
kind: JoinConfiguration
discovery:
  bootstrapToken:
    apiServerEndpoint: 192.168.33.11/6443
    token: TOKEN
    caCertHashes:
    - sha256:HASH
  timeout: 5m0s
nodeRegistration:
  name: testname
  criSocket: /var/run/dockershim.sock
  name: ubuntu-master
  taints: null
```
## Anything else we need to know?
The error says that the port doesn't exist even though I've specified it. Either the apiServerEndpoint isn't getting parsed correctly or the error message is unrelated to the actual error.

Additionally
`kubeadm join /installer/config.yaml` won't run without `--discovery-token-ca-cert-hash sha256:HASH` even though its specified in the file. May be related, or a separate issue.
The error from that is 
```
[discovery.bootstrapToken: Invalid value: "": using token-based discovery without caCertHashes can be unsafe. Set unsafeSkipCAVerification as true in your kubeadm config file or pass --discovery-token-unsafe-skip-ca-verification flag to continue, discovery.bootstrapToken.token: Invalid value: "": the bootstrap token is invalid, discovery.bootstrapToken.apiServerEndpoint: Invalid value: "/installer/test.yaml": address /installer/test.yaml: missing port in address, discovery.tlsBootstrapToken: Invalid value: "": the bootstrap token is invalid]
```

Briefly the reason I'm passing config.yaml is because I'd like to modify the nodes label on the current machine rather than manually doing it on the master machine.
