### ISSUE TITLE
QUESTION: How to persist values set via kubeadm init

### ISSUE THREAD

**Issue by msschl** [kubernetes/kubeadm#2048]
I initialized my cluster with `--service-dns-domain` and `--service-cidr`.

Unfortunately after upgrading to 1.16 and 1.17 these config values where not persisted.
I edit the ConfigMaps kubelet-config-1.16, kubelet-config-1.17 and kubeadm-config manually.

Is there a way to persist these values while doing a cluster update?

# Versions

```sh
kubeadm version: &version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:12:12Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}

kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:16:51Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:07:13Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}

cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

**Comment by neolit123** [comment]
hi, please fill the issue template to provide full detail about your issue:
https://github.com/kubernetes/kubeadm/blob/master/.github/ISSUE_TEMPLATE.md
make sure you include the PATCH releases of 1.16 and 1.17 you are using.

passing these flags to kubeadm would mean it writes the values in the ClusterConfiguration, propagates some values to components such as kubelet and kube-proxy and then it persist these in config maps as you have observed.

i'm not aware of a case where kubeadm upgrade stomps these users values.

/triage needs-information

**Comment by msschl** [comment]
I do have some configuration that I pass in on a cluster update.

```sh
kubeadm upgrade diff --config /etc/kubernetes/kubeadm.conf
kubeadm upgrade plan --config /etc/kubernetes/kubeadm.conf
kubeadm upgrade apply v1.17.3 --config /etc/kubernetes/kubeadm.conf
```

The config file I use above.
```yaml
 cat /etc/kubernetes/kubeadm.conf
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
apiServer:
  extraArgs:
    anonymous-auth: "false"
    audit-log-maxage: "30"
    audit-log-maxbackup: "10"
    audit-log-maxsize: "200"
    audit-log-path: "/var/log/kubernetes/audit.log"
    audit-policy-file: "/etc/kubernetes/policies/audit-policy.yaml"
    enable-admission-plugins: "NodeRestriction,PodSecurityPolicy,AlwaysPullImages,ServiceAccount" #SecurityContextDeny
    #encryption-provider-config: "EncryptionConfig"
    feature-gates: "AdvancedAuditing=true"
    #kubelet-certificate-authority: ""
    profiling: "false"
    #service-account-key-file: ""
    tls-cipher-suites: "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_128_GCM_SHA256"
  extraVolumes:
    - name: "policies"
      hostPath: "/etc/kubernetes/policies"
      mountPath: "/etc/kubernetes/policies"
      readOnly: true
      pathType: "DirectoryOrCreate"
    - name: "log"
      hostPath: "/var/log/kubernetes"
      mountPath: "/var/log/kubernetes"
      pathType: "DirectoryOrCreate"
#  livenessProbe:
#    failureThreshold: 8
#    ## Kube-apiserver keeps restarting when anonymous-auth is set to false. See issue https://github.com/kubernetes/kubernetes/issues/43784 for more informations.
#    tcpSocket:
#      host: "172.18.2.91"
#      port: "6443"
#    initialDelaySeconds: "15"
#    timeoutSeconds: "15"

scheduler:
  extraArgs:
    profiling: "false"

controllerManager:
  extraArgs:
    allocate-node-cidrs: "true"
    cluster-cidr: "10.244.0.0/16"
    node-cidr-mask-size: "24"
    service-cluster-ip-range: "10.96.0.0/12"
    profiling: "false"
    terminated-pod-gc-threshold: "10"
    feature-gates: "RotateKubeletServerCertificate=true"
```
