### ISSUE TITLE
Kubeadm upgrade apply v1.17.4 fails on step `[upgrade/apply] Upgrading your Static Pod-hosted control plane to version "v1.17.4"...`

### ISSUE THREAD

**Issue by msschl** [kubernetes/kubeadm#2061]
Performing an update from v1.17.3 to v1.17.4 fails in the step: `[upgrade/apply] Upgrading your Static Pod-hosted control plane to version "v1.17.4"...`

Logs:
```
kubeadm upgrade apply v1.17.4
[upgrade/config] Making sure the configuration is correct:
[upgrade/config] Reading configuration from the cluster...
[upgrade/config] FYI: You can look at this config file with 'kubectl -n kube-system get cm kubeadm-config -oyaml'
[preflight] Running pre-flight checks.
[upgrade] Making sure the cluster is healthy:
[upgrade/version] You have chosen to change the cluster version to "v1.17.4"
[upgrade/versions] Cluster version: v1.17.3
[upgrade/versions] kubeadm version: v1.17.4
[upgrade/confirm] Are you sure you want to proceed with the upgrade? [y/N]: y
[upgrade/prepull] Will prepull images for components [kube-apiserver kube-controller-manager kube-scheduler etcd]
[upgrade/prepull] Prepulling image for component etcd.
[upgrade/prepull] Prepulling image for component kube-apiserver.
[upgrade/prepull] Prepulling image for component kube-controller-manager.
[upgrade/prepull] Prepulling image for component kube-scheduler.
[apiclient] Found 0 Pods for label selector k8s-app=upgrade-prepull-etcd
[apiclient] Found 1 Pods for label selector k8s-app=upgrade-prepull-kube-controller-manager
[apiclient] Found 0 Pods for label selector k8s-app=upgrade-prepull-kube-scheduler
[apiclient] Found 1 Pods for label selector k8s-app=upgrade-prepull-kube-apiserver
[apiclient] Found 1 Pods for label selector k8s-app=upgrade-prepull-etcd
[apiclient] Found 1 Pods for label selector k8s-app=upgrade-prepull-kube-scheduler
[upgrade/prepull] Prepulled image for component kube-controller-manager.
[upgrade/prepull] Prepulled image for component kube-scheduler.
[upgrade/prepull] Prepulled image for component kube-apiserver.
[upgrade/prepull] Prepulled image for component etcd.
[upgrade/prepull] Successfully prepulled the images for all the control plane components
[upgrade/apply] Upgrading your Static Pod-hosted control plane to version "v1.17.4"...
[upgrade/apply] FATAL: timed out waiting for the condition
To see the stack trace of this error execute with --v=5 or higher
```

## Versions

```
kubeadm version: &version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:12:12Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}

kubectl version
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:07:13Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}

cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

**Comment by msschl** [comment]
Logs from running `kubeadm upgrade apply v1.17.4` with the `--v=5` flag:

```
...
[upgrade/apply] Upgrading your Static Pod-hosted control plane to version "v1.17.4"...
timed out waiting for the condition
[upgrade/apply] FATAL
k8s.io/kubernetes/cmd/kubeadm/app/cmd/upgrade.runApply
        /workspace/anago-v1.17.4-beta.0.54+12bf0cb73007af/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/upgrade/apply.go:165
k8s.io/kubernetes/cmd/kubeadm/app/cmd/upgrade.NewCmdApply.func1
        /workspace/anago-v1.17.4-beta.0.54+12bf0cb73007af/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/upgrade/apply.go:79
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute
        /workspace/anago-v1.17.4-beta.0.54+12bf0cb73007af/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:826
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC
        /workspace/anago-v1.17.4-beta.0.54+12bf0cb73007af/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:914
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute
        /workspace/anago-v1.17.4-beta.0.54+12bf0cb73007af/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:864
k8s.io/kubernetes/cmd/kubeadm/app.Run
        /workspace/anago-v1.17.4-beta.0.54+12bf0cb73007af/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/kubeadm.go:50
main.main
        _output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/kubeadm.go:25
runtime.main
        /usr/local/go/src/runtime/proc.go:203
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1357
```

**Comment by msschl** [comment]
kubeadm-config
```yaml
kubectl -n kube-system get cm kubeadm-config -oyaml
apiVersion: v1
data:
  ClusterConfiguration: |
    apiServer:
      extraArgs:
        authorization-mode: Node,RBAC
        audit-log-maxage: "30"
        audit-log-maxbackup: "10"
        audit-log-maxsize: "200"
        audit-log-path: "/var/log/kubernetes/audit.log"
        audit-policy-file: "/etc/kubernetes/policies/audit-policy.yaml"
        enable-admission-plugins: "NodeRestriction,PodSecurityPolicy,AlwaysPullImages,ServiceAccount" #SecurityContextDeny
        encryption-provider-config: "/etc/kubernetes/encryption.conf"
        feature-gates: "AdvancedAuditing=true"
        profiling: "false"
        tls-cipher-suites: "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_128_GCM_SHA256"
      extraVolumes:
        - name: "policies"
          hostPath: "/etc/kubernetes/policies"
          mountPath: "/etc/kubernetes/policies"
          readOnly: true
          pathType: "DirectoryOrCreate"
        - name: "log"
          hostPath: "/var/log/kubernetes"
          mountPath: "/var/log/kubernetes"
          pathType: "DirectoryOrCreate"
        - name: "encription"
          hostPath: "/etc/kubernetes/encryption.conf"
          mountPath: "/etc/kubernetes/encryption.conf"
          readOnly: true
          pathType: "File"
      timeoutForControlPlane: 4m0s
    apiVersion: kubeadm.k8s.io/v1beta2
    certificatesDir: /etc/kubernetes/pki
    clusterName: kubernetes
    controllerManager:
      extraArgs:
        profiling: "false"
    dns:
      type: CoreDNS
    etcd:
      local:
        dataDir: /var/lib/etcd
    imageRepository: k8s.gcr.io
    kind: ClusterConfiguration
    kubernetesVersion: v1.17.3
    networking:
      dnsDomain: cluster.company.xyz
      podSubnet: 10.244.0.0/16
      serviceSubnet: 10.96.0.0/12
    scheduler:
      extraArgs:
        profiling: "false"
  ClusterStatus: |
    apiEndpoints:
      lxkubemaster01:
        advertiseAddress: 172.18.2.91
        bindPort: 6443
    apiVersion: kubeadm.k8s.io/v1beta2
    kind: ClusterStatus
kind: ConfigMap
metadata:
  creationTimestamp: "2020-02-29T21:32:36Z"
  name: kubeadm-config
  namespace: kube-system
  resourceVersion: "3132201"
  selfLink: /api/v1/namespaces/kube-system/configmaps/kubeadm-config
  uid: 4faefee1-8138-4d8f-9bff-25449273aee7
```

**Comment by msschl** [comment]
kubelet-config-1.17
```yaml
apiVersion: v1
data:
  kubelet: |
    apiVersion: kubelet.config.k8s.io/v1beta1
    authentication:
      anonymous:
        enabled: false
      webhook:
        cacheTTL: 0s
        enabled: true
      x509:
        clientCAFile: /etc/kubernetes/pki/ca.crt
    authorization:
      mode: Webhook
      webhook:
        cacheAuthorizedTTL: 0s
        cacheUnauthorizedTTL: 0s
    clusterDNS:
    - 10.96.0.10
    clusterDomain: cluster.company.xyz
    cpuManagerReconcilePeriod: 0s
    evictionPressureTransitionPeriod: 0s
    fileCheckFrequency: 0s
    healthzBindAddress: 127.0.0.1
    healthzPort: 10248
    httpCheckFrequency: 0s
    imageMinimumGCAge: 0s
    kind: KubeletConfiguration
    nodeStatusReportFrequency: 0s
    nodeStatusUpdateFrequency: 0s
    rotateCertificates: true
    runtimeRequestTimeout: 0s
    staticPodPath: /etc/kubernetes/manifests
    streamingConnectionIdleTimeout: 0s
    syncFrequency: 0s
    volumeStatsAggPeriod: 0s
kind: ConfigMap
metadata:
  creationTimestamp: "2020-02-29T21:32:36Z"
  name: kubelet-config-1.17
  namespace: kube-system
  resourceVersion: "153"
  selfLink: /api/v1/namespaces/kube-system/configmaps/kubelet-config-1.17
  uid: bffb790d-85c7-4348-b439-cca6b300ee13
```

**Comment by neolit123** [comment]
thanks for the report.

please answer these questions:
- is the existing cluster healthy?
- can you show me the list of pods in the kube-system namespace before upgrade apply?
- does the failure happen consistently?
- are you using the --experimental-kustomize feature?
- are you passing a --config to the upgrade apply command?

/triage needs-information

**Comment by neolit123** [comment]
the timeout must be coming from here:
https://github.com/kubernetes/kubernetes/blob/release-1.17/cmd/kubeadm/app/phases/upgrade/staticpods.go#L410
https://github.com/kubernetes/kubernetes/blob/58fcca211f62d2d9dd7932abb255111505d553f9/cmd/kubeadm/app/util/apiclient/wait.go#L240-L252

which is odd because the responsibility of this function is to obtain a list of hashes for the control-plane pods on this node. i have not seen this error recently.

please show the output of `kubectl describe po -n kube-system <api-server-pod-for-this-CP-node> as well.

**Comment by msschl** [comment]
> - is the existing cluster healthy?

The cluster is healthy:
```
kubectl get nodes
NAME             STATUS   ROLES    AGE   VERSION
lxkubemaster01   Ready    master   12d   v1.17.3
lxkubenode01     Ready    <none>   12d   v1.17.3
lxkubenode02     Ready    <none>   12d   v1.17.3
```
Nothing out of the ordinary in a `kubectl cluster-info dump`

> - can you show me the list of pods in the kube-system namespace before upgrade apply?

```
kubectl get pods -n kube-system
NAME                                     READY   STATUS    RESTARTS   AGE
coredns-6955765f44-8hn5q                 1/1     Running   0          4h8m
coredns-6955765f44-qwk7c                 1/1     Running   0          11d
etcd-lxkubemaster01                      1/1     Running   5          11d
kube-controller-manager-lxkubemaster01   1/1     Running   2          11d
kube-flannel-ds-amd64-77w7j              1/1     Running   0          11d
kube-flannel-ds-amd64-97z6r              1/1     Running   7          11d
kube-flannel-ds-amd64-p92hp              1/1     Running   1          11d
kube-proxy-chbbt                         1/1     Running   4          11d
kube-proxy-hn5lq                         1/1     Running   3          11d
kube-proxy-z54w9                         1/1     Running   5          11d
kube-scheduler-lxkubemaster01            1/1     Running   2          11d
```

> - does the failure happen consistently?

No it's actually the first time this happend

> - are you using the --experimental-kustomize feature?

No

> - are you passing a --config to the upgrade apply command?

No

> - is the node name the same as the hostname where you called upgrade apply?

Yes

**Comment by neolit123** [comment]
> kubectl get pods -n kube-system

i'm not finding the api-server pods, do you know what happened to it?
is the file `/etc/kubernetes/manifests/kube-apiserver.yaml` in place?

> kube-flannel-ds-amd64-77w7j

the kubeadm team does not recommend flannel. we are seeing way to many failures with it. Calico or WeaveNet are in a much better state for 1.17+

> RESTARTS

i'm noticing a lot of restarts on your pods.

> please show the output of kubectl describe po -n kube-system [api-server-pod-for-this-CP-node] as well.

i guess this command will not work because there is no api-server pod?

**Comment by msschl** [comment]
> i'm not finding the api-server pod, do you know what happened to it?
> is the file `/etc/kubernetes/manifests/kube-apiserver.yaml` in place?

I was wondering about that myself

`/etc/kubernetes/manifests/kube-apiserver.yaml`
```
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    component: kube-apiserver
    tier: control-plane
  name: kube-apiserver
  namespace: kube-system
spec:
  containers:
  - command:
    - kube-apiserver
    - --advertise-address=172.18.2.91
    - --allow-privileged=true
    - --audit-log-maxage=30
    - --audit-log-maxbackup=10
    - --audit-log-maxsize=200
    - --audit-log-path=/var/log/kubernetes/audit.log
    - --audit-policy-file=/etc/kubernetes/policies/audit-policy.yaml
    - --authorization-mode=Node,RBAC
    - --client-ca-file=/etc/kubernetes/pki/ca.crt
    - --enable-admission-plugins=NodeRestriction,PodSecurityPolicy,AlwaysPullImages,ServiceAccount
    - --enable-bootstrap-token-auth=true
    - --encryption-provider-config=/etc/kubernetes/encryption.conf
    - --etcd-cafile=/etc/kubernetes/pki/etcd/ca.crt
    - --etcd-certfile=/etc/kubernetes/pki/apiserver-etcd-client.crt
    - --etcd-keyfile=/etc/kubernetes/pki/apiserver-etcd-client.key
    - --etcd-servers=https://127.0.0.1:2379
    - --feature-gates=AdvancedAuditing=true
    - --insecure-port=0
    - --kubelet-client-certificate=/etc/kubernetes/pki/apiserver-kubelet-client.crt
    - --kubelet-client-key=/etc/kubernetes/pki/apiserver-kubelet-client.key
    - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
    - --profiling=false
    - --proxy-client-cert-file=/etc/kubernetes/pki/front-proxy-client.crt
    - --proxy-client-key-file=/etc/kubernetes/pki/front-proxy-client.key
    - --requestheader-allowed-names=front-proxy-client
    - --requestheader-client-ca-file=/etc/kubernetes/pki/front-proxy-ca.crt
    - --requestheader-extra-headers-prefix=X-Remote-Extra-
    - --requestheader-group-headers=X-Remote-Group
    - --requestheader-username-headers=X-Remote-User
    - --secure-port=6443
    - --service-account-key-file=/etc/kubernetes/pki/sa.pub
    - --service-cluster-ip-range=10.96.0.0/12
    - --tls-cert-file=/etc/kubernetes/pki/apiserver.crt
    - --tls-private-key-file=/etc/kubernetes/pki/apiserver.key
    image: k8s.gcr.io/kube-apiserver:v1.17.3
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 8
      httpGet:
        host: 172.18.2.91
        path: /healthz
        port: 6443
        scheme: HTTPS
      initialDelaySeconds: 15
      timeoutSeconds: 15
    name: kube-apiserver
    resources:
      requests:
        cpu: 250m
    volumeMounts:
    - mountPath: /etc/ssl/certs
      name: ca-certs
      readOnly: true
    - mountPath: /etc/ca-certificates
      name: etc-ca-certificates
      readOnly: true
    - mountPath: /etc/kubernetes/pki
      name: k8s-certs
      readOnly: true
    - mountPath: /usr/local/share/ca-certificates
      name: usr-local-share-ca-certificates
      readOnly: true
    - mountPath: /usr/share/ca-certificates
      name: usr-share-ca-certificates
      readOnly: true
    - mountPath: /etc/kubernetes/policies
      name: policies
      readOnly: true
    - mountPath: /var/log/kubernetes
      name: log
    - mountPath: /etc/kubernetes/encryption.conf
      name: encription
      readOnly: true
  hostNetwork: true
  priorityClassName: system-cluster-critical
  volumes:
  - hostPath:
      path: /etc/ssl/certs
      type: DirectoryOrCreate
    name: ca-certs
  - hostPath:
      path: /etc/ca-certificates
      type: DirectoryOrCreate
    name: etc-ca-certificates
  - hostPath:
      path: /etc/kubernetes/pki
      type: DirectoryOrCreate
    name: k8s-certs
  - hostPath:
      path: /usr/local/share/ca-certificates
      type: DirectoryOrCreate
    name: usr-local-share-ca-certificates
  - hostPath:
      path: /usr/share/ca-certificates
      type: DirectoryOrCreate
    name: usr-share-ca-certificates
  - hostPath:
      path: /etc/kubernetes/policies
      type: DirectoryOrCreate
    name: policies
  - hostPath:
      path: /var/log/kubernetes
      type: DirectoryOrCreate
    name: log
  - hostPath:
      path: /etc/kubernetes/encryption.conf
      type: File
    name: encription
status: {}
```

> the kubeadm team does not recommend flannel. we are seeing way to many failures with it. Calico or WeaveNet are in a much better state for 1.17+

Ok, I'll probably need to set my cluster up again. Then I'll use Calico.

> i'm noticing a lot of restarts on your pods.

Probably due to the update I was trying

> i guess this command will not work because there is no api-server pod. please provide the output of:
`kubectl describe po -n kube-system kube-controller-manager-lxkubemaster01` instead.

```
kubectl describe po -n kube-system kube-controller-manager-lxkubemaster01
Name:                 kube-controller-manager-lxkubemaster01
Namespace:            kube-system
Priority:             2000000000
Priority Class Name:  system-cluster-critical
Node:                 lxkubemaster01/172.18.2.91
Start Time:           Fri, 13 Mar 2020 11:00:25 +0100
Labels:               component=kube-controller-manager
                      tier=control-plane
Annotations:          container.apparmor.security.beta.kubernetes.io/kube-controller-manager: runtime/default
                      kubernetes.io/config.hash: b2e294f1aa65b361b7c72bc5c712b763
                      kubernetes.io/config.mirror: b2e294f1aa65b361b7c72bc5c712b763
                      kubernetes.io/config.seen: 2020-03-02T10:21:58.123261492+01:00
                      kubernetes.io/config.source: file
                      kubernetes.io/psp: kube-system
                      seccomp.security.alpha.kubernetes.io/pod: runtime/default
Status:               Running
IP:                   172.18.2.91
Controlled By:        Node/lxkubemaster01
Containers:
  kube-controller-manager:
    Container ID:  docker://7cec3f533dbab87380946d649f62a01fa8386b77c5f72d2be0dbe23f4c8254b2
    Image:         k8s.gcr.io/kube-controller-manager:v1.17.3
    Image ID:      docker-pullable://k8s.gcr.io/kube-controller-manager@sha256:2f0bf4d08e72a1fd6327c8eca3a72ad21af3a608283423bb3c10c98e68759844
    Port:          <none>
    Host Port:     <none>
    Command:
      kube-controller-manager
      --allocate-node-cidrs=true
      --authentication-kubeconfig=/etc/kubernetes/controller-manager.conf
      --authorization-kubeconfig=/etc/kubernetes/controller-manager.conf
      --bind-address=127.0.0.1
      --client-ca-file=/etc/kubernetes/pki/ca.crt
      --cluster-cidr=10.244.0.0/16
      --cluster-signing-cert-file=/etc/kubernetes/pki/ca.crt
      --cluster-signing-key-file=/etc/kubernetes/pki/ca.key
      --controllers=*,bootstrapsigner,tokencleaner
      --kubeconfig=/etc/kubernetes/controller-manager.conf
      --leader-elect=true
      --node-cidr-mask-size=24
      --profiling=false
      --requestheader-client-ca-file=/etc/kubernetes/pki/front-proxy-ca.crt
      --root-ca-file=/etc/kubernetes/pki/ca.crt
      --service-account-private-key-file=/etc/kubernetes/pki/sa.key
      --service-cluster-ip-range=10.96.0.0/12
      --use-service-account-credentials=true
    State:          Running
      Started:      Fri, 13 Mar 2020 15:46:16 +0100
    Last State:     Terminated
      Reason:       Error
      Exit Code:    255
      Started:      Fri, 13 Mar 2020 10:41:09 +0100
      Finished:     Fri, 13 Mar 2020 15:46:15 +0100
    Ready:          True
    Restart Count:  3
    Requests:
      cpu:        200m
    Liveness:     http-get https://127.0.0.1:10257/healthz delay=15s timeout=15s period=10s #success=1 #failure=8
    Environment:  <none>
    Mounts:
      /etc/ca-certificates from etc-ca-certificates (ro)
      /etc/kubernetes/controller-manager.conf from kubeconfig (ro)
      /etc/kubernetes/pki from k8s-certs (ro)
      /etc/ssl/certs from ca-certs (ro)
      /usr/libexec/kubernetes/kubelet-plugins/volume/exec from flexvolume-dir (rw)
      /usr/local/share/ca-certificates from usr-local-share-ca-certificates (ro)
      /usr/share/ca-certificates from usr-share-ca-certificates (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  ca-certs:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/ssl/certs
    HostPathType:  DirectoryOrCreate
  etc-ca-certificates:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/ca-certificates
    HostPathType:  DirectoryOrCreate
  flexvolume-dir:
    Type:          HostPath (bare host directory volume)
    Path:          /usr/libexec/kubernetes/kubelet-plugins/volume/exec
    HostPathType:  DirectoryOrCreate
  k8s-certs:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/kubernetes/pki
    HostPathType:  DirectoryOrCreate
  kubeconfig:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/kubernetes/controller-manager.conf
    HostPathType:  FileOrCreate
  usr-local-share-ca-certificates:
    Type:          HostPath (bare host directory volume)
    Path:          /usr/local/share/ca-certificates
    HostPathType:  DirectoryOrCreate
  usr-share-ca-certificates:
    Type:          HostPath (bare host directory volume)
    Path:          /usr/share/ca-certificates
    HostPathType:  DirectoryOrCreate
QoS Class:         Burstable
Node-Selectors:    <none>
Tolerations:       :NoExecute
Events:
  Type    Reason   Age   From                     Message
  ----    ------   ----  ----                     -------
  Normal  Pulled   9m    kubelet, lxkubemaster01  Container image "k8s.gcr.io/kube-controller-manager:v1.17.3" already present on machine
  Normal  Created  9m    kubelet, lxkubemaster01  Created container kube-controller-manager
  Normal  Started  9m    kubelet, lxkubemaster01  Started container kube-controller-manager
```
