### ISSUE TITLE
misleading warning on control-plane join

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubeadm#2065]
if a `--config` JoinConfiguration is provided on `kubeadm join` such as:

```
apiVersion: kubeadm.k8s.io/v1beta2
kind: JoinConfiguration
controlPlane:
  certificateKey: c39a18bae4a72e71b178661f437363da218a3efb83ddb03f1cd91d9ae1da41bd
discovery:
  bootstrapToken:
    apiServerEndpoint: 192.168.0.101:6443
    token: ay101u.bjxcn5of8sjqiop0
    unsafeSkipCAVerification: true
```

without a `--control-plane` flag, the following warning will be printed:
> W0319 00:28:01.398368   28773 join.go:349] [preflight] WARNING: JoinControlPane.controlPlane settings will be ignored when control-plane flag is not set.

but a control-plane will join fine, while also downloading the certificates using the cert key.

as context we had the discussion about this warning here:
https://github.com/kubernetes/kubernetes/pull/83661

the warning comes from:
https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/cmd/join.go#L343-L348

but then the `controlPlane` field is reloaded from here, so some of the nil-ing and warnings don't appear to make sense :
https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/cmd/join.go#L388
https://github.com/kubernetes/kubernetes/blob/34ad7d198472a7f4efc3181391ee21294447e2f6/cmd/kubeadm/app/util/config/joinconfiguration.go#L63-L66

~my proposal for a quick fix:~
~- print the warning only if `--config` is not passed.~
~as per the description [here](https://github.com/kubernetes/kubernetes/pull/83661), print a warning if `--certificate-key` is passed but `--control-plane` is not?~

/kind bug
/priority backlog
/help
