### ISSUE TITLE
Add ability to specify resources and replicas count for dns pods

### ISSUE THREAD

**Issue by yuripastushenko** [kubernetes/kubeadm#2110]
## Is this a BUG REPORT or FEATURE REQUEST?
FEATURE REQUEST

We want to use QoS guaranteed for coreDNS pods.
We would like to specify resources (_limits/requests_) for dns (_coreDNS_) when we initialize or upgrade the cluster.
I had seen that in the kubeadm repository those values are hardcoded in [manifest file](https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/phases/addons/dns/manifests.go#L58).
Will be great if kubeadm's `ClusterConfiguration` yaml file will support resources and replicas count configuration for dns.
For example:
```
kind: ClusterConfiguration
apiVersion: kubeadm.k8s.io/v1beta2
..........
dns:
  type: CoreDNS
  replicasCount: 3
  resources:
    limits:
      cpu: 100m
      memory: 170Mi
    requests:
      cpu: 100m
      memory: 170Mi
```
