### ISSUE TITLE
remove usage of flexvolume in kubeadm

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubeadm#2135]
distroless effort:
https://github.com/kubernetes/kubernetes/issues/70249

see this message from sig-storage https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/kubernetes-dev/zC8jCLg142w/2P3BN5oTAgAJ

> We are gauging the viability of deprecating the Flexvolume master API calls.
> ...
> There is an effort underway to move to core k8s component images to distroless. 

kube-apiserver and kube-scheduler [already moved to distroless](https://github.com/kubernetes/kubernetes/pull/90674), but the kube-controller-manager was blocked. kube-proxy is yet to move too:

currently kubeadm has related logic to manage flex volumes for the kube-controller-manager static Pod:

```
  - hostPath:
      path: /usr/libexec/kubernetes/kubelet-plugins/volume/exec
      type: DirectoryOrCreate
    name: flexvolume-dir
```

```
    - mountPath: /usr/libexec/kubernetes/kubelet-plugins/volume/exec
      name: flexvolume-dir
```

IIRC the above is currently GA and required for the KCM to run properly.
in case the KCM / kubelet deprecates and remove flexvoluime support kubeadm should follow.
