### ISSUE TITLE
kube-apiserver crashloops when using alternate secure port

### ISSUE THREAD

**Issue by chaosaffe** [kubernetes/kubeadm#2198]
## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`):
```
kubeadm version: &version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.4", GitCommit:"c96aede7b5205121079932896c4ad89bb93260af", GitTreeState:"clean", BuildDate:"2020-06-17T11:39:11Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```
**Environment**:
- **Kubernetes version** (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.4", GitCommit:"c96aede7b5205121079932896c4ad89bb93260af", GitTreeState:"clean", BuildDate:"2020-06-17T11:41:22Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.4", GitCommit:"c96aede7b5205121079932896c4ad89bb93260af", GitTreeState:"clean", BuildDate:"2020-06-17T11:33:59Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```
- **Cloud provider or hardware configuration**:
Bare metal machines
- **OS** (e.g. from /etc/os-release):
```bash
NAME="Flatcar Container Linux by Kinvolk"
ID=flatcar
ID_LIKE=coreos
VERSION=2512.2.1
VERSION_ID=2512.2.1
BUILD_ID=2020-06-16-1044
PRETTY_NAME="Flatcar Container Linux by Kinvolk 2512.2.1 (Oklo)"
ANSI_COLOR="38;5;75"
HOME_URL="https://flatcar-linux.org/"
BUG_REPORT_URL="https://issues.flatcar-linux.org"
FLATCAR_BOARD="amd64-usr"
```
- **Kernel** (e.g. `uname -a`):
```bash
Linux [HOSTNAME REDACTED] 4.19.128-flatcar #1 SMP Tue Jun 16 10:17:17 -00 2020 x86_64 Intel(R) Xeon(R) Silver 4114 CPU @ 2.20GHz GenuineIntel GNU/Linux
```
- **Others**:
kubeadm config
```yaml
apiVersion: kubeadm.k8s.io/v1beta2
kind: InitConfiguration
nodeRegistration:
  kubeletExtraArgs:
    volume-plugin-dir: "/var/lib/kubelet/volumeplugins"
---
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
kubernetesVersion: stable
controlPlaneEndpoint: "[REDACTED]:443"
networking:
  dnsDomain: "cluster.local"
  podSubnet: "10.99.96.0/20"
  serviceSubnet: "10.99.134.192/26"
apiServer:
  extraArgs:
    secure-port: "443"
  certSANs:
  - [REDACTED]
  - [REDACTED]
  - [REDACTED]
  - [REDACTED]
  - [REDACTED]
  - [REDACTED]
controllerManager:
  extraArgs:
    flex-volume-plugin-dir: "/var/lib/kubelet/volumeplugins"
```

## What happened?
After deploying the control plane the `kube-apiserver` pods continuously crashloop as the `livenessProbe` is configured for port `6443`, despite the `kube-apiserver` having been configured to listen on `443`

The specific errors in the `kube-apiserver` manifest are:
```
  annotations:
    kubeadm.kubernetes.io/kube-apiserver.advertise-address.endpoint: [REDACTED]:6443
```
and 
```
    livenessProbe:
      failureThreshold: 8
      httpGet:
        host: [REDACTED]
        path: /healthz
        port: 6443
        scheme: HTTPS
      initialDelaySeconds: 15
      timeoutSeconds: 15
```

## What you expected to happen?
The following patch to the generated `kube-apiserver` manifest should have been executed.
``` diff
@@ -4,2 +4,2 @@
  annotations:
-    kubeadm.kubernetes.io/kube-apiserver.advertise-address.endpoint: [REDACTED]:6443
+    kubeadm.kubernetes.io/kube-apiserver.advertise-address.endpoint: [REDACTED]:443
@@ -44,9 +44,9 @@
    livenessProbe:
      failureThreshold: 8
      httpGet:
        host: [REDACTED]
        path: /healthz
-       port: 6443
+       port: 443
        scheme: HTTPS
      initialDelaySeconds: 15
      timeoutSeconds: 15
```

## How to reproduce it (as minimally and precisely as possible)?
Deploy a cluster using a `secure-port` other than `6443`, i.e. using a kubeadm `ClusterConfiguration` as below
```yaml
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
kubernetesVersion: stable
controlPlaneEndpoint: "[REDACTED]:443"
apiServer:
  extraArgs:
    secure-port: "443"
```

**Comment by neolit123** [comment]
hi, i think we had a similar report about this before.

>   extraArgs:
>    secure-port: "443"

that is not a valid way to to propagate the 443 port everywhere.

please try:
```
kind: InitConfiguration
apiVersion: kubeadm.k8s.io/v1beta2
...
localAPIEndpoint:
  advertiseAddress: some-ip
  bindPort: 443
```

xref: https://godoc.org/k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/v1beta2
/triage support
