### ISSUE TITLE
Support add extra certificates sans when join control plane

### ISSUE THREAD

**Issue by pytimer** [kubernetes/kubeadm#2208]
## Is this a BUG REPORT or FEATURE REQUEST?

FEATURE REQUEST

## Versions

**kubeadm version** (use `kubeadm version`): v1.17.2

**Environment**:
- **Kubernetes version** (use `kubectl version`): v1.17.2
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
```sh
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
- **Kernel** (e.g. `uname -a`):
`Linux master1 3.10.0-957.12.2.el7.x86_64 #1 SMP Mon May 20 08:41:20 EDT 2019 x86_64 x86_64 x86_64 GNU/Linux`
- **Others**:

## What happened?

I have three machine, every machine have two network interfaces that one of internal network, another is external network, i use `kubeadm` to init/join control plane,  my cluster listen internal network, but i hope access cluster via external or internal network interface, but connect kube-apiserver failed, because of the kube-apiserver certificate sans only have internal ip, not external ip.

## What you expected to happen?

I hope kubeadm support add certificates extra sans when join control plane, now kubeadm only support `--apiserver-cert-extra-sans` when init.

## How to reproduce it (as minimally and precisely as possible)?

Requirement: machine have two network interfaces.

- kubeadm init
- kubeadm join
- openssl x509 -in /etc/kubernetes/pki/apiserver.crt -noout -text

**Comment by neolit123** [comment]
> --apiserver-cert-extra-sans when init.

we should mark  --apiserver-cert-extra-sans as deprecated and remove it eventually. it duplicates functionality that is already in  --config.

> I have three machine, every machine have two network interfaces that one of internal network, another is external network, i use kubeadm to init/join control plane, my cluster listen internal network, but i hope access cluster via external or internal network interface, but connect kube-apiserver failed, because of the kube-apiserver certificate sans only have internal ip, not external ip.

when you call `kubeadm init`, if you add all the IPs as part of the ClusterConfiguration - apiServer ->certSans https://godoc.org/k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/v1beta2

doesn't that work for you? when calling `kubeadm join` the new control-plane nodes will use the same ClusterConfiguration.

also note that certSans supports wildcards like `10.10.*.*`.


/priority awaiting-more-evidence

**Comment by pytimer** [comment]
Thanks @neolit123 

> when you call kubeadm init --config ..., if you add all the IPs as part of the ClusterConfiguration - apiServer ->certSans https://godoc.org/k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/v1beta2

This way can't work for me, because my cluster maybe remove a control plane node  and join new control plane node, but the `ClusterConfiguration`  no this new external ip, so certSans have no this external ip, only have internal ip.

> also note that certSans supports wildcards like 10.10.*.*.

I use `cfssl` create certificate before, it not support `10.10.*.*`, it support dns domain. So i will try this way via kubeadm.
If this way works, it can solve some of my problems. but if support set certificate sans when join, it maybe adapt to many case, because i am not sure about the situation of network in different user environments.

**Comment by neolit123** [comment]
> This way can't work for me, because my cluster maybe remove a control plane node and join new control plane node, but the ClusterConfiguration no this new external ip, so certSans have no this external ip, only have internal ip.

well, before joining a new CP node, you can patch the ClusterConfiguration to make sure it fits the needs of this particular CP node. you can then restore the ClusterConfiguration to what i was.

> I use cfssl create certificate before, it not support 10.10.*.*, it support dns domain. So i will try this way via kubeadm.
If this way works, it can solve some of my problems. but if support set certificate sans when join, it maybe adapt to many case, because i am not sure about the situation of network in different user environments.

sure, give it a try.

you also have the option to use the "kubeadm init phase certs" to generate certificates for new joining nodes.
you can pass a custom ClusterConfiguration to the above command, but remember that you have to use the same CA.

in any case, we cannot change anything in kubeadm to add support for this for the time being.
even if we add a new config API (v1beta3) its not clear how / where we can add such support:
https://godoc.org/k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/v1beta2#JoinConfiguration

**Comment by pytimer** [comment]
> also note that certSans supports wildcards like 10.10...

@neolit123 I use kubeadm like below configuration, it init failed. 

```yaml
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
apiServer:
    certSANs:
        - "127.0.0.1"
        - "10.33.*.*"
    extraArgs:
        feature-gates: "TaintBasedEvictions=false,TTLAfterFinished=true"
        tls-min-version: "VersionTLS12"
        tls-cipher-suites: "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
        authentication-token-webhook-config-file: "/etc/kubernetes/configs/authwebhookconfig.yaml"
        service-node-port-range: "30000-32767"
        event-ttl: "12h"
    extraVolumes:
    - name: "kubeexternal"
      hostPath: "/etc/kubernetes/configs"
      mountPath: "/etc/kubernetes/configs"
      readOnly: true
      pathType: Directory
```

The error log shows certSANs can not support `10.33.*.*`, so this way not works for me. 

```sh
[apiServer.certSANs: Invalid value: "10.33.*.*": altname is not a valid IP address, DNS label or a DNS label 
with subdomain wildcards: a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', 
and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is 
'[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'); a wildcard DNS-1123 subdomain must start with '*.', 
followed by a valid DNS subdomain, which must consist of lower case alphanumeric characters, '-' or '.' and end with an
alphanumeric character (e.g. '*.example.com', regex used for validation is '\*\.[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')]
```
