### ISSUE TITLE
--pod-network-cidr vs podSubnet in ClusterConfig producing different kubelet behavior

### ISSUE THREAD

**Issue by sccrthlt** [kubernetes/kubeadm#2231]
## What keywords did you search in kubeadm issues before filing this one?

"kubernetes --pod-network-cidr vs subNet key in ClusterConfig manifest"

## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`):
```
{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-06-26T03:45:16Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Kubernetes version** (use `kubectl version`):
```
{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-06-26T03:47:41Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

- **Cloud provider or hardware configuration**:
On-premises

- **OS** (e.g. from /etc/os-release):
```
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

- **Kernel** (e.g. `uname -a`):
```
Linux host 4.15.0-109-generic #110-Ubuntu SMP Tue Jun 23 02:39:32 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

- **Others**:

## What happened?
When I specify the pod cidr via command line argument (i.e., `--pod-network-cidr`) the kubelet is able to boot, but when I specify the cidr via config file (i.e., `kubeadm init --config /path/to/clusterConfig`) using `networking: - podSubnet:`, the kubelet is not able to boot.  Is there a difference between specifying the pod network via `podSubnet` and `--pod-network-cidr`?

### cluster_config.yaml
```
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
kubernetesVersion: v1.18.0
networking:
    dnsDomain: cluster.local
    podSubnet: 192.168.0.0/16
```

### Error
```
"stdout_lines": [
        "[init] Using Kubernetes version: v1.18.0", 
        "[preflight] Running pre-flight checks", 
        "[preflight] Pulling images required for setting up a Kubernetes cluster", 
        "[preflight] This might take a minute or two, depending on the speed of your internet connection", 
        "[preflight] You can also perform this action in beforehand using 'kubeadm config images pull'", 
        "[kubelet-start] Writing kubelet environment file with flags to file \"/var/lib/kubelet/kubeadm-flags.env\"", 
        "[kubelet-start] Writing kubelet configuration to file \"/var/lib/kubelet/config.yaml\"", 
        "[kubelet-start] Starting the kubelet", 
        "[certs] Using certificateDir folder \"/etc/kubernetes/pki\"", 
        "[certs] Generating \"ca\" certificate and key", 
        "[certs] Generating \"apiserver\" certificate and key", 
        "[certs] apiserver serving cert is signed for DNS names [... kubernetes kubernetes.default kubernetes.default.svc kubernetes.default.svc.cluster.local] and IPs [192.168.100.1 10.0.0.67]", 
        "[certs] Generating \"apiserver-kubelet-client\" certificate and key", 
        "[certs] Generating \"front-proxy-ca\" certificate and key", 
        "[certs] Generating \"front-proxy-client\" certificate and key", 
        "[certs] Generating \"etcd/ca\" certificate and key", 
        "[certs] Generating \"etcd/server\" certificate and key", 
        "[certs] etcd/server serving cert is signed for DNS names [... localhost] and IPs [10.0.0.67 127.0.0.1 ::1]", 
        "[certs] Generating \"etcd/peer\" certificate and key", 
        "[certs] etcd/peer serving cert is signed for DNS names [... localhost] and IPs [10.0.0.67 127.0.0.1 ::1]", 
        "[certs] Generating \"etcd/healthcheck-client\" certificate and key", 
        "[certs] Generating \"apiserver-etcd-client\" certificate and key", 
        "[certs] Generating \"sa\" key and public key", 
        "[kubeconfig] Using kubeconfig folder \"/etc/kubernetes\"", 
        "[kubeconfig] Writing \"admin.conf\" kubeconfig file", 
        "[kubeconfig] Writing \"kubelet.conf\" kubeconfig file", 
        "[kubeconfig] Writing \"controller-manager.conf\" kubeconfig file", 
        "[kubeconfig] Writing \"scheduler.conf\" kubeconfig file", 
        "[control-plane] Using manifest folder \"/etc/kubernetes/manifests\"", 
        "[control-plane] Creating static Pod manifest for \"kube-apiserver\"", 
        "[control-plane] Creating static Pod manifest for \"kube-controller-manager\"", 
        "[control-plane] Creating static Pod manifest for \"kube-scheduler\"", 
        "[etcd] Creating static Pod manifest for local etcd in \"/etc/kubernetes/manifests\"", 
        "[wait-control-plane] Waiting for the kubelet to boot up the control plane as static Pods from directory \"/etc/kubernetes/manifests\". This can take up to 4m0s", 
        "[kubelet-check] Initial timeout of 40s passed.", 
        "", 
        "\tUnfortunately, an error has occurred:", 
        "\t\ttimed out waiting for the condition", 
        "", 
        "\tThis error is likely caused by:", 
        "\t\t- The kubelet is not running", 
        "\t\t- The kubelet is unhealthy due to a misconfiguration of the node in some way (required cgroups disabled)", 

```

## What you expected to happen?
The kubelet to 

## How to reproduce it (as minimally and precisely as possible)?
Run the following Ansible playbook:
```
- hosts: master
  become: yes
  tasks:
    - name: create .kube directory
      become: yes
      become_user: ubuntu
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755

    - name: copy configurations to user's .kube directory
      become: yes
      copy:
        src: /home/username/kube-cluster/master
        dest: /home/ubuntu/.kube
        owner: ubuntu

    - name: initialize the cluster
      shell: kubeadm init --config=/home/ubuntu/.kube/master/cluster_config.yaml
      args:
        chdir: $HOME

    - name: copy admin.conf to user's kube config
      become: yes
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/ubuntu/.kube/config
        remote_src: yes
        owner: ubuntu

    - name: install Tigera Calico operator
      become: yes
      become_user: ubuntu
      shell: kubectl create -f https://docs.projectcalico.org/manifests/tigera-operator.yaml >> pod_network_setup.txt
      args:
        chdir: $HOME
        creates: pod_network_setup.txt

    - name: install Calico
      become: yes
      become_user: ubuntu
      shell: kubectl create -f https://docs.projectcalico.org/manifests/custom-resources.yaml >> pod_network_setup.txt
      args:
        chdir: $HOME

```

## Anything else we need to know?
Calico seems to maintain the interface even after performing a `kubeadm reset`:
```
vxlan.calico: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1410
        inet 192.168.79.64
```
