### ISSUE TITLE
Unable to share  one IP with multiple services with metalLB

### ISSUE THREAD

**Issue by mseewooth** [kubernetes/kubeadm#2232]
I have a two vps with only public IP addresses.  167.XXX as master and 207.XX as worker . 

Kubernete version is v1.18.6
MetallB version : v0.9.3 
Flannel network : https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml 

This the metallb configmap : 

```
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
        - 207.XXX.XXX.XXX-207.XXX.XXX.XXX
```
Please note that the ip range in the Configmap is like this e.g  `192.168.100.20-192.168.100.20`  . I  have a single public ip and my vps does not have private ip addresses. i had to assign the public ip itself in the pool on the configmap manifest.
  
 i have deployed a service `selector` to a deployment (`vhost`) which consist a vhost red.nginx.com like below : 

```
apiVersion: v1
kind: Service
metadata:
  name: vhost
  namespace: test
  annotations:
    metallb.universe.tf/allow-shared-ip: 207.XX.X.XX
  labels:
    app: vhost
spec:
  type: LoadBalancer
  loadBalancerIP: 207.XXX.X.X
  selector:
    app: vhost
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http-test
```

```
kubectl get svc -n test
NAME    TYPE           CLUSTER-IP       EXTERNAL-IP       PORT(S)        AGE
vhost   LoadBalancer   10.102.116.194   207.XXX.X.X   80:31070/TCP   16s

```

Now i'm trying to deploy another service ` selector` to deployment (`vhosttest`) consisting a vhost blue.nginx.com: 

```
apiVersion: v1
kind: Service
metadata:
  name: vhosttest
  namespace: test
  annotations:
    metallb.universe.tf/allow-shared-ip: 207.XXX.XXX
  labels:
    app: vhosttest
spec:
  type: LoadBalancer
  loadBalancerIP: 207.XXX.XXX
  selector:
    app: vhosttest
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http-test

```

```
kubectl get svc -n test 
NAME        TYPE           CLUSTER-IP       EXTERNAL-IP       PORT(S)        AGE
vhost       LoadBalancer   10.102.116.194   207.XX.XX.X   80:31070/TCP   6m53s
vhosttest   LoadBalancer   10.102.241.105   <pending>         80:31250/TCP   3s
```

I'm not getting the ip address  `207.xx.x.xx`  shared with the `svc vhosttest`

If this option is not possible, this mean that you can only have one service pointing to single deployment. 

I want to do something like this : 

```
                     METALLB  207.XX.XX.XX
                                         |
                                         |
                  ---------------------------
                 |                                             |
   svc  vhost ip 207.xx.xx.xx        svc  vhosttest  ip 207.xx.xx.xx
       (selector=vhost)                    (selector=vhosttest)
                 |                                             |
            deployment                       deployment
        ( selector= vhost)         (selector=vhostest)
```

In this approach which is a simple, i i can have several apps(websites) on a single IP. 

Please let know if this is possible or a solution how to get the public ip share across multiple services.

Thanks
