### ISSUE TITLE
kubeadm overwrites /var/lib/kubelet/config.yaml even if you already have it

### ISSUE THREAD

**Issue by inductor** [kubernetes/kubeadm#2240]
## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`): v1.18.6

**Environment**:
- **Kubernetes version** (use `kubectl version`): v1.18.6
- **Cloud provider or hardware configuration**: Digital Ocean 4CPU-8GB droplet
- **OS** (e.g. from /etc/os-release): 20.04 LTS (Focal Fossa)
- **Kernel** (e.g. `uname -a`): Linux controller-0 5.4.0-29-generic #33-Ubuntu SMP Wed Apr 29 14:32:27 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- **Others**:

## What happened?

I posted the original question on Kubernetes slack's kubeadm channel. Here it is.

I'm trying to setup a Kubernetes cluster with containerd.
In the documentation, it is suggested to use `KubeletConfiguration` resource to specify `cgroupDriver`. However, if you execute `kubeadm init` having the config as explained in the doc, in `/var/lib/kubelet/config.yaml`, kubeadm overwrites the file and it actually removes my line.

Ref. https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#configure-cgroup-driver-used-by-kubelet-on-control-plane-node

Setting `KUBELET_EXTRA_ARGS=--cgroup-driver=systemd` in `/etc/default/kubelet` works, but it is now deprecated as described in the documentation.

Is there any specific option to specify "default config" that kubeadm respects in the init? Or any other better way to do this?

## What you expected to happen?

kubeadm should respect the kubelet's extra config when it's defined in the config yaml.

In this case I wanted this to be included.

```yaml
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
cgroupDriver: "systemd"
```

## How to reproduce it (as minimally and precisely as possible)?

execute `kubeadm init` having the yaml file.

**Comment by inductor** [comment]
Some person on Slack helped me with this.

I did not specify the config file at creation

Passing the following yaml worked by running `kubeadm init --config config.yaml`

```yaml
apiVersion: kubeadm.k8s.io/v1beta2
kind: InitConfiguration
---
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
cgroupDriver: "systemd"
```

I think that the installation document should mention about this init config option.
