### ISSUE TITLE
Kubeadm init fail using config file

### ISSUE THREAD

**Issue by qian2501** [kubernetes/kubeadm#2255]
## Is this a BUG REPORT or FEATURE REQUEST?

Choose one: BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`):

> kubeadm version: &version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:10:16Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Kubernetes version** (use `kubectl version`):

> Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:12:48Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

- **Cloud provider or hardware configuration**: local vmware on Windows 10
- **OS** (e.g. from /etc/os-release): CentOS 7
- **Kernel** (e.g. `uname -a`): 

> Linux master 3.10.0-1127.18.2.el7.x86_64 #1 SMP Sun Jul 26 15:27:06 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

- **Others**:

## What happened?
When running `kubeadm init --config`, kubeadm ignore kubelet config in config file provided, and performed following action :

> [kubelet-start] Writing kubelet environment file with flags to file "/var/lib/kubelet/kubeadm-flags.env"
> [kubelet-start] Writing kubelet configuration to file "/var/lib/kubelet/config.yaml"
> [kubelet-start] Starting the kubelet

These kubelet config files generated are default, and then failed after kubelet timeout.
`journalctl -xeu kubelet` says:

> `--cgroup-driver` is deprecated 

and 
> node localhost not found,

Which many issue on older version have the same result. Which lead me to think that failed to set cgroupDriver for kubelet lead to the kubeadm init fail.

## What you expected to happen?
kubelet is configured with `cgroupDriver: systemd` during ` kubeadm init`.

## How to reproduce it (as minimally and precisely as possible)?
Just run `kubeadm init --config config.yaml`.
My test setup is basically following the offcial tutorial. Docker, containerd and crio are running.

## Anything else we need to know?
My config is modyfied based on the init-default with som reference from https://godoc.org/k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/v1beta2. I am not sure if I did everything right.
config.yaml:
```
apiVersion: kubeadm.k8s.io/v1beta2
bootstrapTokens:
- groups:
  - system:bootstrappers:kubeadm:default-node-token
  token: ac421c.915daba22f509fe4
  ttl: 24h0m0s
  usages:
  - signing
  - authentication
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: 192.168.100.1
  bindPort: 6443
nodeRegistration:
  criSocket: /var/run/crio/crio.sock
  name: localhost
  taints:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
  kubeletExtraArgs:
    cgroup-driver: "systemd"
---
apiServer:
  timeoutForControlPlane: 4m0s
apiVersion: kubeadm.k8s.io/v1beta2
certificatesDir: /etc/kubernetes/pki
clusterName: kubernetes
controllerManager: {}
dns:
  type: CoreDNS
etcd:
  local:
    dataDir: /var/lib/etcd
imageRepository: k8s.gcr.io
kind: ClusterConfiguration
kubernetesVersion: v1.18.0
networking:
  dnsDomain: cluster.local
  serviceSubnet: 10.96.0.0/12
scheduler: {}
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
cgroupDriver: systemd
```
