### ISSUE TITLE
WARNING: kubeadm cannot validate component configs for API groups [kubelet.config.k8s.io kubeproxy.config.k8s.io]

### ISSUE THREAD

**Issue by ming-ddtechcg** [kubernetes/kubeadm#2272]
Hi,

I am running 1.18.8 with the following kubeadmin config:

```
---
apiVersion: kubeadm.k8s.io/v1beta2
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: 0.0.0.0
  bindPort: 6443
---
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
apiServer:
  certSANs:
  - "192.168.130.52"
  - "192.168.130.53"
  - "192.168.130.54"
  extraArgs:
    endpoint-reconciler-type: "lease"
controlPlaneEndpoint: ""
etcd:
  external:
    endpoints:
    - https://192.168.130.52:2379
    - https://192.168.130.53:2379
    - https://192.168.130.54:2379
    caFile: /etc/kubernetes/pki/etcd/ca.pem
    certFile: /etc/kubernetes/pki/etcd/client.pem
    keyFile: /etc/kubernetes/pki/etcd/client-key.pem
networking:
  podSubnet: "10.244.0.0/16"
  dnsDomain: "cluster.local"
  serviceSubnet: "10.96.0.0/12"
kubernetesVersion: v1.18.8
---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
mode: ""
```

The kubeadmin init complained:

```
W0831 22:06:36.063058    3922 configset.go:202] WARNING: kubeadm cannot validate component configs for API groups [kubelet.config.k8s.io kubeproxy.config.k8s.io]
```

Any suggestion for the  section of KubeProxyConfiguration?

Thanks.
