### ISSUE TITLE
kubelet restarts every ~3m

### ISSUE THREAD

**Issue by kargakis** [kubernetes/kubeadm#230]
Running a self-hosted installation and once I joined a second node, I noticed that the first one is restarting almost every 3m.
```
$ kubeadm version
kubeadm version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.1", GitCommit:"b0b7a323cc5a4a2019b2e9520c21c7830b7f708e", GitTreeState:"clean", BuildDate:"2017-04-03T20:33:27Z", GoVersion:"go1.8rc2", Compiler:"gc", Platform:"linux/arm"}
```
node info:
```
    architecture: arm
    bootID: c32545f1-4e4a-4a1c-85a6-e7630493fcd6
    containerRuntimeVersion: docker://1.13.1
    kernelVersion: 4.4.50-v7+
    kubeProxyVersion: v1.6.1
    kubeletVersion: v1.6.1
    machineID: 2e7311d7868244978f314762db251c8e
    operatingSystem: linux
    osImage: Raspbian GNU/Linux 8 (jessie)
```
```
$ docker version
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 07:25:30 2017
 OS/Arch:      linux/arm

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 07:25:30 2017
 OS/Arch:      linux/arm
 Experimental: false
```
kubectl get events: https://pastebin.com/iwdKjkLF

Attaching the kubelet logs
[kubelet.txt](https://github.com/kubernetes/kubeadm/files/908263/kubelet.txt)

**Comment by eremid** [comment]
Same problem on my cluster since I upgraded from 1.5 to 1.6.1.

**Comment by kargakis** [comment]
And the config I used:
```
apiVersion: kubeadm.k8s.io/v1alpha1
kind: MasterConfiguration
kubernetesVersion: v1.6.1
selfHosted: true
authorizationMode: RBAC
networking:
  dnsDomain: cluster.local
  serviceSubnet: 10.96.0.0/12
  podSubnet: 10.244.0.0/16	
```
May this be related to the fact that I didn't explicitly specify the controllers I want to run, so the bootstrapsigner and tokencleaner controllers never run?
