### ISSUE TITLE
Bootstrap signer controller not running

### ISSUE THREAD

**Issue by challapradyumna** [kubernetes/kubeadm#2329]
## What keywords did you search in kubeadm issues before filing this one?

JWS, Join, BootstrapSigner

## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`): 1.16.9

**Environment**:
- **Kubernetes version** (use `kubectl version`): 1.16.9
- **Cloud provider or hardware configuration**: AWS - EC2
- **OS** (e.g. from /etc/os-release): Ubuntu - Bionic
- **Kernel** (e.g. `uname -a`): Linux ip-172-29-133-151 5.3.0-1035-aws #37-Ubuntu SMP Sun Sep 6 01:17:09 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- **Others**:

## What happened?
Not able to join a new node into the cluster. 
after `kubeadm init`. Created a new token with `kubeadm token create --print-join-command`.
When joining from the new node. The following error happens
Failed to connect to API Server "domain.com:6443": token id "dgtuzb" is invalid for this cluster or it has expired. Use "kubeadm token create" on the control-plane node to create a new valid token. 

Based on the previous tickets raised on similar issue. I've checked cluster-info configmap and the jws tokens are missing in it. 
I could not even see any logs from bootstrapsigner controller also in controller manager pod.
The controller manager pod has `--controllers=*,bootstrapsigner,tokencleaner"`

## What you expected to happen?
Node joins the cluster

## Anything else we need to know?
All the cluster certs are generated according to kubeadm standards and copied to the node without ca.key

**Comment by neolit123** [comment]
/kind support

hi, please show logs of the kube-controller-manager.

what happens if you restart the kube-controller-manager?

> Kubernetes version (use kubectl version): 1.16.9

note this version is no longer in support.

>  I've checked cluster-info configmap and the jws tokens are missing in it.

once you create a new token, can you show the output of the following commands?

```
kubectl get cm cluster-info -n kube-public
kubeadm token list
```

**Comment by challapradyumna** [comment]
> hi, please show logs of the kube-controller-manager.
```
I1020 02:40:37.955534       1 serving.go:319] Generated self-signed cert in-memory
I1020 02:40:38.559063       1 controllermanager.go:161] Version: v1.16.9
I1020 02:40:38.559184       1 healthz.go:123] Installing health checkers for (/healthz): "leaderElection"
I1020 02:40:38.560799       1 secure_serving.go:123] Serving securely on 127.0.0.1:10257
I1020 02:40:38.560881       1 healthz.go:123] Installing health checkers for (/healthz): "leaderElection"
I1020 02:40:38.561792       1 deprecated_insecure_serving.go:53] Serving insecurely on [::]:10252
I1020 02:40:38.561959       1 leaderelection.go:241] attempting to acquire leader lease  kube-system/kube-controller-manager...
I1020 02:40:38.578513       1 leaderelection.go:350] lock is held by ip-172-29-107-19.ec2.internal_2cdf393e-a357-4fe3-adbe-684cfe20863f and has not yet expired
I1020 02:40:38.578687       1 leaderelection.go:246] failed to acquire lease kube-system/kube-controller-manager
```
The lock messages repeat after that. 

> what happens if you restart the kube-controller-manager?
Above logs are from restarting kube-controller-manager.
> once you create a new token, can you show the output of the following commands?
> 
> ```
> kubectl get cm cluster-info -n kube-public
> kubeadm token list
> ```
```
apiVersion: v1
data:
  kubeconfig: |
    apiVersion: v1
    clusters:
    - cluster:
        certificate-authority-data: Base64Cert
        server: https://domain.com:6443
      name: ""
    contexts: []
    current-context: ""
    kind: Config
    preferences: {}
    users: []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-10-14T17:33:01Z"
  name: cluster-info
  namespace: kube-public
  resourceVersion: "233269456"
  selfLink: /api/v1/namespaces/kube-public/configmaps/cluster-info
  uid: f0ca8219-324c-4bd6-a812-60614221c26f
```

```
3rdltz.ra6ewk14mc4w9jvd   11h         2020-10-20T13:47:35Z   authentication,signing   <none>                                                     system:bootstrappers:kubeadm:default-node-token
7kfuqy.mft33n1v6sh1jbkg   12h         2020-10-20T15:37:24Z   authentication,signing   <none>                                                     system:bootstrappers:kubeadm:default-node-token
a86zd1.86o7po98ipipthpc   10h         2020-10-20T13:42:57Z   authentication,signing   <none>                                                     system:bootstrappers:kubeadm:default-node-token
c0wee7.olekk8eb2ywv7sp0   14h         2020-10-20T17:19:03Z   authentication,signing   <none>                                                     system:bootstrappers:kubeadm:default-node-token
dgtuzb.897n6mzy7fwyzmnr   7h          2020-10-20T10:44:19Z   authentication,signing   <none>                                                     system:bootstrappers:kubeadm:default-node-token
grq23y.78l88vj1embgcsq4   7h          2020-10-20T10:31:18Z   authentication,signing   <none>                                                     system:bootstrappers:kubeadm:default-node-token
olu6ma.fniqx4pi4yxo9js2   10h         2020-10-20T13:39:52Z   authentication,signing   <none>                                                     system:bootstrappers:kubeadm:default-node-token
```

**Comment by neolit123** [comment]
that's odd, please answer the bellow questions.

> I1020 02:40:38.578513       1 leaderelection.go:350] lock is held by ip-172-29-107-19.ec2.internal_2cdf393e-a357-4fe3-adbe-684cfe20863f and has not yet expired
I1020 02:40:38.578687       1 leaderelection.go:246] failed to acquire lease kube-system/kube-controller-manager

- this is just an informal message. do you see any log entries prefixed with `E...`?
- are you running an HA setup with multiple controller-managers?

```
apiVersion: v1
data:
  kubeconfig: |
```

the tokens are indeed missing.
- did you temper with the cluster RBAC rules around token signing?
https://kubernetes.io/docs/reference/access-authn-authz/bootstrap-tokens/
https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet-tls-bootstrapping/

what flags are you passing to the KCM, you can just dump the contents of `/etc/kubernetes/manifests/controller-manager.yaml` here.

**Comment by challapradyumna** [comment]
```
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    component: kube-controller-manager
    tier: control-plane
  name: kube-controller-manager
  namespace: kube-system
spec:
  containers:
  - command:
    - kube-controller-manager
    - --allocate-node-cidrs=false
    - --authentication-kubeconfig=/etc/kubernetes/controller-manager.conf
    - --authorization-kubeconfig=/etc/kubernetes/controller-manager.conf
    - --bind-address=127.0.0.1
    - --client-ca-file=/etc/kubernetes/pki/ca.crt
    - --cloud-provider=aws
    - --cluster-cidr=172.29.0.0/16
    - --cluster-name=kubernetes
    - --cluster-signing-cert-file=/etc/kubernetes/pki/ca.crt
    - --cluster-signing-key-file=/etc/kubernetes/pki/ca.key
    - --controllers=*,bootstrapsigner,tokencleaner
    - --feature-gates=TTLAfterFinished=true
    - --horizontal-pod-autoscaler-sync-period=30s
    - --kubeconfig=/etc/kubernetes/controller-manager.conf
    - --leader-elect=true
    - --node-cidr-mask-size=24
    - --node-eviction-rate=.00333
    - --node-monitor-grace-period=300s
    - --requestheader-client-ca-file=/etc/kubernetes/pki/front-proxy-ca.crt
    - --root-ca-file=/etc/kubernetes/pki/ca.crt
    - --secondary-node-eviction-rate=.00333
    - --service-account-private-key-file=/etc/kubernetes/pki/sa.key
    - --service-cluster-ip-range=10.9.0.0/16
    - --use-service-account-credentials=true
    - --v=10
    image: k8s.gcr.io/kube-controller-manager:v1.16.9
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 8
      httpGet:
        host: 127.0.0.1
        path: /healthz
        port: 10252
        scheme: HTTP
      initialDelaySeconds: 15
      timeoutSeconds: 15
    name: kube-controller-manager
    resources:
      requests:
        cpu: 200m
    volumeMounts:
    - mountPath: /etc/ssl/certs
      name: ca-certs
      readOnly: true
    - mountPath: /etc/ca-certificates
      name: etc-ca-certificates
      readOnly: true
    - mountPath: /usr/libexec/kubernetes/kubelet-plugins/volume/exec
      name: flexvolume-dir
    - mountPath: /etc/kubernetes/pki
      name: k8s-certs
      readOnly: true
    - mountPath: /etc/kubernetes/controller-manager.conf
      name: kubeconfig
      readOnly: true
    - mountPath: /usr/local/share/ca-certificates
      name: usr-local-share-ca-certificates
      readOnly: true
    - mountPath: /usr/share/ca-certificates
      name: usr-share-ca-certificates
      readOnly: true
  hostNetwork: true
  priorityClassName: system-cluster-critical
  volumes:
  - hostPath:
      path: /etc/ssl/certs
      type: DirectoryOrCreate
    name: ca-certs
  - hostPath:
      path: /etc/ca-certificates
      type: DirectoryOrCreate
    name: etc-ca-certificates
  - hostPath:
      path: /usr/libexec/kubernetes/kubelet-plugins/volume/exec
      type: DirectoryOrCreate
    name: flexvolume-dir
  - hostPath:
      path: /etc/kubernetes/pki
      type: DirectoryOrCreate
    name: k8s-certs
  - hostPath:
      path: /etc/kubernetes/controller-manager.conf
      type: FileOrCreate
    name: kubeconfig
  - hostPath:
      path: /usr/local/share/ca-certificates
      type: DirectoryOrCreate
    name: usr-local-share-ca-certificates
  - hostPath:
      path: /usr/share/ca-certificates
      type: DirectoryOrCreate
    name: usr-share-ca-certificates
status: {}
```
