### ISSUE TITLE
Token not being added to configmap after kubeadm token create

### ISSUE THREAD

**Issue by distortedsignal** [kubernetes/kubeadm#2331]
## What keywords did you search in kubeadm issues before filing this one?
Through Google, I found ticket #668. This issue is somewhat similar to #668, though I believe that there may be a different root-cause. I do not know the root cause of that issue, so I am opening a narrower issue. This also seems similar to 1988, though all the machines I am using are persistent.

## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`):
```sh
> kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:56:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Kubernetes version** (use `kubectl version`):
```sh
> kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:58:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:51:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```
- **Cloud provider or hardware configuration**:
VM - assume a standard x86 host? Maybe?
- **OS** (e.g. from /etc/os-release):
```sh
> cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
- **Kernel** (e.g. `uname -a`):
```sh
> uname -a
Linux mip-bd-vm218.mip.storage.hpecorp.net 3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 25 17:23:54 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
- **Others**:
I don't think this applies in my case?

## What happened?
When attempting to run `kubeadm token create` when setting up Kubernetes with mTLS, the token is added to the kubeadm token list but is not added to the cluster-info config map.

I attempted to follow [these directions](https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet-tls-bootstrapping), but something goes wrong and this happens:

```sh
[root@mip-bd-vm218 ~]> kubeadm token create --print-join-command
W1022 16:33:27.664081    5442 configset.go:202] WARNING: kubeadm cannot validate component configs for API groups [kubelet.config.k8s.io kubeproxy.config.k8s.io]
kubeadm join mip-bd-vm54.mip.storage.hpecorp.net:10007 --token hm7h66.q9z1tczs5r9wmamu     --discovery-token-ca-cert-hash sha256:$hash
# Ok, this looks normal - we got a token and a hash.
[root@mip-bd-vm218 ~]> kubeadm token list
TOKEN                     TTL         EXPIRES                     USAGES                   DESCRIPTION                                                EXTRA GROUPS
...
bhkfha.h07irt6fcorvdi1b   1h          2020-10-22T17:45:18-07:00   <none>                   Proxy for managing TTL for the kubeadm-certs secret        <none>
hm7h66.q9z1tczs5r9wmamu   23h         2020-10-23T16:33:27-07:00   authentication,signing   <none>                                                     system:bootstrappers:kubeadm:default-node-token
...
# Ok, this also looks normal - there's a list of tokens and the token we received from the previous request is in it.
[root@mip-bd-vm218 ~]> kubectl describe cm cluster-info -n kube-public
Name:         cluster-info
Namespace:    kube-public
Labels:       <none>
Annotations:  <none>

Data
====
kubeconfig:
----
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: ...
    server: https://mip-bd-vm54.mip.storage.hpecorp.net:10007
  name: ""
contexts: null
current-context: ""
kind: Config
preferences: {}
users: null

Events:  <none>
# That's a little weird - shouldn't there be at least the token that we just created in this config map?
... Time passes (~20 minutes?) ...
[root@mip-bd-vm218 ~]> curl -k -v -XGET  -H "User-Agent: kubeadm/v1.18.6 (linux/amd64) kubernetes/dff82dc" -H "Accept: application/json, */*" 'https://localhost:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s'
...
Dull header info
...
# The json below has been human-formatted for a better reading experience.
{
    "apiVersion": "v1",
    "data": {
        "kubeconfig": "apiVersion: v1\nclusters:\n- cluster:\n    certificate-authority-data: --- Dull cert data ---\n    server: https://mip-bd-vm54.mip.storage.hpecorp.net:10007\n  name: \"\"\ncontexts: null\ncurrent-context: \"\"\nkind: Config\npreferences: {}\nusers: null\n"
    },
    "kind": "ConfigMap",
    "metadata": {
        "creationTimestamp": "2020-10-22T22:45:18Z",
        "managedFields": [
            {
                "apiVersion": "v1",
                "fieldsType": "FieldsV1",
                "fieldsV1": {
                    "f:data": {
                        ".": {},
                        "f:kubeconfig": {}
                    }
                },
                "manager": "kubeadm",
                "operation": "Update",
                "time": "2020-10-22T22:45:18Z"
            }
        ],
        "name": "cluster-info",
        "namespace": "kube-public",
        "resourceVersion": "180",
        "selfLink": "/api/v1/namespaces/kube-public/configmaps/cluster-info",
        "uid": "5bed5b3d-5f9b-4f75-a25d-c8860919f9df"
    }
}
* Connection #0 to host localhost left intact
# That's really weird - I gave the system more than enough time to quiesce, so I would think there should be a new key in this configmap by now.
```

## What you expected to happen?
I expected the token to be added to the config-info configmap in a timely fashion.

## How to reproduce it (as minimally and precisely as possible)?
This... is a good question. This may have something to do with the certificate signers that I set up (I'll add them below), but I'm also curious if there are other configurations that could precipitate this behavior. The other things that I'm changing from a valid config are:

* Adding the controllerManager's `cluster-signing-cert-file` and `cluster-signing-key-file` startup params and setting them to the K8s root CA cert and key.
* Adding a `client-ca-file` to the apiServer's startup params and setting it to the K8s root CA.
* Adding `enable-bootstrap-token-auth` to the apiServer's startup params and setting it to `"true"`.

<details>
<summary>YAML files as specified by TLS bootstrap page</summary>

```yaml
# enable bootstrapping nodes to create CSR
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: create-csrs-for-bootstrapping
subjects:
- kind: Group
  name: system:bootstrappers
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: system:node-bootstrapper
  apiGroup: rbac.authorization.k8s.io
---
# Approve all CSRs for the group "system:bootstrappers"
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: auto-approve-csrs-for-group
subjects:
- kind: Group
  name: system:bootstrappers
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: system:certificates.k8s.io:certificatesigningrequests:nodeclient
  apiGroup: rbac.authorization.k8s.io
---
# Approve renewal CSRs for the group "system:nodes"
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: auto-approve-renewals-for-nodes
subjects:
- kind: Group
  name: system:nodes
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: system:certificates.k8s.io:certificatesigningrequests:selfnodeclient
  apiGroup: rbac.authorization.k8s.io
---
# From here down is a hack endorsed by this github comment:
# https://github.com/kubernetes/kubeadm/issues/668#issuecomment-368708398
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:controller:bootstrap-signer
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resourceNames:
  - cluster-info
  resources:
  - configmaps
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:controller:bootstrap-signer
  namespace: kube-public
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:controller:bootstrap-signer
subjects:
- kind: ServiceAccount
  name: bootstrap-signer
  namespace: kube-system
```

</details>

## Anything else we need to know?
I'm sure there is a lot of other stuff I'm doing wrong here, but these are the bits that I think are important to the problem at hand. I look forward to hearing your responses. Let me know if there is more information necessary to get the ball rolling.

**Comment by fabriziopandini** [comment]
/priority awaiting-more-evidence

kubeadm init should set up tokens for you; this document is quite old, but you can find some additional info on how this is implemented https://github.com/kubernetes/kubeadm/blob/master/docs/design/design_v1.9.md

If in your setup kubeadm reset is not working, please provide more info about how your cluster is configured.

**Comment by distortedsignal** [comment]
Hey @fabriziopandini - I'm not 100% sure what information would be relevant in this case. Are there any specific resources or OS configurations that you would like to see?

Here are the resources (I consider) relevant to this issue:

Command used to run `kubeadm`:

```sh
kubeadm init --ignore-preflight-errors Swap,IsDockerSystemdCheck --config=/tmp/kubeadm-config.yaml --upload-certs
```

Here's the `/tmp/kubeadm-config.yaml` file:

```yaml
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
failSwapOn: false
---
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
useHyperKubeImage: false
kubernetesVersion: "1.18.6"
controlPlaneEndpoint: "mip-bd-vm54.mip.storage.hpecorp.net:10007"
etcd:
  local:
    extraArgs:
      quota-backend-bytes: "8589934592"
      auto-compaction-retention: "24h"
      auto-compaction-mode: "periodic"
networking:
  serviceSubnet: 10.96.0.0/12
  podSubnet: 10.192.0.0/12
  dnsDomain: cluster.local
controllerManager:
  extraArgs:
    "node-cidr-mask-size": "25"
    profiling: "false"
    feature-gates: "RotateKubeletServerCertificate=true"
    terminated-pod-gc-threshold: "10"
    # Root key and cert
    cluster-signing-cert-file: "/etc/kubernets/pki/ca.crt"
    cluster-signing-key-file: "/etc/kubernetes/pki/ca.key"
  extraVolumes:
  - name: kubernetes-ca-cert
    hostPath: /etc/kubernetes/pki
    mountPath: /etc/kubernetes/pki
    readOnly: true
    pathType: Directory
scheduler:
  extraArgs:
    profiling: "false"
clusterName: k8s-17
apiServer:
  certSANs:
    # Think of this host as an authenticating proxy for kubectl requests
    - "mip-bd-vm54.mip.storage.hpecorp.net"
  timeoutForControlPlane: 10m0s
  extraArgs:
    requestheader-allowed-names: ""
    runtime-config : "settings.k8s.io/v1alpha1=true"
    enable-admission-plugins : PodPreset,NodeRestriction,PodSecurityPolicy,EventRateLimit,AlwaysPullImages
    admission-control-config-file: "/etc/bluedata/k8s-admission-control-config.yaml"
    advertise-address: 16.143.21.162
    audit-policy-file: "/etc/bluedata/k8s-audit-policy.yaml"
    audit-log-path: "/var/log/bluedata/k8s-audit.log"
    audit-log-maxage: "30"
    audit-log-maxbackup: "10"
    audit-log-maxsize: "1024"
    api-audiences: api,istio-ca
    client-ca-file: /etc/kubernetes/pki/ca.crt
    enable-bootstrap-token-auth: "true"
    service-account-issuer: kubernetes.default.svc
    service-account-key-file: /etc/kubernetes/pki/sa.key
    service-account-signing-key-file: /etc/kubernetes/pki/sa.key
    profiling: "false"
    encryption-provider-config: /etc/kubernetes/pki/encryption.yaml
    tls-cipher-suites: "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384"
  extraVolumes:
  - name: logs
    hostPath: /var/log/bluedata
    mountPath: /var/log/bluedata
    readOnly: false
    pathType: Directory
  - name: audit-policy
    hostPath: /etc/bluedata/k8s-audit-policy.yaml
    mountPath: /etc/bluedata/k8s-audit-policy.yaml
    readOnly: true
    pathType: File
  - name: event-rate-policy
    hostPath: /etc/bluedata/k8s-event-config.yaml
    mountPath: /etc/bluedata/k8s-event-config.yaml
    readOnly: true
    pathType: File
  - name: admission-control-policy
    hostPath: /etc/bluedata/k8s-admission-control-config.yaml
    mountPath: /etc/bluedata/k8s-admission-control-config.yaml
    readOnly: true
    pathType: File
```

The two files from here that I could see being important are `/etc/kubernetes/pki/encryption.yaml`:

```yaml
apiVersion: apiserver.config.k8s.io/v1
kind: EncryptionConfiguration
resources:
  - resources:
    - secrets
    providers:
    - aescbc:
        keys:
        - name: key1
          secret: --- Redacted ---
    - identity: {}
```

and `/etc/bluedata/k8s-admission-control-config.yaml`:

```yaml
apiVersion: apiserver.config.k8s.io/v1
kind: AdmissionConfiguration
plugins:
- name: EventRateLimit
  path: /etc/bluedata/k8s-event-config.yaml
```

Is there anything that you'd like to see that I'm missing here?

**Comment by neolit123** [comment]
hi, do you have any relevant log errors from the kube-apiserver or kube-controller-manager after a bootstrap-token is created but fails to be added to cluster-info?
you could enable higher verbosity with `--v=X` for these components.

this does not look like a problem in kubeadm (unless it's missing some new RBAC?), but we need to figure out what is blocking it exactly.

@kubernetes/sig-auth-bugs

**Comment by neolit123** [comment]
> I'm sure there is a lot of other stuff I'm doing wrong here, but these are the bits that I think are important to the problem at hand. I look forward to hearing your responses. Let me know if there is more information necessary to get the ball rolling.

you could help us to narrow down which extensions you applied that differ from the kubeadm defaults cause this problem.
but quite possibly we may close this ticket and move your discussion to #sig-auth on k8s slack to see if you can get support there, or maybe a kubernetes/kubernetes ticket with `/kind support`.

**Comment by distortedsignal** [comment]
Could you help me out with what you mean by "extensions"? I understood that providing the full `kubeadm-conf.yaml` should be enough to fully define this system.

**Comment by neolit123** [comment]
> Could you help me out with what you mean by "extensions"? I understood that providing the full kubeadm-conf.yaml should be enough to fully define this system.

by extensions i meant functionality that extends the kubeadm defaults for the core components. here are the kubeadm defaults for the api-server and KCM:

```
    - kube-apiserver
    - --advertise-address=192.168.0.101
    - --allow-privileged=true
    - --authorization-mode=Node,RBAC
    - --client-ca-file=/etc/kubernetes/pki/ca.crt
    - --enable-admission-plugins=NodeRestriction
    - --enable-bootstrap-token-auth=true
    - --etcd-cafile=/etc/kubernetes/pki/etcd/ca.crt
    - --etcd-certfile=/etc/kubernetes/pki/apiserver-etcd-client.crt
    - --etcd-keyfile=/etc/kubernetes/pki/apiserver-etcd-client.key
    - --etcd-servers=https://127.0.0.1:2379
    - --insecure-port=0
    - --kubelet-client-certificate=/etc/kubernetes/pki/apiserver-kubelet-client.crt
    - --kubelet-client-key=/etc/kubernetes/pki/apiserver-kubelet-client.key
    - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
    - --proxy-client-cert-file=/etc/kubernetes/pki/front-proxy-client.crt
    - --proxy-client-key-file=/etc/kubernetes/pki/front-proxy-client.key
    - --requestheader-allowed-names=front-proxy-client
    - --requestheader-client-ca-file=/etc/kubernetes/pki/front-proxy-ca.crt
    - --requestheader-extra-headers-prefix=X-Remote-Extra-
    - --requestheader-group-headers=X-Remote-Group
    - --requestheader-username-headers=X-Remote-User
    - --secure-port=6443
    - --service-account-key-file=/etc/kubernetes/pki/sa.pub
    - --service-cluster-ip-range=10.96.0.0/12
    - --tls-cert-file=/etc/kubernetes/pki/apiserver.crt
    - --tls-private-key-file=/etc/kubernetes/pki/apiserver.key

...

    - kube-controller-manager
    - --authentication-kubeconfig=/etc/kubernetes/controller-manager.conf
    - --authorization-kubeconfig=/etc/kubernetes/controller-manager.conf
    - --bind-address=127.0.0.1
    - --client-ca-file=/etc/kubernetes/pki/ca.crt
    - --cluster-name=kubernetes
    - --cluster-signing-cert-file=/etc/kubernetes/pki/ca.crt
    - --cluster-signing-key-file=/etc/kubernetes/pki/ca.key
    - --controllers=*,bootstrapsigner,tokencleaner
    - --kubeconfig=/etc/kubernetes/controller-manager.conf
    - --leader-elect=true
    - --port=0
    - --requestheader-client-ca-file=/etc/kubernetes/pki/front-proxy-ca.crt
    - --root-ca-file=/etc/kubernetes/pki/ca.crt
    - --service-account-private-key-file=/etc/kubernetes/pki/sa.key
    - --use-service-account-credentials=true

```

**Comment by distortedsignal** [comment]
Ok, thanks for helping me understand the "extensions" part. Here's what (I think) you're looking for:

<details>
<summary>API Server Pod Definition File</summary>

```yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubeadm.kubernetes.io/kube-apiserver.advertise-address.endpoint: 16.143.21.162:6443
  creationTimestamp: null
  labels:
    component: kube-apiserver
    tier: control-plane
  name: kube-apiserver
  namespace: kube-system
spec:
  containers:
  - command:
    - kube-apiserver
    - --admission-control-config-file=/etc/bluedata/k8s-admission-control-config.yaml // I think this is in the text above?
    - --advertise-address=16.143.21.162
    - --allow-privileged=true
    - --api-audiences=api,istio-ca
    - --audit-log-maxage=30
    - --audit-log-maxbackup=10
    - --audit-log-maxsize=1024
    - --audit-log-path=/var/log/bluedata/k8s-audit.log
    - --audit-policy-file=/etc/bluedata/k8s-audit-policy.yaml
    - --authorization-mode=Node,RBAC
    - --client-ca-file=/etc/kubernetes/pki/ca.crt
    - --enable-admission-plugins=PodPreset,NodeRestriction,PodSecurityPolicy,EventRateLimit,AlwaysPullImages
    - --enable-bootstrap-token-auth=true
    - --encryption-provider-config=/etc/kubernetes/pki/encryption.yaml // Also in text above?
    - --etcd-cafile=/etc/kubernetes/pki/etcd/ca.crt
    - --etcd-certfile=/etc/kubernetes/pki/apiserver-etcd-client.crt
    - --etcd-keyfile=/etc/kubernetes/pki/apiserver-etcd-client.key
    - --etcd-servers=https://127.0.0.1:2379
    - --insecure-port=0
    - --kubelet-client-certificate=/etc/kubernetes/pki/apiserver-kubelet-client.crt
    - --kubelet-client-key=/etc/kubernetes/pki/apiserver-kubelet-client.key
    - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
    - --profiling=false
    - --proxy-client-cert-file=/etc/kubernetes/pki/front-proxy-client.crt
    - --proxy-client-key-file=/etc/kubernetes/pki/front-proxy-client.key
    - --requestheader-allowed-names=
    - --requestheader-client-ca-file=/etc/kubernetes/pki/front-proxy-ca.crt
    - --requestheader-extra-headers-prefix=X-Remote-Extra-
    - --requestheader-group-headers=X-Remote-Group
    - --requestheader-username-headers=X-Remote-User
    - --runtime-config=settings.k8s.io/v1alpha1=true
    - --secure-port=6443
    - --service-account-issuer=kubernetes.default.svc
    - --service-account-key-file=/etc/kubernetes/pki/sa.key
    - --service-account-signing-key-file=/etc/kubernetes/pki/sa.key
    - --service-cluster-ip-range=10.96.0.0/12
    - --tls-cert-file=/etc/kubernetes/pki/apiserver.crt
    - --tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
    - --tls-private-key-file=/etc/kubernetes/pki/apiserver.key
    env:
    - name: ftp_proxy
      value: http://web-proxy.corp.hpecorp.net:8080
    - name: NODE_PROXY
      value: proxy
    image: k8s.gcr.io/kube-apiserver:v1.18.6
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 8
      httpGet:
        host: 16.143.21.162
        path: /healthz
        port: 6443
        scheme: HTTPS
      initialDelaySeconds: 15
      timeoutSeconds: 15
    name: kube-apiserver
    resources:
      requests:
        cpu: 250m
    volumeMounts:
    - mountPath: /etc/bluedata/k8s-admission-control-config.yaml
      name: admission-control-policy
      readOnly: true
    - mountPath: /etc/bluedata/k8s-audit-policy.yaml
      name: audit-policy
      readOnly: true
    - mountPath: /etc/ssl/certs
      name: ca-certs
      readOnly: true
    - mountPath: /etc/pki
      name: etc-pki
      readOnly: true
    - mountPath: /etc/bluedata/k8s-event-config.yaml
      name: event-rate-policy
      readOnly: true
    - mountPath: /etc/kubernetes/pki
      name: k8s-certs
      readOnly: true
    - mountPath: /var/log/bluedata
      name: logs
  hostNetwork: true
  priorityClassName: system-cluster-critical
  volumes:
  - hostPath:
      path: /etc/bluedata/k8s-admission-control-config.yaml
      type: File
    name: admission-control-policy
  - hostPath:
      path: /etc/bluedata/k8s-audit-policy.yaml
      type: File
    name: audit-policy
  - hostPath:
      path: /etc/ssl/certs
      type: DirectoryOrCreate
    name: ca-certs
  - hostPath:
      path: /etc/pki
      type: DirectoryOrCreate
    name: etc-pki
  - hostPath:
      path: /etc/bluedata/k8s-event-config.yaml
      type: File
    name: event-rate-policy
  - hostPath:
      path: /etc/kubernetes/pki
      type: DirectoryOrCreate
    name: k8s-certs
  - hostPath:
      path: /var/log/bluedata
      type: Directory
    name: logs
status: {}
```

</details>



<details>
<summary>Controller Manager Pod Definition File</summary>

```yaml
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    component: kube-controller-manager
    tier: control-plane
  name: kube-controller-manager
  namespace: kube-system
spec:
  containers:
  - command:
    - kube-controller-manager
    - --allocate-node-cidrs=true
    - --authentication-kubeconfig=/etc/kubernetes/controller-manager.conf
    - --authorization-kubeconfig=/etc/kubernetes/controller-manager.conf
    - --bind-address=127.0.0.1
    - --client-ca-file=/etc/kubernetes/pki/ca.crt
    - --cluster-cidr=10.192.0.0/12
    - --cluster-name=k8s-17
    - --cluster-signing-cert-file=/etc/kubernets/pki/ca.crt
    - --cluster-signing-key-file=/etc/kubernetes/pki/ca.key
    - --controllers=*,bootstrapsigner,tokencleaner
    - --feature-gates=RotateKubeletServerCertificate=true
    - --kubeconfig=/etc/kubernetes/controller-manager.conf
    - --leader-elect=true
    - --node-cidr-mask-size=25
    - --port=0
    - --profiling=false
    - --requestheader-client-ca-file=/etc/kubernetes/pki/front-proxy-ca.crt
    - --root-ca-file=/etc/kubernetes/pki/ca.crt
    - --service-account-private-key-file=/etc/kubernetes/pki/sa.key
    - --service-cluster-ip-range=10.96.0.0/12
    - --terminated-pod-gc-threshold=10
    - --use-service-account-credentials=true
    env:
    - name: ftp_proxy
      value: http://web-proxy.corp.hpecorp.net:8080
    - name: NODE_PROXY
      value: proxy
    image: k8s.gcr.io/kube-controller-manager:v1.18.6
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 8
      httpGet:
        host: 127.0.0.1
        path: /healthz
        port: 10257
        scheme: HTTPS
      initialDelaySeconds: 15
      timeoutSeconds: 15
    name: kube-controller-manager
    resources:
      requests:
        cpu: 200m
    volumeMounts:
    - mountPath: /etc/ssl/certs
      name: ca-certs
      readOnly: true
    - mountPath: /etc/pki
      name: etc-pki
      readOnly: true
    - mountPath: /usr/libexec/kubernetes/kubelet-plugins/volume/exec
      name: flexvolume-dir
    - mountPath: /etc/kubernetes/pki
      name: k8s-certs
      readOnly: true
    - mountPath: /etc/kubernetes/controller-manager.conf
      name: kubeconfig
      readOnly: true
    - mountPath: /etc/kubernetes/pki
      name: kubernetes-ca-cert
      readOnly: true
  hostNetwork: true
  priorityClassName: system-cluster-critical
  volumes:
  - hostPath:
      path: /etc/ssl/certs
      type: DirectoryOrCreate
    name: ca-certs
  - hostPath:
      path: /etc/pki
      type: DirectoryOrCreate
    name: etc-pki
  - hostPath:
      path: /usr/libexec/kubernetes/kubelet-plugins/volume/exec
      type: DirectoryOrCreate
    name: flexvolume-dir
  - hostPath:
      path: /etc/kubernetes/pki
      type: DirectoryOrCreate
    name: k8s-certs
  - hostPath:
      path: /etc/kubernetes/controller-manager.conf
      type: FileOrCreate
    name: kubeconfig
  - hostPath:
      path: /etc/kubernetes/pki
      type: Directory
    name: kubernetes-ca-cert
status: {}
```

</details>

Is there anything in here that you would like to see further?
