### ISSUE TITLE
fix some issues in the kubeadm HA etcd documentation

### ISSUE THREAD

**Issue by FireDrunk** [kubernetes/kubeadm#2334]
EDIT by neolit123

see this for `help-wanted` on updating the kubeadm HA docs:
https://github.com/kubernetes/kubeadm/issues/2334#issuecomment-868025463
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/setup-ha-etcd-with-kubeadm/

(original issue report below)

-------------

## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`):
Tested with 1.17.12 and 1.19.3

**Environment**:
- **Kubernetes version** (use `kubectl version`): none yet
- **Cloud provider or hardware configuration**: n/a
- **OS** (e.g. from /etc/os-release): Debian 10.3
- **Kernel** (e.g. `uname -a`): 4.19.0-12-amd64
- **Others**: nothing special

Setup:
3 machines, nuc[1-3], IP [192.168.1.4[0-2], nothing special.

## What happened?
I'm following this guide:
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/setup-ha-etcd-with-kubeadm/

It generates kubeadmcfg.yaml files, with the *peerCertSANs* and *serverCertSANs* options.
In my case:

/tmp/192.168.1.41/kubeadmcfg.yaml:
```yaml
apiVersion: "kubeadm.k8s.io/v1beta2"
kind: ClusterConfiguration
etcd:
  local:
    serverCertSANs:
      - "192.168.1.41"
    peerCertSANs:
      - "192.168.1.41"
    extraArgs:
      initial-cluster: nuc1=https://192.168.1.40:2380,nuc2=https://192.168.1.41:2380,nuc3=https://192.168.1.42:2380
      initial-cluster-state: new
      name: nuc2
      listen-peer-urls: https://192.168.1.41:2380
      listen-client-urls: https://192.168.1.41:2379
      advertise-client-urls: https://192.168.1.41:2379
      initial-advertise-peer-urls: https://192.168.1.41:2380
```
The first one is exactly the same, but is generated correctly. The problem is with the second node.
The command:
`kubeadm init phase certs etcd-server --config=/tmp/192.168.1.41/kubeadmcfg.yaml`
outputs this:

```bash
root@nuc1:/etc/kubernetes/pki/etcd# kubeadm init phase certs etcd-server --config=/tmp/192.168.1.41/kubeadmcfg.yaml
W1024 15:02:07.697774   25946 configset.go:348] WARNING: kubeadm cannot validate component configs for API groups [kubelet.config.k8s.io kubeproxy.config.k8s.io]
[certs] Generating "etcd/server" certificate and key
[certs] etcd/server serving cert is signed for DNS names [localhost nuc1 nuc2] and IPs [192.168.1.40 127.0.0.1 ::1 192.168.1.41]
```

## What you expected to happen?
I think it should *not* generate a certificate with the *current* hostname as a SAN. It should just follow the kubeadmcfg.yaml variables.

Further on this gives issues when joining nodes.

## How to reproduce it (as minimally and precisely as possible)?
`kubeadm init phase certs etcd-ca`

Generate manifests with (as from the example page):
etcd_manifests.sh:
```bash
#!/bin/bash
export HOST0=192.168.1.40
export HOST1=192.168.1.41
export HOST2=192.168.1.42

# Create temp directories to store files that will end up on other hosts.
mkdir -p /tmp/${HOST0}/ /tmp/${HOST1}/ /tmp/${HOST2}/

ETCDHOSTS=(${HOST0} ${HOST1} ${HOST2})
NAMES=("nuc1" "nuc2" "nuc3")

for i in "${!ETCDHOSTS[@]}"; do
HOST=${ETCDHOSTS[$i]}
NAME=${NAMES[$i]}
cat << EOF > /tmp/${HOST}/kubeadmcfg.yaml
apiVersion: "kubeadm.k8s.io/v1beta2"
kind: ClusterConfiguration
etcd:
  local:
    serverCertSANs:
      - "${HOST}"
    peerCertSANs:
      - "${HOST}"
    extraArgs:
      initial-cluster: ${NAMES[0]}=https://${ETCDHOSTS[0]}:2380,${NAMES[1]}=https://${ETCDHOSTS[1]}:2380,${NAMES[2]}=https://${ETCDHOSTS[2]}:2380
      initial-cluster-state: new
      name: ${NAME}
      listen-peer-urls: https://${HOST}:2380
      listen-client-urls: https://${HOST}:2379
      advertise-client-urls: https://${HOST}:2379
      initial-advertise-peer-urls: https://${HOST}:2380
EOF
done
```

Execute:
`kubeadm init phase certs etcd-server --config=/tmp/192.168.1.41/kubeadmcfg.yaml`

See output & results in /etc/kubernetes/pki/etcd/

## Anything else we need to know?
I've tried to read up on etcd ssl certificates and signing here:
https://etcd.io/docs/v3.4.0/op-guide/security/

To my understanding:

*both* peer and server certificates are *per node*. They require DNSNames that match the initial-cluster name argument, and the connection is required to come from a matching IP in the certificate. The certificate should be signed by a common CA.

This ensures that the combination of DNS and IP is singed by the CA.

In the example. this generates 3 certificates, 1 signed for nuc1, 1 for nuc1 with a san of nuc2, and 1 for nuc1 with a san for nuc3.

I've tried adding - "${NAME}" to both the peerCertSANs and serverCertSANs entries, which added the proper name to the certificates, but it still kept the hostname of the node that the command is run on.

I don't think that's correct...

**Comment by FireDrunk** [comment]
After moving the ca.key & ca.cert files to the nodes and generating the certifcates on the nodes themselfes, the Etcd cluster comes online perfectly.

Upon following the guide, (i've created the cluster configuration).
`kubeadm init --config kubeadm-config.yaml --upload-certs` gives me errors regarding an already existing manifest for etcd, which is correct, since I created it in the previous step.

To circumvent this issue i had to do: `kubeadm init --config kubeadm-config.yaml --upload-certs --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-etcd.yaml,Port-10250`.

I think this is a bug, and kubeadm should not check these manifests or ports if the cluster configuration states the Etcd cluster is external.

After using the above command, the installation fails with:
```Error writing Crisocket information for the control-plane node```
This is because it cannot find the proper node in the API Server (which comes online perfectly).

I'm investigating why the node doesn't exist (yet).

**Comment by neolit123** [comment]
> I've tried adding - "${NAME}" to both the peerCertSANs and serverCertSANs entries, which added the proper name to the certificates, but it still kept the hostname of the node that the command is run on.
> I don't think that's correct...

could you please clarify what do you mean by "proper name" here?
why do you think that adding the node name to the SANs is a problem?

> Upon following the guide, (i've created the cluster configuration).
> kubeadm init --config kubeadm-config.yaml --upload-certs

uploading the control-plane certificates (--upload certs) during the creation of etcd server instances in an HA etcd setup, should not be done.
it's not in this guide:
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/setup-ha-etcd-with-kubeadm/

it should be called only once during the first "init" called on Kubernetes nodes.

> To circumvent this issue i had to do: kubeadm init --config kubeadm-config.yaml --upload-certs --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-etcd.yaml,Port-10250.

you need to call `kubeadm reset` before calling `kubeadm init` even on the etcd nodes.

/kind support

**Comment by FireDrunk** [comment]
> 
> 
> > I've tried adding - "${NAME}" to both the peerCertSANs and serverCertSANs entries, which added the proper name to the certificates, but it still kept the hostname of the node that the command is run on.
> > I don't think that's correct...
> 
> could you please clarify what do you mean by "proper name" here?
> why do you think that adding the node name to the SANs is a problem?

In previous attempts, joining the second node resulted in both nodes spewing errors regarding the incoming and outgoing connection certificate name not being nuc1 (when the nuc2 was the joining node). It looked like it was expecting it's own certificate instead of one signed by the ca. This went away wen generating the certificate on the second node (which caused it to have nuc2 as it's first 'name'.

> > Upon following the guide, (i've created the cluster configuration).
> > kubeadm init --config kubeadm-config.yaml --upload-certs
> 
> uploading the control-plane certificates (--upload certs) during the creation of etcd server instances in an HA etcd setup, should not be done.
> it's not in this guide:
> https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/setup-ha-etcd-with-kubeadm/
> 
> --upload-certs should be called only once, during the first "init" on a the first Kubernetes nodes that kubeadm creates.
> 
> > To circumvent this issue i had to do: kubeadm init --config kubeadm-config.yaml --upload-certs --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-etcd.yaml,Port-10250.
> 
> you need to call `kubeadm reset` before calling `kubeadm init` even on the etcd nodes (external etcd)
> 
> /kind support

That's indead my mistake. I'm trying to build a basic stacked etcd configuration, but that's also failing.
I was trying to do the stacked configuration manually with the external etcd but still on the same nodes.
So running kubeadm reset will break the working etcd cluster, since it deletes the /var/lib/etcd data directories.

After running a `kubeadm reset` and running:
`kubeadm init --control-plane-endpoint "k8s.prv.cloud:6443" --upload-certs`

Gives me the same node-not-found.
```
I1026 21:11:42.800782   11671 request.go:1017] Response Body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"nodes \"nuc1\" not found","reason":"NotFound","details":{"name":"nuc1","kind":"nodes"},"code":404}   
I1026 21:11:42.801069   11671 round_trippers.go:423] curl -k -v -XGET  -H "User-Agent: kubeadm/v1.17.12 (linux/amd64) kubernetes/5ec4722" -H "Accept: application/json, */*" 'https://k8s.prv.cloud:6443/api/v1/nodes/nuc1?timeout=10s'
I1026 21:11:42.804564   11671 round_trippers.go:443] GET https://k8s.prv.cloud:6443/api/v1/nodes/nuc1?timeout=10s 404 Not Found in 3 milliseconds
I1026 21:11:42.804599   11671 round_trippers.go:449] Response Headers:
I1026 21:11:42.804617   11671 round_trippers.go:452]     Cache-Control: no-cache, private
I1026 21:11:42.804633   11671 round_trippers.go:452]     Content-Type: application/json
I1026 21:11:42.804651   11671 round_trippers.go:452]     Content-Length: 178
I1026 21:11:42.804666   11671 round_trippers.go:452]     Date: Mon, 26 Oct 2020 20:11:42 GMT
I1026 21:11:42.804730   11671 request.go:1017] Response Body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"nodes \"nuc1\" not found","reason":"NotFound","details":{"name":"nuc1","kind":"nodes"},"code":404}   
timed out waiting for the condition
```

When opening a second shell, and executing:
```
root@nuc1:~# kubectl --kubeconfig /etc/kubernetes/admin.conf get node -A
No resources found
```

That doesn't seem right, but I don't know where in the process the nodes get added.

**Comment by neolit123** [comment]
>  I'm trying to build a basic stacked etcd configuration, but that's also failing.

as in not passing `etcd.external` in the kubeadm config?

> I was trying to do the stacked configuration manually with the external etcd but still on the same nodes.

i don't believe any of the kubeadm maintainers have tried that.
from a a high-availability stand point it gains you no benefits over using the kubeadm stacked etcd (i.e. not passing `etcd.external` in the config, but either passing or omitting `etcd.local`)

> Gives me the same node-not-found.

sadly, the node-not-found problem is not very descriptive and can be caused by a number of factors including container runtime misconfiguration. you'd have to dig in the kubelet logs to find any errors.

> That doesn't seem right, but I don't know where in the process the nodes get added.

it's the kubelet that creates the Node objects via the TLS bootstrap process.
so for a Node to be created, kubeadm writes `/etc/kubernetes/*kubelet.conf` files, and from there the kubelet takes over.

since i don't see a kubeadm bug here, i'm going to close this ticket, but feel free to ask further questions if needed here or at:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/kind support
/close

**Comment by FireDrunk** [comment]
After a s**tload of debugging and some cursing later, I found out there was a second systemd override file in /etc/systemd/system/kubelet.service.d/ directory which interfered with the kubelet configuration generated by the kubeadm installation.

Removing the file fixed everything since the kubelet now bootstrapped correctly.

Thanks all for the help.

**Comment by mrksngl** [comment]
I still think this is a bug (or maybe rather a missing feature, or just a mistake in the docs) , I ran into the exact same problem:

When following https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/setup-ha-etcd-with-kubeadm/ step-by-step, the certificates for `${HOST2}` and `${HOST1}` are wrong.
The docs suggest that all certificates are generated on the same node, more specific on `${HOST0}`. Then when generating certificates for `${HOST2}`, we see
```
host0# kubeadm init phase certs etcd-server --config=/tmp/${HOST2}/kubeadmcfg.yaml
[certs] etcd/server serving cert is signed for DNS names [localhost host0 host2] and IPs [IP_OF_HOST0 127.0.0.1 ::1]
```

So obviously `kubeadm` always throws in the name and IP of the node it is running on.
Thus, certificates are not generated the way they are supposed to be.

Workaround is, as @FireDrunk suggested, to copy the CA (of step three in the docs) to the target nodes (i.e. to `${HOST1}` and `${HOST2}`) and execute `kubeadm` from there.
But then again, either `kubeadm` does not work as suggested by the docs or the docs should be adapted towards this workaround.

**Comment by neolit123** [comment]
> host0# kubeadm init phase certs etcd-server --config=/tmp/${HOST2}/kubeadmcfg.yaml
[certs] etcd/server serving cert is signed for DNS names [localhost host0 host2] and IPs [IP_OF_HOST0 127.0.0.1 ::1]

should the IP  of host2 be also in this list

> So obviously kubeadm always throws in the name and IP of the node it is running on.
> Thus, certificates are not generated the way they are supposed to be.

i think your observation is correct.
the logic is here:
https://github.com/kubernetes/kubernetes/blob/61641a0640f197e6e67a41b49b49a7b5bd3af6a9/cmd/kubeadm/app/util/pkiutil/pki_helpers.go#L473-L500

to workaround this try using this config instead:
```
apiVersion: "kubeadm.k8s.io/v1beta2"
kind: InitConfiguration
nodeRegistration:
    name: ${HOSTNAME}
localAPIEndpoint:
    advertiseAddress: ${HOST}
---
apiVersion: "kubeadm.k8s.io/v1beta2"
kind: ClusterConfiguration
etcd:
    local:
        serverCertSANs:
        - "${HOST}"
        peerCertSANs:
        - "${HOST}"
        extraArgs:
            initial-cluster: ${NAMES[0]}=https://${ETCDHOSTS[0]}:2380,${NAMES[1]}=https://${ETCDHOSTS[1]}:2380,${NAMES[2]}=https://${ETCDHOSTS[2]}:2380
            initial-cluster-state: new
            name: ${NAME}
            listen-peer-urls: https://${HOST}:2380
            listen-client-urls: https://${HOST}:2379
            advertise-client-urls: https://${HOST}:2379
            initial-advertise-peer-urls: https://${HOST}:2380
```

note that $HOSTNAME must be something that is obtained in the loop with e.g. `HOSTNAME=$(hostname)`
let me know if that works for you.

> But then again, either kubeadm does not work as suggested by the docs or the docs should be adapted towards this workaround.

the page is maintained on a best effort at that point since we are understaffed.
contributions are welcome!

**Comment by neolit123** [comment]
/kind documentation
/milestone v1.22
/help-wanted
(details above)

**Comment by mrksngl** [comment]
Of course I set the `HOSTn` variables to something meaningful, above was just an example assuing `HOST0=host0, ...`.

I also already figured setting an `localAPIEndpoint.advertiseAddress` in the `InitConfiguration` but that got only the IP right. 

Thanks for pointing out `nodeRegistration.name`. Seems like all certificates are fine now.

**Comment by pacoxu** [comment]
/assign
I will be the backup if nobody picks it.
I may work on it next week.

**Comment by alekc** [comment]
Can we also document if it's possible to set up stacked etcd with custom ip? 
I've tried to use following config 
node01
```
export ENDPOINT=k8s.xxx.dev:6443
export NODE_NAME=k8s-master-01
export PUBLIC_IP=$(curl http://checkip.amazonaws.com)
cat <<EOF > /root/kubeadm-config.yaml
apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: ${PUBLIC_IP}
  bindPort: 6443
nodeRegistration:
  name: ${NODE_NAME}
---
apiVersion: "kubeadm.k8s.io/v1beta3"
kind: ClusterConfiguration
networking:
  podSubnet: "10.244.0.0/16"
controlPlaneEndpoint: ${ENDPOINT}
etcd:
  local:
    extraArgs:
      name: ${NODE_NAME}
      listen-peer-urls: https://0.0.0.0:2380
      listen-client-urls: https://0.0.0.0:2379
      listen-metrics-urls: http://0.0.0.0:2381
      advertise-client-urls: https://${PUBLIC_IP}:2379
      initial-advertise-peer-urls: https://${PUBLIC_IP}:2380
EOF
```

it comes up correctly with node up and running. 

Once I add up a second node  with 
```
export ENDPOINT=k8s.xxx.dev:6443
export NODE_NAME=k8s-master-02
export PUBLIC_IP=$(curl http://checkip.amazonaws.com)
export TOKEN=0lbajb.24mtbrzuwtxbczmn
export CA_CERT_HASH=sha256:0170b62dd94852782e6dff52b3d709305e7dae54c1f177753b6d7df3b382a6c0
export CERT_KEY=ecb389f758f50e99573a1931ee59c1c3efa916cbeb356a2dee766fa08e6dbede

cat <<EOF > /root/kubeadm-config.yaml
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: JoinConfiguration
caCertPath: /etc/kubernetes/pki/ca.crt
discovery:
  bootstrapToken:
    apiServerEndpoint: ${ENDPOINT}
    token: ${TOKEN}
    caCertHashes: 
      - ${CA_CERT_HASH}
    unsafeSkipCAVerification: false
nodeRegistration:
  name: ${NODE_NAME}
controlPlane:
  certificateKey: ${CERT_KEY}
  localAPIEndpoint: 
    advertiseAddress: ${PUBLIC_IP}
    bindPort: 6443
---
apiVersion: "kubeadm.k8s.io/v1beta3"
kind: ClusterConfiguration
controlPlaneEndpoint: ${ENDPOINT}
etcd:
  local:    
    extraArgs:
      name: ${NODE_NAME}
      listen-peer-urls: https://0.0.0.0:2380
      listen-client-urls: https://0.0.0.0:2379
      listen-metrics-urls: http://0.0.0.0:2381
      advertise-client-urls: https://${PUBLIC_IP}:2379
      initial-advertise-peer-urls: https://${PUBLIC_IP}:2380
EOF
```

etcd on the second node never come up just crashing, and on the first node etcd crashes as well bringing down cluster. 

is there something I am blatanly missing?
