### ISSUE TITLE
Bind controller-manager and scheduler to node ip address to expose `/metrics` endpoint

### ISSUE THREAD

**Issue by ksa-real** [kubernetes/kubeadm#2388]
FEATURE REQUEST

## Versions

**kubeadm version** (use `kubeadm version`): 1.20.2

**Environment**:
- **Kubernetes version** (use `kubectl version`): v1.20.2
- **Cloud provider or hardware configuration**: Bare-metal
- **OS** (e.g. from /etc/os-release): Gentoo 2.7
- **Kernel** (e.g. `uname -a`): 5.10.4-gentoo
- **Others**:

## What happened?
TL;DR Controller manager and scheduler's metrics endpoint is inaccessible with the default kubeadm setup. The proposal is to use the node IP address instead of 127.0.0.1 for kube-controller-manager (KCM) and kube-scheduler's (KS) `--bind-address` argument and probe configs.

Both KCM and KS bind to 127.0.0.1 with port 10257 and 10258 to expose `/healthz` and `/metrics` endpoints. `/healthz` is exposed mostly for local consumptions (probes), where `/metrics` is expected to be scraped by central metrics scraper (Prometheus or similar) which is not expected to run as a daemon set on control plane nodes. The current workaround is to use `--bind-address=0.0.0.0` which may overexpose metrics to unwanted interfaces and effectively to the internet. This may be fixed by applying firewall rules (e.g. iptables) to drop all traffic coming to these ports except for node IP destination. 

Another solution would be patching `kubeadm.yml` kubeadm config file with the below sections right before applying `kubeadm init phase control-plane controller-manager --config kubeadm.yml` (same for KS):
```
controllerManager:
  extraArgs:
    bind-address: <NODE IP ADDRESS>
scheduler:
  extraArgs:
    bind-address: <NODE IP ADDRESS>
```

One more workaround is to use `kubeadm`'s  `--experimental-patches` argument. The downside is that it fixes static manifests instead of kubeadm config. It depends on --bind-address argument position in the argument list, and requires patching multiple places (command line and two probes for each component).

Arguably, most users would prefer `/metrics` endpoint be set up in a useful way by default and without such an effort.

The proposed solutions are:
- Bind to node IP address by default, similarly to `api-server` and `etcd`.
- Provide argument in kubeadm config to bind to node IP instead of 127.0.0.1. For example:
```
controllerManager:
  bindToNodeAddress: true
scheduler:
  bindToNodeAddress: true
```
- Provide variable for kubeadm, which will be replaced with the node id. Example:
```
controllerManager:
  extraArgs:
    bind-address: $NODE_IP_ADDRESS # or template style - {{ nodeIPAddress }}
scheduler:
  extraArgs:
    bind-address: $NODE_IP_ADDRESS
```

**Comment by neolit123** [comment]
binding to the node IP is intuitive, but here is my argument against this:
- kubeadm users that care about metrics are not a majority.
- this goes against security hardening. if a component doesn't have to be served on a non-loopback by default then it shouldn't be.

> bindToNodeAddress: true
> ...
> bind-address: $NODE_IP_ADDRESS

these options are unlikely going to happen, given there exist a number of workarounds including phases and patches.

> One more workaround is to use kubeadm's --experimental-patches argument. The downside is that it fixes static manifests instead of kubeadm config. It depends on --bind-address argument position in the argument list, and requires patching multiple places (command line and two probes for each component).

the positional argument problem is not true. you can pass additional `--bind-address` flags and only the last one will be used.
i.e. your patch can insert at the end of the container args.

the probe host is a key, so there is no problem there.

the `kube-scheduler.json` and `kube-controller-manager.json` patches look like this.
```
[
	{ "op": "add", "path": "/spec/containers/0/command/-", "value": "--bind-address=SOME_IP" },
	{ "op": "replace", "path": "/spec/containers/0/livenessProbe/httpGet/host", "value": "SOME_IP" }
]
```

**Comment by ksa-real** [comment]
Thanks. Confirmed the suggested kubeadm patches work. My slightly modified version:
```yaml
# kubeadm-patches/kube-controller-manager+json.yaml
- op: add
  path: /spec/containers/0/command/-
  value: --bind-address=SOME_IP
- op: replace
  path: /spec/containers/0/livenessProbe/httpGet/host
  value: SOME_IP
- op: replace
  path: /spec/containers/0/startupProbe/httpGet/host
  value: SOME_IP
  
# kubeadm-patches/kube-scheduler+json.yaml
- op: add
  path: /spec/containers/0/command/-
  value: --bind-address=SOME_IP
- op: replace
  path: /spec/containers/0/livenessProbe/httpGet/host
  value: SOME_IP
- op: replace
  path: /spec/containers/0/startupProbe/httpGet/host
  value: SOME_IP
```

My small concern about patches was that they are applied to manifests. If manifests structure stability is not guaranteed, then  patches may become wrong or non-applicable. However, in this particular case a breakage is unlikely, so patches are good enough for me.
