### ISSUE TITLE
kubeadm join uses wrong ip

### ISSUE THREAD

**Issue by mrksngl** [kubernetes/kubeadm#2418]
## Is this a BUG REPORT or FEATURE REQUEST?

FEATURE REQUEST

## Versions

**kubeadm version** (use `kubeadm version`): 1.20

**Environment**:
- **Kubernetes version** (use `kubectl version`): 1.20
- **Cloud provider or hardware configuration**: VirtualBox provided by vagrant with image ubuntu/bionic64 (virtualbox, 20210319.0.0)
- **OS** (e.g. from /etc/os-release): 18.04.5 LTS (Bionic Beaver)
- **Kernel** (e.g. `uname -a`): Linux pa1 4.15.0-139-generic #143-Ubuntu SMP Tue Mar 16 01:30:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- **Others**:

## What happened?

My machines have two interfaces, `enp0s3` and `enp0s8`. The first is providing the default route, the latter is meant for communication across the machines. The latter should also be used for communication in kubernetes.
Note: my later deployment will be similar, where the machines will communicate internally in a vlan whereas the default route is provided by another interface. Thus, I don't think my scenario is too artificial.
Additionally, there is a virtual IP for load balancing the control endpoint, within the network of and reachable via `enp0s8`.

Using a proper configuration file for `kubeadm init`, it generates all certificates and configurations on the intended, internal ip, i.e. that of `enp0s8`.  
However, using `kubeadm join` on a second node (supposed to be on the control plane) fails to do so:
 - all certificates are issued on the external address of `enp0s3`
 - the `kube-apiserver.yaml` manifest has the external address as `--advertise-address` and also on all probes
 - all `/etc/kubernetes/*.conf` files use the external address
 - when bringing up `etcd`, it also advertises the wrong address, bringing the `etcd` on my first node into a failed state

## What you expected to happen?

That I could somehow specify the addresses to be used for `join`, very much as I could do for `init`.

Although I would rather expect that `kubeadm join` uses the address of the interface on which the api server endpoint (in my case, that was the virtual ip) can be reached, rather than falling back to the interface having the default route.

## How to reproduce it (as minimally and precisely as possible)?

 - Create a new master using `kubeadm init` and set its `localAPIEndpoint.advertiseAddress` to an address which is not on the network interface having the default route
 - Try to join a second node using `kubeadm join`

Below is my configuration for joining. There is also a section on `etcd` which I omitted here.
The node's internal ip (which should be used) is `192.168.3.12`, the virtual ip where the first master can be found is `192.168.3.100`.

```
apiVersion: kubeadm.k8s.io/v1beta2
kind: JoinConfiguration
nodeRegistration:
  criSocket: "unix:///var/run/crio/crio.sock"
  kubeletExtraArgs:
    node-ip: 192.168.3.12
  taints: []
controlPlane:
  localApiEndpoint:
    advertiseAddress: 192.168.3.12
    bindPort: 6443
  certificateKey: "..."
discovery:
  bootstrapToken:
    apiServerEndpoint: 192.168.3.100:6443
    token: ...
    caCertHashes:
      - ...
    unsafeSkipCAVerification: false
  timeout: 5m0s
```
