### ISSUE TITLE
how to use external etcd within kubeadm 1.6.1?

### ISSUE THREAD

**Issue by James-Dao** [kubernetes/kubeadm#243]
hi
How to use external etcd within kubeadm 1.6.1?  I found one flag within 1.5.

**Comment by Dmitry1987** [comment]
Hi @James-Dao ,  use a config file like this one for example:

```
apiVersion: kubeadm.k8s.io/v1alpha1
kind: MasterConfiguration
kubernetesVersion: v1.6.1
api:
  advertiseAddress: xx.xx.xx.xx
etcd:
  endpoints:
  - http://etcd-external.yourdomain.or.ip:2379

```
