### ISSUE TITLE
Unable to start kubeadm - GracefulNodeShutdown is not a valid feature name

### ISSUE THREAD

**Issue by avoidik** [kubernetes/kubeadm#2436]
## Is this a BUG REPORT or FEATURE REQUEST?

Choose one: BUG REPORT

Getting `GracefulNodeShutdown is not a valid feature name` error

```bash
# kubeadm init --node-name=$KUBEADM_NODE_NAME --cri-socket=$KUBEADM_SOCKET --ignore-preflight-errors=NumCPU,Mem,Swap --config kubeadm-config.yaml
featureGates: Invalid value: map[string]bool{"GracefulNodeShutdown":true}: GracefulNodeShutdown is not a valid feature name.
To see the stack trace of this error execute with --v=5 or higher
```

```yaml
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
...
featureGates:
  GracefulNodeShutdown: true
```

## Versions

**kubeadm version** (use `kubeadm version`):

```bash
# kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5", GitCommit:"6b1d87acf3c8253c123756b9e61dac642678305f", GitTreeState:"clean", BuildDate:"2021-03-18T01:08:27Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Kubernetes version** (use `kubectl version`): `v1.20.5`
- **Cloud provider or hardware configuration**: `virtualbox`
- **OS** (e.g. from /etc/os-release): `ubuntu 20.04 amd64`
- **Kernel** (e.g. `uname -a`): `5.4.0-58-generic`
- **Others**:

## What happened?

I'm trying to deploy v1.20.5 kubernetes cluster, these two options have requested me to add `GracefulNodeShutdown` feature gate

```yaml
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
...
shutdownGracePeriod: "30s"
shutdownGracePeriodCriticalPods: "10s"
```

Now I'm getting `GracefulNodeShutdown is not a valid feature name` error

## What you expected to happen?

Start deployment process

## How to reproduce it (as minimally and precisely as possible)?

```bash
kubeadm config print init-defaults --component-configs KubeletConfiguration > kubeadm-config.yaml
```

change the values as described above, run

```bash
kubeadm init --node-name=test --ignore-preflight-errors=NumCPU,Mem,Swap --config kubeadm-config.yaml
```

## Anything else we need to know?

Nope
