### ISSUE TITLE
Concise instructions needed when init cluster as schedulable

### ISSUE THREAD

**Issue by robtayl0r** [kubernetes/kubeadm#2454]
taint init config-file cluster-config initconfiguration worker master control-plane 

## BUG

It is unclear how one should initialize a cluster using kubeadm _with_ a configuration (initConfiguration) file and have the initial (control-plane/master) node be scheduleable. This seems like it would be a common use case. 

When specifying empty taints as per suggested [here](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/troubleshooting-kubeadm/#the-noderegistration-taints-field-is-omitted-when-marshalling-kubeadm-configuration) (assuming the author's use of "empty slice", the Go type, meaning empty YAML mapping), the node still has the NoSchedule taint after init:

```shell
Name:               k8s-control-centralus-preprod
Roles:              control-plane,master
Labels:             beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/os=linux
                    kubernetes.io/arch=amd64
                    kubernetes.io/hostname=k8s-control-centralus-preprod
                    kubernetes.io/os=linux
                    node-role.kubernetes.io/control-plane=
                    node-role.kubernetes.io/master=
Annotations:        kubeadm.alpha.kubernetes.io/cri-socket: unix:///var/run/containerd/containerd.sock
                    node.alpha.kubernetes.io/ttl: 0
                    volumes.kubernetes.io/controller-managed-attach-detach: true
CreationTimestamp:  Tue, 20 Apr 2021 17:45:03 +0000
Taints:             node-role.kubernetes.io/master:NoSchedule
Unschedulable:      false
```

`kubeadm init -v 4 --config=/etc/kubernetes/kubeadm.yaml`

Given the `kubeadm.yaml`  config:
```yaml
kind: InitConfiguration
apiVersion: kubeadm.k8s.io/v1beta2
bootstrapTokens:
  - groups: [system:bootstrappers:kubeadm:default-node-token]
    token: ***
    ttl: 0h # @todo: use shorter lived tokens
    usages: [signing,authentication]
nodeRegistration:
  criSocket: unix:///var/run/containerd/containerd.sock
  taints:
#  taints:
#  - effect: PreferNoSchedule
#    key: role.kubernetes.io/master
---
kind: ClusterConfiguration
apiVersion: kubeadm.k8s.io/v1beta2
dns:
  type: CoreDNS
networking:
  podSubnet: 10.244.0.0/16
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
cgroupDriver: systemd
```

## Versions

```
kubeadm/kubernetes-xenial,now 1.20.4-00 amd64 [installed,upgradable to: 1.21.0-00]
kubectl/kubernetes-xenial,now 1.20.4-00 amd64 [installed,upgradable to: 1.21.0-00]
kubelet/kubernetes-xenial,now 1.20.4-00 amd64 [installed,upgradable to: 1.21.0-00]
kubernetes-cni/kubernetes-xenial,now 0.8.7-00 amd64 [installed,automatic]

Ubuntu 18.04.5 LTS (Bionic Beaver)

Linux k8s-control-centralus-preprod 5.4.0-1040-azure #42~18.04.1-Ubuntu SMP Mon Feb 8 19:05:32 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

## What happened?

Initialized node has NoSchedule taint.

## What you expected to happen?

Initialized node taints would be empty 

## How to reproduce it (as minimally and precisely as possible)?

My config and command above. Using containerd.
