### ISSUE TITLE
the newly generated kubelet configuration file /var/lib/kubelet/config.yaml does not contain the KubeletConfiguration section content

### ISSUE THREAD

**Issue by OPSTime** [kubernetes/kubeadm#2465]
**The configuration file contains the KubeletConfiguration section**
**kubeadm join configure file:**
```
$ cat /etc/kubernetes/kubeadm.join.conf 
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
cgroupDriver: systemd
enforceNodeAllocatable:
  - pods
  - kube-reserved
systemReservedCgroup: /system.slice
kubeReservedCgroup: /system.slice/kubelet.service
# Reserve Compute Resources for System Daemons
kubeReserved: 
  cpu: '1'
  memory: 1Gi
evictionHard:
  imagefs.available: 10%
  memory.available: 5%
  nodefs.available: 10%
evictionSoft: 
  imagefs.available: 10%
  memory.available: 5%
  nodefs.available: 10%
evictionSoftGracePeriod:
  imagefs.available: 2m
  memory.available: 2m
  nodefs.available: 2m
evictionMinimumReclaim: 
  imagefs.available: 500Mi
  memory.available: 0Mi
  nodefs.available: 500Mi
evictionMaxPodGracePeriod: 30---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
mode: ipvs
---
apiVersion: kubeadm.k8s.io/v1beta2
caCertPath: /etc/kubernetes/pki/ca.crt
discovery:
  bootstrapToken:
    apiServerEndpoint: k8s-apiserver.example.com:16443
    token: otnwlz.ghjdz65vxw013wvv
    unsafeSkipCAVerification: true
  timeout: 5m0s
  tlsBootstrapToken: otnwlz.ghjdz65vxw013wvv
kind: JoinConfiguration
nodeRegistration:
  criSocket: /var/run/dockershim.sock
  name: k8s-myhome-node-06
  taints: null
```

**$ kubeadm join --config /etc/kubernetes/kubeadm.join.conf**                                         
```
[preflight] Running pre-flight checks
        [WARNING FileExisting-tc]: tc not found in system path
[preflight] Reading configuration from the cluster...
[preflight] FYI: You can look at this config file with 'kubectl -n kube-system get cm kubeadm-config -o yaml'
[kubelet-start] Writing kubelet configuration to file "/var/lib/kubelet/config.yaml"
[kubelet-start] Writing kubelet environment file with flags to file "/var/lib/kubelet/kubeadm-flags.env"
[kubelet-start] Starting the kubelet
[kubelet-start] Waiting for the kubelet to perform the TLS Bootstrap...

This node has joined the cluster:
* Certificate signing request was sent to apiserver and a response was received.
* The Kubelet was informed of the new secure connection details.

Run 'kubectl get nodes' on the control-plane to see this node join the cluster.
```

**However, the newly generated kubelet configuration file /var/lib/kubelet/config.yaml does not contain the KubeletConfiguration section content**
```
$ cat /var/lib/kubelet/config.yaml
apiVersion: kubelet.config.k8s.io/v1beta1
authentication:
  anonymous:
    enabled: false
  webhook:
    cacheTTL: 0s
    enabled: true
  x509:
    clientCAFile: /etc/kubernetes/pki/ca.crt
authorization:
  mode: Webhook
  webhook:
    cacheAuthorizedTTL: 0s
    cacheUnauthorizedTTL: 0s
cgroupDriver: systemd
clusterDNS:
- 10.220.0.10
clusterDomain: cluster.local
cpuManagerReconcilePeriod: 0s
evictionPressureTransitionPeriod: 0s
fileCheckFrequency: 0s
healthzBindAddress: 127.0.0.1
healthzPort: 10248
httpCheckFrequency: 0s
imageMinimumGCAge: 0s
kind: KubeletConfiguration
logging: {}
nodeStatusReportFrequency: 0s
nodeStatusUpdateFrequency: 0s
rotateCertificates: true
runtimeRequestTimeout: 0s
shutdownGracePeriod: 0s
shutdownGracePeriodCriticalPods: 0s
staticPodPath: /etc/kubernetes/manifests
streamingConnectionIdleTimeout: 0s
syncFrequency: 0s
volumeStatsAggPeriod: 0s
```

**Comment by fabriziopandini** [comment]
kubeadm as of today supports providing KubeletConfig only during kubeadm init, if you want to apply some kubelet specific configuration you can use kubeletextra args in `Joinconfiguration.nodeRegistration.kubeletExtraArgs`. 
See 
- https://pkg.go.dev/k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/v1beta2 
- https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-join/#config-file
for more info

/close

**Comment by OPSTime** [comment]
Is there a complete and correct example?
I failed to test the following configurations，can not achieve the desired effect.

1:
```
---
apiVersion: kubeadm.k8s.io/v1beta2
caCertPath: /etc/kubernetes/pki/ca.crt
discovery:
  bootstrapToken:
    apiServerEndpoint: k8s-apiserver.example.com:16443
    token: otnwlz.ghjdz65vxw013wvv
    unsafeSkipCAVerification: true
  timeout: 5m0s
  tlsBootstrapToken: otnwlz.ghjdz65vxw013wvv
kind: JoinConfiguration
JoinConfiguration:
#NodeRegistrationOptions:
  nodeRegistration:
    criSocket: /var/run/dockershim.sock
    name: k8s-myhome-node-06
    taints: null
    kubeletExtraArgs:
      - "--cgroup-driver=systemd"
      - "--enforce-node-allocatable=pods,kube-reserved"
      - "--kube-reserved-cgroup=/system.slice/kubelet.service"
      - "--system-reserved-cgroup=/system.slice"
      - "--kube-reserved=cpu=1,memory=2Gi"
```

2:
```
apiVersion: kubeadm.k8s.io/v1beta2
caCertPath: /etc/kubernetes/pki/ca.crt
discovery:
  bootstrapToken:
    apiServerEndpoint: k8s-apiserver.ops.owhat.com.cn:16443
    token: otnwlz.ghjdz65vxw013wvv
    unsafeSkipCAVerification: true
  timeout: 5m0s
  tlsBootstrapToken: otnwlz.ghjdz65vxw013wvv
kind: JoinConfiguration
nodeRegistration:
  criSocket: /var/run/dockershim.sock
  name: k8s-myhome-node-06
  taints: null
  kubeletExtraArgs:
    cgroupDriver: systemd
    enforceNodeAllocatable:
      - pods
      - kube-reserved
    systemReservedCgroup: /system.slice
    kubeReservedCgroup: /system.slice/kubelet.service
    # Reserve Compute Resources for System Daemons
    kubeReserved: 
      cpu: "1"
      memory: 1Gi
    evictionHard:
      imagefs.available: 10%
      memory.available: 5%
      nodefs.available: 10%
    evictionSoft: 
      imagefs.available: 10%
      memory.available: 5%
      nodefs.available: 10%
    evictionSoftGracePeriod:
      imagefs.available: 2m
      memory.available: 2m
      nodefs.available: 2m
    evictionMinimumReclaim: 
      imagefs.available: 500Mi
      memory.available: 0Mi
      nodefs.available: 500Mi
    evictionMaxPodGracePeriod: 30
    mode: ipvs
```
