### ISSUE TITLE
ETCD Bind to DNS-Name instead of IP

### ISSUE THREAD

**Issue by Lemonn** [kubernetes/kubeadm#2506]
## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT

## Versions

**kubeadm version**:

kubeadm version: &version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:17:27Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Kubernetes version**:
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:25:06Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}

- **Cloud provider or hardware configuration**:
Bare-Metal 
- **OS**:
Ubuntu 20.04
- **Kernel**:
Linux server3 5.4.0-67-generic #75-Ubuntu SMP Fri Feb 19 18:03:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

## What happened?

During the process of setting up an HA-Cluster (internal ETCD cluster managed by Kubeadm) on three servers, each with multiple network interfaces (Public-IP, VLAN-Alias), everything went fine. But after blocking the ports on the first interface (Public-IP), I noticed that ETCD is no longer able to communicate whit the other Cluster-Members. A look at the open Ports revealed that ETCD binds to the Public-IP, instead of binding to the VLAN-IP. As loadbalancer, Keepalived and HA-Proxy is used, both run on all three servers. The load-balancing is done over the VLAN-Interface whit the floating IP 172.25.01 and the DNS-Name loadbalancer.cluster.

To work around this I tried to change the config file in `/etc/kubernetes/manifests/etcd.yaml`, to the IP of the VLAN-Interface, but this resulted in another Problem, the certificate was only valid for the external IP, not the VLAN-IP (Cert-SANs: localhost, server2 [hostname of the server], IP-Adress: 95.x.x.176 (External IP), IP-Adress: 127.0.0.1, Adress: 0:0:0:0:0:0:0:1). To work around this, I tried to use a DNS-Name which was Part of the certificate, instead. But this wasn't successful either. It seems that ETCD does not support DNS-Names in the configuration, but I'm not sure about this.
My next approach was to apply the solution from https://github.com/kubernetes/kubeadm/issues/786#issuecomment-387545581, but these options were ignored as the cert still only contained the default values (Cert-SANs: localhost, server2 [hostname of the server], IP-Adress: 95.x.x.176, IP-Adress: 127.0.0.1, Adress: 0:0:0:0:0:0:0:1).

As the last approach, I tried to submit the following flags on the init process and on each master join `--apiserver-bind-port 6444 --apiserver-advertise-address=172.25.0.4 (On each server the IP of the VLAN-Interface)`. This resulted in a Working Cluster, as ETCD binds to the IP submitted in apiserver-advertise-address. This also resulted in the fact, that the IP which was submitted, was used in the certificate SANs.

The cluster works kind of, but Calico reports the following error from time to time  `Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create pod network sandbox example-deployment-b6c678db5-jfph6_default_d60289c8-6705-406b-af4f-970ca2cc1c63_0(4ae4abcdf08ff8d30d8e7387927d6bcc1f8bac1ec4e26895d2beed45f87baf8b): error getting ClusterInformation: Get "https://[192.168.0.1]:443/apis/crd.projectcalico.org/v1/clusterinformations/default": dial tcp 192.168.0.1:443: i/o timeout`. My guess is that this is due to the fact that the IP from `kubeadm join loadbalancer.cluster:6443`
and `apiserver-advertise-address`, which points to the IP of the VLAN-Interface-IP on each server, are different.

This only affects the Communication of ETCD, the other Communication seems to work as expected over the local network, as the process of joining another master to the cluster gets stuck at ETCD synch.

## What you expected to happen?

It should be possible to select on which IP/DNS-Name ETCD binds to independent of the `apiserver-advertise-address` value (or bind to all IPs), furthermore, the config values as described in https://github.com/kubernetes/kubeadm/issues/786#issuecomment-387545581 should be recognized, to allow the manual edit of the ETCD config without the need to manually create new certificate's.

## How to reproduce it (as minimally and precisely as possible)?
-

### Init Command:

loadbalancer.cluster resolves to 172.25.0.1

`sudo kubeadm init --control-plane-endpoint=loadbalancer.cluster:6443 --apiserver-bind-port 6444 --pod-network-cidr=192.168.0.0/16 --upload-certs --config=config.yaml`

### Kubeadm Config

```yaml
apiVersion: kubeadm.k8s.io/v1beta2
bootstrapTokens:
  - groups:
      - system:bootstrappers:kubeadm:default-node-token
    token: abcdef.0123456789abcdef
    ttl: 24h0m0s
    usages:
      - signing
      - authentication
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: 172.25.0.2
  bindPort: 6444
nodeRegistration:
  criSocket: unix:///var/run/crio/crio.sock
  name: server1
  taints: null
---
apiServer:
  timeoutForControlPlane: 4m0s
apiVersion: kubeadm.k8s.io/v1beta2
certificatesDir: /etc/kubernetes/pki
clusterName: kubernetes
controllerManager: {}
dns:
  type: CoreDNS
etcd:
  serverCertSANs:
    - 172.25.0.1
    - 172.25.0.2
    - 172.25.0.3
    - 172.25.0.4
    - server1
    - server2
    - server3
    - server1.cluster
    - server2.cluster
    - server3.cluster
    - loadbalancer.cluster
  peerCertSANs:
    - 172.25.0.1
    - 172.25.0.2
    - 172.25.0.3
    - 172.25.0.4
    - server1
    - server2
    - server3
    - server1.cluster
    - server2.cluster
    - server3.cluster
    - loadbalancer.cluster
imageRepository: k8s.gcr.io
kind: ClusterConfiguration
controlPlaneEndpoint: loadbalancer.cluster:6444
kubernetesVersion: 1.21.0
networking:
  dnsDomain: cluster.local
  serviceSubnet: 192.168.0.0/16
scheduler: {}
cgroupDriver: systemd
---
apiVersion: kubelet.config.k8s.io/v1beta1
authentication:
  anonymous:
    enabled: false
  webhook:
    cacheTTL: 0s
    enabled: true
  x509:
    clientCAFile: /etc/kubernetes/pki/ca.crt
authorization:
  mode: Webhook
  webhook:
    cacheAuthorizedTTL: 0s
    cacheUnauthorizedTTL: 0s
clusterDNS:
  - 192.168.0.10
clusterDomain: cluster.local
cpuManagerReconcilePeriod: 0s
evictionPressureTransitionPeriod: 0s
fileCheckFrequency: 0s
healthzBindAddress: 127.0.0.1
healthzPort: 10248
httpCheckFrequency: 0s
imageMinimumGCAge: 0s
kind: KubeletConfiguration
logging: {}
nodeStatusReportFrequency: 0s
nodeStatusUpdateFrequency: 0s
resolvConf: /run/systemd/resolve/resolv.conf
rotateCertificates: true
runtimeRequestTimeout: 0s
shutdownGracePeriod: 0s
shutdownGracePeriodCriticalPods: 0s
staticPodPath: /etc/kubernetes/manifests
streamingConnectionIdleTimeout: 0s
syncFrequency: 0s
volumeStatsAggPeriod: 0s
```

###  Network config of one of the servers, all other servers have the same interfaces
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: enp35s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether a8:a1:59:2f:f5:1e brd ff:ff:ff:ff:ff:ff
    inet 95.x.x.176/32 scope global enp35s0
       valid_lft forever preferred_lft forever
    inet6 xxxx:xxx:xx:xxxx::2/64 scope global 
       valid_lft forever preferred_lft forever
    inet6 xxxx:xxx:xx:xxxx::f51e/64 scope link 
       valid_lft forever preferred_lft forever
3: cluster_vlan1@enp35s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1400 qdisc noqueue state UP group default qlen 1000
    link/ether a8:a1:59:2f:f5:1e brd ff:ff:ff:ff:ff:ff
    inet 172.25.0.4/24 brd 172.25.0.255 scope global cluster_vlan1
       valid_lft forever preferred_lft forever
    inet6 fe80::aaa1:59ff:fe2f:f51e/64 scope link 
       valid_lft forever preferred_lft forever
```
