### ISSUE TITLE
master join error "need /etc/kubernetes/pki/ca.crt file"

### ISSUE THREAD

**Issue by denghuancong** [kubernetes/kubeadm#2514]
## Versions

**kubeadm version** (use `kubeadm version`):
kubeadm version: &version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:25:59Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Kubernetes version** (use `kubectl version`):  v1.20.2
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):  centos 7.4
- **Kernel** (e.g. `uname -a`):  linux 4.1.0-25.el7
- **Others**: 

## master init config
- I using cmd :  kubeadm init --upload-certs --config="/root/deploy/kubeadm.yaml" to init master, using config as following:
```
apiVersion: kubeadm.k8s.io/v1beta2
kind: InitConfiguration
bootstrapTokens:
- groups:
  - system:bootstrappers:kubeadm:default-node-token
  token: xxx
  ttl: "0"
  usages:
  - signing
  - authentication
localAPIEndpoint:
  advertiseAddress: 10.0.0.14
  bindPort: 6443
nodeRegistration:
  criSocket: /var/run/containerd/containerd.sock
  name: 10.0.0.14
certificateKey: certificateKeyxxxx
---
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
imageRepository: 172.31.0.5:5000
kubernetesVersion: v1.20.2
networking:
  dnsDomain: cluster.local
  serviceSubnet: "172.16.0.0/16"
  podSubnet: "192.168.0.0/16"
apiServer:
  certSANs:
    - 192.168.177.190
controlPlaneEndpoint: "10.0.0.13:6443"
scheduler:
  extraArgs:
     bind-address: "0.0.0.0"
     port: "10251"
clusterName: "xxxm.k8s.cluster"
etcd:
    local:
      extraArgs:
        listen-metrics-urls: "http://0.0.0.0:2381"
---
```

## What happened?
kubeadm join master using configfile error, print out the following:
```
I0623 19:09:03.722257  180859 preflight.go:101] [preflight] Running configuration dependant checks

One or more conditions for hosting a new control plane instance is not satisfied.

failure loading certificate for CA: couldn't load the certificate file /etc/kubernetes/pki/ca.crt: open /etc/kubernetes/pki/ca.crt: no such file or directory
```

the config file as following:
```
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
controlPlaneEndpoint: "10.0.0.13:6443"
certificateKey: certificateKeyxxxx
---
apiVersion: kubeadm.k8s.io/v1beta1
kind: JoinConfiguration
discovery:
  bootstrapToken:
    apiServerEndpoint: 10.0.0.13:6443
    token:  xxxxxxx
    unsafeSkipCAVerification: true
controlPlane:
  certificateKey: certificateKeyxxxx
  localAPIEndpoint:
    advertiseAddress: 10.0.0.15
    bindPort: 6443
nodeRegistration:
  kubeletExtraArgs:
    cloud-provider: external
    provider-id: xxxxk://cn//vm-xIOB0rg7R
  name: 10.0.0.15
  criSocket: /var/run/containerd/containerd.sock
```

- the certificateKey and token is currect,  I join one work node into the cluster success , and I using the following config :
```
apiVersion: kubeadm.k8s.io/v1beta1
kind: JoinConfiguration
discovery:
  bootstrapToken:
    apiServerEndpoint: 10.0.0.13:6443
    token: xxxx
    unsafeSkipCAVerification: true
nodeRegistration:
  kubeletExtraArgs:
    cloud-provider: external
    provider-id: xxx://cn//vm-411f09gnR
  name: 10.0.0.17
  criSocket: /var/run/containerd/containerd.sock
```

I check the kubeadm code, it run failed at /k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/join/preflight.go:114 , the func check join params:
```
		hasCertificateKey := len(j.CertificateKey()) > 0
		if err := checkIfReadyForAdditionalControlPlane(&initCfg.ClusterConfiguration, hasCertificateKey); err != nil {
			// outputs the not ready for hosting a new control plane instance message
			ctx := map[string]string{
				"Error": err.Error(),
			}

			var msg bytes.Buffer
			notReadyToJoinControlPlaneTemp.Execute(&msg, ctx)
			return errors.New(msg.String())
		}
```

- lb address : 10.0.0.13
- master a 10.0.0.14, inited master.
- master b: 10.0.0.15 that I want to join to the cluster
- work node a: 10.0.0.17 aleardy join the cluster

I want to ask , where is wrong of the config?
