### ISSUE TITLE
Add custom annotations to static pod manifests

### ISSUE THREAD

**Issue by F1ko** [kubernetes/kubeadm#2568]
## Is this a BUG REPORT or FEATURE REQUEST?

Choose one: ~~BUG REPORT or~~ FEATURE REQUEST

## Versions

**kubeadm version** (use `kubeadm version`):
```shell
$ kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.4", GitCommit:"3cce4a82b44f032d0cd1a1790e6d2f5a55d20aae", GitTreeState:"clean", BuildDate:"2021-08-11T18:14:53Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
```

## What happened?

`ClusterConfiguration` does currently not support adding custom annotations to static pod manifests.

## What you expected to happen?

I expect `ClusterConfiguration` to have an option for additional Pod annotations, something similar to:
```yaml
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
clusterName: my-amazing-cluster
kubernetesVersion: v1.21.4
etcd:
  local:
    imageTag: 3.4.13-0
    annotations:
      foo: bar
```

After executing `kubeadm init phase etcd local --config <file>` this should result in something like:
```yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubeadm.kubernetes.io/etcd.advertise-client-urls: xyz
    foo: bar
  creationTimestamp: null
  labels:
    component: etcd
    tier: control-plane
  name: etcd
  namespace: kube-system
[...]
```

The same may also be useful for labels.

## Anything else we need to know?

This should not only be possible for `etcd` but for all static pod manifests created by `kubeadm`.
The reason this feature comes in handy is because annotations and/or labels can be used as a discovery mechanism by third-party tools (e.g. metrics).
