### ISSUE TITLE
Kubeadm Init Phase including vSphere provider and control plane endpoint.

### ISSUE THREAD

**Issue by mprzygrodzki** [kubernetes/kubeadm#2573]
Hello everyone - i didn't find any suitable solution how to resolve my problem on init phase, so that's why i'm writing here. In the past i've used to initialize K8s by specifying config for vSphere provider to be able to used persistent volumes in local setup in VMware host. Right now I need to setup cluster where I will specify vSphere provider and control-plane-endpoint specified as a domain name. After several checks and searches through browser I didnt find solution to add this in config file. My example config file looks like this:

```
apiVersion: kubeadm.k8s.io/v1beta2
bootstrapTokens:
- groups:
  - system:bootstrappers:kubeadm:default-node-token
  token: y7yaev.9dvwxx6ny4ef8vlq
  ttl: 0s
  usages:
  - signing
  - authentication
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: 192.168.0.100
  bindPort: 6443
nodeRegistration:
  criSocket: /var/run/dockershim.sock
  name: k8s-node
  taints: null
  kubeletExtraArgs:
    cloud-config: /etc/kubernetes/vsphere.conf
    cloud-provider: vsphere
  name: bc-k8s-master-01
  taints:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
---
apiServer:
  extraArgs:
    cloud-config: /etc/kubernetes/vsphere.conf
    cloud-provider: vsphere
  extraVolumes:
  - hostPath: /etc/kubernetes/vsphere.conf
    mountPath: /etc/kubernetes/vsphere.conf
    name: cloud
  timeoutForControlPlane: 4m0s
apiVersion: kubeadm.k8s.io/v1beta2
certificatesDir: /etc/kubernetes/pki
clusterName: k8s-malogoszcz
controllerManager:
  extraArgs:
    cloud-config: /etc/kubernetes/vsphere.conf
    cloud-provider: vsphere
  extraVolumes:
  - hostPath: /etc/kubernetes/vsphere.conf
    mountPath: /etc/kubernetes/vsphere.conf
    name: cloud
dns:
  type: CoreDNS
etcd:
  local:
    dataDir: /var/lib/etcd
imageRepository: k8s.gcr.io
kind: ClusterConfiguration
kubernetesVersion: 1.21.0
networking:
  dnsDomain: cluster.local
  podSubnet: 10.244.0.0/16
  serviceSubnet: 10.96.0.0/12
scheduler: {}
```
(edit by neolit123 - formatting)

## Versions

**kubeadm version** (use `kubeadm version`): 1.21.5

**Environment**:
- **Kubernetes version** (use `kubectl version`):1.21
- **Cloud provider or hardware configuration**: VMware 
- **OS** (e.g. from /etc/os-release): Ubuntu 20.04 Server

## What you expected to happen?

Need an advice how to run kubeadm init phase with vSphere provider specified as some kubelet extra args like this:

`kubeadm init \
  --pod-network-cidr=10.0.0.0/16 \
  --control-plane-endpoint=k8s-cluster.mycompany.com
  -- ... `
  
Or if its possible add control plane endpoint to config file (I believe this approach isn't possible).
