### ISSUE TITLE
`config print init-defaults` emits wrong nodeRegistration.criSocket

### ISSUE THREAD

**Issue by dilyanpalauzov** [kubernetes/kubeadm#2585]
My understanding for the kubeadm init --config=file workflow is:

• The config file is generated by running `kubeadm config print init-defaults`
• The file is modified
• Then `kubeadm init --config=file` is called

I use cri-o and I have no docker.  `kubeadm config print init-defaults` emits

```
apiVersion: kubeadm.k8s.io/v1beta3 
kind: InitConfiguration
nodeRegistration:
  criSocket: /var/run/dockershim.sock
  imagePullPolicy: IfNotPresent
  name: node
  taints: null

```
When I run `kubeadm init --config=file`, the output is:

```
[preflight] WARNING: Couldn't create the interface used for talking to the container runtime: docker is required for container runtime: exec: "docker": executable file not found in $PATH
        [WARNING Hostname]: hostname "node" could not be reached
        [WARNING Hostname]: hostname "node": lookup node on 127.0.0.53:53: server misbehaving
```

When I instead just run `kubeadm init` the above warnings do not appear.

* Alter `kubeadm config print init-defaults` to emit the defaults, that would be applied, if no `--config=file` is applied.  This means printing the correct/detected `criSocket:` and `name:` under `nodeRegistration:`
* or do not emit `criSocket:` and `name:`. on `kubeadm print init-defaults` under `nodeRegistration`

## Is this a BUG REPORT or FEATURE REQUEST?

This is subjective.

## Versions

kubeadm version: &version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.3-rc.0.12+2c0e4a232a3c10", GitCommit:"2c0e4a232a3c10a9083012ec28a3622bd4e4be90", GitTreeState:"clean", BuildDate:"2021-09-25T19:32:20Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
