### ISSUE TITLE
Cleanup IPVS / iptables rules during `kubeadm reset`

### ISSUE THREAD

**Issue by dilyanpalauzov** [kubernetes/kubeadm#2587]
Calling `kubeadm init && kubeadm reset` prints:

```
The reset process does not reset or clean up iptables rules or IPVS tables.
If you wish to reset iptables, you must do so manually by using the "iptables" command.

If your cluster was setup to utilize IPVS, run ipvsadm --clear (or similar)
to reset your system's IPVS tables.
```

Since [kube-proxy --cleanup](https://kubernetes.io/docs/reference/command-line-tools-reference/kube-proxy/) is supposed to cleanup these things, `kubeadm reset` shall just call `kube-proxy --cleanup`.

**Comment by aojea** [comment]
> do you happen to know more about this `--cleanup` flag?

kube-proxy creates the iptables rules in the host namespace,  it runs as host-network and mount the required path to use iptables
```
        image: k8s.gcr.io/kube-proxy:v1.22.1
        imagePullPolicy: IfNotPresent
        name: kube-proxy
        resources: {}
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/kube-proxy
          name: kube-proxy
        - mountPath: /run/xtables.lock
          name: xtables-lock
        - mountPath: /lib/modules
          name: lib-modules
          readOnly: true
      dnsPolicy: ClusterFirst
      hostNetwork: true
```

> also i'm pretty sure that the kubelet adds iptables rules too? which means the kube-proxy only cleanup would be incomplete.

that flag deletes the kube-proxy rules, indeed kubelet adds rules too.

> making kubeadm reset exec into the right kube-proxy pod for that particular node also seems very hacky.

indeed, these things are not simple, but one could argue that if you want to start from scratch if could be legit to ask to reset the whole iptables rules,
