### ISSUE TITLE
node-ip is not utilized on all control-plane nodes

### ISSUE THREAD

**Issue by cortex3** [kubernetes/kubeadm#2595]
## Is this a BUG REPORT or FEATURE REQUEST?
I'm actually unsure

## Versions
**kubeadm version**: v1.21.4
**Environment**:
- **Kubernetes version**: v1.21.4
- **Cloud provider or hardware configuration**: baremetal
- **OS**: Ubuntu 20.04
- **Kernel** : 5.4.0

## What happened?
when creating a HA stacked etcd cluster with kubeadm using node-ip the first control-plane node will utilize node-ip while the other nodes will ignore the parameter.

## What you expected to happen?
For a clean cluster formation I would expect node-ip to be utilized on all nodes.

## How to reproduce it (as minimally and precisely as possible)?
build a HA stacked etcd cluster with a different IP address using node-ip. 
I supplied the following to the first node:
```
apiVersion: kubeadm.k8s.io/v1beta2
kind: InitConfiguration
nodeRegistration:
  kubeletExtraArgs:
    node-ip: "{{ kubernetes_address }}"
localAPIEndpoint:
  advertiseAddress: "{{ kubernetes_address }}"
```

and this to the other control-plane nodes:
```
apiVersion: kubeadm.k8s.io/v1beta2
kind: JoinConfiguration
nodeRegistration:
  kubeletExtraArgs:
    node-ip: "{{ kubernetes_address }}"
```
