### ISSUE TITLE
etcd manifest isn't created

### ISSUE THREAD

**Issue by kbreit** [kubernetes/kubeadm#2596]
## What keywords did you search in kubeadm issues before filing this one?

etcd, listen-metrics-urls, and extraargs

## Is this a BUG REPORT or FEATURE REQUEST?

Choose one: BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`): kubeadm version: &version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:25:59Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Kubernetes version** (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:31:32Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:20:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```
- **Cloud provider or hardware configuration**: ClusterAPI vSphere
- **OS** (e.g. from /etc/os-release):
```
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```
- **Kernel** (e.g. `uname -a`): `Linux test-kubeadm-control-plane-jj5jq 5.4.0-73-generic #82-Ubuntu SMP Wed Apr 14 17:39:42 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
- **Others**:

## What happened?
When I try to pass listen-metrics-urls to etcd via ClusterAPI vSphere it isn't creating the etcd static manifest and sometimes doesn't create any static pod manifests. This was reported at https://github.com/kubernetes-sigs/cluster-api/issues/5564 and was recommended I create an issue here.

## What you expected to happen?

I expected the `/etc/kubernetes/manifests/etcd.yaml` file to be created with the `--listen-metrics-urls` argument.

## How to reproduce it (as minimally and precisely as possible)?

Create CAPI cluster with the following settings:

```
apiVersion: controlplane.cluster.x-k8s.io/v1alpha4
kind: KubeadmControlPlane
metadata:
  name: {{ .Values.cluster.fullName }}-kubeadm-control-plane
spec:
  machineTemplate:
    infrastructureRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
      kind: VSphereMachineTemplate
      name: {{ .Values.cluster.fullName }}-control-plane-machine-template-{{ .Values.cluster.version }}
  kubeadmConfigSpec:
    clusterConfiguration:
      etcd:
        local:
          extraArgs:
            listen-metrics-urls: http://0.0.0.0:2381
```

## Anything else we need to know?
Noteworthy error from `cloud-init-output.log`:

`[2021-11-02 14:42:31] error execution phase control-plane-join/etcd: error creating local etcd static pod manifest file: etcdserver: unhealthy cluster`

```
root@test-kubeadm-control-plane-jj5jq:/run/kubeadm# cat kubeadm-join-config.yaml
apiVersion: kubeadm.k8s.io/v1beta2
controlPlane:
  localAPIEndpoint: {}
discovery:
  bootstrapToken:
    apiServerEndpoint: 10.207.62.213:6443
    caCertHashes:
    - sha256:ad79326b92955d3cde8ba9ae5698ecf41c6d4816bbdab2a26c05f5d2058fa2ee
    token: <sanitized>
kind: JoinConfiguration
nodeRegistration:
  criSocket: /var/run/containerd/containerd.sock
  kubeletExtraArgs:
    cloud-provider: external
  name: 'test-kubeadm-control-plane-jj5jq'
```
