### ISSUE TITLE
add extra parameters to support changing etcd default ports

### ISSUE THREAD

**Issue by Tendrun101** [kubernetes/kubeadm#2602]
## Versions

**kubeadm version** (use `kubeadm version`): 1.18.15

**Environment**:
- **Kubernetes version** (use `kubectl version`): 1.18.15
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Others**:

## What happened?
kubeadm deploy my k8s cluster，the ports of new etcd cluster  conflict with another existing etcd cluster。

## What you expected to happen?
If we have some hosts，there is an etcd cluster of another team on them。The etcd cluster of another team  uses ports： 2379 2380 2381. So our k8s cluster cannot be deployed.   Shall we add some extra parameter to change the default ports, so we can use other ports, not only 2379 2380 2381

**Comment by RA489** [comment]
/retitle add extra parameters to support changing etcd default ports

**Comment by neolit123** [comment]
hi, i don't think the kubeadm project will be in favor of this change due to the complexity of how stacked etcd (co-located etcd members on apiserver hosts) is designed. allowing a port to be passed similarly to etcd.local.dataDir will be much more difficult to propagate in the code base.

also, running multiple instances of etcd on the same host sounds like a bad idea. you need to make sure they don't write to the same data directory or share certificates.

to achieve what you want today you can used kubeadm's external etcd mode.

you can pass something like this to kubeadm init:
```
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
etcd:
    external:
        endpoints:
        - https://ETCD_0_IP:CUSTOM_PORT
        caFile: /etc/kubernetes/pki/etcd/ca.crt
        certFile: /etc/kubernetes/pki/apiserver-etcd-client.crt
        keyFile: /etc/kubernetes/pki/apiserver-etcd-client.key
```

these links should give you more information:

https://serverfault.com/questions/1002323/include-own-external-etcd-cluster-in-kubeadm-init
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/high-availability/
https://pkg.go.dev/k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/v1beta3
