### ISSUE TITLE
[FR] `kubeadm join --config` should accept a `.dockerconfigjson` as a `JoinConfiguration` parameter (and fail if it doesn't work)

### ISSUE THREAD

**Issue by brianthelion** [kubernetes/kubeadm#2617]
## Is this a BUG REPORT or FEATURE REQUEST?

FEATURE REQUEST

When using a private registry, `kubeadm join` is currently not sufficient to bootstrap a kubelet. Additional out-of-band steps are required to install registry secrets and log in to the registry. These steps *should* be handled by `kubeadm`, where the `.dockerconfigjson` is delivered in-line with the rest of the `JoinConfiguration`.

Ideally, the kubelet service would report on its ability log in to the target registry, and die in the event of failed login.

This proposed feature is important for preempting tedious image pull failures that could be caught MUCH earlier in the kubelet lifecycle.

## Versions

**kubeadm version** (use `kubeadm version`): 

```
kubeadm version: &version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:47:19Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Kubernetes version** (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:48:33Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-21T23:01:33Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
```
- **Cloud provider or hardware configuration**: bare metal
- **OS** (e.g. from /etc/os-release): 

```NAME="Ubuntu"
VERSION="20.10 (Groovy Gorilla)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.10"
VERSION_ID="20.10"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
```

- **Kernel** (e.g. `uname -a`): `Linux sever 5.13.4-051304-generic #202107201535 SMP Tue Jul 20 16:05:33 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

- **Others**:

**Comment by fabriziopandini** [comment]
I'm personally -1; kubeadm should be agnostic from the CRI in use, but let's hear other opinions

**Comment by brianthelion** [comment]
@neolit123 @fabriziopandini The issue of bootstrapping private registry credentials presumably exists regardless of the user's choice of CRI, no?

**Comment by neolit123** [comment]
The issue exists but the abstaction in kubeadm to support the different CR
setup for credentials is not something that we'd like to maintain.

**Comment by brianthelion** [comment]
@neolit123 Certainly there is some compromise here that both (1) minimizes the burden of support for `kubeadm` but also (2) dramatically increases utility for the users who depend on private registries.

One candidate would be a simple scripting interface added to the `JoinConfiguration` as follows:

```yaml
apiVersion: ...
kind: JoinConfiguration
discovery:
  bootstrapToken:
    apiServerEndpoint: ...
    token: ...
    caCertHashes:
      - sha256:...
nodeRegistration:
  name: ...
daemonScripts: |
  set -e
  curl -o ${KUBELET_CREDENTIALS_DIR}/foo.json https://foo.com/user/dockerconfig.json
  REGISTRY=$(jq -r .... ${DAEMON_CREDENTIALS_DIR}/foo.json)
  docker login ${REGISTRY}
```

The main challenge with this approach would be providing a set of environment variables (in this case represented by `KUBELET_CREDENTIALS_DIR`) to cover the possible use cases.

Thoughts?
