### ISSUE TITLE
kubeadm pull images from private (cache/remote) repository, pointing to k8s.gcr.io

### ISSUE THREAD

**Issue by zenhighzer** [kubernetes/kubeadm#2627]
Hi there, 

hope you can help me. After doing some research I still can´t find the right place for a cool solution. 
I try to setup a "remote-repository" for caching k8s-images (with jfrog artifactory), called arti.mydomain.net:8082/k8s-remote-cache (pointing to k8s.gcr.io)

```
kubeadm config images pull --image-repository arti.mydomain.net:8082/k8s-remote-cache:  

arti.mydomain.net:8082/k8s-remote-cache/kube-apiserver:v1.23.0		- OK
arti.mydomain.net:8082/k8s-remote-cache/kube-controller-manager:v1.23.0	- OK
arti.mydomain.net:8082/k8s-remote-cache/kube-scheduler:v1.23.0		- OK
arti.mydomain.net:8082/k8s-remote-cache/kube-proxy:v1.23.0		- OK
arti.mydomain.net:8082/k8s-remote-cache/pause:3.6			- OK
arti.mydomain.net:8082/k8s-remote-cache/etcd:3.5.1-0			- OK
arti.mydomain.net:8082/k8s-remote-cache/coredns:v1.8.6 			- FAILS, because kubeadm requests arti.mydomain.net:8082/k8s-remote-cache/coredns:v1.8.6, unfortunately not arti.mydomain.net:8082/k8s-remote-cache/COREDNS/coredns:v1.8.6 like in the default k8s.gcr.io-repository
```

Workaround - pulling/tagging/pushing to local repo called arti.mydomain.net:8082/k8s-local: 

```
Get list of images: 
kubeadm config images list

k8s.gcr.io/kube-apiserver:v1.23.0
k8s.gcr.io/kube-controller-manager:v1.23.0
k8s.gcr.io/kube-scheduler:v1.23.0
k8s.gcr.io/kube-proxy:v1.23.0
k8s.gcr.io/pause:3.6
k8s.gcr.io/etcd:3.5.1-0
k8s.gcr.io/coredns/coredns:v1.8.6
```

Now for every Image:

```
docker pull k8s.gcr.io/kube-apiserver:v1.23.0 
docker tag k8s.gcr.io/kube-apiserver:v1.23.0 arti.mydomain.net:8082/k8s-local/kube-apiserver:v1.23.0 
docker push arti.mydomain.net:8082/k8s-local/kube-apiserver:v1.23.0 

[...]
```

Last but not least: the "problem Image" / removing sub-path "coredns": 

```
docker pull k8s.gcr.io/coredns/coredns:v1.8.6
docker tag k8s.gcr.io/coredns/coredns:v1.8.6 arti.mydomain.net:8082/k8s-local/coredns:v1.8.6
docker push arti.mydomain.net:8082/k8s-local/coredns:v1.8.6
```

With 
`kubeadm config images pull --image-repository arti.mydomain.net:8082/k8s-local `
Now kubeadm can find all requested images at the right place

I just wonder if there is a smarter solution for this? I also checked https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-config/ but I can´t find any propper solution for my problem

Wish you a nice weekend, stay healthy and best regards

**Comment by neolit123** [comment]
Hi, i think you have the right solution.
Unfortunately the coredns image is special and has a subpath at gcr but not in private repositories.

We mention it in the links here
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/#preparing-the-required-container-images

You can use 'kubeadm config images list --image-repository ...' to know where to push.
You can also change the coredns image path with config.

/kind support

**Comment by zenhighzer** [comment]
Hey @neolit123, 

thank you for your reply. I also read through https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/#preparing-the-required-container-images, but I still have no clue how to set the coredns image path

So far i tried:

```
kubeadm config print  init-defaults

apiVersion: kubeadm.k8s.io/v1beta3
bootstrapTokens:
- groups:
  - system:bootstrappers:kubeadm:default-node-token
  token: abcdef.0123456789abcdef
  ttl: 24h0m0s
  usages:
  - signing
  - authentication
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: 1.2.3.4
  bindPort: 6443
nodeRegistration:
  criSocket: /var/run/dockershim.sock
  imagePullPolicy: IfNotPresent
  name: node
  taints: null
---
apiServer:
  timeoutForControlPlane: 4m0s
apiVersion: kubeadm.k8s.io/v1beta3
certificatesDir: /etc/kubernetes/pki
clusterName: kubernetes
controllerManager: {}
dns: {}
etcd:
  local:
    dataDir: /var/lib/etcd
imageRepository: k8s.gcr.io
kind: ClusterConfiguration
kubernetesVersion: 1.23.0
networking:
  dnsDomain: cluster.local
  serviceSubnet: 10.96.0.0/12
scheduler: {}
```

In this config I could change 

`imageRepository: k8s.gcr.io`

to 

`imageRepository: arti.mydomain.net:8082/k8s-remote-cache`

But how can I specify "coredns image path with config" like you mentioned before? 
Thank you very much for your help and Best Regards! :-)

**Comment by zenhighzer** [comment]
Hi again, 

i think i got it now: 

first create config with: 

`kubeadm config print  init-defaults > kubeadm_config.yaml` 

then modify kubeadm_config.yaml like this: 

```
apiVersion: kubeadm.k8s.io/v1beta3
bootstrapTokens:
- groups:
  - system:bootstrappers:kubeadm:default-node-token
  token: abcdef.0123456789abcdef
  ttl: 24h0m0s
  usages:
  - signing
  - authentication
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: 1.2.3.4
  bindPort: 6443
nodeRegistration:
  criSocket: /var/run/dockershim.sock
  imagePullPolicy: IfNotPresent
  name: node
  taints: null
---
apiServer:
  timeoutForControlPlane: 4m0s
apiVersion: kubeadm.k8s.io/v1beta3
certificatesDir: /etc/kubernetes/pki
clusterName: kubernetes
controllerManager: {}
dns: {imageRepository: arti.mydomain.net:8082/k8s-remote-cache/coredns}
etcd:
  local:
    dataDir: /var/lib/etcd
imageRepository: arti.mydomain.net:8082/k8s-remote-cache/k8s
kind: ClusterConfiguration
kubernetesVersion: 1.23.0
networking:
  dnsDomain: cluster.local
  serviceSubnet: 10.96.0.0/12
scheduler: {}
```

finally pulling with following command seems to work:
`kubeadm config images pull --config kubeadm_config.yaml`
