### ISSUE TITLE
CoreDNS image cannot be pulled when use --image-repository

### ISSUE THREAD

**Issue by fanglijun** [kubernetes/kubeadm#2714]
## What keywords did you search in kubeadm issues before filing this one?
coredns image

## Is this a BUG REPORT or FEATURE REQUEST?
BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`):
kubeadm version: &version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.2", GitCommit:"f66044f4361b9f1f96f0053dd46cb7dce5e990a8", GitTreeState:"clean", BuildDate:"2022-06-15T14:20:54Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Kubernetes version** (use `kubectl version`): kubeadm version: &version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.2", GitCommit:"f66044f4361b9f1f96f0053dd46cb7dce5e990a8", GitTreeState:"clean", BuildDate:"2022-06-15T14:20:54Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}
- **Cloud provider or hardware configuration**: exsi virtual machine
- **OS** (e.g. from /etc/os-release): CentOS Linux 7 (Core)
- **Kernel** (e.g. `uname -a`):Linux master-01 3.10.0-1160.66.1.el7.x86_64 #1 SMP Wed May 18 16:02:34 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
- **Container runtime (CRI)** (e.g. containerd, cri-o):containerd
- **Container networking plugin (CNI)** (e.g. Calico, Cilium):
- **Others**:

## What happened?
`kubeadm config images list`  output:
...
...
k8s.gcr.io/coredns/coredns:v1.8.6

BUT when `kubeadm config images pull --image-repository=harbor.xxx.tech/k8s-gcr-proxy`
ERROR: 
failed to pull image "harbor.xxx.tech/k8s-gcr-proxy/coredns:v1.8.6"

the image path should be harbor.xxx.tech/k8s-gcr-proxy/**coredns/coredns**:v1.8.6 instead of `harbor.xxx.tech/k8s-gcr-proxy/coredns:v1.8.6`

## What you expected to happen?
this command `kubeadm config images pull --image-repository=harbor.xxx.tech/k8s-gcr-proxy` should be able to pull coredns image 

## How to reproduce it (as minimally and precisely as possible)?
1. clean machine

2. install kubeadm, kubelet and kubectl

3. execute  `kubeadm config images pull --image-repository=harbor.xxx.tech/k8s-gcr-proxy`

## Anything else we need to know?

`harbor.xxx.tech/k8s-gcr-proxy` is a registry proxy using https://github.com/goharbor/harbor

**Comment by neolit123** [comment]
Please see
https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-init/#custom-images

The difference in image path is by design.

/close
/kind support

**Comment by wnow20** [comment]
I think coredns not be resolved correctly with `--image-repository` argument, example:

```shell
root@master:/etc/containerd/certs.d# kubeadm config images list --image-repository=next-repo-host
next-repo-host/kube-apiserver:v1.24.2
next-repo-host/kube-controller-manager:v1.24.2
next-repo-host/kube-scheduler:v1.24.2
next-repo-host/kube-proxy:v1.24.2
next-repo-host/pause:3.7
next-repo-host/etcd:3.5.3-0
next-repo-host/coredns:v1.8.6
```

**Comment by mhbahmani** [comment]
Same here. it isn't possible to pull coredns image with custom image repository.
In [this doc](https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-init/#custom-images), there is a `imageTag` config that i couldn't find anywhere to set this.
It seems to be a kubeadm problem.

**Comment by mhbahmani** [comment]
more description on stackoverflow:  
https://stackoverflow.com/questions/74005758/coredns-image-cannot-be-pulled-when-use-image-repository

**Comment by neolit123** [comment]
this section explains how to handle it:

https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-init/#custom-images

> For example, one image might have a subpath at registry.k8s.io/subpath/image, but be defaulted to my.customrepository.io/image when using a custom repository.

and steps bellow.

**Comment by pacoxu** [comment]
Here is a demo.
We use synced image repo in China for GFW.
- we sync images from `registry.k8s.io` to `k8s.m.daocloud.io`
- `registry.k8s.io/coredns/coredns` is synced to `k8s.m.daocloud.io/coredns/coredns`.

```
[root@paco ~]# cat init.yaml
apiVersion: kubeadm.k8s.io/v1beta3
bootstrapTokens:
- groups:
  - system:bootstrappers:kubeadm:default-node-token
  token: abcdef.0123456789abcdef
  ttl: 24h0m0s
  usages:
  - signing
  - authentication
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: 1.2.3.4
  bindPort: 6443
nodeRegistration:
  criSocket: unix:///var/run/containerd/containerd.sock
  imagePullPolicy: IfNotPresent
  name: node
  taints: null
---
apiServer:
  timeoutForControlPlane: 4m0s
apiVersion: kubeadm.k8s.io/v1beta3
certificatesDir: /etc/kubernetes/pki
clusterName: kubernetes
controllerManager: {}
dns:
  imageRepository: k8s.m.daocloud.io/coredns
etcd:
  local:
    dataDir: /var/lib/etcd
imageRepository: k8s.m.daocloud.io
kind: ClusterConfiguration
kubernetesVersion: 1.25.0
networking:
  dnsDomain: cluster.local
  serviceSubnet: 10.96.0.0/12
scheduler: {}



[root@paco ~]# kubeadm config images pull --config init.yaml
[config/images] Pulled k8s.m.daocloud.io/kube-apiserver:v1.25.0
[config/images] Pulled k8s.m.daocloud.io/kube-controller-manager:v1.25.0
[config/images] Pulled k8s.m.daocloud.io/kube-scheduler:v1.25.0
[config/images] Pulled k8s.m.daocloud.io/kube-proxy:v1.25.0
[config/images] Pulled k8s.m.daocloud.io/pause:3.8
[config/images] Pulled k8s.m.daocloud.io/etcd:3.5.4-0
[config/images] Pulled k8s.m.daocloud.io/coredns/coredns:v1.9.3
```

**Comment by et304383** [comment]
This is absurd.  This issue must be resolved.  We're encountering this trying to create 1.21 K8s cluster with --image-repository pointing at registry.k8s.io

**Comment by Lirt** [comment]
This is example for anyone wondering how to write a kubeadm config file ([docs](https://kubernetes.io/docs/reference/config-api/kubeadm-config.v1beta3/)):

```yaml
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
imageRepository: my-private-registry/registry.k8s.io
dns:
  imageRepository: my-private-registry/registry.k8s.io/coredns
```

Then run `kubeadm init --config ...`
