### ISSUE TITLE
How to set the cpu and memory of etcd pod in kubeadm init --config

### ISSUE THREAD

**Issue by ChenJhua** [kubernetes/kubeadm#2732]
How to set the cpu and memory of etcd pod in `kubeadm init --config`
I checked the documentation and didn't see any relevant information
I looked at this code and found that there are default values, but I don't know how to modify the default values through configuration

https://github.com/kubernetes/kubernetes/blob/release-1.23/cmd/kubeadm/app/phases/etcd/local.go

k8s: 1.23.0

**Comment by ChenJhua** [comment]
![image](https://user-images.githubusercontent.com/34536902/180735206-a0456fce-043e-42d5-9005-bf88b95095a1.png)

**Comment by neolit123** [comment]
you can use the clusterconfiguration.etcd.local.extraargs which will apply to all etcd instances
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/control-plane-flags/#etcd-flags

you can use per node patches
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/control-plane-flags/#patches

for support questions please use the support channels
/support

**Comment by ChenJhua** [comment]
> 你可以使用 clusterconfiguration.etcd.local.extraargs 将适用于所有 etcd 实例 https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/control-plane-flags/#etcd-flags
> 
> （所有类型的自定义）
> 
> 或者您可以使用每个设备来修理静态pod。https://kubernetsetup/production-environment/tools/kubeadm/control-plane-flags/docs/# [patches](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/control-plane-flags/#patches)
> 
> 有关支持问题，请使用支持 /support
@neolit123 Can you provide me with an example? I have a configuration error here
I checked the code extraArgs structure is map[string]string, I don't know how to configure init config for etcd resoures
```
etcd:
  local:
    extraArgs:
      snapshot-count: 100000
      heartbeat-interval: 1000
      election-timeout: 1000
      max-snapshots: 3
      max-wals: 50
      auto-compaction-mode: periodic
      auto-compaction-retention: 24h
      dataDir: /data/k8s/etcd
      resources:
        requests:
          cpu: 1000m
          memory: 1024Mi
```
