### ISSUE TITLE
Expected imageRepository field to be validated

### ISSUE THREAD

**Issue by randomvariable** [kubernetes/kubeadm#2758]
## What keywords did you search in kubeadm issues before filing this one?

validate 
imageRepository

## Is this a BUG REPORT or FEATURE REQUEST?
Bug report

## Versions

**kubeadm version** (use `kubeadm version`): v1.25.0

**Environment**:
- **Kubernetes version** (use `kubectl version`): N/A
- **Cloud provider or hardware configuration**: N/A
- **OS** (e.g. from /etc/os-release): N/A
- **Kernel** (e.g. `uname -a`): N/A
- **Container runtime (CRI)** (e.g. containerd, cri-o): N/A
- **Container networking plugin (CNI)** (e.g. Calico, Cilium): N/A
- **Others**: N/A

## What happened?

I modified a kind kubeadm configuration as follows:

```yaml
apiServer:
  certSANs:
  - localhost
  - 127.0.0.1
  extraArgs:
    runtime-config: ""
apiVersion: kubeadm.k8s.io/v1beta3
clusterName: kind
controlPlaneEndpoint: kind-control-plane:6443
dns:
  imageRepository: |
    registry.contoso.com/kubernetes
      s
```

the key bit being

```yaml
dns:
  imageRepository: |
    registry.contoso.com/kubernetes
      s
```

This was then passed into `kubeadm init --config blah.yaml`, and kubeadm proceeded until preflight with

```
[preflight] You can also perform this action in beforehand using 'kubeadm config images pull'
error execution phase preflight: [preflight] Some fatal errors occurred:
        [ERROR ImagePull]: failed to pull image registry.contoso.com/kubernetes
  s
/coredns:v1.9.3: output: E0921 13:07:35.156113    6667 remote_image.go:238] "PullImage from image servic
e failed" err="rpc error: code = Unknown desc = failed to parse image reference \"registry.contoso.com/kubernetes\\n  s\\n/coredns:v1.9.3\": invalid reference format" image=<
        registry.contoso.com/kubernetes
          s
        /coredns:v1.9.3
 >
```

## What you expected to happen?

kubeadm to throw a validation error.

See also https://github.com/kubernetes-sigs/cluster-api/issues/7257 

## How to reproduce it (as minimally and precisely as possible)?

See above.
