### ISSUE TITLE
kubeadm patch (type json - RFC 6902 conform) doesn't ensure path if not exists

### ISSUE THREAD

**Issue by bavarianbidi** [kubernetes/kubeadm#2770]
## Is this a BUG REPORT or FEATURE REQUEST?

Choose one: BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`): `1.25.3`

**Environment**:
- **Kubernetes version** (use `kubectl version`): `1.25.3`
- **Cloud provider or hardware configuration**: `-`
- **OS** (e.g. from /etc/os-release): `ubuntu 22.04`
- **Kernel** (e.g. `uname -a`): `5.15.0-50-generic`
- **Container runtime (CRI)** (e.g. containerd, cri-o): `containerd`
- **Container networking plugin (CNI)** (e.g. Calico, Cilium): `cilium`
- **Others**: `-`

## What happened?

According to the [RFC 6902](https://datatracker.ietf.org/doc/html/rfc6902/#appendix-A.16), `kubeadm` doesn't accecpt a valid json patch. `kubeadm` fails, when items on `pod.spec.containers.env` should get appened if `env` doesn't exist:

```
[patches] Found the following patch files: [kube-apiserver+json.json]
error execution phase control-plane/apiserver: failed to patch static Pod manifest file for "kube-apiserver": could not apply the following patch of type "application/json-patch+json" to target "kube-apiserver":
[{"op":"add","path":"/spec/dnsPolicy","value":"ClusterFirstWithHostNet"},{"op":"add","path":"/spec/containers/0/env/-","value":{"name":"MY_COMPANY_VAR","value":"fancy_company_specific_value"}}]
: add operation does not apply: doc is missing path: "/spec/containers/0/env/-": missing value
```

The current `kubeadm` implementation make use of `github.com/evanphx/json-patch`. This implementation doesn't fully implemented RFC 6902. `v5` added some patch options where it's possible to set `EnsurePathExistsOnAdd` to `true`.

## What you expected to happen?

A generated manifest file where `env` is defined.

```
grep -C 6 env /etc/kubernetes/manifests/kube-apiserver.yaml 
    - --service-account-issuer=https://kubernetes.default.svc.cluster.local
    - --service-account-key-file=/etc/kubernetes/pki/sa.pub
    - --service-account-signing-key-file=/etc/kubernetes/pki/sa.key
    - --service-cluster-ip-range=10.96.0.0/12
    - --tls-cert-file=/etc/kubernetes/pki/apiserver.crt
    - --tls-private-key-file=/etc/kubernetes/pki/apiserver.key
    env:
    - name: MY_COMPANY_VAR
      value: fancy_company_specific_value
    image: registry.k8s.io/kube-apiserver:v1.26.0-alpha.1
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 8
```

## How to reproduce it (as minimally and precisely as possible)?

1. create a json-patch and save as `kube-apiserver+json.json` under `/tmp/mypatch`
   ```json
   [
       {
           "op": "add",
           "path": "/spec/dnsPolicy",
           "value": "ClusterFirstWithHostNet"
       },
       {
           "op": "add",
           "path": "/spec/containers/0/env/-",
           "value": {
                   "name": "MY_COMPANY_VAR",
                   "value": "fancy_company_specific_value"
           }
       }
   ]
   ```

1. run
   ```
   kubeadm init phase control-plane apiserver --patches /tmp/mypatch
   ```

### if `env` isn't empty, it works:

The json-patch from above works fine, if `env` already exist. The current implementation of `kubeadm` (todo link) add the `env` section if `HTTP_PROXY`/`HTTPS_PROXY` or `NO_PROXY` is set in the environment variables.

Therefore a
```
HTTP_PROXY="http://my-proxy-server:3128" kubeadm init phase control-plane apiserver --patches /root/files/patchv5
```

is working fine and result in following valid generated api-server manifest:

```
grep -C 6 env /etc/kubernetes/manifests/kube-apiserver.yaml
     - --service-account-issuer=https://kubernetes.default.svc.cluster.local
     - --service-account-key-file=/etc/kubernetes/pki/sa.pub
     - --service-account-signing-key-file=/etc/kubernetes/pki/sa.key
     - --service-cluster-ip-range=10.96.0.0/12
     - --tls-cert-file=/etc/kubernetes/pki/apiserver.crt
     - --tls-private-key-file=/etc/kubernetes/pki/apiserver.key
     env:
     - name: HTTP_PROXY
       value: http://my-proxy-server:3128
     - name: MY_COMPANY_VAR
       value: fancy_company_specific_value
    image: registry.k8s.io/kube-apiserver:v1.25.3
    imagePullPolicy: IfNotPresent
```

### we have to use the `ApplyWithOptions` method from `` instead of `Apply`

Example snippet on [go.dev/play](https://go.dev/play/p/SKTx8EHUj4Z)

The current `kubeadm` impl. make use of the `Apply` func (as in Line 73) and is failing.
By making use of `ApplyWithOptions` (Line 66) a json patch (according to RFC 6902) get applied and result in the desired output.
