### ISSUE TITLE
json patch conflicts with auto discoverd proxy variables

### ISSUE THREAD

**Issue by bavarianbidi** [kubernetes/kubeadm#2771]
## Is this a BUG REPORT or FEATURE REQUEST?

Choose one: BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`): `1.25.3`

**Environment**:
- **Kubernetes version** (use `kubectl version`): `1.25.3`
- **Cloud provider or hardware configuration**: `-`
- **OS** (e.g. from /etc/os-release): `ubuntu 22.04`
- **Kernel** (e.g. `uname -a`): `5.15.0-50-generic`
- **Container runtime (CRI)** (e.g. containerd, cri-o): `containerd`
- **Container networking plugin (CNI)** (e.g. Calico, Cilium): `cilium`
- **Others**: `-`

## What happened?

By making use of the current `kubeadm init control-plane` phase implementiation it's not possible to add additional `env` variables added via a `json patch + get the automaticall proxy variables (`HTTP_PROXY`, `HTTPS_PROXY` and `NO_PROXY`) injection to `pod.spec.containers.env` 

## What you expected to happen?

Both kind (`json patch` defined variables) and auto discovered proxy variables should get injected in the rendered pod manifests.

## How to reproduce it (as minimally and precisely as possible)?

due #2770  we have to define additional environment variables in the following format

```json
[
    {
        "op": "add",
        "path": "/spec/dnsPolicy",
        "value": "ClusterFirstWithHostNet"
    },
    {
        "op": "add",
        "path": "/spec/containers/0/env",
        "value": [
                {
                        "name": "MY_COMPANY_VAR",
                        "value": "fancy_company_specific_value"
                }
        ]
    }
]
```

a `kubeadm init phase control-plane apiserver --patches /tmp/mypatch` lead to following generated manifest:

```
root@bc2cb8640c6e:/# grep -C 6 env /etc/kubernetes/manifests/kube-apiserver.yaml 
    - --service-account-issuer=https://kubernetes.default.svc.cluster.local
    - --service-account-key-file=/etc/kubernetes/pki/sa.pub
    - --service-account-signing-key-file=/etc/kubernetes/pki/sa.key
    - --service-cluster-ip-range=10.96.0.0/12
    - --tls-cert-file=/etc/kubernetes/pki/apiserver.crt
    - --tls-private-key-file=/etc/kubernetes/pki/apiserver.key
    env:
    - name: MY_COMPANY_VAR
      value: fancy_company_specific_value
    image: registry.k8s.io/kube-apiserver:v1.25.3
    imagePullPolicy: Always
    livenessProbe:
      failureThreshold: 8
```

By running the same `kubeadm init` with a set `HTTP_PROXY` variable via `HTTP_PROXY="http://my-proxy-server:3128" kubeadm init phase control-plane apiserver --patches /root/files/patch` the generated still doesn't contain the proxy variable:

```
root@bc2cb8640c6e:/# grep -C 6 env /etc/kubernetes/manifests/kube-apiserver.yaml 
    - --service-account-issuer=https://kubernetes.default.svc.cluster.local
    - --service-account-key-file=/etc/kubernetes/pki/sa.pub
    - --service-account-signing-key-file=/etc/kubernetes/pki/sa.key
    - --service-cluster-ip-range=10.96.0.0/12
    - --tls-cert-file=/etc/kubernetes/pki/apiserver.crt
    - --tls-private-key-file=/etc/kubernetes/pki/apiserver.key
    env:
    - name: MY_COMPANY_VAR
      value: fancy_company_specific_value
    image: registry.k8s.io/kube-apiserver:v1.25.3
    imagePullPolicy: Always
    livenessProbe:
      failureThreshold: 8
```

Doing the same command without the `--patches` flag (`HTTP_PROXY="http://my-proxy-server:3128" kubeadm init phase control-plane apiserver`) generate the following manifest

```
root@bc2cb8640c6e:/# grep -C 6 env /etc/kubernetes/manifests/kube-apiserver.yaml 
    - --service-account-issuer=https://kubernetes.default.svc.cluster.local
    - --service-account-key-file=/etc/kubernetes/pki/sa.pub
    - --service-account-signing-key-file=/etc/kubernetes/pki/sa.key
    - --service-cluster-ip-range=10.96.0.0/12
    - --tls-cert-file=/etc/kubernetes/pki/apiserver.crt
    - --tls-private-key-file=/etc/kubernetes/pki/apiserver.key
    env:
    - name: HTTP_PROXY
      value: http://my-proxy-server:3128
    image: registry.k8s.io/kube-apiserver:v1.25.3
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 8
```

## Anything else we need to know?

* As `patches` are a thing since few years i'm wondering if we should drop this proxy-variable auto discovery + injection as it could be confusing at all.
* The proposed fix in https://github.com/kubernetes/kubernetes/pull/113092 (tracked in https://github.com/kubernetes/kubeadm/issues/2770) solves this issue.
