### ISSUE TITLE
Synced Server and CertificateAuthorityData from the cluster-info ConfigMap may not work

### ISSUE THREAD

**Issue by YTGhost** [kubernetes/kubeadm#2781]
## What keywords did you search in kubeadm issues before filing this one?
discovery

## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`):v1.23.0

**Environment**:
- **Kubernetes version** (use `kubectl version`):v1.23.0
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Container runtime (CRI)** (e.g. containerd, cri-o):
- **Container networking plugin (CNI)** (e.g. Calico, Cilium):
- **Others**:

## What happened?
I use kubeadm like this `kubeadm join --config=kubeadm-join.conf`

`kubeadm-join.conf`:
```yaml
apiVersion: kubeadm.k8s.io/v1beta3
kind: JoinConfiguration
discovery:
  file:
    kubeConfigPath: /var/lib/kubelet/discovery.conf
  tlsBootstrapToken: 8gtr4q.keramu8frl1v3ltn
nodeRegistration:
  criSocket: /run/containerd/containerd.sock
  name: izbp16wq7lq85r4pm8546az
  ignorePreflightErrors:
    - FileAvailable--etc-kubernetes-kubelet.conf
  kubeletExtraArgs:
    rotate-certificates: "false"
    pod-infra-container-image: registry.cn-hangzhou.aliyuncs.com/google_containers/pause:3.2
    node-labels: openyurt.io/is-edge-worker=true
    container-runtime: remote
    container-runtime-endpoint: /run/containerd/containerd.sock
```
`discovery.conf`:
```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM2VENDQWRHZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQ0FYRFRJeU1URXhNVEV5TXpVeU5Gb1lEekl4TWpJeE1ERTRNVEl6TlRJMFdqQVZNUk13RVFZRApWUVFERXdwcmRXSmxjbTVsZEdWek1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBCjA5VDNDeUdHcHgzTysvTVRvNzkzOTIra2M2UkE3WFNjRk4yQ3NOOUYyRGVUc3BvTC9LZ0MvNUtoa0V5bVlWWmUKbzZ1a0RLUkhMOWF0NDdoQURWWkFHWHVjM2h3QmNkT3hlQ0tRUGUxaHNTOGZDbmxEb0FRWHVvY1h0WEtXRDdiRApkdnhLeURnT0xsL0NDVFhJMk9BVXRNUWJobUFGWFEzVUtLVmt3UngzSmh4anE2dTU3RlBxT0JObmJpV3VjdmNpClhiaTNxNUNlTkVZUENBQ1JQOEliN0EwUlp0SkJjSGlLbDcwMURZcTkzb0xDZFlQR0kvZXpsbXM3Nnh4STlWYUEKMitzWFViRGYrY3ljaDBXa3lSVzJ2UytKTzdRU2IxS3JDNm5jKzROejRDS0JpaTd0RlpodGViMXU4UkN4b3d4eQppV0ZPZ0w0cW5JZktXNU91d2thZm53SURBUUFCbzBJd1FEQU9CZ05WSFE4QkFmOEVCQU1DQXFRd0R3WURWUjBUCkFRSC9CQVV3QXdFQi96QWRCZ05WSFE0RUZnUVVNVGxKZUp5WWM0eVIyazROVGllZkt1ZE5zVFV3RFFZSktvWkkKaHZjTkFRRUxCUUFEZ2dFQkFCTE05SFB0VVBkSVlXQUd6bWRzMzhtYXppVjdvUWJoMnIrMkJmL212WkZocWJicQp6aC9wQk04VmNrZWl1ZFRUM2F0ZFAwZFVrS3QrVEppUE56Wi9OcjVPTG4rdGRKVlI0RVlNbmtpV3NTaExzTmZFCmlGSjBRNjhocWZzNjgwVVNUbzg5TTVYdG5IVitnM2NhZGFvdkJPUGtrbFl4NlZWMzZCRm1TWmx5SC8wc3FJRXAKVUFrUm5TaWRZR0NWMVc5L01JNWZyNW1pSGR3ckJNNEJoSmVjcUY2VUtkVEduN3oweThjdG5qYVROeHBYVUhKZApsUDBJalQxYVlBb0xxa2Q3VDVpWkRKd0VNb01NN3d5a09hZ3Jod281ZW0vVnZ3QWtlbjZFamhBQllvZTR1N2czCm1tTStZM1NlSUJFUUJkWTRnTlFVMmRXUlVCSmw2ZFE1WGRQdXpuZz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    server: https://xxx.xx.xxx.xx:6443
  name: ""
contexts: null
current-context: ""
kind: Config
preferences: {}
users: null
```
As you can see, I wanted to configure `discovery.file.kubeConfigPath` to change the server address, and I found the logic for reading the file in `cmd/kubeadm/app/discovery/file/file.go`
But in the `ValidateConfigInfo` function, I met some problems.
In my case, `config` will be rebuilt via `kubeconfigutil.CreateBasic`
```go
// Create a new kubeconfig object from the discovery file config, with only the server and the CA cert.
// NB. We do this in order to not pick up other possible misconfigurations in the clusterinfo file
config = kubeconfigutil.CreateBasic(
	currentCluster.Server,
	clustername,
	"", // no user provided
	currentCluster.CertificateAuthorityData,
)
```
This will result in the final `Synced Server and CertificateAuthorityData` process not being modified. Because only values are passed in when rebuilding `config` and not pointers
```go
// We somehow got hold of the ConfigMap, try to read some data from it. If we can't, fallback on the user-provided file
refreshedBaseKubeConfig, err := tryParseClusterInfoFromConfigMap(clusterinfoCM)
if err != nil {
klog.V(1).Infof("[discovery] The %s ConfigMap isn't set up properly (%v), but the TLS cert is valid so proceeding...\n", bootstrapapi.ConfigMapClusterInfo, err)
return config, nil
}

refreshedCluster := kubeconfigutil.GetClusterFromKubeConfig(refreshedBaseKubeConfig)
// Because it is not a pointer that is passed when rebuilding the config, the change here will have no effect
currentCluster.Server = refreshedCluster.Server
currentCluster.CertificateAuthorityData = refreshedCluster.CertificateAuthorityData

klog.V(1).Infof("[discovery] Synced Server and CertificateAuthorityData from the %s ConfigMap", bootstrapapi.ConfigMapClusterInfo)
```
If this is not a bug, perhaps it should be returned immediately after rebuilding the config?
## What you expected to happen?
If this is a bug, the rebuilt `config` should be synced correctly.
If this were not a bug, perhaps it should be returned immediately after rebuilding the `config`.

## How to reproduce it (as minimally and precisely as possible)?
using the `discovery.file.kubeConfigPath` in `JoinConfiguration`, you will found that Server and CertificateAuthorityData are not syncd correctly

## Anything else we need to know?
If there is indeed a problem with this piece of code, I think I can contribute a pr.
