### ISSUE TITLE
The configuration inside kubeadm-config.yaml does not work

### ISSUE THREAD

**Issue by MonkeyKingLuffy** [kubernetes/kubeadm#2843]
#### issue overview:
> As described in my tile,the configuration inside kubeadm-config.yaml does not work,when i using `kubeadm init --config kubeadm-config.yaml ` to initialization

## Is this a BUG REPORT or FEATURE REQUEST?

- bug

## Versions
<details>
  <summary>Kubernetes version:</summary>
<pre><blockcode> 
kubeadm version: &version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.0", GitCommit:"b46a3f887ca979b1a5d14fd39cb1af43e7e5d12d", GitTreeState:"clean", BuildDate:"2022-12-08T19:57:06Z", GoVersion:"go1.19.4", Compiler:"gc", Platform:"linux/amd64"}
</blockcode></pre>
</details>

**Environment**:
<details>
  <summary>kubelet version:</summary>
<pre><blockcode> 
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.0", GitCommit:"b46a3f887ca979b1a5d14fd39cb1af43e7e5d12d", GitTreeState:"clean", BuildDate:"2022-12-08T19:58:30Z", GoVersion:"go1.19.4", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
</blockcode></pre>
</details>

- **hardware configuration**: `virtualbox`
- **OS** : `centos 8.5`
- Kernel : `Linux  6.2.2-1.el8.elrepo.x86_64`
- **Container runtime** : `Docker Engine`([cri-dockerd](https://kubernetes.io/docs/setup/production-environment/container-runtimes/#docker))

#### The detail of issue:
> For example,the `criSocket` inside my kubeadm-config.yaml is :`unix:///var/run/cri-dockerd.sock`;however,after i run `kubeadm init --config kubeadm-config.yaml `,the actual result of `criSocket`  is `unix:///var/run/containerd/containerd.sock`

#### Below are all the commands I run and their output:

- `kubeadm init` output:

```shell
root@master1 ~/k8s/]# kubeadm init --config=kubeadm-config.yaml --upload-certs
[init] Using Kubernetes version: v1.26.0
[preflight] Running pre-flight checks
	[WARNING FileExisting-tc]: tc not found in system path
[preflight] Pulling images required for setting up a Kubernetes cluster
[preflight] This might take a minute or two, depending on the speed of your internet connection
[preflight] You can also perform this action in beforehand using 'kubeadm config images pull'

...

Your Kubernetes control-plane has initialized successfully!

To start using your cluster, you need to run the following as a regular user:

  mkdir -p $HOME/.kube
  sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
  sudo chown $(id -u):$(id -g) $HOME/.kube/config
``` 

-  This is my kubeadm-config.yaml:
```yaml
apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
nodeRegistration:
  criSocket: unix:///var/run/cri-dockerd.sock 
  kubeletExtraArgs:
    runtime-cgroups: /system.slice/docker.service
    pod-infra-container-image: gcr.io/google_containers/google_containers/pause:3.7

---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
mode: ipvs
ipvs:
  minSyncPeriod: 8s
  syncPeriod: 8s
  scheduler: 'wrr'
```
- This is the output after i run `kubeadm config print init-defaults`:
```shell
[root@master1 k8s]# kubeadm config print init-defaults
apiVersion: kubeadm.k8s.io/v1beta3
bootstrapTokens:
- groups:
  - system:bootstrappers:kubeadm:default-node-token
  token: abcdef.0123456789abcdef
  ttl: 24h0m0s
  usages:
  - signing
  - authentication
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: 1.2.3.4
  bindPort: 6443
nodeRegistration:
  criSocket: unix:///var/run/containerd/containerd.sock
  imagePullPolicy: IfNotPresent
  name: node
  taints: null
```
