### ISSUE TITLE
Kubeadm KubeletConfiguration JoinConfiguration Patch not working

### ISSUE THREAD

**Issue by tlb1galaxy** [kubernetes/kubeadm#2860]
### What happened?

Attempting to join a worker node to a cluster that will:

1. join the cluster
2. configure the kubelet with the base config from the controller
3. patch the kublet config locally on the worker to merge additional settings (/var/lib/kubelet/config.yaml)

The patch is never applied to the worker node.
I do not see any errors in the output of kubeadm.
Not sure where else I can look for any error logs for the kubeadm join process

### What did you expect to happen?

Expect the following logical process to occur during a worker node join process:

1. worker node join the cluster
2. configure the kubelet config with the base configuration from the controller
3. patch (add) additional settings (flags) to the kubelet config (/var/lib/kubelet/config.yaml)
4. configure the local (worker) kubelet with all combined settings

### How can we reproduce it (as minimally and precisely as possible)?

1. Create initial control plane node with clusterconfiguration.yaml
2. On Controller - 
    1. sudo mkdir -p /etc/kubernetes/patches
    2. copy kubeletconfiguration0+strategic.yaml to /etc/kubernetes/patches
3. On Worker - 
    1. sudo mkdir -p /etc/kubernetes/patches
    2. copy kubeletconfiguration0+strategic.yaml to /etc/kubernetes/patches
    3. copy joinconfiguration.yaml to ~/
    4. sudo kubeadm join --v=5 --config ~/joinconfiguration.yaml
    5. After the join process is complete;
        1. sudo less /var/lib/kubelet/config.yaml
        2. Look for settings declared in kubeletconfiguration0+strategic.yaml

``` yaml
# clusterconfiguration.yaml
---
apiVersion: kubeadm.k8s.io/v1beta3
bootstrapTokens:
- groups:
  - system:bootstrappers:kubeadm:default-node-token
  token: abcdef.0123456789abcdef
  ttl: 24h0m0s
  usages:
  - signing
  - authentication
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: 10.1.1.1
  bindPort: 6443
nodeRegistration:
  criSocket: unix:///run/containerd/containerd.sock
  imagePullPolicy: IfNotPresent
  name: controller01.etc.local
  taints: null
---
apiServer:
  timeoutForControlPlane: 4m0s
  extraArgs:
    enable-admission-plugins: AlwaysPullImages,EventRateLimit,NodeRestriction,SecurityContextDeny
    admission-control-config-file: /etc/kubernetes/admission-control-config.yaml
    profiling: "false"
    request-timeout: "300s"
    audit-policy-file: /etc/kubernetes/audit-policy-global.yaml
    audit-log-path: /var/log/kubernetes/audit/audit.log
    audit-log-maxage: '30'
    audit-log-maxbackup: '10'
    audit-log-maxsize: '100'
    tls-cipher-suites: TLS_AES_128_GCM_SHA256,TLS_AES_256_GCM_SHA384,TLS_CHACHA20_POLY1305_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256,TLS_RSA_WITH_AES_128_CBC_SHA,TLS_RSA_WITH_AES_128_GCM_SHA256,TLS_RSA_WITH_AES_256_CBC_SHA,TLS_RSA_WITH_AES_256_GCM_SHA384
  extraVolumes:
    - name: admissioncontrolconfig
      hostPath: /etc/kubernetes/admission-control-config.yaml
      mountPath: /etc/kubernetes/admission-control-config.yaml
      pathType: "File"
      readOnly: true
    - name: eventratelimit
      hostPath: /etc/kubernetes/eventratelimit-server-namespace-user.yaml
      mountPath: /etc/kubernetes/eventratelimit-server-namespace-user.yaml
      readOnly: true
      pathType: "File"
    - name: audit
      hostPath: /etc/kubernetes/audit-policy-global.yaml
      mountPath: /etc/kubernetes/audit-policy-global.yaml
      readOnly: true
      pathType: "File"
    - name: audit-log
      hostPath: /var/log/kubernetes/audit/
      mountPath: /var/log/kubernetes/audit/
      readOnly: false
      pathType: "DirectoryOrCreate"
apiVersion: kubeadm.k8s.io/v1beta3
certificatesDir: /etc/kubernetes/pki
clusterName: kubernetes
controllerManager:
  extraArgs:
    profiling: "false"
    terminated-pod-gc-threshold: '10'
dns: {}
etcd:
  local:
    dataDir: /var/lib/etcd
imageRepository: k8s.gcr.io
kind: ClusterConfiguration
kubernetesVersion: v1.24.2
controlPlaneEndpoint: controller01.etc.local
networking:
  dnsDomain: cluster.local
  serviceSubnet: 172.16.0.0/16
  podSubnet: 192.168.0.0/16
scheduler: {}
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
cgroupDriver: systemd
eventRecordQPS: 10
tlsCipherSuites:
  - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
  - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
  - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
  - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
  - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
  - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
  - TLS_RSA_WITH_AES_256_GCM_SHA384
  - TLS_RSA_WITH_AES_128_GCM_SHA256
```

``` yaml
# joinconfiguration.yaml
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: JoinConfiguration
caCertPath: /etc/kubernetes/pki/ca.crt
discovery:
  bootstrapToken:
    apiServerEndpoint: controller01.etc.local:6443
    token: abcdef.0123456789abcdef
    unsafeSkipCAVerification: true
  timeout: 5m0s
  tlsBootstrapToken: abcdef.0123456789abcdef
nodeRegistration:
  criSocket: unix:///var/run/containerd/containerd.sock
  imagePullPolicy: AlwaysPullImages
  taints: null
patches:
  directory: /etc/kubernetes/patches/
...
```

``` yaml
# /etc/kubernetes/patches/kubeletconfiguration0+strategic.yaml
protectKernelDefaults: true
```

### Anything else we need to know?

**Source doc**: [Kubeadm patches](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/control-plane-flags/#patches)

**Patch location**:  It is not declared where the patch file needs to reside (controller or worker).  So for now, I have put on both.

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.2", GitCommit:"f66044f4361b9f1f96f0053dd46cb7dce5e990a8", GitTreeState:"clean", BuildDate:"2022-06-15T14:22:29Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.2", GitCommit:"f66044f4361b9f1f96f0053dd46cb7dce5e990a8", GitTreeState:"clean", BuildDate:"2022-06-15T14:15:38Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}

</details>

### Cloud provider

<details>
kubeadm
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>
kubeadm version: &version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.2", GitCommit:"f66044f4361b9f1f96f0053dd46cb7dce5e990a8", GitTreeState:"clean", BuildDate:"2022-06-15T14:20:54Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}
</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
