### ISSUE TITLE
Cluster is non-compliant with CIS benchmark because of /var/lib/etcd ownership

### ISSUE THREAD

**Issue by boomcubist** [kubernetes/kubeadm#2931]
FEATURE REQUEST

Clusters deployed with kubeadm are non-compliant with section 

> 1.1.12 Ensure that the etcd data directory ownership is set to etcd:etcd 

because ownership of the directory is set to `root:root`. 

Can it be that kubeadm creates an etcd user and group and assigns ownership `/var/lib/etcd` to `etcd:etcd`?

## Versions

```
clientVersion:
  buildDate: "2023-03-15T13:40:17Z"
  compiler: gc
  gitCommit: 9e644106593f3f4aa98f8a84b23db5fa378900bd
  gitTreeState: clean
  gitVersion: v1.26.3
  goVersion: go1.19.7
  major: "1"
  minor: "26"
  platform: linux/amd64
kustomizeVersion: v4.5.7
serverVersion:
  buildDate: "2023-03-15T13:33:12Z"
  compiler: gc
  gitCommit: 9e644106593f3f4aa98f8a84b23db5fa378900bd
  gitTreeState: clean
  gitVersion: v1.26.3
  goVersion: go1.19.7
  major: "1"
  minor: "26"
  platform: linux/amd64
```

## What happened?
`/var/lib/etcd` created with `root:root` ownership

## What you expected to happen?
`/var/lib/etcd` created with `etcd:etcd` ownership

## How to reproduce it (as minimally and precisely as possible)?
`stat -c %U:%G /var/lib/etcd`
