### ISSUE TITLE
1.30 kubeadm does not respect timeout configuration in v1beta3 api

### ISSUE THREAD

**Issue by penghez** [kubernetes/kubeadm#3074]
### What happened?

The v1beta3 timeout configuration does not work. For example, the following `timeout` field in `JoinConfiguration` is not being respected:

```
discovery:
  bootstrapToken:
    apiServerEndpoint: kube-apiserver:6443
    token: abcdef.0123456789abcdef
    unsafeSkipCAVerification: true
  timeout: 1s
  tlsBootstrapToken: abcdef.0123456789abcdef
```
---

Take `JoinConfiguration` as example.

The reason might be  due to [this change for newly introduced `Timeout` field](https://github.com/kubernetes/kubernetes/commit/caf5311413230c1e48d1d46acafd6cac5c0f6da2#diff-34ecadaab06af85de7b4761d286d82305353976123e2334631e3ec3686612ec0). In this change, kubeadm introduce an overall `timeout` [field in v1beta4 api](https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/apis/kubeadm/v1beta4/types.go#L400) (we are using v1beta3), and removed the specific `timeout` field in `discovery`. Meanwhile, the kubeadm code seems like did not handle the corresponding version skew, it simple uses the newly introduced timeout field ([ref](https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/discovery/discovery.go#L75)). And for v1beta3 api, the timeout for discovery will always be default to [5 min](https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/apis/kubeadm/v1beta3/conversion.go#L60). 

### What did you expect to happen?

The timeout should work.

### How can we reproduce it (as minimally and precisely as possible)?

Set timeout to 10s in v1beta3 `JoinConfiguration` api with the placeholder. And run `kubeadm join phase preflight --config /tmp/kubeadm_join_defaults.yaml`, the timeout is 300s for discovery instead of 10s.

### Kubernetes version

1.30

### Cloud provider

N/A

### OS version

N/A

### Install tools

N/A

### Container runtime (CRI) and version (if applicable)

N/A

### Related plugins (CNI, CSI, ...) and versions (if applicable)

N/A
