### ISSUE TITLE
v1beta4 extraArgs duplicate values policy

### ISSUE THREAD

**Issue by tico88612** [kubernetes/kubeadm#3173]
Hi folks,

I checked the documentation, and it said, `Extra arguments will override existing default arguments. Duplicate extra arguments are allowed.`
I was under the impression that other things like Pod env were the last wins policy for duplicate names.

I would like to ensure that the `extraArgs` repeating value is also the last win policy?

Original v1beta4 ClusterConfiguration:

```yaml
apiServer:
  extraArgs:
  - name: default-not-ready-toleration-seconds
    value: "300" # Kubespray Default Template
  - name: default-unreachable-toleration-seconds
    value: "300" # Kubespray Default Template
  - name: anonymous-auth
    value: "True"
# <!-- truncate -->
  - name: "default-not-ready-toleration-seconds"
    value: "10" # User use Kubespray apiserver_extra_args to render
  - name: "default-unreachable-toleration-seconds"
    value: "10" # User use Kubespray apiserver_extra_args to render
```

But the final result would be:

```yaml
spec:
  containers:
  - command:
    - kube-apiserver
# <!-- truncate -->
    - --default-not-ready-toleration-seconds=10
    - --default-not-ready-toleration-seconds=300 # Last win
    - --default-unreachable-toleration-seconds=10
    - --default-unreachable-toleration-seconds=300 # Last win
    - --enable-admission-plugins=NodeRestriction
    - --enable-aggregator-routing=False
```

FYI: https://github.com/kubernetes-sigs/kubespray/issues/12021#issuecomment-2721150239
