### ISSUE TITLE
kubeadm does not use right advertise address when joining Control plane node

### ISSUE THREAD

**Issue by rakeshk121** [kubernetes/kubeadm#3175]
Im trying to create a cluster using kubeadm using 3 control planes and using kube-vip for High availability.

Kubeadm version used: 1.31.2

I have 3 control plane nodes with below IPs
```
192.168.100.145
192.168.100.122
192.168.100.140
```

`192.168.100.220` is the VIP for kube-vip

I have performed the kubeadm init on the first control plane( i.e, 192.168.100.145) using below kubeadm config

```
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
dns:
  imageRepository: docker.io/coredgeio
imageRepository: docker.io/coredgeio
kubernetesVersion: v1.31.2
controllerManager:
  extraArgs:
    profiling: "false"      
apiServer:
  extraArgs:
    advertise-address: 192.168.100.145
    profiling: "false"
    audit-log-path: "/var/log/apiserver/audit.log"
    audit-log-maxage: "30"
    audit-log-maxbackup: "10"
    audit-log-maxsize: "100"
scheduler:
    extraArgs:
     profiling: "false"                 
controlPlaneEndpoint: 192.168.100.220:6443
networking:
  podSubnet: 10.244.0.0/16
``` 

Kubeadm init was performed using: `kubeadm init  --config=kubeadm.yaml  --upload-certs`

To add other control planes, On the Control-plane 2 that is `192.168.100.122` , im using below command 

```
kubeadm join 192.168.100.220:6443 --token gmwwwu.jr526ifymkyve39q --discovery-token-ca-cert-hash sha256:d1a07eee7ad2b903d41a09138c54b0a6de0a164c544c28f48b0461ce3ace1638  --control-plane --certificate-key a4e5a3460f1b3ace118d1fecd38215e4ca1f1045bee4491e18f1a29b7d02d3c0 --apiserver-advertise-address=192.168.100.122
```

Even though the advertise-address is passed explicitly(as in above command), I see that the value updated to `/etc/kubernetes/manifests/kube-apiserver.yaml` is the IP of first control plane (i.e 192.168.100.145) instead of IP of second control plane (i.e 192.168.100.122)
The details are below, (Please notice that annotation is updated correctly but command section is having wrong IP)

```
root@nodeb40:/etc/kubernetes/manifests# cat kube-apiserver.yaml 
apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubeadm.kubernetes.io/kube-apiserver.advertise-address.endpoint: 192.168.100.122:6443
  creationTimestamp: null
  labels:
    component: kube-apiserver
    tier: control-plane
  name: kube-apiserver
  namespace: kube-system
spec:
  containers:
  - command:
    - kube-apiserver
    - --advertise-address=192.168.100.145
    - --allow-privileged=true
    - --audit-log-maxage=30
.
.
.
```

**Comment by neolit123** [comment]
ClusterConfiguration.apiServer.extraArgs apply to all machines. you should remove the advertise address from there.
instead, you should use InitConfiguration.localAPIEndpoint and JoinConfiguration.controlPlane.localAPIEndpoint.

for both cases it looks like
```
...
localAPIEndpoint:
  advertiseAddress: xx
  bindPort: 6443
```

that way you can pass a custom ip for advertise address on the init/join machines.

https://kubernetes.io/docs/reference/config-api/kubeadm-config.v1beta3/
