### ISSUE TITLE
automatically mount etcd certs volumes on k8s-apiserver container if set in MasterConfiguration file

### ISSUE THREAD

**Issue by aanm** [kubernetes/kubeadm#318]
In MasterConfiguration file the user can set the ca/cert/key Files for etcd. There are no indication if the paths are host paths or containers paths.
```
apiVersion: kubeadm.k8s.io/v1alpha1
kind: MasterConfiguration
api:
  advertiseAddress: <address|string>
  bindPort: <int>
etcd:
  endpoints:
  - <endpoint1|string>
  - <endpoint2|string>
  caFile: <path|string>
  certFile: <path|string>
  keyFile: <path|string>
```

I suggest the ca/cert/key File paths would point to the host paths and they would be atomically mounted to the k8s api-server container as well the appropriate flags for the k8s-apiserver to point to the mounted paths.
