### ISSUE TITLE
Failed to create load balancer: User "system:kube-controller-manager" cannot create configmaps in the namespace "kube-system".

### ISSUE THREAD

**Issue by Dirbaio** [kubernetes/kubeadm#425]
## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT

## Versions

**kubeadm version** 1.7.5

**Environment**:
- **Kubernetes version** 1.7.5
- **Cloud provider or hardware configuration**: GCE (with multizone on)
- **OS** Ubuntu 16.04
- **Kernel** Linux vk-prod4-master 4.10.0-32-generic #36~16.04.1-Ubuntu SMP Wed Aug 9 09:19:02 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- **Others**: Calico networking

## What happened?
- Deployed k8s master like this:
```
cat > kubeadm.yaml <<EOF
apiVersion: kubeadm.k8s.io/v1alpha1
kind: MasterConfiguration
api:
  advertiseAddress: $MASTER_HOSTNAME
  bindPort: 443
networking:
  serviceSubnet: 10.1.0.0/16
  podSubnet: 10.0.0.0/16
kubernetesVersion: v1.7.5
cloudProvider: gce
apiServerExtraArgs:
  runtime-config: batch/v2alpha1=true
  oidc-client-id: BLAHBLAHBLAH.apps.googleusercontent.com  # beta
  oidc-issuer-url: https://accounts.google.com
  oidc-username-claim: email
controllerManagerExtraArgs:
  configure-cloud-routes: "true"
apiServerCertSANs:
- $CLUSTER_NAME.example.com
token: $CLUSTER_TOKEN
EOF

# --skip-preflight-checks because kubeadm doesn't like docker overlay2 yet
kubeadm init --skip-preflight-checks --config kubeadm.yaml
```

- Deployed k8s node like this:
```
kubeadm join \
    --skip-preflight-checks \
    --token $CLUSTER_TOKEN \
    $MASTER_HOST:443
```

- Everything in the cluster comes up fine and healthy.
- Create a LoadBalancer service like this:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress
  namespace: nginx-ingress
spec:
  ports:
    - name: http
      port: 80
    - name: https
      port: 443
  selector:
    app: nginx-ingress
  type: LoadBalancer
  externalTrafficPolicy: Local
  loadBalancerIP: X.Y.Z.W
```
- Wait for a bit
- Load balancer fails to be created. `kubectl describe svc` shows:
```
  FirstSeen	LastSeen	Count	From			SubObjectPath	Type		Reason				Message
  ---------	--------	-----	----			-------------	--------	------				-------
  1m		15s		5	service-controller			Normal		CreatingLoadBalancer		Creating load balancer
  1m		15s		5	service-controller			Warning		CreatingLoadBalancerFailed	Error creating load balancer (will retry): Failed to create load balancer for service nginx-ingress/nginx-ingress: User "system:kube-controller-manager" cannot create configmaps in the namespace "kube-system". (post configmaps)
```

## What you expected to happen?
Load balancer gets created successfully.

## How to reproduce it (as minimally and precisely as possible)?
See above

## Anything else we need to know?
This seems to be caused to missing RBAC roles/bindings. As a workaround, applying the following and recreating the service makes it work:
```yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: rbac-fix
  namespace: kube-system
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - "*"
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: rbac-fix
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rbac-fix
subjects:
- kind: User
  name: system:kube-controller-manager
  namespace: kube-system
```
