### ISSUE TITLE
Rerunning kubeadm init with replaced kubedns

### ISSUE THREAD

**Issue by mattymo** [kubernetes/kubeadm#433]
## What keywords did you search in kubeadm issues before filing this one?
kube-dns
## Is this a BUG REPORT or FEATURE REQUEST?
Choose one: BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`): v1.7.3

**Environment**:
- **Kubernetes version** (use `kubectl version`):
- **Cloud provider or hardware configuration**: none
- **OS** (e.g. from /etc/os-release): Ubuntu Xenial
- **Kernel** (e.g. `uname -a`): 4.10.0-32-generic
- **Others**:

## What happened?
To customize kubedns after deployment, an administrator should run the commands in sequence:
```
kubeadm init $ARGS
kubectl apply -f kube-dns.yml
```
Later, the administrator wants to modify admin settings and re-run kubeadm init.

## What you expected to happen?
kubeadm init should pass and either respect that kubedns was modified OR force its own version.

## How to reproduce it (as minimally and precisely as possible)?
Run kubeadm init
Apply the following kubedns definition: https://gist.githubusercontent.com/mattymo/f5049e7772d30f414c94a692acb437b0/raw/79776e1eec840ba6aa9f9e37c18410bd027ad6d1/kubedns.yml
Re-run kubeadm init

## Anything else we need to know?
Error output:
```
unable to create/update the kube-dns service: Service "kube-dns" is invalid: spec.clusterIP: Invalid value: "10.233.0.10": field is immutable.
```

Kubeadm should follow one of the two strategies:
1 - Create kube-dns if it doesn't exist. If it does, just leave it alone (or perhaps update the image only).
2 - Use kubectl apply --force to delete and recreate kube-dns.

I think the only workaround for now is use kubeadm phases.

**Comment by hongjyan** [comment]
Hi, 
this problem should be fix but still i encountered.
```
[root@81-k8s-1 ~]# cat kubeadm-config.yaml 
apiVersion: kubeadm.k8s.io/v1alpha3
kind: ClusterConfiguration
kubernetesVersion: v1.12.2
networking:
  podSubnet: 10.244.0.0/16
  serviceSubnet: 10.254.0.0/16
#controlPlaneEndpoint: 10.183.36.63:6443
#invalid
#advertiseAddress: 10.183.36.11
#invalid
#invalid
#api:
#  advertiseAddress: 10.183.36.11
#  bindPort: 6443
#invalid
apiServerExtraArgs:
  advertise-address: 10.181.131.226
  bind-address: 192.168.0.19
  service-cluster-ip-range: 10.254.0.0/16
apiServerCertSANs:
#- 30-k8s-1.novalocal
#- 71-k8s-1.novalocal
- 81-k8s-1.novalocal
#- 10.183.36.11
#- 10.181.198.3
- 10.181.131.226
#- 192.168.0.31
#- 192.168.0.13
- 192.168.0.19
- 127.0.0.1
- 10.183.36.63
etcd:
  external:
    endpoints:
    - https://10.183.36.11:2379
    - https://10.181.198.3:2379
    - https://10.181.131.226:2379
    caFile: /etc/kubernetes/ssl/ca.pem
    certFile: /etc/kubernetes/ssl/kubernetes.pem
    keyFile: /etc/kubernetes/ssl/kubernetes-key.pem
    dataDir: /var/lib/etcd
#token: 547df0.182e9215291ff27f
#tokenTTL: "0"
``` 

with kubeadm init --config kubeadm-config.yaml 
```
error ensuring dns addon: unable to create/update the DNS service: Service "kube-dns" is invalid: spec.clusterIP: Invalid value: "10.254.0.10": field is immutable
```
I tried removed serviceSubnet: 10.254.0.0/16 from config file, then do "kubectl get svc kube-dns -n kube-system -o yaml > kube-dns.yaml", then change it spec.clusterIP to 10.254.0.10, then apply this file, but immutable error throw out still.
```
[root@81-k8s-1 ~]# kubectl apply -f kube-dns.yaml 
Warning: kubectl apply should be used on resource created by either kubectl create --save-config or kubectl apply
The Service "kube-dns" is invalid: spec.clusterIP: Invalid value: "10.254.0.10": field is immutable
```
I am entangled here about 1 day, any help is appreciated!
