### ISSUE TITLE
Localhost is not respected by kubeadm for advertiseAddress

### ISSUE THREAD

**Issue by onorua** [kubernetes/kubeadm#487]
### kubeadm config:
```
kind: MasterConfiguration
apiVersion: kubeadm.k8s.io/v1alpha1
api:
  advertiseAddress: "127.0.0.1"
networking:
  podSubnet: "10.244.0.0/16"
controllerManagerExtraArgs:
  horizontal-pod-autoscaler-use-rest-clients: "true"
  horizontal-pod-autoscaler-sync-period: "10s"
  node-monitor-grace-period: "10s"
apiServerExtraArgs:
  runtime-config: "api/all=true"
  feature-gates: "TaintBasedEvictions=true"
  admission-control: "NamespaceLifecycle,LimitRanger,ServiceAccount,PersistentVolumeLabel,DefaultStorageClass,ResourceQuota,DefaultTolerationSeconds"
kubernetesVersion: "v1.8.0"
```

## What happened?
In case I set advertiseAddress to 127.0.0.1, it doesn't respect that value, but rather discover it automatically. 
I can see that following code is doing that:
https://github.com/kubernetes/apimachinery/blob/dc1f89aff9a7509782bde3b68824c8043a3e58cc/pkg/util/net/interface.go#L384

But localhost is completely valid use case. Let me elaborate, at the moment we have haproxy working as a API server load balancer, as well as health checker for kube-proxy.

## What you expected to happen?
Respect configured value. 

## How to reproduce it (as minimally and precisely as possible)?
take kubeadm config mentioned above, executed:
```
kubeadm init --config kubeadm.conf --skip-preflight-checks --dry-run
```

Check for api server manifest, all the config maps, basically everything pointing to the automatically discovered IP, instead one from configuration file.
