### ISSUE TITLE
How to change the serverAdress after the cluster is running?

### ISSUE THREAD

**Issue by KeithTt** [kubernetes/kubeadm#550]
kube version: 1.8.2
etcd version: 3.29
OS version: debian stretch

I user `kubeadm init --config=kubeadm-config.yml`start the master, there are two network adapters on the master:

```
# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eno1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 34:e6:d7:89:9e:5d brd ff:ff:ff:ff:ff:ff
    inet 122.14.206.195/23 brd 122.14.207.255 scope global eno1
       valid_lft forever preferred_lft forever
    inet6 fe80::36e6:d7ff:fe89:9e5d/64 scope link
       valid_lft forever preferred_lft forever
3: eno2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 34:e6:d7:89:9e:5e brd ff:ff:ff:ff:ff:ff
    inet 192.168.5.42/20 brd 192.168.15.255 scope global eno2
       valid_lft forever preferred_lft forever
    inet 192.168.6.15/32 scope global eno2
       valid_lft forever preferred_lft forever
    inet6 fe80::36e6:d7ff:fe89:9e5e/64 scope link
       valid_lft forever preferred_lft forever
4: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
    link/ether 02:42:98:3f:bd:44 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 scope global docker0
       valid_lft forever preferred_lft forever
5: tunl0@NONE: <NOARP,UP,LOWER_UP> mtu 1440 qdisc noqueue state UNKNOWN group default qlen 1
    link/ipip 0.0.0.0 brd 0.0.0.0
    inet 192.168.122.0/32 scope global tunl0
       valid_lft forever preferred_lft forever
```

I use a config file like this:

```
apiVersion: kubeadm.k8s.io/v1alpha1
kind: MasterConfiguration
api:
  advertiseAddress: "192.168.5.42"
etcd:
  endpoints:
  - "http://192.168.5.42:2379"
  - "http://192.168.5.104:2379"
  - "http://192.168.5.105:2379"
kubernetesVersion: "v1.8.2"
apiServerCertSANs:
- uy05-13
- uy08-07
- uy08-08
- 192.168.6.15
- 127.0.0.1
- 192.168.5.42
- 192.168.5.104
- 192.168.5.105
- 10.254.0.1
- 10.96.0.1
- kubernetes
- kubernetes.default
- kubernetes.default.svc
- kubernetes.default.svc.cluster
- kubernetes.default.svc.cluster.local
tokenTTL: 87600h
networking:
  podSubnet: 192.168.122.0/24
```

I have set the `advertiseAddress` to the inner IP, but it seems not take effect, when I access the api it still return externel IP:

```
# curl -kL https://127.0.0.1:6443/api
{
  "kind": "APIVersions",
  "versions": [
    "v1"
  ],
  "serverAddressByClientCIDRs": [
    {
      "clientCIDR": "0.0.0.0/0",
      "serverAddress": "122.14.206.195:6443"
    }
  ]
}

# curl -kL https://192.168.5.42:6443/api
{
  "kind": "APIVersions",
  "versions": [
    "v1"
  ],
  "serverAddressByClientCIDRs": [
    {
      "clientCIDR": "0.0.0.0/0",
      "serverAddress": "122.14.206.195:6443"
    }
  ]
}
```

I use `keepalived` start a VIP, and I have changed the serveraddress to my VIP in the config files `admin.conf  controller-manager.conf  kubelet.conf  scheduler.conf` like this:
```
server: https://192.168.6.15:6443
```
