### ISSUE TITLE
Does it need to set podSubnetCIDR when use contiv network?

### ISSUE THREAD

**Issue by KeithTt** [kubernetes/kubeadm#608]
kube version: 1.8.5
contiv version: 1.1.7

I set 10.244.0.0/16 when init the kubernetes cluster with kubeadm, this is my config file of kubeadm:

```
# cat kubeadm-config.yml
apiVersion: kubeadm.k8s.io/v1alpha1
kind: MasterConfiguration
api:
  advertiseAddress: "192.168.5.62"
etcd:
  endpoints:
  - "http://192.168.5.84:2379"
  - "http://192.168.5.85:2379"
  - "http://192.168.2.77:2379"
kubernetesVersion: "v1.8.5"
apiServerCertSANs:
- uy06-04
- uy06-05
- uy08-10
- uy08-11
- 192.168.6.16
- 127.0.0.1
- 192.168.5.62
- 192.168.5.63
- 192.168.5.107
- 192.168.5.108
- 30.0.0.1
- 10.244.0.1
- 10.96.0.1
- kubernetes
- kubernetes.default
- kubernetes.default.svc
- kubernetes.default.svc.cluster
- kubernetes.default.svc.cluster.local
tokenTTL: 0s
networking:
  podSubnet: 30.0.0.0/10
```

And contiv has a ui to create a network or use netctl to create a network, so should I set the podSubnetCIDR when use contiv?

And is it necessary to add the first ip of the subnet to the SAN of apiserverCert?

Thanks in advance!
