### ISSUE TITLE
Nodes registered with FQDN, but labelled with short hostname

### ISSUE THREAD

**Issue by hickey** [kubernetes/kubeadm#653]
## What keywords did you search in kubeadm issues before filing this one?

* hostname

## Is this a BUG REPORT or FEATURE REQUEST?

Choose one: BUG REPORT

## Versions

**kubeadm version**: &version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.1", GitCommit:"3a1c9449a956b6026f075fa3134ff92f7d55f812", GitTreeState:"clean", BuildDate:"2018-01-04T11:40:06Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Kubernetes version**: 1.9.1
- **Cloud provider or hardware configuration**: AWS
- **OS**: Amazon Linux 2.0 (2017.12) LTS Release Candidate
- **Kernel**: Linux ip-10-67-12-187 4.9.70-2.243.amzn2.x86_64 #1 SMP Thu Jan 4 03:49:00 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- **Others**:

## What happened?

Build cluster with the following config file:

```yaml
api:
  advertiseAddress: 10.67.12.187
  bindPort: 6443
apiServerCertSANs:
- master.dev.smartsheet.com
- apiserver.dev.smartsheet.com
authorizationModes:
- Node
- RBAC
certificatesDir: /etc/kubernetes/pki
cloudProvider: aws
etcd:
  caFile: ""
  certFile: ""
  dataDir: /var/lib/etcd
  endpoints: null
  image: ""
  keyFile: ""
imageRepository: gcr.io/google_containers
kubeProxy:
  config:
    bindAddress: 0.0.0.0
    clientConnection:
      acceptContentTypes: ""
      burst: 10
      contentType: application/vnd.kubernetes.protobuf
      kubeconfig: /var/lib/kube-proxy/kubeconfig.conf
      qps: 5
    clusterCIDR: 192.168.0.0/16
    configSyncPeriod: 15m0s
    conntrack:
      max: null
      maxPerCore: 32768
      min: 131072
      tcpCloseWaitTimeout: 1h0m0s
      tcpEstablishedTimeout: 24h0m0s
    enableProfiling: false
    featureGates: ""
    healthzBindAddress: 0.0.0.0:10256
    hostnameOverride: ""
    iptables:
      masqueradeAll: false
      masqueradeBit: 14
      minSyncPeriod: 0s
      syncPeriod: 30s
    ipvs:
      minSyncPeriod: 0s
      scheduler: ""
      syncPeriod: 30s
    metricsBindAddress: 127.0.0.1:10249
    mode: ""
    oomScoreAdj: -999
    portRange: ""
    resourceContainer: /kube-proxy
    udpTimeoutMilliseconds: 250ms
kubeletConfiguration: {}
kubernetesVersion: v1.9.1
networking:
  dnsDomain: cluster.local
  podSubnet: 192.168.0.0/16
  serviceSubnet: 172.20.0.0/22
nodeName: ip-10-67-12-187.dev.smartsheet.com
token: ""
tokenTTL: 0s
unifiedControlPlaneImage: ""
```

With fully resolvable DNS records for hosts (both forward and reverse records) the nodes register themselves with their FQDN. 

```
NAME                                 STATUS    ROLES     AGE       VERSION   LABELS
ip-10-67-12-187.dev.smartsheet.com   Ready     master    1h        v1.9.1    beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=m5.large,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=us-west-2,failure-domain.beta.kubernetes.io/zone=us-west-2c,kubernetes.io/hostname=ip-10-67-12-187,node-role.kubernetes.io/master=
ip-10-67-13-11.dev.smartsheet.com    Ready     <none>    1h        v1.9.1    beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=m5.large,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=us-west-2,failure-domain.beta.kubernetes.io/zone=us-west-2a,kubernetes.io/hostname=ip-10-67-13-11
ip-10-67-13-178.dev.smartsheet.com   Ready     <none>    1h        v1.9.1    beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=m5.large,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=us-west-2,failure-domain.beta.kubernetes.io/zone=us-west-2a,kubernetes.io/hostname=ip-10-67-13-178
ip-10-67-14-40.dev.smartsheet.com    Ready     <none>    1h        v1.9.1    beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=m5.large,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=us-west-2,failure-domain.beta.kubernetes.io/zone=us-west-2b,kubernetes.io/hostname=ip-10-67-14-40
ip-10-67-14-66.dev.smartsheet.com    Ready     <none>    1h        v1.9.1    beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=m5.large,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=us-west-2,failure-domain.beta.kubernetes.io/zone=us-west-2b,kubernetes.io/hostname=ip-10-67-14-66
ip-10-67-15-129.dev.smartsheet.com   Ready     <none>    1h        v1.9.1    beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=m5.large,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=us-west-2,failure-domain.beta.kubernetes.io/zone=us-west-2c,kubernetes.io/hostname=ip-10-67-15-129
ip-10-67-15-22.dev.smartsheet.com    Ready     <none>    1h        v1.9.1    beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=m5.large,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=us-west-2,failure-domain.beta.kubernetes.io/zone=us-west-2c,kubernetes.io/hostname=ip-10-67-15-22
```

Some applications target themselves (Rook mon processes)  to a specific node using the `kubernetes.io/hostname` label, but use the node name as it is registered formally (i.e. FQDN).

## What you expected to happen?

The `kubernetes.io/hostname` label's value to match the node name. 

## How to reproduce it (as minimally and precisely as possible)?

Create a cluster where nodes resolve completely in DNS (both forward and reverse records). Join nodes to the cluster and they should be registered using the node's FQDN. Inspect the `kubernetes.io/hostname` label and its value will be the short hostname instead of the registered node name. 

## Anything else we need to know?

I think that the default should be to register the node and set hostname label to the short hostname, but there should be a setting in at least the config file (maybe a CLI switch also) that allows the admin to specify that the FQDN be used in both cases.
