### ISSUE TITLE
How to use IPVSProxy when deploy k8s with kubeadm?

### ISSUE THREAD

**Issue by KeithTt** [kubernetes/kubeadm#655]
kubeadm version: 1.9.1
OS version: debian stretch

I followed the official guide: https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-init/

There is a option `SupportIPVSProxyMode=true` in the guide.

![image](https://user-images.githubusercontent.com/15189954/34788069-6b42d352-f674-11e7-9362-48940e558024.png)

but I do not find this option in my environment....

![image](https://user-images.githubusercontent.com/15189954/34788114-a1dec948-f674-11e7-901e-c66628e51ac8.png)

Here is my config file of kubeadm:
```
apiVersion: kubeadm.k8s.io/v1alpha1
kind: MasterConfiguration
api:
  advertiseAddress: "192.168.5.42"
etcd:
  endpoints:
  - "http://192.168.5.42:2379"
  - "http://192.168.5.104:2379"
  - "http://192.168.5.105:2379"
kubernetesVersion: "v1.9.1"
apiServerCertSANs:
- uy05-13
- uy08-07
- uy08-08
- uy02-07
- 192.168.6.15
- 127.0.0.1
- 192.168.5.42
- 192.168.5.104
- 192.168.5.105
- 192.168.5.40
- 20.0.0.1
- 10.96.0.1
- kubernetes
- kubernetes.default
- kubernetes.default.svc
- kubernetes.default.svc.cluster
- kubernetes.default.svc.cluster.local
tokenTTL: 0s
networking:
  podSubnet: 20.0.0.0/10
#apiServerExtraArgs:
#  enable-swagger-ui: true
#  insecure-bind-address: 0.0.0.0
#  insecure-port: 8080
#  endpoint-reconciler-type: lease
featureGates:
  CoreDNS: true
#  SupportIPVSProxyMode: true
```

Other than IPVSProxy, `apiServerExtraArgs` this sec can not be recognized, how to define these params?

**Comment by Lion-Wei** [comment]
https://github.com/m1093782566/kubernetes/blob/f8e27cf78cd8ea7e581284cc6c0093c996d9d346/pkg/proxy/ipvs/README.md#L42-L45

I'm pretty sure this is the right way. : )

**Comment by KeithTt** [comment]
@Lion-Wei Thanks for your guide.

But there is no this option in my environment. What is your kubeadm version and OS version?

**Comment by Lion-Wei** [comment]
I think kubeadm 1.9.1 is ok. You don't need add `feature-gate` flag, just add those line above to your kubeadm config file, and use `kubeadm init --config=<config file path>`, should work.

**Comment by KeithTt** [comment]
@Lion-Wei Can you paste your config file? Thanks.

**Comment by Lion-Wei** [comment]
Sure, config file:
```
kind: MasterConfiguration
apiVersion: kubeadm.k8s.io/v1alpha1
api:
  advertiseAddress: "35.225.76.193"
  bindPort: 443
networking:
  podSubnet: "10.32.0.0/12"
kubernetesVersion: "ci/latest"
token: "936bcf.f687ae7d46a89bcd"
cloudProvider: "gce"
kubeProxy:
  config:
    featureGates: SupportIPVSProxyMode=true
    mode: "ipvs"
```
Command: `kubeadm init --skip-preflight-checks --config /etc/kubeadm/kubeadm.yaml`.

If not work, you can paste your Command/config file/and result, maybe I can help. : )

**Comment by KeithTt** [comment]
@Lion-Wei Thanks a lot!!!

Your usage of `kubeProxy` is not displayed in the official guide.

https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-init/#config-file

Is there some docs else?

**Comment by KeithTt** [comment]
@Lion-Wei Thanks a lot!

**Comment by KeithTt** [comment]
@Lion-Wei BTW, another two questions:

1、Do you know how to set `apiServerExtraArgs` options of apiserver?
```
#apiServerExtraArgs:
#  enable-swagger-ui: true
#  insecure-bind-address: 0.0.0.0
#  insecure-port: 8080
#  endpoint-reconciler-type: lease
```

2、Do you use `kube-router`? If set proxy mode to `ipvs`, will kubeadm deploy kube-router by default or we can use kube-proxy with ipvs mode and deploy another network plugin?

**Comment by Lion-Wei** [comment]
I'm not sure about how to use `apiServerExtraArgs`, but I noticed this field is in type `map[string]string`, maybe you can try:
```yaml
apiServerExtraArgs:
  enable-swagger-ui: "true"
  insecure-bind-address: "0.0.0.0"
  insecure-port: "8080"
  endpoint-reconciler-type: "lease"
```

2. You can use kube-proxy ipvs sproxy mode with other network plugin, Actually I think kube-proxy need to be removed if you want use kube-router.
https://github.com/cloudnativelabs/kube-router/blob/master/Documentation/kubeadm.md

**Comment by KeithTt** [comment]
I think this config will be ok.
```
apiVersion:" kubeadm.k8s.io/v1alpha1
kind: MasterConfiguration
api:
  advertiseAddress: "192.168.5.42"
etcd:
  endpoints:
  - "http://192.168.5.42:2379"
  - "http://192.168.5.104:2379"
  - "http://192.168.5.105:2379"
kubernetesVersion: "v1.9.1"
apiServerCertSANs:
- uy05-13
- uy08-07
- uy08-08
- uy02-07
- 192.168.6.15
- 127.0.0.1
- 192.168.5.42
- 192.168.5.104
- 192.168.5.105
- 192.168.5.40
- 20.0.0.1
- 10.96.0.1
- kubernetes
- kubernetes.default
- kubernetes.default.svc
- kubernetes.default.svc.cluster
- kubernetes.default.svc.cluster.local
tokenTTL: 0s
networking:
  podSubnet: 20.0.0.0/10
apiServerExtraArgs:
  enable-swagger-ui: "true"
  insecure-bind-address: "0.0.0.0"
  insecure-port: "8080"
  endpoint-reconciler-type: "lease"
featureGates:
  CoreDNS: true
kubeProxy:
  config:
    featureGates:
      SupportIPVSProxyMode: true
    mode: "ipvs"
```

I will have another try..

**Comment by Lion-Wei** [comment]
Good luck : )

I'll send a pr, but right now maybe this README file is the only official doc : (

**Comment by KeithTt** [comment]
After a test, the config works with this version:
```
apiVersion: kubeadm.k8s.io/v1alpha1
kind: MasterConfiguration
api:
  advertiseAddress: "192.168.5.62"
etcd:
  endpoints:
  - "http://192.168.5.84:2379"
  - "http://192.168.5.85:2379"
  - "http://192.168.2.77:2379"
kubernetesVersion: "v1.9.1"
apiServerCertSANs:
- uy06-04
- uy06-05
- uy08-10
- uy08-11
- 192.168.6.16
- 192.168.6.17
- 127.0.0.1
- 192.168.5.62
- 192.168.5.63
- 192.168.5.107
- 192.168.5.108
- 30.0.0.1
- 10.96.0.1
- kubernetes
- kubernetes.default
- kubernetes.default.svc
- kubernetes.default.svc.cluster
- kubernetes.default.svc.cluster.local
tokenTTL: 0s
networking:
  podSubnet: 30.0.0.0/10
apiServerExtraArgs:
  enable-swagger-ui: "true"
  insecure-bind-address: 0.0.0.0
  insecure-port: "8088"
  endpoint-reconciler-type: "lease"
controllerManagerExtraArgs:
  address: 0.0.0.0
schedulerExtraArgs:
  address: 0.0.0.0
featureGates:
  CoreDNS: true
kubeProxy:
  config:
    featureGates: "SupportIPVSProxyMode=true"
    mode: "ipvs"
```

Hope your PR been merged soon.

Do you know how to check the proxy mode of kube-proxy? I have deploy with the config, and how to check the mode is ipvs or not?
