### ISSUE TITLE
Support specifying kube-proxy tolerations

### ISSUE THREAD

**Issue by discordianfish** [kubernetes/kubeadm#699]
## FEATURE REQUEST

kubeadm deploys kube-proxy with these tolerations:
```
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      - effect: NoSchedule
        key: node.cloudprovider.kubernetes.io/uninitialized
        value: "true"
```

This allows kube-proxy to run on masters but not any other tainted hosts. In my case, I want to taint a group of hosts to reserve them for special workloads. But they still need to run kube-proxy. I could just edit the daemonset directly but would prefer a declarative way (e.g kubeadm config) and I'm worried that kubeadm might revert this change on upgrades/replacing masters.

Alternatively the toleration could also just be made to apply to all NoSchedule taints which would solve my problem without introducing a new flag/config.
