### ISSUE TITLE
External Etcd version check fails with TLS

### ISSUE THREAD

**Issue by jnummelin** [kubernetes/kubeadm#730]
## What keywords did you search in kubeadm issues before filing this one?

external etcd

## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`): v1.10.0-beta.3

**Environment**: 
- **Kubernetes version** (use `kubectl version`): v1.9.3
- **Cloud provider or hardware configuration**: Vagrant
- **OS** (e.g. from /etc/os-release):  Ubuntu 16.04.4 LTS
- **Kernel** (e.g. `uname -a`): 4.4.0-116-generic
- **Others**:

## What happened?

`kubeadm init` ran with configuration options for external etcd:
```
---
apiVersion: kubeadm.k8s.io/v1alpha1
kind: MasterConfiguration
kubernetesVersion: 1.9.3
apiServerCertSANs:
- 192.168.100.100
networking:
  serviceSubnet: 10.96.0.0/12
  podSubnet: 10.32.0.0/16
api:
  advertiseAddress: 192.168.100.100
etcd:
  endpoints:
  - https://127.0.0.1:2379
  version: 3.3.2
  certFile: "/vagrant/etcd_certs/client.pem"
  keyFile: "/vagrant/etcd_certs/client-key.pem"
```

```
sudo kubeadm init --config /tmp/kubeadm.cfg.f992a6537faee776f3c2da98e2268152 
[init] Using Kubernetes version: v1.9.3
[init] Using Authorization modes: [Node RBAC]
[preflight] Running pre-flight checks.
[preflight] Some fatal errors occurred:
	[ERROR ExternalEtcdVersion]: couldn't parse external etcd version "": Version string empty
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
```

I'm perfectly ok to `curl` the version out of etcd:
```
curl --cacert /vagrant/etcd_certs/ca.pem --cert /vagrant/etcd_certs/client.pem --key /vagrant/etcd_certs/client-key.pem   -L https://127.0.0.1:2379/version
{"etcdserver":"3.3.2","etcdcluster":"3.3.0"}
```

## What you expected to happen?

Everything configured to use the external etcd setup with certs.

## How to reproduce it (as minimally and precisely as possible)?

1. Generate some self-signed certs using cfssl: https://kubernetes.io/docs/setup/independent/high-availability/#setting-up-an-ha-etcd-cluster

2. Run etcd with the certs:
```
docker run -d -v /vagrant/etcd_certs:/certs  -p 2379:2379   -p 2380:2380   -v /tmp/etcd-data.tmp:/etcd-data   --name etcd   gcr.io/etcd-development/etcd:v3.3.2   /usr/local/bin/etcd   --name s1   --data-dir /etcd-data   --listen-client-urls https://0.0.0.0:2379   --advertise-client-urls https://0.0.0.0:2379   --listen-peer-urls http://0.0.0.0:2380   --initial-advertise-peer-urls http://0.0.0.0:2380   --initial-cluster s1=http://0.0.0.0:2380   --initial-cluster-token tkn --cert-file=/certs/ca.pem --key-file=/certs/ca-key.pem --client-cert-auth --trusted-ca-file=/certs/ca.pem
```

3. Run `kubeadm init --config ` with a config file pointing to the external etcd and the created certs.

## Anything else we need to know?

Other folks hitting also similar issues in the past:
https://kubernetes.slack.com/archives/C2P1JHS2E/p1496795519265558
