### ISSUE TITLE
ImageInspectError - Failed to inspect image - Error response from daemon: readlink /var/lib/docker/overlay2: invalid argument

### ISSUE THREAD

**Issue by dkirrane** [kubernetes/kubeadm#738]
## Is this a BUG REPORT or FEATURE REQUEST?

Choose one: BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`):
```
kubeadm version: &version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:13:31Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Kubernetes version** (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:21:50Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:13:31Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

- **Kernel** (e.g. `uname -a`):
Linux master1-dev 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

- **Others**:
```
docker version
Client:
 Version:         1.13.1
 API version:     1.26
 Package version: <unknown>
 Go version:      go1.8.3
 Git commit:      774336d/1.13.1
 Built:           Wed Mar  7 17:06:16 2018
 OS/Arch:         linux/amd64

Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: <unknown>
 Go version:      go1.8.3
 Git commit:      774336d/1.13.1
 Built:           Wed Mar  7 17:06:16 2018
 OS/Arch:         linux/amd64
 Experimental:    false
```

## What happened?
I created a cluster with `kubeadm init --pod-network-cidr=10.244.0.0/16 --kubernetes-version 1.9.6 --ignore-preflight-errors=cri` 

All control plane pods are running `Running` state 
However I cannot start a simple postgres pod on the cluster. `kubectl describe pod postgres-664cfc9966-sz9zf` shows
```
Events:
  Type     Reason                 Age               From                  Message
  ----     ------                 ----              ----                  -------
  Normal   Scheduled              26s               default-scheduler     Successfully assigned postgres-6847cfbf7d-vgr47 to minion3-dev
  Normal   SuccessfulMountVolume  25s               kubelet, minion3-dev  MountVolume.SetUp succeeded for volume "default-token-kdq6z"
  Warning  InspectFailed          2s (x8 over 23s)  kubelet, minion3-dev  Failed to inspect image "postgres:9.6.5": rpc error: code = Unknown desc = Error response from daemon: readlink /var/lib/docker/overlay2: invalid argument
  Warning  Failed                 2s (x8 over 23s)  kubelet, minion3-dev  Error: ImageInspectError
  Normal   SandboxChanged         1s (x8 over 22s)  kubelet, minion3-dev  Pod sandbox changed, it will be killed and re-created.
```

All pods
```
default       postgres-664cfc9966-sz9zf               0/1       ImageInspectError   0          22m
kube-system   etcd-master1-dev                        1/1       Running             0          29m
kube-system   kube-apiserver-master1-dev              1/1       Running             0          26m
kube-system   kube-controller-manager-master1-dev     1/1       Running             0          26m
kube-system   kube-dns-6f4fd4bdf-qd4r5                3/3       Running             0          30m
kube-system   kube-flannel-ds-2g6wx                   1/1       Running             0          30m
kube-system   kube-flannel-ds-dw79b                   1/1       Running             0          29m
kube-system   kube-flannel-ds-qpp29                   1/1       Running             0          30m
kube-system   kube-flannel-ds-qtvbn                   1/1       Running             0          30m
kube-system   kube-proxy-lfcwt                        1/1       Running             0          30m
kube-system   kube-proxy-qc7jv                        1/1       Running             0          29m
kube-system   kube-proxy-rf2fz                        1/1       Running             0          30m
kube-system   kube-proxy-vvrpl                        1/1       Running             0          30m
kube-system   kube-scheduler-master1-dev              1/1       Running             0          29m
kube-system   kubernetes-dashboard-5bd6f767c7-4l77b   1/1       Running             0          29m
kube-system   tiller-deploy-865dd6c794-2wp8r          1/1       Running             0          29m
```

## What you expected to happen?

Pod starts

## How to reproduce it (as minimally and precisely as possible)?
- kubeadm init --pod-network-cidr=10.244.0.0/16 --kubernetes-version 1.9.6 --ignore-preflight-errors=cri
- kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/v0.9.1/Documentation/kube-flannel.yml
- kubeadm token create --print-join-command
- join minions
- kubectl create -f postgres.yaml

## Anything else we need to know?
postgres.yaml
```
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: default
spec:
  selector:
    app: postgres
  ports:
  - port: 5432

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres  
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:9.6.5
        env:
        - name: POSTGRES_USER
          value: admin
        - name: POSTGRES_PASSWORD
          value: admin
        ports:
        - containerPort: 5432
```
