### ISSUE TITLE
kubeadm 1.10 doesn't give possibility to configure DNS based advertise address

### ISSUE THREAD

**Issue by onorua** [kubernetes/kubeadm#769]
There is kubeadm configuration file:
#### cat /etc/kubeadm/kubeadm.yml
```
kind: MasterConfiguration
apiVersion: kubeadm.k8s.io/v1alpha1
api:
  advertiseAddress: "airflow.k8s.afdata.io"
  bindPort: 6443
networking:
  podSubnet: "10.244.0.0/16"
...
```

#### kubeadm init  --config  /etc/kubeadm/kubeadm.yml  --dry-run  --ignore-preflight-errors=all
```
[dryrun] Would perform action CREATE on resource "configmaps" in API group "core/v1"
[dryrun] Attached object:
	apiVersion: v1
	data:
	  MasterConfiguration: |
	    api:
	      advertiseAddress: 172.31.84.94
	      bindPort: 6443
	      controlPlaneEndpoint: ""
	    apiServerCertSANs:
```

Advertise address is completely messed up. Especially for AWS cases, when you have no public IP, it makes API servers impossible to use without manually changing the configmaps. 

#### kubeadm version
```
kubeadm version: &version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

I can see that it was explicitly disabled for some unknown reason:
https://github.com/kubernetes/kubernetes/blob/c8cded58d71e36665bd345a70fbe404e7523abb8/cmd/kubeadm/app/util/config/masterconfig.go#L44

What is wrong with DNS based advertise address? Why do you prevent us from using localhost based API addresses, and now you are forbidding DNS based ones. It seems to me, that the sole reason is to make HA configuration harder without cloud provider's load balancer.
