### ISSUE TITLE
How do I create PSP enabled cluster using Kubeadm?

### ISSUE THREAD

**Issue by tamalsaha** [kubernetes/kubeadm#791]
I am trying to create a PSP enabled cluster using Kubeadm 1.10. But I can't see the pod list in `kube-system` namespace. These are the steps I followed:

```console
$ ./restart.sh
+ minikube delete
Deleting local Kubernetes cluster...
Machine deleted.
+ minikube start --extra-config=apiserver.feature-gates=CustomResourceSubresources=true --extra-config=apiserver.admission-control=NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,DefaultTolerationSeconds,NodeRestriction,PodSecurityPolicy,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota
Starting local Kubernetes v1.10.0 cluster...
Starting VM...
Getting VM IP address...
Moving files into cluster...
Setting up certs...
Connecting to cluster...
Setting up kubeconfig...
Starting cluster components...
Kubectl is now configured to use the cluster.
Loading cached images from config file.

$ kubectl apply -f psp.yaml
podsecuritypolicy.extensions "default" created
podsecuritypolicy.extensions "privileged" created

$ kubectl apply -f cluster-roles.yaml
clusterrole.rbac.authorization.k8s.io "psp:privileged" created
clusterrole.rbac.authorization.k8s.io "psp:default" created

$ ./role-bindings.sh
+ kubectl create rolebinding psp:kube-dns --clusterrole=psp:privilged --serviceaccount=kube-system:kube-dns --namespace=kube-system
rolebinding.rbac.authorization.k8s.io "psp:kube-dns" created
+ kubectl create rolebinding psp:kube-proxy --clusterrole=psp:privilged --serviceaccount=kube-system:kube-proxy --namespace=kube-system
rolebinding.rbac.authorization.k8s.io "psp:kube-proxy" created
+ kubectl create rolebinding psp:default --clusterrole=psp:privilged --serviceaccount=kube-system:default --namespace=kube-system
rolebinding.rbac.authorization.k8s.io "psp:default" created
+ kubectl create rolebinding psp:storage-provisioner --clusterrole=psp:privilged --serviceaccount=kube-system:storage-provisioner --namespace=kube-system
rolebinding.rbac.authorization.k8s.io "psp:storage-provisioner" created

$ kubectl get pods -n kube-system
NAME                                    READY     STATUS    RESTARTS   AGE
kubernetes-dashboard-5498ccf677-5jxmq   1/1       Running   3          2m
storage-provisioner                     0/1       Error     2          1m
```

You can find all the files here: https://github.com/appscodelabs/tasty-kube/tree/master/minikube/1.10/psp . How do I create PSP enabled cluster using Kubeadm?

**Comment by tamalsaha** [comment]
After giving all pods in `kube-system` namespace run in privileged mode, it seems that cluster is stable (not restarts). But I can't still see the pods that are run via  manifests (static pods).

```
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: minikube
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: psp:privileged
  apiGroup: rbac.authorization.k8s.io
subjects:
# Authorize all service accounts in a namespace:
- kind: Group
  apiGroup: rbac.authorization.k8s.io
  name: system:serviceaccounts
```
