### ISSUE TITLE
kubeadm does not work with v1alpha1 configurations

### ISSUE THREAD

**Issue by chuckha** [kubernetes/kubeadm#884]
## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT

## Versions
latest

**kubeadm version** (use `kubeadm version`):
'kubeadm version: &version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.0-alpha.0.763+d1b72711809dbe-dirty", GitCommit:"d1b72711809dbe81b8ffc874810404cdcee7fb69", GitTreeState:"dirty", BuildDate:"2018-06-04T18:19:11Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}

## What happened?
I ran `kubeadm init --config=config.yaml`

config.yaml:
```
apiVersion: kubeadm.k8s.io/v1alpha1
kind: MasterConfiguration
api:
    advertiseAddress: "10.0.0.8"
networking:
    podSubnet: "192.168.0.0/24"
nodeName: ip-10-0-0-8.us-west-2.compute.internal
apiServerCertSANs:
- "test2-controlplane-ty30khy0zwqo-201148835.us-west-2.elb.amazonaws.com"
```

I got all the way to the end with no errors and no warnings but no join command ever printed.

## What you expected to happen?
kubeadm to show me a join command.

## How to reproduce it (as minimally and precisely as possible)?
Use any valid v1alpha1 configuration that does *not* contain a bootstrap token and you will have the same result.

## Anything else we need to know?
There is a PR for this fix already.
