### ISSUE TITLE
`kubeadm config migrate` does not output valid yaml

### ISSUE THREAD

**Issue by chuckha** [kubernetes/kubeadm#904]
## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT

## Versions
master

## What happened?
I ran `kubectl config migrate --old-config=config.yaml`

contents of config.yaml
```
apiVersion: kubeadm.k8s.io/v1alpha2
kind: MasterConfiguration
api:
    advertiseAddress: "10.0.0.7"
networking:
    podSubnet: "192.168.0.0/24"
nodeName: ip-10-0-0-7.us-west-2.compute.internal
apiServerCertSANs:
- "test-controlplanel-1v1nyy82pcc3r-1234567890.us-west-2.elb.amazonaws.com"
```

## What you expected to happen?
I expected the output to be valid yaml

## How to reproduce it (as minimally and precisely as possible)?
 copy the contents above into config.yaml and run `kubectl config migrate --old-config=config.yaml`.
