### ISSUE TITLE
featureGates: StoreCertsInSecrets fails in Kubeadm v1.11

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes/kubeadm#923]
## Is this a BUG REPORT or FEATURE REQUEST?
BUG REPORT

## Versions
v1.11 (.debs, kubeadm binary e docker images build from master)

## What happened?
`kubeadm init` with `SelfHosting: true`  and `featureGates:StoreCertsInSecrets: true` fails with:

```bash
...
[self-hosted] creating self-hosted control plane
[self-hosted] Created TLS secret "ca" from ca.crt and ca.key
[self-hosted] Created TLS secret "apiserver" from apiserver.crt and apiserver.key
[self-hosted] Created TLS secret "apiserver-kubelet-client" from apiserver-kubelet-client.crt and apiserver-kubelet-client.key
[self-hosted] Created TLS secret "sa" from sa.pub and sa.key
[self-hosted] Created TLS secret "front-proxy-ca" from front-proxy-ca.crt and front-proxy-ca.key
[self-hosted] Created TLS secret "front-proxy-client" from front-proxy-client.crt and front-proxy-client.key
[self-hosted] Created secret for kubeconfig file "scheduler.conf"
[self-hosted] Created secret for kubeconfig file "controller-manager.conf"
[apiclient] Found 0 Pods for label selector k8s-app=self-hosted-kube-apiserver
[apiclient] Found 1 Pods for label selector k8s-app=self-hosted-kube-apiserver
[apiclient] The old Pod "kube-apiserver-kubeadm-test-master" is now removed (which is desired)
[apiclient] All control plane components are healthy after 0.002673 seconds
[self-hosted] self-hosted kube-apiserver ready after 4.715637 seconds
error creating self hosted control plane: timed out waiting for the condition
```

or

```bash
...
[self-hosted] self-hosted kube-apiserver ready after 6.712564 seconds
[apiclient] Found 0 Pods for label selector k8s-app=self-hosted-kube-controller-manager
[apiclient] Error getting Pods with label selector "k8s-app=self-hosted-kube-controller-manager" [Get https://10.10.10.11:6443/api/v1/namespaces/kube-system/pods?labelSelector=k8s-app%3Dself-hosted-kube-controller-manager: dial tcp 10.10.10.11:6443: connect: connection refused]
```

NB. `kubeadm init` with `featureGates:SelfHosting: true` only works properly, so I assume the issue should be related to `featureGates:StoreCertsInSecrets: true` 

## What you expected to happen?
Kubeadm init complete, control plane self-hosted and certs stored in secrets

## How to reproduce it (as minimally and precisely as possible)?
use this config file:

```yaml
---
apiVersion: kubeadm.k8s.io/v1alpha2
kind: MasterConfiguration
kubernetesVersion: "1.11.0"
api:
  advertiseAddress: "10.10.10.11"

bootstrapTokens:
- token: "abcdef.0123456789abcdef"
nodeRegistration:
  kubeletExtraArgs:
    node-ip: "10.10.10.11"
featureGates:
  SelfHosting: true
  StoreCertsInSecrets: true
```
